const en = {
  // Navigation
  home: "Home",
  search: "Search",
  dashboard: "Dashboard",
  profile: "Profile",
  settings: "Settings",
  language: "Language",
  selectLanguage: "Select Language",
  languageNote: "Language settings will be saved for your next visit",
  scholarships: "Scholarships",

  // Hero Section
  heroBadge: "AI-Powered Matching",
  heroTitle: "Find Your Perfect University Match",
  heroSubtitle: "Discover universities worldwide",
  heroDescription:
    "Discover universities worldwide that match your academic goals, budget, and preferences",
  heroStudents: "Students Helped",
  heroUniversities: "Universities",
  heroSuccessRate: "Success Rate",
  heroCta: "Start Your Journey",
  heroDemo: "Watch Demo",

  // Search
  searchPlaceholder: "Search universities, programs, or locations...",
  searchTitle: "Find Your Dream University",
  searchSubtitle: "Filter by location, program, budget, and more",
  searchFilters: "Filters",
  searchResults: "Results",
  searchLocation: "Location",
  searchProgram: "Program",
  searchBudget: "Budget",
  searchRanking: "Ranking",

  // Dashboard
  dashboardTitle: "Your Dashboard",
  dashboardWelcome: "Welcome back!",
  dashboardRecentSearches: "Recent Searches",
  dashboardSavedUniversities: "Saved Universities",
  dashboardApplications: "Applications",
  dashboardScholarships: "Scholarships",

  // University Cards
  universityTuition: "Tuition",
  universityAcceptanceRate: "Acceptance Rate",
  universityPrograms: "Programs",
  universityLearnMore: "Learn More",
  universityApplyNow: "Apply Now",

  // Scholarships
  scholarshipTitle: "Top Scholarships",
  scholarshipSubtitle: "Discover funding opportunities for your education",
  scholarshipMerit: "Merit-Based",
  scholarshipNeed: "Need-Based",
  scholarshipAthletic: "Athletic",
  scholarshipAcademic: "Academic",

  // Featured Universities
  featuredTitle: "Featured Universities",
  featuredSubtitle: "Top-rated institutions from around the world",

  // Actions
  save: "Save",
  cancel: "Cancel",
  edit: "Edit",
  delete: "Delete",
  apply: "Apply",
  view: "View",
  learnMore: "Learn More",
  viewAll: "View All",

  // Status
  success: "Success",
  error: "Error",
  loading: "Loading...",
  noResults: "No results found",

  // Additional
  deadline: "Deadline",
  type: "Type",
  meritBased: "Merit-Based",
  needBased: "Need-Based",
  projectBased: "Project-Based",
  notifications: "Notifications",
  close: "Close",
  open: "Open",
  light: "Light",
  dark: "Dark",
  switchToLight: "Switch to Light Mode",
  switchToDark: "Switch to Dark Mode",

  // Forms
  email: "Email",
  password: "Password",
  firstName: "First Name",
  lastName: "Last Name",
  phone: "Phone",
  address: "Address",
  city: "City",
  country: "Country",
  zipCode: "ZIP Code",

  // Time
  today: "Today",
  yesterday: "Yesterday",
  tomorrow: "Tomorrow",
  thisWeek: "This Week",
  thisMonth: "This Month",
  thisYear: "This Year",

  // Numbers
  thousand: "K",
  million: "M",
  billion: "B",

  // Theme
  lightMode: "Light Mode",
  darkMode: "Dark Mode",
  toggleTheme: "Toggle Theme",

  // Favorites
  favoriteSave: "Add to favorites",
  favoriteSaved: "Saved",
  favoriteUniversitiesTitle: "Favorite Universities",
  favoriteUniversitiesDescription:
    "Your saved universities list. Remove any item anytime.",
  favoriteUniversitiesEmpty: "You have no favorite universities yet.",

  // Search page
  searchNoResults: "No institutions match.",

  // Search Fields page
  searchFieldsTitle: "Search by Field",
  searchFieldsPickField: "Pick a field of study",
  searchFieldsClearAll: "Clear all",
  searchFieldsSelectedOne: "field selected",
  searchFieldsSelectedMany: "fields selected",
  searchFieldsSelectPrompt: "Select one or more fields above to see matching universities.",
  searchFieldsDegreeLevel: "Degree level",
  searchFieldsLanguage: "Language",
  searchFieldsTuition: "Tuition range (€)",
  searchFieldsResults: "Matching universities",
  searchFieldsLoading: "Loading…",
  searchFieldsViewDetails: "View details",
  searchFieldsAdditionalFilters: "Additional filters",
  searchFieldsFiltersActive: "active",
  searchFieldsRemember: "Remember my choices",
  searchFieldsCompact: "Compact view",
  searchFieldsFull: "Full view",
  searchFieldsResultOne: "result",
  searchFieldsResultMany: "results",
  filterAllLevels: "All levels",
  filterBachelor: "Bachelor",
  filterMaster: "Master",
  filterPhd: "PhD / Doctorate",
  filterAnyLanguage: "Any language",
  tuitionFree: "Free / public",
  tuitionPerYear: "/ year",

  // Field Detail page
  fieldDetailBack: "Back to fields",
  fieldDetailUniSingular: "university offers this field",
  fieldDetailUniPlural: "universities offer this field",

  // University Detail page
  uniDetailPrograms: "Programs at this university",

  // Field + University Detail page
  fieldUniNotFound: "University not found",
  fieldUniBackToFields: "Back to field search",
  fieldUniBackToResults: "Back to results",
  fieldUniSelectedFields: "Selected fields at this university",
  fieldUniNoMatchingFields: "No matching fields found for this university.",
  fieldUniDegrees: "Degrees",
  fieldUniLanguages: "Languages",
  fieldUniViewFull: "View full university profile",

  // Search Programs page
  searchProgramsTitle: "Search Programs",
  searchProgramsPlaceholder: "Search programs by name…",
  searchProgramsFilters: "Filters",
  searchProgramsCategory: "Category",
  searchProgramsCountry: "Country",
  searchProgramsResults: "Programs",

  // Program Detail page
  programDetailTitle: "Program Details",
  programDetailNotFound: "Program not found.",
  programDetailBack: "Back to programs",
  programDetailUniversity: "University",
  programDetailLocation: "Location",
  programDetailDegree: "Degree",
  programDetailLanguage: "Language",
  programDetailDuration: "Duration",
  programDetailTuition: "Tuition",
  programDetailDescription: "Description",
  programDetailWebsite: "Visit website",

  // Favorite Programs page
  favoriteProgramsTitle: "Favorite Programs",
  favoriteProgramsEmpty: "You have no favorite programs yet.",
  favoriteProgramsRemove: "Remove",

  // Shared page labels
  comingSoon: "Coming Soon",
  getStarted: "Get Started",
  startNow: "Start Now",
  keyFeatures: "Key Features",
  howItWorks: "How It Works",
  popularTopics: "Popular Topics",

  // Essay Reviews page
  essayReviewsTitle: "Essay Reviews",
  essayReviewsDesc: "Get professional feedback on your application essays",
  essayReviewsIntro: "Submit your essays for expert review. Our team provides detailed feedback on structure, content, grammar, and persuasiveness to help you craft compelling applications.",
  essayReviewsAiFeedback: "AI-Powered Feedback",
  essayReviewsAiFeedbackDesc: "Instant analysis of tone, clarity, and impact",
  essayReviewsStructure: "Structure Analysis",
  essayReviewsStructureDesc: "Paragraph flow and logical argument mapping",
  essayReviewsGrammar: "Grammar & Style",
  essayReviewsGrammarDesc: "Advanced grammar, punctuation, and style checks",
  essayReviewsTone: "Tone & Voice",
  essayReviewsToneDesc: "Ensure your authentic voice shines through",
  essayReviewsPersonalStatement: "Personal Statement",
  essayReviewsSupplemental: "Supplemental Essays",
  essayReviewsDiversity: "Diversity Statement",
  essayReviewsResearchPurpose: "Statement of Purpose",
  essayReviewsSubmitEssay: "Submit Essay",
  essayReviewsTurnaround: "24-48h turnaround",

  // Match Universities page
  matchUnisTitle: "Match Universities",
  matchUnisDesc: "AI-powered university matching based on your profile",
  matchUnisIntro: "Our AI analyzes your academic profile, preferences, and goals to find the best-fit universities for you. Complete your profile for more accurate matches.",
  matchUnisProfileAnalysis: "Profile Analysis",
  matchUnisProfileAnalysisDesc: "Deep analysis of your academic strengths",
  matchUnisCompatibility: "Compatibility Score",
  matchUnisCompatibilityDesc: "Percentage match based on multiple factors",
  matchUnisSmartFilter: "Smart Filtering",
  matchUnisSmartFilterDesc: "Filters adapt to your changing preferences",
  matchUnisRealtime: "Real-Time Updates",
  matchUnisRealtimeDesc: "Matches refresh as new data becomes available",
  matchUnisProfileComplete: "Profile Completion",
  matchUnisCompleteProfile: "Complete your profile for better results",

  // Match Scholarships page
  matchScholarshipsTitle: "Match Scholarships",
  matchScholarshipsDesc: "Find scholarships that match your profile",
  matchScholarshipsIntro: "Discover scholarships you are eligible for based on your academic record, nationality, field of study, and financial situation.",
  matchScholarshipsEligibility: "Eligibility Matching",
  matchScholarshipsEligibilityDesc: "Automatic check against scholarship criteria",
  matchScholarshipsDeadlines: "Deadline Tracking",
  matchScholarshipsDeadlinesDesc: "Never miss an application deadline",
  matchScholarshipsGuidance: "Application Guidance",
  matchScholarshipsGuidanceDesc: "Step-by-step help for each application",
  matchScholarshipsCalculator: "Financial Calculator",
  matchScholarshipsCalculatorDesc: "Estimate your total funding potential",
  matchScholarshipsMerit: "Merit-Based",
  matchScholarshipsNeed: "Need-Based",
  matchScholarshipsCountry: "Country-Specific",
  matchScholarshipsField: "Field-Specific",

  // Similar Students page
  similarStudentsTitle: "Similar Students",
  similarStudentsDesc: "Connect with students who share your goals",
  similarStudentsIntro: "Find students with similar academic backgrounds, target universities, and career goals. Share experiences and learn from each other's journeys.",
  similarStudentsMatching: "Profile Matching",
  similarStudentsMatchingDesc: "Find students with similar goals and backgrounds",
  similarStudentsGroups: "Study Groups",
  similarStudentsGroupsDesc: "Join or create study groups by topic",
  similarStudentsExperience: "Experience Sharing",
  similarStudentsExperienceDesc: "Read and share application experiences",
  similarStudentsNetwork: "Build Network",
  similarStudentsNetworkDesc: "Connect with peers applying to similar universities",

  // Alumni Mentors page
  alumniMentorsTitle: "Alumni Mentors",
  alumniMentorsDesc: "Get guidance from successful alumni",
  alumniMentorsIntro: "Connect with alumni who studied abroad and can share real experiences, application tips, cultural guidance, and career advice.",
  alumniMentorsCareer: "Career Guidance",
  alumniMentorsCareerDesc: "Learn about career paths after graduation",
  alumniMentorsTips: "Application Tips",
  alumniMentorsTipsDesc: "Get advice from those who succeeded",
  alumniMentorsCulture: "Cultural Insights",
  alumniMentorsCultureDesc: "Prepare for life in a new country",
  alumniMentorsAccess: "Network Access",
  alumniMentorsAccessDesc: "Join a growing community of alumni",

  // Connect Friends page
  connectFriendsTitle: "Connect Friends",
  connectFriendsDesc: "Build your network with fellow applicants",
  connectFriendsIntro: "Meet other students preparing for study abroad. Share tips, find roommates, and build lasting friendships with fellow applicants.",
  connectFriendsInterest: "Interest Matching",
  connectFriendsInterestDesc: "Connect based on shared hobbies and goals",
  connectFriendsStudy: "Study Partners",
  connectFriendsStudyDesc: "Find study partners for test preparation",
  connectFriendsCampus: "Campus Connections",
  connectFriendsCampusDesc: "Meet students heading to the same university",
  connectFriendsCultural: "Cultural Exchange",
  connectFriendsCulturalDesc: "Learn about different cultures and backgrounds",

  // Mock Interviews page
  mockInterviewsTitle: "Mock Interviews",
  mockInterviewsDesc: "Practice for university admission interviews",
  mockInterviewsIntro: "Prepare for university interviews with AI-powered practice sessions. Get real-time feedback on your answers, body language tips, and confidence scores.",
  mockInterviewsAi: "AI Interviewer",
  mockInterviewsAiDesc: "Practice with realistic AI-generated questions",
  mockInterviewsFeedback: "Real-Time Feedback",
  mockInterviewsFeedbackDesc: "Instant analysis of your responses",
  mockInterviewsBank: "Question Bank",
  mockInterviewsBankDesc: "University-specific question collections",
  mockInterviewsTrack: "Performance Tracking",
  mockInterviewsTrackDesc: "Track improvement across sessions",
  mockInterviewsGeneral: "General Admission",
  mockInterviewsTechnical: "Technical Interview",
  mockInterviewsScholarship: "Scholarship Interview",
  mockInterviewsPortfolio: "Portfolio Review",

  // Concierge Support page
  conciergeSupportTitle: "Concierge Support",
  conciergeSupportDesc: "Premium personalized guidance for your journey",
  conciergeSupportIntro: "Get dedicated support from our expert advisors. From university selection to visa applications, we guide you through every step of studying abroad.",
  conciergeSupportPriority: "Priority Support",
  conciergeSupportPriorityDesc: "Skip the queue with priority response times",
  conciergeSupportAdvisor: "Dedicated Advisor",
  conciergeSupportAdvisorDesc: "Personal advisor assigned to your case",
  conciergeSupportDocReview: "Document Review",
  conciergeSupportDocReviewDesc: "Expert review of all application documents",
  conciergeSupportTracking: "Application Tracking",
  conciergeSupportTrackingDesc: "Real-time status updates on applications",

  // English page
  englishTitle: "English Preparation",
  englishDesc: "Prepare for IELTS, TOEFL, and academic English",
  englishIntro: "Boost your English skills for university admission. Practice reading, writing, listening, and speaking with targeted exercises for IELTS, TOEFL, and academic contexts.",
  englishIelts: "IELTS Preparation",
  englishIeltsDesc: "Full practice tests and strategy guides",
  englishToefl: "TOEFL Preparation",
  englishToeflDesc: "Section-by-section practice and tips",
  englishAcademic: "Academic English",
  englishAcademicDesc: "Writing, reading, and presentation skills",
  englishSpeaking: "Speaking Practice",
  englishSpeakingDesc: "AI-powered conversation drills",
  englishReading: "Reading",
  englishWriting: "Writing",
  englishListening: "Listening",
  englishSpeakingSkill: "Speaking",

  // Math page
  mathTitle: "Math Preparation",
  mathDesc: "Prepare for SAT, GRE, and university math requirements",
  mathIntro: "Strengthen your math skills with guided practice for standardized tests and university-level courses. Covers algebra, calculus, statistics, and problem-solving strategies.",
  mathSat: "SAT / ACT Math",
  mathSatDesc: "Practice problems and test-taking strategies",
  mathAdvanced: "Advanced Topics",
  mathAdvancedDesc: "Calculus, linear algebra, and beyond",
  mathPractice: "Practice Problems",
  mathPracticeDesc: "Thousands of problems with step-by-step solutions",
  mathProgress: "Progress Tracking",
  mathProgressDesc: "Track mastery across all topics",
  mathAlgebra: "Algebra",
  mathCalculus: "Calculus",
  mathStatistics: "Statistics",
  mathGeometry: "Geometry",

  // AI Literacy page
  aiLiteracyTitle: "AI Literacy",
  aiLiteracyDesc: "Learn to use AI tools effectively for academics",
  aiLiteracyIntro: "Understand AI fundamentals, learn prompt engineering, and explore ethical AI use in academic and professional contexts. Essential skills for the modern student.",
  aiLiteracyFundamentals: "AI Fundamentals",
  aiLiteracyFundamentalsDesc: "Core concepts of artificial intelligence",
  aiLiteracyPrompt: "Prompt Engineering",
  aiLiteracyPromptDesc: "Write effective prompts for AI tools",
  aiLiteracyData: "Data Literacy",
  aiLiteracyDataDesc: "Understand and work with data effectively",
  aiLiteracyEthics: "Ethical AI",
  aiLiteracyEthicsDesc: "Responsible use of AI in academics",

  // Get Courses page
  getCoursesTitle: "Browse Courses",
  getCoursesDesc: "Explore our course catalog for test preparation and skills",
  getCoursesIntro: "Discover self-paced courses designed to help you succeed in university applications and academics. From test prep to soft skills, find the right course for you.",
  getCoursesVideo: "Video Lectures",
  getCoursesVideoDesc: "Learn from expert instructors at your own pace",
  getCoursesInteractive: "Interactive Exercises",
  getCoursesInteractiveDesc: "Practice with hands-on activities",
  getCoursesCertificate: "Certificates",
  getCoursesCertificateDesc: "Earn certificates to boost your profile",
  getCoursesSelfPaced: "Self-Paced",
  getCoursesSelfPacedDesc: "Study on your own schedule",
  getCoursesTestPrep: "Test Preparation",
  getCoursesLanguage: "Language Courses",
  getCoursesSkills: "Soft Skills",
  getCoursesAcademic: "Academic Writing",

  // Essay Writing page
  essayWritingTitle: "Essay Writing",
  essayWritingDesc: "Learn to write compelling application essays",
  essayWritingIntro: "Master the art of essay writing with templates, AI-powered suggestions, and university-specific guidance. Turn your experiences into powerful narratives.",
  essayWritingTemplates: "Essay Templates",
  essayWritingTemplatesDesc: "Proven structures for different essay types",
  essayWritingAi: "AI Suggestions",
  essayWritingAiDesc: "Smart recommendations to improve your writing",
  essayWritingPeer: "Peer Review",
  essayWritingPeerDesc: "Get feedback from fellow applicants",
  essayWritingUniTips: "University-Specific Tips",
  essayWritingUniTipsDesc: "Tailored advice for each university's prompts",

  // Contact Premium page
  contactPremiumTitle: "Contact Support",
  contactPremiumDesc: "Reach our premium support team",
  contactPremiumIntro: "Have questions or need help? Our support team is ready to assist you with university applications, account issues, and platform guidance.",
  contactPremiumPriority: "Priority Response",
  contactPremiumPriorityDesc: "Get fast responses from our dedicated team",
  contactPremiumVideo: "Video Consultations",
  contactPremiumVideoDesc: "Schedule face-to-face video calls",
  contactPremiumDoc: "Document Help",
  contactPremiumDocDesc: "Assistance with documents and applications",
  contactPremiumTeam: "Expert Team",
  contactPremiumTeamDesc: "Support from experienced education advisors",
  contactPremiumEmail: "Email Support",
  contactPremiumEmailDesc: "Send us a message and get a response within 24 hours",
  contactPremiumChat: "Live Chat",
  contactPremiumChatDesc: "Chat with our team in real time during business hours",
  contactPremiumCall: "Schedule a Call",
  contactPremiumCallDesc: "Book a one-on-one call with an education advisor",
  contactPremiumContactUs: "Contact Us",
  contactPremiumChannels: "Contact Channels",

  // Dream University page
  dreamUniTitle: "Dream University",
  dreamUniDesc: "Plan and track your path to your dream university",
  dreamUniIntro: "Set your target universities, track application deadlines, and monitor your progress. Stay organized and focused on reaching your goals.",
  dreamUniGoals: "Goal Tracking",
  dreamUniGoalsDesc: "Set and monitor your application milestones",
  dreamUniDeadlines: "Deadline Reminders",
  dreamUniDeadlinesDesc: "Never miss an important application deadline",
  dreamUniTimeline: "Progress Timeline",
  dreamUniTimelineDesc: "Visualize your journey from start to acceptance",
  dreamUniChecklist: "Application Checklist",
  dreamUniChecklistDesc: "Track every document and requirement",

  // Search Scholarships page
  searchScholarshipsTitle: "Search Scholarships",
  searchScholarshipsDesc: "Find scholarships and funding opportunities worldwide",
  searchScholarshipsIntro: "Explore thousands of scholarships for Central Asian students. Filter by country, field, amount, and deadline to find the perfect funding opportunity.",
  searchScholarshipsType: "By Type",
  searchScholarshipsTypeDesc: "Merit, need-based, country-specific, and more",
  searchScholarshipsCountry: "By Country",
  searchScholarshipsCountryDesc: "Filter scholarships by destination country",
  searchScholarshipsDeadline: "Deadline Calendar",
  searchScholarshipsDeadlineDesc: "Track upcoming scholarship deadlines",
  searchScholarshipsEligibility: "Eligibility Check",
  searchScholarshipsEligibilityDesc: "Quick check if you qualify",

  // Profile page
  profileTitle: "My Profile",
  profileDesc: "Manage your account settings",
  profileChangePhoto: "Change Photo",
  profileFullName: "Full Name",
  profileFirstName: "First name",
  profileLastName: "Last name",
  profileEmail: "Email",
  profilePhone: "Phone",
  profileLocation: "Location",
  profileCertifications: "Certifications and qualifications",
  profileCertificationsHint:
    "One per line (for example diplomas, language tests, exam scores relevant to program requirements).",
  profileShareTitle: "Profile link",
  profileShareDesc: "Share this link or scan the code to open your profile on this device.",
  profileCopyLink: "Copy link",
  profileLinkCopied: "Link copied",
  profileLoadError: "Could not load profile. Check that you are signed in and the server is running.",
  profileSaveError: "Could not save changes.",
  profileSaveSuccess: "Profile saved.",
  profileGuestHint:
    "Sign in to load and save your profile, certifications, and share link.",
  profileSaving: "Saving…",
  profileApplications: "Applications",
  profileScholarships: "Scholarships",
  profileViews: "Profile Views",
  profilePremium: "Premium Member",
  profilePremiumDesc: "You have access to all premium features",
  profilePremiumMatch: "Unlimited university matches",
  profilePremiumSupport: "Priority application support",
  profilePremiumAlerts: "Exclusive scholarship alerts",
  profilePremiumMentor: "Direct mentor access",
  profileSave: "Save Changes",
  profileLogout: "Logout",

  // Dashboard
  dashMain: "Main",
  dashDreamUniversity: "Dream University",
  dashSearchUniversities: "Search Universities",
  dashFavoriteUniversities: "Favorite Universities",
  dashSearchFields: "Search Fields",
  dashSearchPrograms: "Search Programs",
  dashFavoritePrograms: "Favorite Programs",
  dashSearchScholarships: "Search Scholarships",
  dashAiMatching: "AI & Smart Matching",
  dashMatchUniversities: "Match Universities",
  dashMatchScholarships: "Match Scholarships",
  dashSimilarStudents: "Similar Students",
  dashCommunity: "Community",
  dashConnectFriends: "Connect Friends",
  dashAlumniMentors: "Alumni Mentors",
  dashPremiumServices: "Premium Services",
  dashEssayReviews: "Essay Reviews",
  dashMockInterviews: "Mock Interviews",
  dashConciergeSupport: "Concierge Support",
  dashLearning: "Learning & Courses",
  dashGetCourses: "Get Courses",
  dashMath: "Math",
  dashEnglish: "English",
  dashEssayWriting: "Essay Writing",
  dashAiLiteracy: "AI Literacy",
  dashDashboard: "Dashboard",
  dashTagline: "Your university journey starts here",
  dashSendInfo: "Send Info & Get Premium",
  dashJoinCommunity: "Join Our Community",
  dashLogout: "Logout",
  dashNotifications: "Notifications",
  dashProfile: "Profile",

  appTimelineTitle: "Application Timeline",
  appTimelineDesc: "Track your application deadlines and progress",
  appTimelineFeature1: "Deadline Tracking",
  appTimelineFeature1Desc: "Never miss an application deadline with smart reminders",
  appTimelineFeature2: "Progress Monitoring",
  appTimelineFeature2Desc: "See your application status at a glance across all universities",
  appTimelineFeature3: "Milestone Planning",
  appTimelineFeature3Desc: "Plan key milestones from test prep to visa applications",
  appTimelineFeature4: "Calendar Sync",
  appTimelineFeature4Desc: "Sync deadlines to your calendar for seamless scheduling",
  appTimelineCta: "Start Tracking",

  myDocsTitle: "My Documents",
  myDocsDesc: "Manage your application documents and transcripts",
  myDocsFeature1: "Document Storage",
  myDocsFeature1Desc: "Securely store transcripts, essays, and recommendations",
  myDocsFeature2: "Version Control",
  myDocsFeature2Desc: "Track changes and manage multiple essay drafts",
  myDocsFeature3: "Quick Share",
  myDocsFeature3Desc: "Share documents with advisors and mentors for review",
  myDocsFeature4: "Checklist Manager",
  myDocsFeature4Desc: "Track required documents for each university application",
  myDocsCta: "Upload Documents",

  careerAnalysisTitle: "Career Path Analysis",
  careerAnalysisDesc: "Analyze potential career paths and opportunities",
  careerAnalysisFeature1: "Industry Insights",
  careerAnalysisFeature1Desc: "Explore career trends and salary data by industry",
  careerAnalysisFeature2: "Skill Mapping",
  careerAnalysisFeature2Desc: "Match your skills to in-demand career opportunities",
  careerAnalysisFeature3: "Path Comparison",
  careerAnalysisFeature3Desc: "Compare career paths side-by-side with growth projections",
  careerAnalysisFeature4: "Goal Setting",
  careerAnalysisFeature4Desc: "Set career milestones and track progress toward your goals",
  careerAnalysisCta: "Analyze Careers",

  internshipsTitle: "Internships Matching",
  internshipsDesc: "Find internship opportunities that match your goals",
  internshipsFeature1: "Smart Matching",
  internshipsFeature1Desc: "AI-powered matching connects you with relevant internships",
  internshipsFeature2: "Application Tracker",
  internshipsFeature2Desc: "Track your internship applications in one place",
  internshipsFeature3: "Company Research",
  internshipsFeature3Desc: "In-depth profiles of companies offering internships",
  internshipsFeature4: "Skill Building",
  internshipsFeature4Desc: "Identify skills to develop for your target internships",
  internshipsCta: "Find Internships",

  mastersTitle: "Masters Matching",
  mastersDesc: "Explore graduate programs worldwide",
  mastersFeature1: "Program Search",
  mastersFeature1Desc: "Explore masters programs across universities globally",
  mastersFeature2: "Admission Insights",
  mastersFeature2Desc: "Understand admission requirements and acceptance rates",
  mastersFeature3: "Funding Options",
  mastersFeature3Desc: "Discover scholarships and assistantships for graduate study",
  mastersFeature4: "Career Outcomes",
  mastersFeature4Desc: "See employment statistics for program graduates",
  mastersCta: "Explore Programs",

  uniReelsTitle: "University Reels",
  uniReelsDesc: "Watch university tours and student life videos",
  uniReelsFeature1: "Campus Tours",
  uniReelsFeature1Desc: "Virtual tours of campuses from around the world",
  uniReelsFeature2: "Student Stories",
  uniReelsFeature2Desc: "Hear from current students about their experiences",
  uniReelsFeature3: "City Guides",
  uniReelsFeature3Desc: "Explore the cities where top universities are located",
  uniReelsFeature4: "Event Highlights",
  uniReelsFeature4Desc: "Watch highlights from open days and campus events",
  uniReelsCta: "Watch Now",

  privacyTitle: "My Privacy Dashboard",
  privacyDesc: "Manage your privacy settings and data",
  privacyFeature1: "Data Control",
  privacyFeature1Desc: "See and manage all data we collect about you",
  privacyFeature2: "Visibility Settings",
  privacyFeature2Desc: "Control who can see your profile and activity",
  privacyFeature3: "Export Data",
  privacyFeature3Desc: "Download a copy of all your personal data anytime",
  privacyFeature4: "Delete Account",
  privacyFeature4Desc: "Permanently remove your account and all associated data",
  privacyCta: "Review Settings",

  studyTogetherTitle: "Study Together",
  studyTogetherDesc: "Connect with peers and study groups",
  studyTogetherFeature1: "Group Matching",
  studyTogetherFeature1Desc: "Find study partners with similar goals and schedules",
  studyTogetherFeature2: "Live Sessions",
  studyTogetherFeature2Desc: "Join real-time study sessions with peers worldwide",
  studyTogetherFeature3: "Resource Sharing",
  studyTogetherFeature3Desc: "Share notes, materials, and study strategies",
  studyTogetherFeature4: "Progress Together",
  studyTogetherFeature4Desc: "Track shared goals and motivate each other",
  studyTogetherCta: "Find Study Partners",
};

export default en;
