const en = {
  // Navigation
  home: "Home",
  search: "Search",
  dashboard: "Dashboard",
  profile: "Profile",
  settings: "Settings",
  language: "Language",
  selectLanguage: "Select Language",
  languageNote: "Language settings will be saved for your next visit",
  scholarships: "Scholarships",

  // Hero Section
  heroBadge: "AI-Powered Matching",
  heroTitle: "Find Your Perfect University Match",
  heroSubtitle: "Discover universities worldwide",
  heroDescription:
    "Discover universities worldwide that match your academic goals, budget, and preferences",
  heroStudents: "Students Helped",
  heroUniversities: "Universities",
  heroSuccessRate: "Success Rate",
  heroCta: "Start Your Journey",
  heroDemo: "Watch Demo",

  // Search
  searchPlaceholder: "Search universities, programs, or locations...",
  searchTitle: "Find Your Dream University",
  searchSubtitle: "Filter by location, program, budget, and more",
  searchFilters: "Filters",
  searchResults: "Results",
  searchLocation: "Location",
  searchProgram: "Program",
  searchBudget: "Budget",
  searchRanking: "Ranking",

  // Dashboard
  dashboardTitle: "Your Dashboard",
  dashboardWelcome: "Welcome back!",
  dashboardRecentSearches: "Recent Searches",
  dashboardSavedUniversities: "Saved Universities",
  dashboardApplications: "Applications",
  dashboardScholarships: "Scholarships",

  // University Cards
  universityTuition: "Tuition",
  universityAcceptanceRate: "Acceptance Rate",
  universityPrograms: "Programs",
  universityLearnMore: "Learn More",
  universityApplyNow: "Apply Now",

  // Scholarships
  scholarshipTitle: "Top Scholarships",
  scholarshipSubtitle: "Discover funding opportunities for your education",
  scholarshipMerit: "Merit-Based",
  scholarshipNeed: "Need-Based",
  scholarshipAthletic: "Athletic",
  scholarshipAcademic: "Academic",

  // Featured Universities
  featuredTitle: "Featured Universities",
  featuredSubtitle: "Top-rated institutions from around the world",

  // Actions
  save: "Save",
  cancel: "Cancel",
  edit: "Edit",
  delete: "Delete",
  apply: "Apply",
  view: "View",
  learnMore: "Learn More",
  uniTypeUniversity: "University",
  uniTypeCollege: "College",
  viewAll: "View All",

  // Status
  success: "Success",
  error: "Error",
  loading: "Loading...",
  noResults: "No results found",

  // Additional
  deadline: "Deadline",
  type: "Type",
  meritBased: "Merit-Based",
  needBased: "Need-Based",
  projectBased: "Project-Based",
  notifications: "Notifications",
  close: "Close",
  open: "Open",
  light: "Light",
  dark: "Dark",
  switchToLight: "Switch to Light Mode",
  switchToDark: "Switch to Dark Mode",

  // Forms
  email: "Email",
  password: "Password",
  firstName: "First Name",
  lastName: "Last Name",
  phone: "Phone",
  address: "Address",
  city: "City",
  country: "Country",
  zipCode: "ZIP Code",

  // Time
  today: "Today",
  yesterday: "Yesterday",
  tomorrow: "Tomorrow",
  thisWeek: "This Week",
  thisMonth: "This Month",
  thisYear: "This Year",

  // Numbers
  thousand: "K",
  million: "M",
  billion: "B",

  // Theme
  lightMode: "Light Mode",
  darkMode: "Dark Mode",
  toggleTheme: "Toggle Theme",

  // Favorites
  favoriteSave: "Add to favorites",
  favoriteSaved: "Saved",
  favoriteUniversitiesTitle: "Favorite Universities",
  favoriteUniversitiesDescription:
    "Your saved universities list. Remove any item anytime.",
  favoriteUniversitiesEmpty: "You have no favorite universities yet.",

  // Search page
  searchNoResults: "No institutions match.",

  // Search Fields page
  searchFieldsTitle: "Search by Field",
  searchFieldsPickField: "Pick a field of study",
  searchFieldsClearAll: "Clear all",
  searchFieldsSelectedOne: "field selected",
  searchFieldsSelectedMany: "fields selected",
  searchFieldsSelectPrompt: "Select one or more fields above to see matching universities.",
  searchFieldsDegreeLevel: "Degree level",
  searchFieldsLanguage: "Language",
  searchFieldsTuition: "Tuition range (€)",
  searchFieldsResults: "Matching universities",
  searchFieldsLoading: "Loading…",
  searchFieldsViewDetails: "View details",
  searchFieldsAdditionalFilters: "Additional filters",
  searchFieldsFiltersActive: "active",
  searchFieldsRemember: "Remember my choices",
  searchFieldsCompact: "Compact view",
  searchFieldsFull: "Full view",
  searchFieldsResultOne: "result",
  searchFieldsResultMany: "results",
  filterAllLevels: "All levels",
  filterBachelor: "Bachelor",
  filterMaster: "Master",
  filterPhd: "PhD / Doctorate",
  filterAnyLanguage: "Any language",
  tuitionFree: "Free / public",
  tuitionPerYear: "/ year",

  // Field Detail page
  fieldDetailBack: "Back to fields",
  fieldDetailUniSingular: "university offers this field",
  fieldDetailUniPlural: "universities offer this field",

  // University Detail page
  uniDetailPrograms: "Programs at this university",

  // Field + University Detail page
  fieldUniNotFound: "University not found",
  fieldUniBackToFields: "Back to field search",
  fieldUniBackToResults: "Back to results",
  fieldUniSelectedFields: "Selected fields at this university",
  fieldUniNoMatchingFields: "No matching fields found for this university.",
  fieldUniDegrees: "Degrees",
  fieldUniLanguages: "Languages",
  fieldUniViewFull: "View full university profile",

  // Search Programs page
  searchProgramsTitle: "Search Programs",
  searchProgramsPlaceholder: "Search programs by name…",
  searchProgramsFilters: "Filters",
  searchProgramsCategory: "Category",
  searchProgramsCountry: "Country",
  searchProgramsResults: "Programs",

  // Program Detail page
  programDetailTitle: "Program Details",
  programDetailNotFound: "Program not found.",
  programDetailBack: "Back to programs",
  programDetailUniversity: "University",
  programDetailLocation: "Location",
  programDetailDegree: "Degree",
  programDetailLanguage: "Language",
  programDetailDuration: "Duration",
  programDetailTuition: "Tuition",
  programDetailDescription: "Description",
  programDetailWebsite: "Visit website",

  // Favorite Programs page
  favoriteProgramsTitle: "Favorite Programs",
  favoriteProgramsEmpty: "You have no favorite programs yet.",
  favoriteProgramsRemove: "Remove",

  // Public landing nav
  navFeatures: "Features",
  navAbout: "About Us",
  navFaq: "FAQ",
  navContact: "Contact Us",
  navLogin: "Log in",
  navGetStarted: "Get started",
  // Shared page labels
  comingSoon: "Coming Soon",
  getStarted: "Get Started",
  startNow: "Start Now",
  keyFeatures: "Key Features",
  howItWorks: "How It Works",
  popularTopics: "Popular Topics",

  // Essay Reviews page
  essayReviewsTitle: "Essay Reviews",
  essayReviewsDesc: "Get professional feedback on your application essays",
  essayReviewsIntro: "Submit your essays for expert review. Our team provides detailed feedback on structure, content, grammar, and persuasiveness to help you craft compelling applications.",
  essayReviewsAiFeedback: "AI-Powered Feedback",
  essayReviewsAiFeedbackDesc: "Instant analysis of tone, clarity, and impact",
  essayReviewsStructure: "Structure Analysis",
  essayReviewsStructureDesc: "Paragraph flow and logical argument mapping",
  essayReviewsGrammar: "Grammar & Style",
  essayReviewsGrammarDesc: "Advanced grammar, punctuation, and style checks",
  essayReviewsTone: "Tone & Voice",
  essayReviewsToneDesc: "Ensure your authentic voice shines through",
  essayReviewsPersonalStatement: "Personal Statement",
  essayReviewsSupplemental: "Supplemental Essays",
  essayReviewsDiversity: "Diversity Statement",
  essayReviewsResearchPurpose: "Statement of Purpose",
  essayReviewsSubmitEssay: "Submit Essay",
  essayReviewsTurnaround: "24-48h turnaround",

  // Match Universities page
  matchUnisTitle: "Match Universities",
  matchUnisDesc: "AI-powered university matching based on your profile",
  matchUnisIntro: "Our AI analyzes your academic profile, preferences, and goals to find the best-fit universities for you. Complete your profile for more accurate matches.",
  matchUnisProfileAnalysis: "Profile Analysis",
  matchUnisProfileAnalysisDesc: "Deep analysis of your academic strengths",
  matchUnisCompatibility: "Compatibility Score",
  matchUnisCompatibilityDesc: "Percentage match based on multiple factors",
  matchUnisSmartFilter: "Smart Filtering",
  matchUnisSmartFilterDesc: "Filters adapt to your changing preferences",
  matchUnisRealtime: "Real-Time Updates",
  matchUnisRealtimeDesc: "Matches refresh as new data becomes available",
  matchUnisProfileComplete: "Profile Completion",
  matchUnisCompleteProfile: "Complete your profile for better results",

  // Match Scholarships page
  matchScholarshipsTitle: "Match Scholarships",
  matchScholarshipsDesc: "Find scholarships that match your profile",
  matchScholarshipsIntro: "Discover scholarships you are eligible for based on your academic record, nationality, field of study, and financial situation.",
  matchScholarshipsEligibility: "Eligibility Matching",
  matchScholarshipsEligibilityDesc: "Automatic check against scholarship criteria",
  matchScholarshipsDeadlines: "Deadline Tracking",
  matchScholarshipsDeadlinesDesc: "Never miss an application deadline",
  matchScholarshipsGuidance: "Application Guidance",
  matchScholarshipsGuidanceDesc: "Step-by-step help for each application",
  matchScholarshipsCalculator: "Financial Calculator",
  matchScholarshipsCalculatorDesc: "Estimate your total funding potential",
  matchScholarshipsMerit: "Merit-Based",
  matchScholarshipsNeed: "Need-Based",
  matchScholarshipsCountry: "Country-Specific",
  matchScholarshipsField: "Field-Specific",

  // Similar Students page
  similarStudentsTitle: "Similar Students",
  similarStudentsDesc: "Connect with students who share your goals",
  similarStudentsIntro: "Find students with similar academic backgrounds, target universities, and career goals. Share experiences and learn from each other's journeys.",
  similarStudentsMatching: "Profile Matching",
  similarStudentsMatchingDesc: "Find students with similar goals and backgrounds",
  similarStudentsGroups: "Study Groups",
  similarStudentsGroupsDesc: "Join or create study groups by topic",
  similarStudentsExperience: "Experience Sharing",
  similarStudentsExperienceDesc: "Read and share application experiences",
  similarStudentsNetwork: "Build Network",
  similarStudentsNetworkDesc: "Connect with peers applying to similar universities",

  // Alumni Mentors page
  alumniMentorsTitle: "Alumni Mentors",
  alumniMentorsDesc: "Get guidance from successful alumni",
  alumniMentorsIntro: "Connect with alumni who studied abroad and can share real experiences, application tips, cultural guidance, and career advice.",
  alumniMentorsCareer: "Career Guidance",
  alumniMentorsCareerDesc: "Learn about career paths after graduation",
  alumniMentorsTips: "Application Tips",
  alumniMentorsTipsDesc: "Get advice from those who succeeded",
  alumniMentorsCulture: "Cultural Insights",
  alumniMentorsCultureDesc: "Prepare for life in a new country",
  alumniMentorsAccess: "Network Access",
  alumniMentorsAccessDesc: "Join a growing community of alumni",

  // Connect Friends page
  connectFriendsTitle: "Connect Friends",
  connectFriendsDesc: "Build your network with fellow applicants",
  connectFriendsIntro: "Meet other students preparing for study abroad. Share tips, find roommates, and build lasting friendships with fellow applicants.",
  connectFriendsInterest: "Interest Matching",
  connectFriendsInterestDesc: "Connect based on shared hobbies and goals",
  connectFriendsStudy: "Study Partners",
  connectFriendsStudyDesc: "Find study partners for test preparation",
  connectFriendsCampus: "Campus Connections",
  connectFriendsCampusDesc: "Meet students heading to the same university",
  connectFriendsCultural: "Cultural Exchange",
  connectFriendsCulturalDesc: "Learn about different cultures and backgrounds",

  // Mock Interviews page
  mockInterviewsTitle: "Mock Interviews",
  mockInterviewsDesc: "Practice for university admission interviews",
  mockInterviewsIntro: "Prepare for university interviews with AI-powered practice sessions. Get real-time feedback on your answers, body language tips, and confidence scores.",
  mockInterviewsAi: "AI Interviewer",
  mockInterviewsAiDesc: "Practice with realistic AI-generated questions",
  mockInterviewsFeedback: "Real-Time Feedback",
  mockInterviewsFeedbackDesc: "Instant analysis of your responses",
  mockInterviewsBank: "Question Bank",
  mockInterviewsBankDesc: "University-specific question collections",
  mockInterviewsTrack: "Performance Tracking",
  mockInterviewsTrackDesc: "Track improvement across sessions",
  mockInterviewsGeneral: "General Admission",
  mockInterviewsTechnical: "Technical Interview",
  mockInterviewsScholarship: "Scholarship Interview",
  mockInterviewsPortfolio: "Portfolio Review",

  // Concierge Support page
  conciergeSupportTitle: "Concierge Support",
  conciergeSupportDesc: "Premium personalized guidance for your journey",
  conciergeSupportIntro: "Get dedicated support from our expert advisors. From university selection to visa applications, we guide you through every step of studying abroad.",
  conciergeSupportPriority: "Priority Support",
  conciergeSupportPriorityDesc: "Skip the queue with priority response times",
  conciergeSupportAdvisor: "Dedicated Advisor",
  conciergeSupportAdvisorDesc: "Personal advisor assigned to your case",
  conciergeSupportDocReview: "Document Review",
  conciergeSupportDocReviewDesc: "Expert review of all application documents",
  conciergeSupportTracking: "Application Tracking",
  conciergeSupportTrackingDesc: "Real-time status updates on applications",

  // English page
  englishTitle: "English Preparation",
  englishDesc: "Prepare for IELTS, TOEFL, and academic English",
  englishIntro: "Boost your English skills for university admission. Practice reading, writing, listening, and speaking with targeted exercises for IELTS, TOEFL, and academic contexts.",
  englishIelts: "IELTS Preparation",
  englishIeltsDesc: "Full practice tests and strategy guides",
  englishToefl: "TOEFL Preparation",
  englishToeflDesc: "Section-by-section practice and tips",
  englishAcademic: "Academic English",
  englishAcademicDesc: "Writing, reading, and presentation skills",
  englishSpeaking: "Speaking Practice",
  englishSpeakingDesc: "AI-powered conversation drills",
  englishReading: "Reading",
  englishWriting: "Writing",
  englishListening: "Listening",
  englishSpeakingSkill: "Speaking",

  // Math page
  mathTitle: "Math Preparation",
  mathDesc: "Prepare for SAT, GRE, and university math requirements",
  mathIntro: "Strengthen your math skills with guided practice for standardized tests and university-level courses. Covers algebra, calculus, statistics, and problem-solving strategies.",
  mathSat: "SAT / ACT Math",
  mathSatDesc: "Practice problems and test-taking strategies",
  mathAdvanced: "Advanced Topics",
  mathAdvancedDesc: "Calculus, linear algebra, and beyond",
  mathPractice: "Practice Problems",
  mathPracticeDesc: "Thousands of problems with step-by-step solutions",
  mathProgress: "Progress Tracking",
  mathProgressDesc: "Track mastery across all topics",
  mathAlgebra: "Algebra",
  mathCalculus: "Calculus",
  mathStatistics: "Statistics",
  mathGeometry: "Geometry",

  // AI Literacy page
  aiLiteracyTitle: "AI Literacy",
  aiLiteracyDesc: "Learn to use AI tools effectively for academics",
  aiLiteracyIntro: "Understand AI fundamentals, learn prompt engineering, and explore ethical AI use in academic and professional contexts. Essential skills for the modern student.",
  aiLiteracyFundamentals: "AI Fundamentals",
  aiLiteracyFundamentalsDesc: "Core concepts of artificial intelligence",
  aiLiteracyPrompt: "Prompt Engineering",
  aiLiteracyPromptDesc: "Write effective prompts for AI tools",
  aiLiteracyData: "Data Literacy",
  aiLiteracyDataDesc: "Understand and work with data effectively",
  aiLiteracyEthics: "Ethical AI",
  aiLiteracyEthicsDesc: "Responsible use of AI in academics",

  // Get Courses page
  getCoursesTitle: "Browse Courses",
  getCoursesDesc: "Explore our course catalog for test preparation and skills",
  getCoursesIntro: "Discover self-paced courses designed to help you succeed in university applications and academics. From test prep to soft skills, find the right course for you.",
  getCoursesVideo: "Video Lectures",
  getCoursesVideoDesc: "Learn from expert instructors at your own pace",
  getCoursesInteractive: "Interactive Exercises",
  getCoursesInteractiveDesc: "Practice with hands-on activities",
  getCoursesCertificate: "Certificates",
  getCoursesCertificateDesc: "Earn certificates to boost your profile",
  getCoursesSelfPaced: "Self-Paced",
  getCoursesSelfPacedDesc: "Study on your own schedule",
  getCoursesTestPrep: "Test Preparation",
  getCoursesLanguage: "Language Courses",
  getCoursesSkills: "Soft Skills",
  getCoursesAcademic: "Academic Writing",

  // Essay Writing page
  essayWritingTitle: "Essay Writing",
  essayWritingDesc: "Learn to write compelling application essays",
  essayWritingIntro: "Master the art of essay writing with templates, AI-powered suggestions, and university-specific guidance. Turn your experiences into powerful narratives.",
  essayWritingTemplates: "Essay Templates",
  essayWritingTemplatesDesc: "Proven structures for different essay types",
  essayWritingAi: "AI Suggestions",
  essayWritingAiDesc: "Smart recommendations to improve your writing",
  essayWritingPeer: "Peer Review",
  essayWritingPeerDesc: "Get feedback from fellow applicants",
  essayWritingUniTips: "University-Specific Tips",
  essayWritingUniTipsDesc: "Tailored advice for each university's prompts",

  // Contact page (premium support + community)
  contactPremiumTitle: "Contact",
  contactPremiumDesc: "Reach our team",
  contactPremiumKicker: "Premium guidance",
  contactPremiumLeftLabel: "Premium support and booking",
  contactPremiumIntro:
    "Have questions or need help? Our team can assist with applications, documents, and planning your path—plus priority replies when it matters.",
  contactBookMeeting: "Book a meeting",
  contactBookMeetingHint: "Opens your email app with the subject prefilled; we will confirm a time.",
  contactBookMeetingEmailSubject: "Meeting request — Ilmi",
  contactAsideLabel: "Community and contact details",
  contactTelegramTitle: "Telegram channel",
  contactTelegramDesc: "Join updates, reminders, and conversation with other applicants.",
  contactOpenTelegram: "Open in Telegram",
  contactReachUsTitle: "Direct contact",
  contactEmailLabel: "Email",
  contactTelegramLabel: "Community",
  contactTelegramChannelShort: "Official Ilmi channel",
  contactReachUsFootnote:
    "For formal requests or documents, email works best. Telegram is ideal for quick questions and community announcements.",
  contactPremiumPriority: "Priority Response",
  contactPremiumPriorityDesc: "Get fast responses from our dedicated team",
  contactPremiumVideo: "Video Consultations",
  contactPremiumVideoDesc: "Schedule face-to-face video calls",
  contactPremiumDoc: "Document Help",
  contactPremiumDocDesc: "Assistance with documents and applications",
  contactPremiumTeam: "Expert Team",
  contactPremiumTeamDesc: "Support from experienced education advisors",
  contactPremiumEmail: "Email Support",
  contactPremiumEmailDesc: "Send us a message and get a response within 24 hours",
  contactPremiumChat: "Live Chat",
  contactPremiumChatDesc: "Chat with our team in real time during business hours",
  contactPremiumCall: "Schedule a Call",
  contactPremiumCallDesc: "Book a one-on-one call with an education advisor",
  contactPremiumContactUs: "Contact Us",
  contactPremiumChannels: "Contact Channels",

  // Dream University page
  dreamUniTitle: "Dream University",
  dreamUniDesc: "Plan and track your path to your dream university",
  dreamUniIntro: "Set your target universities, track application deadlines, and monitor your progress. Stay organized and focused on reaching your goals.",
  dreamUniGoals: "Goal Tracking",
  dreamUniGoalsDesc: "Set and monitor your application milestones",
  dreamUniDeadlines: "Deadline Reminders",
  dreamUniDeadlinesDesc: "Never miss an important application deadline",
  dreamUniTimeline: "Progress Timeline",
  dreamUniTimelineDesc: "Visualize your journey from start to acceptance",
  dreamUniChecklist: "Application Checklist",
  dreamUniChecklistDesc: "Track every document and requirement",

  // Search Scholarships page
  searchScholarshipsTitle: "Search Scholarships",
  searchScholarshipsDesc: "Find scholarships and funding opportunities worldwide",
  searchScholarshipsIntro: "Explore thousands of scholarships for Central Asian students. Filter by country, field, amount, and deadline to find the perfect funding opportunity.",
  searchScholarshipsType: "By Type",
  searchScholarshipsTypeDesc: "Merit, need-based, country-specific, and more",
  searchScholarshipsCountry: "By Country",
  searchScholarshipsCountryDesc: "Filter scholarships by destination country",
  searchScholarshipsDeadline: "Deadline Calendar",
  searchScholarshipsDeadlineDesc: "Track upcoming scholarship deadlines",
  searchScholarshipsEligibility: "Eligibility Check",
  searchScholarshipsEligibilityDesc: "Quick check if you qualify",

  // Profile page
  profileTitle: "My Profile",
  profileDesc: "Manage your account settings",
  profileChangePhoto: "Change Photo",
  profileFullName: "Full Name",
  profileFirstName: "First name",
  profileLastName: "Last name",
  profileEmail: "Email",
  profilePhone: "Phone",
  profileLocation: "Location",
  profileCertifications: "Certifications and qualifications",
  profileCertificationsHint:
    "One per line (for example diplomas, language tests, exam scores relevant to program requirements).",
  profileShareTitle: "Profile link",
  profileShareDesc: "Share this link or scan the code to open your profile on this device.",
  profileCopyLink: "Copy link",
  profileLinkCopied: "Link copied",
  profileLoadError: "Could not load profile. Check that you are signed in and the server is running.",
  profileSaveError: "Could not save changes.",
  profileSaveSuccess: "Profile saved.",
  profileGuestHint:
    "Sign in to load and save your profile, certifications, and share link.",
  profileSaving: "Saving…",
  profileApplications: "Applications",
  profileScholarships: "Scholarships",
  profileViews: "Profile Views",
  profilePremium: "Premium Member",
  profilePremiumDesc: "You have access to all premium features",
  profilePremiumMatch: "Unlimited university matches",
  profilePremiumSupport: "Priority application support",
  profilePremiumAlerts: "Exclusive scholarship alerts",
  profilePremiumMentor: "Direct mentor access",
  profileSave: "Save Changes",
  profileLogout: "Logout",

  // Dashboard
  dashMain: "Main",
  dashDreamUniversity: "Dream University",
  dashDreamPeakLabel: "UCA track",
  dashDreamCardTagline: "Your north-star school — keep documents, scores, and deadlines aligned with this goal.",
  dashDreamPillFit: "92% fit with your profile",
  dashDreamPillDeadline: "Next: UCA application · Oct 6",
  dashDreamPillDocs: "Pack list · 4 open",
  dashDreamReadinessLabel: "Readiness for this goal",
  dashSearchUniversities: "Search Universities",
  dashFavoriteUniversities: "Favorite Universities",
  dashSearchFields: "Search Fields",
  dashSearchPrograms: "Search Programs",
  dashFavoritePrograms: "Favorite Programs",
  dashSearchScholarships: "Search Scholarships",
  dashAiMatching: "AI & Smart Matching",
  dashMatchUniversities: "Match Universities",
  dashMatchScholarships: "Match Scholarships",
  dashEssayReview: "Essay Review",
  dashSimilarStudents: "Similar Students",
  dashCommunity: "Community",
  dashOthers: "Others",
  dashConnections: "Connections",
  dashConnectFriends: "Connect Friends",
  dashAlumniMentors: "Alumni Mentors",
  dashPremiumServices: "Premium Services",
  dashEssayReviews: "Essay Reviews",
  dashMockInterviews: "Mock Interviews",
  dashConciergeSupport: "Concierge Support",
  dashLearning: "Learning & Courses",
  dashGetCourses: "Get Courses",
  dashMath: "Math",
  dashEnglish: "English",
  dashEssayWriting: "Essay Writing",
  dashAiLiteracy: "AI Literacy",
  dashDashboard: "Dashboard",
  dashTagline: "Your university journey starts here",
  dashSendInfo: "Send Info & Get Premium",
  dashJoinCommunity: "Join Our Community",
  dashLogout: "Logout",
  dashNotifications: "Notifications",
  dashProfile: "Profile",
  dashWelcomeBackPrefix: "Welcome back,",
  dashDefaultDisplayName: "Name Surname",
  dashOpenPage: "Open page",
  dashCardDashboardDesc: "Return to your main dashboard overview.",
  dashCardDreamDesc: "Review your dream university goals and progress.",
  dashCardUniversitiesDesc: "Explore universities and compare options.",
  dashCardFavoriteUniversitiesDesc: "Open universities you have saved.",
  dashCardFieldsDesc: "Browse study fields that match your interests.",
  dashCardProgramsDesc: "Discover degree programs from top schools.",
  dashCardFavoriteProgramsDesc: "See your saved programs in one place.",
  dashCardScholarshipsDesc: "Find scholarships you can apply for.",
  dashCardMatchUniversitiesDesc: "Get AI-powered university matches.",
  dashCardMatchScholarshipsDesc: "Get AI-powered scholarship matches.",
  dashCardSimilarStudentsDesc: "See insights from similar student profiles.",
  dashCardFriendsDesc: "Connect with friends on the same journey.",
  dashCardMentorsDesc: "Find alumni mentors for guidance.",
  dashCardProfileDesc: "View and update your profile settings.",
  dashCardSendInfoDesc: "Send your details and request premium support.",
  dashContactPremium: "Contact",
  dashNavAiTools: "AI tools",
  dashNavApply: "Apply",
  dashMyAcademics: "My Academics",
  dashMyApplications: "My Applications",
  dashNavOpportunities: "Opportunities",
  dashJobs: "Jobs & Internships",
  dashCourses: "Courses",
  dashNavAdmin: "Admin",
  dashAdminReview: "Scraping Review",
  dashNavFriendsAndMentors: "Friends",
  dashNavSectionAiUniversities: "AI · Universities",
  dashNavSectionAiScholarships: "AI · Scholarships",
  dashNavSectionAiSimilarStudents: "AI · Similar students",
  dashNavSectionConnectFriends: "Connect Friends",
  dashNavSectionAlumniMentors: "Alumni Mentors",
  dashNavSectionContactPremium: "Contact",
  dashCardContactPremiumDesc: "Reach the team, book time, or join Telegram.",
  dashAiDashboardUniTitle: "AI · Best university matches",
  dashAiShowcaseSeeWholeList: "See the whole list",
  dashCtaSeeAllUniversityMatches: "See all university matches",
  dashCtaSeeAllScholarshipMatches: "See all scholarship matches",
  dashCtaSeeAllFriends: "See all friends",
  dashCtaBrowseAllMentors: "Browse all mentors",
  dashConnAsideFriendsLabel: "Friends in this preview",
  dashFriendsCombinedSectionTitle: "Friends & people to meet",
  dashFriendsSimilarColumnTitle: "People you could connect with",
  dashFriendsSimilarSeeMore: "See more",
  dashFriendsOnlineColumnTitle: "Your friends",
  dashFriendsOnlineNow: "Online now",
  dashFriendsAllFriendsLabel: "All friends",
  dashFriendsSeeCountCta: "See {{count}} friends",
  dashFriendsOnlineEmpty: "No one online right now",
  dashConnAsideMentorsLabel: "Mentors in this preview",
  dashSimilarStudentsAddFriend: "Add friend",
  dashAiShowcaseUniCtaHint: "Full matcher with filters and every pick.",
  dashAiShowcaseScholCtaHint: "Browse every scholarship and eligibility detail.",
  dashAiDashboardScholTitle: "AI · Best scholarship matches",
  dashAiDashboardPeersTitle: "AI · Similar students",
  dashAiUniMatchLead: "Schools ranked for fit with your profile, goals, and scores.",
  dashAiScholMatchLead: "Scholarships you are most likely to qualify for next.",
  dashAiPeersMatchLead: "Peers with overlapping goals so you can learn from their path.",
  dashAiScholCardIntlTitle: "Global Merit Fund",
  dashAiScholCardIntlMeta: "International applicants · Deadline Apr 15",
  dashSimilarStudent2Name: "Eldar M.",
  dashSimilarStudent2Desc: "STEM track, scholarship-first applications.",
  dashSimilarStudent3Name: "Timur B.",
  dashSimilarStudent3Desc: "Europe-focused list, strong English scores.",
  dashSimilarTagField: "Same field",
  dashSimilarTagRegion: "Same region focus",
  dashSimilarTagScores: "Similar scores",
  dashSimilarOverlapGpa: "Similar GPA band",
  dashSimilarOverlapShortlist: "Overlapping shortlist picks",
  dashSimilarOverlapIntake: "Same target intake",
  dashSimilarOverlapScholarFirst: "Scholarship-first strategy",
  dashSimilarOverlapEuTargets: "Overlapping EU targets",
  dashSimilarOverlapAidFocus: "Both tracking need-based aid",
  dashSimilarOverlapEuropeList: "Europe-heavy lists",
  dashSimilarOverlapIelts: "Comparable English scores",
  dashSimilarOverlapStemExtra: "Similar STEM activities",
  dashSimilaritiesLabel: "Similarities with your profile",
  dashFriend2SampleName: "Erkeaiym D.",
  dashFriend2SampleDesc: "Favorite list overlap: Netherlands & Germany.",
  dashFriend3SampleName: "Sultan K.",
  dashFriend3SampleDesc: "Essay swap partner · last active yesterday.",
  dashMentor2SampleName: "Laura N.",
  dashMentor2SampleDesc: "MBA admissions, interview prep, and CV reviews.",
  dashMentorBadgeStem: "Engineering",
  dashMentorBadgeMba: "Business & MBA",
  dashMentorVerified: "Verified mentor",
  dashAway: "Away",
  dashConnectionFriendsTitle: "Connect · Friends",
  dashConnectionFriendsLead: "People you study alongside or may want to message.",
  dashConnectionMentorsTitle: "Connect · Alumni mentors",
  dashConnectionMentorsLead: "Graduates who help with applications and interviews.",
  dashConnectionActionChat: "Open chat",
  dashConnectionActionMentor: "View profile",
  dashConnectionPremiumTitle: "Premium support",
  dashConnectionPremiumLead: "Dedicated help for deadlines, essays, and strategy.",
  dashConnectionPremiumPoint1: "Priority responses from the ilmi team",
  dashConnectionPremiumPoint2: "Essay and interview reviews with clear feedback",
  dashConnectionPremiumPoint3: "Concierge-style planning for your shortlist",
  dashContactSubheading: "Contact",
  dashContactDetailsTitle: "Reach us",
  dashContactCompactHint: "Quick links below. Use the Contact page when you want to send a full message.",
  dashContactFullPageCta: "Open full Contact page",
  dashContactUsTitle: "Contact Us",
  dashContactPhoneLabel: "Phone",
  dashContactTelegramQrCaption: "Just scan/click to open our Telegram channel.",
  dashContactSocialListLabel: "Social and community links",
  dashContactFormTitle: "Send us a message",
  dashContactFormName: "Full name",
  dashContactFormNamePh: "Enter your full name",
  dashContactFormEmail: "Email",
  dashContactFormEmailPh: "you@example.com",
  dashContactFormTopic: "Topic",
  dashContactFormTopicPh: "What do you need help with?",
  dashContactFormMessage: "Message",
  dashContactFormMessagePh:
    "Write your message here — include enough detail so we can help you properly.",
  dashContactFormSubmit: "Send Message",
  dashContactFormThanks: "Thanks! We received your message and will reply soon.",
  dashContactFormAgain: "Send another message",
  contactPlatformLinkedIn: "LinkedIn",
  contactPlatformTelegram: "Telegram",
  contactPlatformInstagram: "Instagram",
  contactPlatformX: "X",
  contactPlatformYouTube: "YouTube",
  contactPlatformTikTok: "TikTok",
  dashPerfectMatch: "Perfect Match",
  dashUcaName: "University of Central Asia",
  dashUcaLocation: "Naryn, Kyrgyzstan",
  dashStartClimb: "Start Climb",
  dashPackList: "Pack List",
  dashUpcomingDeadlines: "Upcoming Deadlines",
  dashShowAll: "Show All",
  dashUcaApplication: "UCA Application",
  dashAucaScholarship: "AUCA Scholarship",
  dashMitApplication: "MIT Application",
  dashOct6: "Oct 6, 2025",
  dashOct8: "Oct 8, 2025",
  dashDeadlineFarTitle: "Stanford SCEA · portfolio & transcripts",
  dashDeadlineFarDate: "Jan 15, 2027",
  dashTimeAbout9mo: "~9 months",
  dashTime45m: "45 min left",
  dashTime2h15m: "2h 15m left",
  dashTime2d3h: "2d 3h left",
  dashViewsTitle: "University & Scholarship Views",
  dashViewsTotal: "Sample data",
  dashViewsDesc: "Track how many universities and scholarships you have viewed",
  dashRecommendedUniversities: "Recommended Universities",
  dashPreviewSearchPlaceholder: "Search by name or location…",
  dashFilters: "Filters",
  dashFilterAll: "All",
  dashFilterEurope: "Europe",
  dashFilterEnglishTaught: "English taught",
  dashSearchPopularFilters: "Popular filters",
  dashSearchClearFilters: "Clear all",
  dashStartSearching: "Start searching",
  dashSearchUniPlaceholder: "Search by university or college name…",
  dashUniPopUnder10k: "Under €10k / year",
  dashUniPopUnder5k: "≤ €5k / year",
  dashUniPopBusinessLaw: "Business & law",
  dashUniPopMedicine: "Medicine & sciences",
  dashUniPopArts: "Arts & design",
  dashFieldTeaserCs: "Computer science & IT",
  dashFieldTeaserBusiness: "Business & management",
  dashFieldTeaserMedicine: "Medicine & health",
  dashFieldTeaserEngineering: "Engineering",
  dashFieldTeaserArts: "Arts & design",
  dashScholarshipUrlHintMerit: "You opened merit-based scholarships from the dashboard.",
  dashScholarshipUrlHintNeed: "You opened need-based scholarships from the dashboard.",
  dashSearchTeaserSearchUniversities: "Search universities",
  dashSearchTeaserSearchFields: "Search fields",
  dashSearchTeaserSearchScholarships: "Search scholarships",
  dashSearchFieldPlaceholder: "Search by field name…",
  dashSearchScholarshipPlaceholder: "Search scholarships…",
  dashPreviewMatches: "matches",
  dashPreviewNoResults: "No matches for this filter.",
  dashPreviewUniversitiesLead: "Preview of search: filters on the left narrow the list on the right.",
  dashPreviewProgramsLead: "Preview of program search with quick filters and a short list.",
  dashPreviewScholarshipsLead: "Preview of scholarship search with type filters.",
  dashProgramFilterMaster: "Master",
  dashProgramFilterBachelor: "Bachelor",
  dashScholarshipFilterMerit: "Merit",
  dashScholarshipFilterNeed: "Need-based",
  dashProgramPreviewMsTitle: "M.Sc. Computer Science",
  dashProgramPreviewMsMeta: "STEM · Fall intake",
  dashProgramPreviewBsTitle: "B.A. International Relations",
  dashProgramPreviewBsMeta: "Social sciences · Rolling",
  dashProgramPreviewMbaTitle: "MBA",
  dashProgramPreviewMbaMeta: "Business · GMAT friendly",
  dashScholPreviewMeritTitle: "Merit Excellence Award",
  dashScholPreviewMeritMeta: "Up to €5,000 · Deadline Mar 1",
  dashScholPreviewNeedTitle: "Need-based Support Grant",
  dashScholPreviewNeedMeta: "Income-based · Rolling",
  dashApplicationStatus: "Application Status",
  dashStatusCardLead: "Every status you track on ilmi — counts and share of your pipeline.",
  dashStatusDonutLabel: "Applications",
  dashStatusTotal: "15 Total",
  dashStatusPlan: "Plan to Apply",
  dashStatusApplied: "Applied",
  dashStatusAccepted: "Accepted",
  dashStatusWaitlist: "Waitlist",
  dashStatusRejected: "Rejected",
  dashRank: "Rank",
  dashMatch: "Match",
  dashUni1Name: "Massachusetts Institute of Technology",
  dashUni1Loc: "Cambridge, MA, USA",
  dashUni1Rank: "#1",
  dashUni1Match: "95%",
  dashUni2Name: "Stanford University",
  dashUni2Loc: "Stanford, CA, USA",
  dashUni2Rank: "#2",
  dashUni2Match: "92%",
  dashAiSampleUniversities: "Top matches based on profile and goals.",
  dashAiSampleScholarships: "Scholarships aligned with budget and scores.",
  dashAiSampleStudents: "Students with similar paths and outcomes.",
  dashFriendSampleName: "Aizada K.",
  dashFriendSampleDesc: "Applying to Data Science programs.",
  dashMentorSampleName: "Murat R.",
  dashMentorSampleDesc: "Alumni mentor for engineering admissions.",
  dashOnline: "Online",

  appTimelineTitle: "Application Timeline",
  appTimelineDesc: "Track your application deadlines and progress",
  appTimelineFeature1: "Deadline Tracking",
  appTimelineFeature1Desc: "Never miss an application deadline with smart reminders",
  appTimelineFeature2: "Progress Monitoring",
  appTimelineFeature2Desc: "See your application status at a glance across all universities",
  appTimelineFeature3: "Milestone Planning",
  appTimelineFeature3Desc: "Plan key milestones from test prep to visa applications",
  appTimelineFeature4: "Calendar Sync",
  appTimelineFeature4Desc: "Sync deadlines to your calendar for seamless scheduling",
  appTimelineCta: "Start Tracking",

  myDocsTitle: "My Documents",
  myDocsDesc: "Manage your application documents and transcripts",
  myDocsFeature1: "Document Storage",
  myDocsFeature1Desc: "Securely store transcripts, essays, and recommendations",
  myDocsFeature2: "Version Control",
  myDocsFeature2Desc: "Track changes and manage multiple essay drafts",
  myDocsFeature3: "Quick Share",
  myDocsFeature3Desc: "Share documents with advisors and mentors for review",
  myDocsFeature4: "Checklist Manager",
  myDocsFeature4Desc: "Track required documents for each university application",
  myDocsCta: "Upload Documents",

  careerAnalysisTitle: "Career Path Analysis",
  careerAnalysisDesc: "Analyze potential career paths and opportunities",
  careerAnalysisFeature1: "Industry Insights",
  careerAnalysisFeature1Desc: "Explore career trends and salary data by industry",
  careerAnalysisFeature2: "Skill Mapping",
  careerAnalysisFeature2Desc: "Match your skills to in-demand career opportunities",
  careerAnalysisFeature3: "Path Comparison",
  careerAnalysisFeature3Desc: "Compare career paths side-by-side with growth projections",
  careerAnalysisFeature4: "Goal Setting",
  careerAnalysisFeature4Desc: "Set career milestones and track progress toward your goals",
  careerAnalysisCta: "Analyze Careers",

  internshipsTitle: "Internships Matching",
  internshipsDesc: "Find internship opportunities that match your goals",
  internshipsFeature1: "Smart Matching",
  internshipsFeature1Desc: "AI-powered matching connects you with relevant internships",
  internshipsFeature2: "Application Tracker",
  internshipsFeature2Desc: "Track your internship applications in one place",
  internshipsFeature3: "Company Research",
  internshipsFeature3Desc: "In-depth profiles of companies offering internships",
  internshipsFeature4: "Skill Building",
  internshipsFeature4Desc: "Identify skills to develop for your target internships",
  internshipsCta: "Find Internships",

  mastersTitle: "Masters Matching",
  mastersDesc: "Explore graduate programs worldwide",
  mastersFeature1: "Program Search",
  mastersFeature1Desc: "Explore masters programs across universities globally",
  mastersFeature2: "Admission Insights",
  mastersFeature2Desc: "Understand admission requirements and acceptance rates",
  mastersFeature3: "Funding Options",
  mastersFeature3Desc: "Discover scholarships and assistantships for graduate study",
  mastersFeature4: "Career Outcomes",
  mastersFeature4Desc: "See employment statistics for program graduates",
  mastersCta: "Explore Programs",

  uniReelsTitle: "University Reels",
  uniReelsDesc: "Watch university tours and student life videos",
  uniReelsFeature1: "Campus Tours",
  uniReelsFeature1Desc: "Virtual tours of campuses from around the world",
  uniReelsFeature2: "Student Stories",
  uniReelsFeature2Desc: "Hear from current students about their experiences",
  uniReelsFeature3: "City Guides",
  uniReelsFeature3Desc: "Explore the cities where top universities are located",
  uniReelsFeature4: "Event Highlights",
  uniReelsFeature4Desc: "Watch highlights from open days and campus events",
  uniReelsCta: "Watch Now",

  privacyTitle: "My Privacy Dashboard",
  privacyDesc: "Manage your privacy settings and data",
  privacyFeature1: "Data Control",
  privacyFeature1Desc: "See and manage all data we collect about you",
  privacyFeature2: "Visibility Settings",
  privacyFeature2Desc: "Control who can see your profile and activity",
  privacyFeature3: "Export Data",
  privacyFeature3Desc: "Download a copy of all your personal data anytime",
  privacyFeature4: "Delete Account",
  privacyFeature4Desc: "Permanently remove your account and all associated data",
  privacyCta: "Review Settings",

  studyTogetherTitle: "Study Together",
  studyTogetherDesc: "Connect with peers and study groups",
  studyTogetherFeature1: "Group Matching",
  studyTogetherFeature1Desc: "Find study partners with similar goals and schedules",
  studyTogetherFeature2: "Live Sessions",
  studyTogetherFeature2Desc: "Join real-time study sessions with peers worldwide",
  studyTogetherFeature3: "Resource Sharing",
  studyTogetherFeature3Desc: "Share notes, materials, and study strategies",
  studyTogetherFeature4: "Progress Together",
  studyTogetherFeature4Desc: "Track shared goals and motivate each other",
  studyTogetherCta: "Find Study Partners",

  // SendInfo page
  sendInfoPageTitle: "Send Info & Get Premium",
  sendInfoOfferHeadline: "Get 7 Days Premium FREE!",
  sendInfoOfferBody:
    "Send us your university or scholarship inquiry and receive 7 days of premium access instantly.",
  sendInfoTabUniversity: "University Info",
  sendInfoTabScholarship: "Scholarship Info",
  sendInfoTabApplication: "Application Help",
  sendInfoTabMeeting: "Book Meeting",
  sendInfoTabOther: "Other Request",
  sendInfoFieldFullName: "Full Name",
  sendInfoFieldEmail: "Email",
  sendInfoFieldPhone: "Phone",
  sendInfoFieldUniversity: "University",
  sendInfoFieldUniversityInterest: "University of Interest",
  sendInfoFieldProgram: "Program",
  sendInfoFieldProgramMajor: "Program/Major",
  sendInfoFieldGpa: "Your GPA",
  sendInfoFieldAdditional: "Additional Information",
  sendInfoFieldScholarshipName: "Scholarship Name",
  sendInfoFieldAchievements: "Your Academic Achievements",
  sendInfoFieldDeadline: "Application Deadline",
  sendInfoFieldHelp: "What help do you need?",
  sendInfoFieldMeetingType: "Meeting Type",
  sendInfoFieldPreferredDate: "Preferred Date",
  sendInfoFieldPreferredTime: "Preferred Time",
  sendInfoFieldNotes: "Additional Notes",
  sendInfoFieldSubject: "Subject",
  sendInfoFieldMessage: "Message",
  sendInfoPhFullName: "Enter your full name",
  sendInfoPhEmail: "Enter your email",
  sendInfoPhPhone: "Enter your phone number",
  sendInfoPhUniversityInterest: "Which university are you interested in?",
  sendInfoPhProgramInterest: "What program are you interested in?",
  sendInfoPhGpa: "Enter your GPA",
  sendInfoPhGoals: "Tell us more about your goals...",
  sendInfoPhScholarship: "Which scholarship are you interested in?",
  sendInfoPhUniversityOpt: "Associated university (if any)",
  sendInfoPhAchievements: "Describe your achievements...",
  sendInfoPhUniversityRequired: "Which university?",
  sendInfoPhProgramRequired: "Which program?",
  sendInfoPhHelp: "Describe what assistance you need...",
  sendInfoPhSubject: "What is your request about?",
  sendInfoPhContact: "Tell us how we can help...",
  sendInfoPhNotes: "Any additional information...",
  sendInfoMeetingSelect: "Select meeting type",
  sendInfoMeetingConsult: "General Consultation",
  sendInfoMeetingAppReview: "Application Review",
  sendInfoMeetingScholarship: "Scholarship Advice",
  sendInfoMeetingCareer: "Career Guidance",
  sendInfoSubmit: "Send Information & Get Premium",
  sendInfoSubmitting: "Sending...",
  sendInfoError: "Couldn't send your request. Please check your connection and try again.",
  sendInfoSuccessTitle: "Information Sent Successfully!",
  sendInfoSuccessBody:
    "Thank you for reaching out. Our team will review your information and contact you soon.",
  sendInfoPremiumActivated: "Premium Access Activated!",
  sendInfoPremiumActivatedBody: "You now have access to premium features for 7 days.",
  sendInfoBackToDashboard: "Back to Dashboard",
  sendInfoTitleBack: "Back to Dashboard",
  required: "required",

  // Search shared
  smartMatch: "Smart Match",

  // PublicHomePage extras
  aboutCoreAccess: "Core Access Included",
  aboutGlobal: "Global",
  contactLabelEmail: "Email",
  contactLabelTopic: "Topic",

  // Login page
  loginSubtitle: "Welcome back! Please sign in to your account.",
  loginEmailLabel: "Email Address",
  loginEmailPlaceholder: "Enter your email",
  loginPasswordLabel: "Password",
  loginPasswordPlaceholder: "Enter your password",
  loginSubmit: "Sign In",
  loginSubmitting: "Signing In...",
  loginNoAccount: "Don't have an account?",
  loginSignUpHere: "Sign up here",
  loginContinueAsGuest: "Continue as guest",
  loginGuestSuffix: "— bypass login and try the app.",
  loginForgotLink: "Forgot password?",
  forgotSubtitle: "Enter your email and we'll send a reset link.",
  forgotSubmit: "Send reset link",
  forgotSent: "If that email is registered, a reset link is on its way. Check your inbox.",
  forgotBackToLogin: "Back to sign in",
  forgotError: "Couldn't start the reset. Please try again.",
  resetSubtitle: "Choose a new password.",
  resetNoToken: "This reset link is missing its token. Request a new one.",
  resetDone: "Password updated. You can sign in now.",
  resetGoToLogin: "Go to sign in",
  resetNewPasswordLabel: "New password",
  resetNewPasswordPlaceholder: "At least 8 characters",
  resetSubmit: "Update password",
  resetTooShort: "Password must be at least 8 characters.",
  resetError: "This reset link is invalid or has expired.",
  verifyVerifying: "Verifying your email…",
  verifyOk: "Your email is verified. Thank you!",
  verifyError: "This verification link is invalid or has expired.",
  loginFailedMessage: "Login failed. Check your email and password.",

  // Register page
  registerSubtitle: "Create your account — choose your country to join.",
  registerFirstName: "First name",
  registerLastName: "Last name",
  registerEmail: "Email",
  registerEmailPlaceholder: "you@example.com",
  registerPassword: "Password",
  registerCountry: "Country",
  registerCountriesLoading: "Loading countries...",
  registerSelectCountry: "Select your country",
  registerCountryHint: "Required to create your account.",
  registerNoCountriesHint:
    "No countries loaded. Start the backend and ensure the database has countries, or use \"Continue as guest\" below.",
  registerSubmit: "Create account & join",
  registerSubmitting: "Creating account...",
  registerHaveAccount: "Already have an account?",
  registerLogIn: "Log in",
  registerGuestSuffix: "— try the app without signing up.",
  registerSelectCountryError: "Please select a country.",
  registerFillAllError: "Please fill in all fields.",
  registerFailedError: "Registration failed.",

  // PublicHome contact + nav extras
  publicSeeHowItWorks: "See how it works on YouTube",
  publicAboutUs: "About Us",
  publicSupportQr: "Support QR",
  publicFaq: "Frequently Asked Questions",
  publicContactUs: "Contact Us",
  publicSendMessage: "Send us a message",
  publicMessageSent: "Thanks! Your message has been sent.",
  publicFullName: "Full name",
  publicFullNamePh: "Enter your full name",
  publicTopicPh: "What do you need help with?",
  publicMessageLabel: "Message",
  publicMessagePh: "Write your message",
  publicFooterPrivacy: "Privacy",
  publicFooterTerms: "Terms",
  publicFooterContact: "Contact",
  publicStudentSupport: "Student Support",
  publicUnisWorldwide: "Universities Worldwide",
  publicSupportNumber: "Support Number",
  publicQrPlaceholder: "Add your support QR image here",
  publicAboutLead:
    "ilmi helps students worldwide find the right university and scholarships through AI-powered matching. Our mission is to make higher education accessible to everyone.",
  publicAboutCopy:
    "Core access for university and scholarship discovery is included, with practical tools students can use right away.",
  publicMainServices: "Main Services",

  // Search Universities extras
  searchUniNamePlaceholder: "Search by university or college name…",
  searchUniClearAll: "Clear all",
  searchUniTuitionRange: "Tuition per year (€)",
  searchUniMatching: "Matching institutions",
  searchUniLoadingList: "Loading universities...",

  // University detail
  uniDetailLoadingTitle: "Loading...",
  uniDetailLoadingBody: "Loading university details...",
  uniDetailNotFound: "Institution not found",

  // Search Universities options
  searchUniPopularUnder10k: "Under €10k / year",
  searchUniPopularUnder5k: "≤ €5k / year",
  searchUniPopularEnglish: "English taught",
  searchUniPopularEurope: "Europe",
  searchUniPopularBusiness: "Business & law",
  searchUniPopularMedicine: "Medicine & sciences",
  searchUniPopularArts: "Arts & design",
  searchUniInstAll: "All",
  searchUniInstUniversities: "Universities only",
  searchUniInstColleges: "Colleges only",
  searchUniDegreeAll: "All levels",
  searchUniDegreeAssociate: "Associate",
  searchUniDegreeDiploma: "Diploma",
  searchUniDegreeBachelor: "Bachelor",
  searchUniDegreeMaster: "Master",
  searchUniDegreePhd: "PhD / Doctorate",
  searchUniLangAny: "Any language",
  searchUniLangEnglish: "English",
  searchUniLangGerman: "German",
  searchUniLangFrench: "French",
  searchUniLangSpanish: "Spanish",
  searchUniLangDutch: "Dutch",
  searchUniLangCatalan: "Catalan",
  searchUniAllCountries: "All countries",
  searchUniAllFields: "All fields",
  searchUniAllCities: "All cities in this country",

  // Search Universities JSX labels
  searchResultOne: "result",
  searchResultMany: "results",
  searchUniNameLabel: "Search by institution name",
  searchUniPopularHeading: "Popular filters",
  searchUniInstTypeLabel: "Institution type",
  searchUniCountryLabel: "Country",
  searchUniCityLabel: "City / region",
  searchUniFieldLabel: "Field of study",
  searchUniDegreeLabel: "Degree level",
  searchUniLanguageLabel: "Language of instruction",
  searchUniMin: "Min",
  searchUniMax: "Max",

  // Landing features
  featureSmartMatchTitle: "Smart University Matching",
  featureSmartMatchDesc:
    "Our AI reviews your profile, goals, and preferences to recommend universities that fit your path.",
  featureScholarshipTitle: "Scholarship and Funding Guidance",
  featureScholarshipDesc:
    "Find scholarships, grants, and aid options to plan your education budget with confidence.",
  featureInsightsTitle: "Admission Insights",
  featureInsightsDesc:
    "Compare admission trends, program details, and outcomes so you can make informed choices.",
  featureGlobalTitle: "Global University Access",
  featureGlobalDesc:
    "Explore universities in multiple countries with clear program and admission information.",
  featureAnyDeviceTitle: "Easy Access on Any Device",
  featureAnyDeviceDesc:
    "Use ilmi smoothly on mobile or desktop to check matches and track your next steps.",
  featureAdvisorTitle: "Advisor Support",
  featureAdvisorDesc:
    "Get practical help from advisors who understand admissions, applications, and planning.",

  // Programs/Fields options
  programsAllCategories: "All categories",
  programsAllCountries: "All countries",
  programsTuitionFree: "Free / public",
  searchUniLangItalian: "Italian",
  searchUniLangJapanese: "Japanese",
  searchUniLangKorean: "Korean",

  // Dashboard chart
  chartUnis: "Universities",
  chartScholarshipsLabel: "Scholarships",
  monthJan: "Jan",
  monthFeb: "Feb",
  monthMar: "Mar",
  monthApr: "Apr",
  monthMay: "May",
  monthJun: "Jun",

  // PublicHome hero
  heroTitleLine2: "Guidance for your study journey",
  heroDescription2:
    "Get clear guidance on universities, scholarships, admissions, and master's programs in one simple platform.",
  heroCtaPrimary: "Get started",
  heroCtaSecondary: "How it works",

  // PublicHome FAQ
  faqQ1: "Does ilmi cost anything to use?",
  faqA1:
    "Core features—university matching, scholarship discovery, and key insights—are included with no paywall. Optional premium support is paid.",
  faqQ2: "How does the matching process work?",
  faqA2:
    "Our AI reviews your goals, profile, and preferences, then shows a ranked list of universities and scholarships that fit your needs.",
  faqQ3: "Which countries and universities are included?",
  faqA3:
    "We include universities and scholarship opportunities across many countries. You can filter by country, program, and funding options.",
  faqQ4: "How can I support ilmi?",
  faqA4:
    "You can support us through donations listed in the About section. Your support helps us keep core access available for all students.",

  // UI components
  searchFieldDefaultPlaceholder: "Search institutions",
  selectFieldDefaultPlaceholder: "Select option",
  skyToggleToLight: "Switch to light mode",
  skyToggleToDark: "Switch to dark mode",

  // Generic errors
  errFailedLoadFavorites: "Failed to load favorites.",
  errFailedRemoveFavorite: "Failed to remove favorite.",

  // Profile — interests section
  interestsTitle: "Your interests",
  interestsIntro:
    "Tell us the degree levels and fields you're interested in. We'll use these to tailor your matches.",
  interestsDegreeLabel: "Interested degree",
  interestsFieldLabel: "Interested field",
  interestsAdded: "Added",
  interestsAddDegree: "Add degree",
  interestsAddField: "Add field",
  interestsNoDegrees: "No degrees yet",
  interestsNoFields: "No fields yet",
  interestsRemoveAria: "remove",

  // Profile — funding section
  fundingTitle: "Budget — funding sources",
  fundingTotalLabel: "Total",
  fundingHint:
    "Add what you can put toward tuition (family, savings, scholarship, loan). The total becomes your budget for affordability matching.",
  fundingRemoveAria: "Remove {label}",
  fundingSourcePlaceholder: "Source (e.g. Family)",
  fundingAmountPlaceholder: "Amount/yr (USD)",
  fundingAdd: "Add",

  // Profile — max budget field
  profileMaxBudget: "Max budget / year (USD)",
  profileMaxBudgetPlaceholder: "e.g. 15000",

  // Dashboard — empty states & match badges
  dashNoDeadlines: "No deadlines yet. Track an application to see its deadline here.",
  dashNoTopMatches:
    "Add your grades on the matching page to see your real top university matches here.",
  dashNoTopScholarships:
    "Once scholarships are available for your profile, your best matches show here.",
  dashEligible: "Eligible",
  dashNotYet: "Not yet",
  dashNotEligible: "Not eligible",

  // University matches page
  matchTitle: "University Matches",
  matchDescriptionGuest: "See which programs you qualify for, ranked by fit.",
  matchDescription: "Enter your academic info to see which programs you qualify for.",
  matchGuestCtaTitle: "Create a free account to get matched",
  matchGuestCtaDesc:
    "Matching uses your grades and exam scores, so it needs a saved profile. Guests can browse, but matches require an account.",
  matchGuestSignUp: "Sign up",
  matchAcademicInfoTitle: "Your academic info",
  matchAcademicInfoIntro:
    "Add your subject grades and an exam score. We compare them against each program's published requirements — your data is saved to your profile.",
  matchGradingSystem: "Grading system",
  matchHighestDegree: "Highest degree",
  matchSubjects: "Subjects",
  matchSubjectPlaceholder: "Subject",
  matchGradePlaceholder: "Grade",
  matchRemoveSubject: "Remove subject",
  matchAddSubject: "+ Add subject",
  matchExam: "Exam",
  matchScore: "Score",
  matchScorePlaceholder: "e.g. 100",
  matchMaxScore: "Max score",
  matchMaxScorePlaceholder: "e.g. 120",
  matchSaving: "Saving…",
  matchSaveAndFind: "Save & Find Matches",
  matchFinding: "Finding your matches…",
  matchPromptSave: "Add your grades above and select “Save & Find Matches”.",
  matchNoPrograms: "No programs available yet. Check back once programs are added.",
  matchEligibleOf: "{eligible} eligible of {total} programs",
  matchTuitionFree: "Tuition-free",
  matchGradingGpa4: "GPA (4.0 scale)",
  matchGradingGpa5: "GPA (5.0 scale)",
  matchGradingFive: "5-point (CIS)",
  matchGradingTen: "10-point",
  matchDegreeHighSchool: "High school diploma",
  matchDegreeAssociate: "Associate",
  matchDegreeBachelor: "Bachelor",
  matchDegreeMaster: "Master",
  matchDegreeDoctorate: "Doctorate",
  matchExamNone: "No exam",
  matchTierSafety: "Safety",
  matchTierTarget: "Target",
  matchTierReach: "Reach",
  matchTierFarReach: "Far reach",
  matchTranscriptSelfReported: "Self-reported",
  matchTuitionPerYear: "{amount} {currency}/yr",
  matchPercentFit: "{fit}% fit",
  matchPercentAcademic: "{score}% academic",
  matchEligible: "Eligible",
  matchNotYetEligible: "Not yet eligible",
  matchAllMet: "✓ You meet all requirements.",
  matchWhatsMissing: "What's missing",
  matchNeedHave: "need {required}, have {actual}",
  matchTracking: "✓ Tracking",
  matchAdding: "Adding…",
  matchTrackApplication: "+ Track application",

  // My applications page
  appsTitle: "My Applications",
  appsDescription:
    "Track every program you're applying to — status, deadlines, and notes in one place.",
  appsNoDeadlineSet: "No deadline set",
  appsPastDue: "Past due ({days}d ago)",
  appsDueToday: "Due today",
  appsDaysLeft: "{days}d left",
  appsLoading: "Loading your applications…",
  appsEmptyTitle: "No applications yet",
  appsEmptyHintBefore: "Find programs that fit you and tap",
  appsTrackApplicationQuoted: "“Track application”",
  appsEmptyHintAfter: "to start a checklist with deadlines.",
  appsFindMatches: "Find your matches →",
  appsCountOne: "{count} application",
  appsCountMany: "{count} applications",
  appsStatus: "Status",
  appsDeadline: "Deadline",
  appsRemove: "Remove",
  appsSubmitted: "Submitted {date}",
  appsHideChecklist: "▾ Hide checklist",
  appsShowChecklist: "▸ Checklist",

  // Application checklist
  checklistLoading: "Loading checklist…",
  checklistDone: "{done}/{total} done",
  checklistRemoveTask: "Remove task: {title}",
  checklistAddPlaceholder: "Add a task…",
  checklistAdd: "Add",

  // University detail page
  uniDetailBackToSearch: "Back to search",
  uniDetailNoMatch: "No university matches “{slug}”.",
  uniDetailReturnToSearch: "Return to search",
  uniDetailUniversity: "University",
  uniDetailCollege: "College",
  uniDetailLanguages: "Languages: {languages}",
  uniDetailApply: "Apply",
  uniDetailTuitionPublic: "No tuition (public)",
  uniDetailTuitionAnnual: "≈ {amount} / year",
  uniDetailProgramFree: "Free / public",

  // Onboarding banner
  onboardingRegionLabel: "Get started",
  onboardingTitle: "Welcome to ilmi 👋",
  onboardingSub:
    "Add your grades and one exam to unlock your university matches, admission chances, and scholarship fit — about a minute.",
  onboardingCta: "Get matched →",
  onboardingDismiss: "Dismiss",

  // Jobs page
  jobsTitle: "Jobs & Internships",
  jobsDesc: "Opportunities for students — filter by field.",
  jobsFieldLabel: "Field",
  jobsAllFields: "All fields",
  jobsLoading: "Loading jobs…",
  jobsEmpty: "No jobs yet for this filter.",
  loadMore: "Load more",
  loadingMore: "Loading…",
  jobsCount: "{count} opportunities",
  jobsApply: "Apply",

  // Search scholarships page
  searchScholarshipsPageTitle: "Scholarships",
  searchScholarshipsPageDesc: "Browse scholarships — filter by field and level.",
  searchScholarshipsFieldLabel: "Field",
  searchScholarshipsAllFields: "All fields",
  searchScholarshipsLevelLabel: "Level",
  searchScholarshipsAllLevels: "All levels",
  searchScholarshipsLevelBachelor: "Bachelor",
  searchScholarshipsLevelMaster: "Master",
  searchScholarshipsLevelDoctorate: "Doctorate",
  searchScholarshipsLoading: "Loading scholarships…",
  searchScholarshipsEmpty: "No scholarships match your filters yet — try broadening the field or level.",
  searchScholarshipsCount: "{count} scholarships",
  searchScholarshipsAwardFullTuition: "Full tuition",
  searchScholarshipsAwardPercentOff: "{value}% off tuition",
  searchScholarshipsAwardDefault: "Award",

  // Match scholarships page
  matchScholTitle: "Scholarship Matches",
  matchScholDesc: "Active scholarships ranked against your profile — citizenship, GPA, and interests.",
  matchScholGuestDesc: "See which scholarships you likely qualify for, ranked by fit.",
  matchScholGuestCtaTitle: "Create a free account to get matched",
  matchScholGuestCtaDesc: "Matching uses your country, grades, and interests — guests can browse, but scholarship matches need a saved profile.",
  matchScholGuestCtaBtn: "Sign up",
  matchScholEligibleOnly: "Eligible only",
  matchScholLoading: "Finding scholarships for you…",
  matchScholEmptyPrefix: "No scholarships available yet. Check back as the catalog grows, or set your ",
  matchScholEmptyLink: "interests and budget",
  matchScholErrorDefault: "Could not load scholarship matches",
  matchScholCount: "{eligible} you likely qualify for of {total}",
  matchScholEligible: "Eligible",
  matchScholNotEligible: "Not eligible",
  matchScholYourInterest: "★ Your interest",
  matchScholDue: "Due {date}",
  matchScholAwardFullTuition: "Full tuition",
  matchScholAwardFullCost: "Full cost of attendance",
  matchScholAwardPercentOff: "{value}% off tuition",
  matchScholAwardTuitionDiscount: "Tuition discount",
  matchScholAwardFixed: "Fixed award",
  matchScholAwardVariable: "Variable award",

  // Essay review page
  essayTitle: "Essay Review",
  essayDesc: "Paste your application essay and get AI feedback tuned for Central-Asian ESL applicants.",
  essayNotAvailableTitle: "Not available yet",
  essayNotAvailableText: "AI essay review isn’t enabled on this environment yet. Check back soon — when it’s on, you’ll be able to paste an essay here and get structured feedback.",
  essayTypeLabel: "Essay type",
  essayTypePersonalStatement: "Personal statement",
  essayTypeMotivationLetter: "Scholarship motivation letter",
  essayTypeStatementOfPurpose: "Statement of purpose",
  essayTypeCommonApp: "Common App essay",
  essayTypeOther: "Other",
  essayPlaceholder: "Paste your essay here…",
  essayReviewing: "Reviewing…",
  essayGetFeedback: "Get feedback",
  essayFeedbackTitle: "AI feedback",

  // Courses page
  coursesDesc: "Partner prep courses (English, math, and more).",
  coursesSubjectLabel: "Subject",
  coursesAllSubjects: "All subjects",
  coursesLoading: "Loading courses…",
  coursesEmpty: "No courses yet.",
  coursesCount: "{count} courses",
  coursesView: "View",

  // Dashboard layout
  dashToggleMenu: "Toggle menu",
  dashDeadlinesDueSoon: "{count} application deadlines due soon",
  dashDeadlineToday: "Today",
  dashDaysAgo: "{n}d ago",
  dashDaysLeft: "{n}d left",

  // Public footer
  publicFooterRights: "© {year} ilmi. All rights reserved",
};

export default en;
