// Kazakh (Қазақша)
// Fully translated — every key has a native value. Base spread of en provides an
// English (not Russian) safety net for any key that might be added later.
import en from "./en";

const kk = {
  ...en,
essayWritingTitle: "Эссе жазу",

home: "Басты бет",
search: "Іздеу",
dashboard: "Басқару тақтасы",
profile: "Профиль",
settings: "Параметрлер",
language: "Тіл",
selectLanguage: "Тілді таңдаңыз",
languageNote: "Тіл параметрлері келесі кіруде сақталады",
scholarships: "Стипендиялар",
heroBadge: "AI-таңдау",
heroTitle: "Өзіңізге сай университет табыңыз",
heroSubtitle: "Әлем бойынша университеттерді ашыңыз",
heroDescription: "Академиялық мақсаттарыңызға, бюджетіңіз бен қалауларыңызға сай әлем бойынша университеттерді ашыңыз",
heroStudents: "Студентке көмектестік",
heroUniversities: "Университеттер",
heroSuccessRate: "Табыстылық",
heroCta: "Жолыңызды бастаңыз",
heroDemo: "Демо қараңыз",
searchPlaceholder: "Университет, бағдарлама немесе орын іздеңіз...",
searchTitle: "Арман университетіңізді табыңыз",
searchSubtitle: "Орын, бағдарлама, бюджет және басқа параметрлер бойынша сүзіңіз",
searchFilters: "Сүзгілер",
searchResults: "Нәтижелер",
searchLocation: "Орын",
searchProgram: "Бағдарлама",
searchBudget: "Бюджет",
searchRanking: "Рейтинг",
dashboardTitle: "Сіздің панельіңіз",
dashboardWelcome: "Қайта оралғаныңызбен!",
dashboardRecentSearches: "Соңғы іздеулер",
dashboardSavedUniversities: "Сақталған университеттер",
dashboardApplications: "Өтінімдер",
dashboardScholarships: "Стипендиялар",
universityTuition: "Оқу ақысы",
universityAcceptanceRate: "Қабылдау пайызы",
universityPrograms: "Бағдарламалар",
universityLearnMore: "Толығырақ",
universityApplyNow: "Өтінім беру",
scholarshipTitle: "Үздік стипендиялар",
scholarshipSubtitle: "Білімге арналған қаржыландыру мүмкіндіктерін ашыңыз",
scholarshipMerit: "Үлгерімге негізделген",
scholarshipNeed: "Мұқтаждыққа негізделген",
scholarshipAthletic: "Спорттық",
scholarshipAcademic: "Академиялық",
featuredTitle: "Таңдаулы университеттер",
featuredSubtitle: "Әлем бойынша жоғары бағаланған оқу орындары",
save: "Сақтау",
cancel: "Болдырмау",
edit: "Өзгерту",
delete: "Жою",
apply: "Өтінім беру",
view: "Қарау",
learnMore: "Толығырақ",
uniTypeUniversity: "Университет",
uniTypeCollege: "Колледж",
notFoundTitle: "Бет табылмады",
notFoundMessage: "Іздеген бетіңіз жоқ немесе жылжытылған.",
notFoundBackDashboard: "Панельге оралу",
notFoundBackHome: "Басты бетке оралу",
errorBoundaryTitle: "Қате орын алды",
errorBoundaryMessage: "Күтпеген қате бетті тоқтатты. Жаңарту әдетте көмектеседі.",
errorBoundaryReload: "ilmi қайта жүктеу",
sessionExpiredMessage: "Сессияның мерзімі аяқталды. Қайта кіріңіз.",
serverUnreachableMessage: "Серверге қосылу мүмкін емес. Байланысты тексеріп, қайта көріңіз.",
serverErrorMessage: "Біздің жақта қате кетті. Қайта көріңіз.",
errorGeneric: "Қате орын алды. Қайта көріңіз.",
viewAll: "Барлығын қарау",
success: "Сәтті",
error: "Қате",
loading: "Жүктелуде...",
noResults: "Нәтиже табылмады",
deadline: "Мерзімі",
type: "Түрі",
meritBased: "Үлгерімге негізделген",
needBased: "Мұқтаждыққа негізделген",
projectBased: "Жобаға негізделген",
notifications: "Хабарламалар",
close: "Жабу",
open: "Ашу",
light: "Ашық",
dark: "Қара",
switchToLight: "Ашық тақырыпқа ауысу",
switchToDark: "Қара тақырыпқа ауысу",
email: "Электрондық пошта",
password: "Құпиясөз",
firstName: "Аты",
lastName: "Тегі",
phone: "Телефон",
address: "Мекенжай",
city: "Қала",
country: "Ел",
zipCode: "Пошта индексі",
today: "Бүгін",
yesterday: "Кеше",
tomorrow: "Ертең",
thisWeek: "Осы аптада",
thisMonth: "Осы айда",
thisYear: "Осы жылы",
thousand: "К",
million: "М",
billion: "Млрд",
lightMode: "Ашық тақырып",
darkMode: "Қара тақырып",
toggleTheme: "Тақырыпты ауыстыру",
favoriteSave: "Таңдаулыға қосу",
favoriteSaved: "Сақталды",
favoriteUniversitiesTitle: "Таңдаулы университеттер",
favoriteUniversitiesDescription: "Сақталған университеттер тізімі. Кез келгенін кез келген уақытта алып тастаңыз.",
favoriteUniversitiesEmpty: "Әзірше таңдаулы университетіңіз жоқ.",
searchNoResults: "Сәйкес оқу орны табылмады.",
searchFieldsTitle: "Бағыт бойынша іздеу",
searchFieldsPickField: "Оқу бағытын таңдаңыз",
searchFieldsClearAll: "Бәрін тазалау",
searchFieldsSelectedOne: "бағыт таңдалды",
searchFieldsSelectedMany: "бағыт таңдалды",
searchFieldsSelectPrompt: "Сәйкес университеттерді көру үшін жоғарыдан бір немесе бірнеше бағытты таңдаңыз.",
searchFieldsDegreeLevel: "Дәреже деңгейі",
searchFieldsLanguage: "Оқу тілі",
searchFieldsTuition: "Оқу ақысы (€)",
searchFieldsResults: "Сәйкес университеттер",
searchFieldsLoading: "Жүктелуде…",
searchFieldsViewDetails: "Толығырақ",
searchFieldsAdditionalFilters: "Қосымша сүзгілер",
searchFieldsFiltersActive: "белсенді",
searchFieldsRemember: "Таңдауымды есте сақтау",
searchFieldsCompact: "Қысқаша көрініс",
searchFieldsFull: "Толық көрініс",
searchFieldsResultOne: "нәтиже",
searchFieldsResultMany: "нәтиже",
filterAllLevels: "Барлық деңгейлер",
filterBachelor: "Бакалавр",
filterMaster: "Магистр",
filterPhd: "PhD / Докторантура",
filterAnyLanguage: "Кез келген тіл",
tuitionFree: "Тегін / мемлекеттік",
tuitionPerYear: "/ жыл",
tuitionMin: "Мин",
tuitionMax: "Макс",
programResultOne: "бағдарлама",
programResultMany: "бағдарлама",
favResultOne: "нәтиже",
favResultMany: "нәтиже",
uniDetailCampusAlt: "кампус",
uniDetailLogoAlt: "логотип",
fundingPerYear: "/жыл",
dashLogoHome: "ilmi басты бет",
fundingSourceAria: "Қаржыландыру көзінің атауы",
fundingAmountAria: "Қаржыландыру сомасы",
fieldDetailBack: "Бағыттарға оралу",
fieldDetailUniSingular: "университет осы бағытты ұсынады",
fieldDetailUniPlural: "университет осы бағытты ұсынады",
uniDetailPrograms: "Осы университеттегі бағдарламалар",
fieldUniNotFound: "Университет табылмады",
fieldUniBackToFields: "Бағыт іздеуге оралу",
fieldUniBackToResults: "Нәтижелерге оралу",
fieldUniSelectedFields: "Осы университеттегі таңдалған бағыттар",
fieldUniNoMatchingFields: "Осы университет үшін сәйкес бағыт табылмады.",
fieldUniDegrees: "Дәрежелер",
fieldUniLanguages: "Тілдер",
fieldUniViewFull: "Университеттің толық профилі",
searchProgramsTitle: "Бағдарламаларды іздеу",
searchProgramsPlaceholder: "Бағдарламаларды атауы бойынша іздеу…",
searchProgramsFilters: "Сүзгілер",
searchProgramsCategory: "Санат",
searchProgramsCountry: "Ел",
searchProgramsResults: "Бағдарламалар",
programDetailTitle: "Бағдарлама туралы",
programDetailNotFound: "Бағдарлама табылмады.",
programDetailBack: "Бағдарламаларға оралу",
programDetailUniversity: "Университет",
programDetailLocation: "Орналасқан жері",
programDetailDegree: "Дәреже",
programDetailLanguage: "Тіл",
programDetailDuration: "Ұзақтығы",
programDetailTuition: "Оқу ақысы",
programDetailDescription: "Сипаттама",
programDetailWebsite: "Сайтқа өту",
favoriteProgramsTitle: "Сүйікті бағдарламалар",
favoriteProgramsEmpty: "Сізде әлі сүйікті бағдарлама жоқ.",
favoriteProgramsRemove: "Жою",
navFeatures: "Мүмкіндіктер",
navAbout: "Біз туралы",
navFaq: "Сұрақ-жауап",
navContact: "Байланыс",
navLogin: "Кіру",
navGetStarted: "Бастау",
comingSoon: "Жақын арада",
getStarted: "Бастау",
startNow: "Қазір бастау",
keyFeatures: "Негізгі мүмкіндіктер",
howItWorks: "Қалай жұмыс істейді",
popularTopics: "Танымал тақырыптар",
essayReviewsTitle: "Эссені тексеру",
essayReviewsDesc: "Өтінім эссеңізге кәсіби пікір алыңыз",
essayReviewsIntro: "Эссеңізді сараптамаға жіберіңіз. Командамыз құрылым, мазмұн, грамматика және сендіргіштік бойынша егжей-тегжейлі пікір береді.",
essayReviewsAiFeedback: "AI талдауы",
essayReviewsAiFeedbackDesc: "Тон, анықтық және әсерді жедел талдау",
essayReviewsStructure: "Құрылым талдауы",
essayReviewsStructureDesc: "Абзацтар ағымы мен логикалық дәлел картасы",
essayReviewsGrammar: "Грамматика және стиль",
essayReviewsGrammarDesc: "Грамматика, тыныс белгілері және стиль тексеруі",
essayReviewsTone: "Тон және дауыс",
essayReviewsToneDesc: "Өзіндік дауысыңыздың шынайы естілуін қамтамасыз етіңіз",
essayReviewsPersonalStatement: "Жеке мәлімдеме",
essayReviewsSupplemental: "Қосымша эсселер",
essayReviewsDiversity: "Әртүрлілік туралы мәлімдеме",
essayReviewsResearchPurpose: "Мақсат мәлімдемесі",
essayReviewsSubmitEssay: "Эссені жіберу",
essayReviewsTurnaround: "24-48 сағат ішінде",
matchUnisTitle: "Университет таңдау",
matchUnisDesc: "AI профиліңізге негізделген университет таңдауы",
matchUnisIntro: "Біздің AI академиялық профиліңізді, қалауларыңыз бен мақсаттарыңызды талдап, сізге ең лайықты университеттерді табады. Нақтырақ нәтиже үшін профиліңізді толтырыңыз.",
matchUnisProfileAnalysis: "Профиль талдауы",
matchUnisProfileAnalysisDesc: "Академиялық күшті жақтарыңызды терең талдау",
matchUnisCompatibility: "Сәйкестік деңгейі",
matchUnisCompatibilityDesc: "Бірнеше факторға негізделген сәйкестік пайызы",
matchUnisSmartFilter: "Ақылды сүзгілеу",
matchUnisSmartFilterDesc: "Сүзгілер қалауларыңызға бейімделеді",
matchUnisRealtime: "Нақты уақытта жаңарту",
matchUnisRealtimeDesc: "Жаңа деректер қосылған сайын нәтижелер жаңарады",
matchUnisProfileComplete: "Профильді толтыру",
matchUnisCompleteProfile: "Жақсырақ нәтиже үшін профиліңізді толтырыңыз",
matchScholarshipsTitle: "Стипендия таңдау",
matchScholarshipsDesc: "Профиліңізге сәйкес стипендияларды табыңыз",
matchScholarshipsIntro: "Академиялық жазбаңыз, ұлтыңыз, оқу бағытыңыз және қаржылық жағдайыңызға негізделген стипендияларды табыңыз.",
matchScholarshipsEligibility: "Сәйкестікті тексеру",
matchScholarshipsEligibilityDesc: "Стипендия талаптарына автоматты тексеру",
matchScholarshipsDeadlines: "Мерзімдерді бақылау",
matchScholarshipsDeadlinesDesc: "Өтінім мерзімдерін жіберіп алмаңыз",
matchScholarshipsGuidance: "Өтінімге көмек",
matchScholarshipsGuidanceDesc: "Әр өтінім бойынша қадамдық нұсқаулық",
matchScholarshipsCalculator: "Қаржы калькуляторы",
matchScholarshipsCalculatorDesc: "Жалпы қаржыландыру мүмкіндігіңізді бағалаңыз",
matchScholarshipsMerit: "Үлгерімге негізделген",
matchScholarshipsNeed: "Қажеттілікке негізделген",
matchScholarshipsCountry: "Елге арналған",
matchScholarshipsField: "Бағытқа арналған",
similarStudentsTitle: "Ұқсас студенттер",
similarStudentsDesc: "Бір мақсаттағы студенттермен байланысыңыз",
similarStudentsIntro: "Ұқсас академиялық деңгейдегі, бірдей мақсатты университеттері бар және мансаптық мақсаттары сәйкес студенттерді табыңыз. Тәжірибемен бөлісіп, бір-бірінізден үйреніңіз.",
similarStudentsMatching: "Профиль сәйкестігі",
similarStudentsMatchingDesc: "Ұқсас мақсат пен тәжірибесі бар студенттерді табыңыз",
similarStudentsGroups: "Оқу топтары",
similarStudentsGroupsDesc: "Тақырып бойынша оқу топтарына қосылыңыз немесе жасаңыз",
similarStudentsExperience: "Тәжірибе бөлісу",
similarStudentsExperienceDesc: "Өтінім тәжірибелерін оқыңыз және бөлісіңіз",
similarStudentsNetwork: "Желі құру",
similarStudentsNetworkDesc: "Ұқсас университеттерге өтініш берушілермен байланысыңыз",
alumniMentorsTitle: "Түлек тәлімгерлер",
alumniMentorsDesc: "Табысты түлектерден кеңес алыңыз",
alumniMentorsIntro: "Шет елде оқыған және нақты тәжірибе, өтінім кеңестері, мәдени нұсқаулық және мансаптық кеңес бере алатын түлектермен байланысыңыз.",
alumniMentorsCareer: "Мансаптық нұсқаулық",
alumniMentorsCareerDesc: "Бітіргеннен кейінгі мансап жолдары туралы біліңіз",
alumniMentorsTips: "Өтінім кеңестері",
alumniMentorsTipsDesc: "Табысқа жеткендерден кеңес алыңыз",
alumniMentorsCulture: "Мәдени түсінік",
alumniMentorsCultureDesc: "Жаңа елдегі өмірге дайындалыңыз",
alumniMentorsAccess: "Желіге қол жеткізу",
alumniMentorsAccessDesc: "Өсіп келе жатқан түлектер қауымдастығына қосылыңыз",
connectFriendsTitle: "Достар табу",
connectFriendsDesc: "Өтінім берушілермен байланыс орнатыңыз",
connectFriendsIntro: "Шетелде оқуға дайындалып жатқан басқа студенттермен танысыңыз. Кеңестер бөлісіп, бөлмелес табыңыз және мықты достықтар орнатыңыз.",
connectFriendsInterest: "Қызығушылық бойынша",
connectFriendsInterestDesc: "Ортақ хобби мен мақсаттар арқылы байланысыңыз",
connectFriendsStudy: "Оқу серіктестері",
connectFriendsStudyDesc: "Тест дайындығына серіктес табыңыз",
connectFriendsCampus: "Кампус байланыстары",
connectFriendsCampusDesc: "Бір университетке баратын студенттермен танысыңыз",
connectFriendsCultural: "Мәдени алмасу",
connectFriendsCulturalDesc: "Әртүрлі мәдениеттер мен тұрмыс туралы біліңіз",
mockInterviewsTitle: "Жаттығу сұхбаттары",
mockInterviewsDesc: "Университетке қабылдау сұхбатына дайындалыңыз",
mockInterviewsIntro: "AI-сұхбаттасу сессиялары арқылы университет сұхбаттарына дайындалыңыз. Жауаптарыңыз, дене тілі кеңестері және сенімділік деңгейіңіз бойынша нақты уақытта пікір алыңыз.",
mockInterviewsAi: "AI сұхбаттасушы",
mockInterviewsAiDesc: "AI жасаған нақты сұрақтармен жаттығыңыз",
mockInterviewsFeedback: "Нақты уақытта пікір",
mockInterviewsFeedbackDesc: "Жауаптарыңызды жедел талдау",
mockInterviewsBank: "Сұрақтар банкі",
mockInterviewsBankDesc: "Университеттерге арналған сұрақтар жинақтары",
mockInterviewsTrack: "Нәтижелерді бақылау",
mockInterviewsTrackDesc: "Сессиялар арасындағы жетілуді бақылаңыз",
mockInterviewsGeneral: "Жалпы қабылдау",
mockInterviewsTechnical: "Техникалық сұхбат",
mockInterviewsScholarship: "Стипендия сұхбаты",
mockInterviewsPortfolio: "Портфолио шолуы",
conciergeSupportTitle: "Жеке қолдау",
conciergeSupportDesc: "Жолыңыздағы Premium жеке нұсқаулық",
conciergeSupportIntro: "Сарапшы кеңесшілерімізден арнайы қолдау алыңыз. Университет таңдаудан виза өтінімдеріне дейін — шетелде оқудың әр қадамында сізге бағыт береміз.",
conciergeSupportPriority: "Басым қолдау",
conciergeSupportPriorityDesc: "Кезектен өтіп, жедел жауап алыңыз",
conciergeSupportAdvisor: "Жеке кеңесші",
conciergeSupportAdvisorDesc: "Сіздің ісіңізге бекітілген жеке кеңесші",
conciergeSupportDocReview: "Құжаттарды тексеру",
conciergeSupportDocReviewDesc: "Барлық өтінім құжаттарын сараптамалық тексеру",
conciergeSupportTracking: "Өтінімдерді бақылау",
conciergeSupportTrackingDesc: "Өтінімдер күйін нақты уақытта жаңарту",
englishTitle: "Ағылшын тіліне дайындық",
englishDesc: "IELTS, TOEFL және академиялық ағылшын тіліне дайындалыңыз",
englishIntro: "Университетке қабылдану үшін ағылшын тілі дағдыларыңызды жетілдіріңіз. IELTS, TOEFL және академиялық контекстке арналған оқу, жазу, тыңдау және сөйлеу жаттығулары.",
englishIelts: "IELTS дайындығы",
englishIeltsDesc: "Толық жаттығу тесттері мен стратегия нұсқаулықтары",
englishToefl: "TOEFL дайындығы",
englishToeflDesc: "Бөлім бойынша жаттығу және кеңестер",
englishAcademic: "Академиялық ағылшын",
englishAcademicDesc: "Жазу, оқу және презентация дағдылары",
englishSpeaking: "Сөйлеу жаттығуы",
englishSpeakingDesc: "AI-мен сөйлесу жаттығулары",
englishReading: "Оқу",
englishWriting: "Жазу",
englishListening: "Тыңдау",
englishSpeakingSkill: "Сөйлеу",
mathTitle: "Математикаға дайындық",
mathDesc: "SAT, GRE және университет математикасына дайындалыңыз",
mathIntro: "Стандартталған тесттер мен университет деңгейіндегі курстарға арналған бағытты жаттығулармен математика дағдыларыңызды нығайтыңыз. Алгебра, есептеу, статистика және есеп шешу стратегиялары қамтылған.",
mathSat: "SAT / ACT математикасы",
mathSatDesc: "Жаттығу есептері мен тест тапсыру стратегиялары",
mathAdvanced: "Жоғары деңгей тақырыптары",
mathAdvancedDesc: "Математикалық талдау, сызықтық алгебра және тағы басқа",
mathPractice: "Жаттығу есептері",
mathPracticeDesc: "Қадамдық шешімдері бар мыңдаған есептер",
mathProgress: "Жетістікті бақылау",
mathProgressDesc: "Барлық тақырыптар бойынша меңгеруді бақылаңыз",
mathAlgebra: "Алгебра",
mathCalculus: "Математикалық талдау",
mathStatistics: "Статистика",
mathGeometry: "Геометрия",
aiLiteracyTitle: "AI сауаттылығы",
aiLiteracyDesc: "AI құралдарын академияда тиімді пайдалануды үйреніңіз",
aiLiteracyIntro: "AI негіздерін, жылдам инженерияны және академиялық және кәсіби контексттерде AI-ды этикалық пайдалануды зерттеңіз. Заманауи студентке қажетті дағдылар.",
aiLiteracyFundamentals: "AI негіздері",
aiLiteracyFundamentalsDesc: "Жасанды интеллекттің негізгі тұжырымдамалары",
aiLiteracyPrompt: "Жылдам инженерия",
aiLiteracyPromptDesc: "AI құралдары үшін тиімді жылдамдықтар жазыңыз",
aiLiteracyData: "Деректер сауаттылығы",
aiLiteracyDataDesc: "Деректерді тиімді түсіну және жұмыс жасау",
aiLiteracyEthics: "AI этикасы",
aiLiteracyEthicsDesc: "Академияда AI-ды жауапты пайдалану",
getCoursesTitle: "Курстарды шолу",
getCoursesDesc: "Тест дайындығы мен дағдыларға арналған курстар каталогы",
getCoursesIntro: "Университетке өтінімде және академияда табысқа жетуге көмектесетін өз қарқынында оқылатын курстарды табыңыз. Тест дайындығынан жұмсақ дағдыларға дейін — өзіңізге лайықты курсты таңдаңыз.",
getCoursesVideo: "Бейне дәрістер",
getCoursesVideoDesc: "Сарапшы оқытушылардан өз қарқыныңызда үйреніңіз",
getCoursesInteractive: "Интерактивті жаттығулар",
getCoursesInteractiveDesc: "Практикалық тапсырмалармен жаттығыңыз",
getCoursesCertificate: "Сертификаттар",
getCoursesCertificateDesc: "Профиліңізді нығайту үшін сертификаттар алыңыз",
getCoursesSelfPaced: "Өз қарқынымен",
getCoursesSelfPacedDesc: "Өз кестеңізде оқыңыз",
getCoursesTestPrep: "Тест дайындығы",
getCoursesLanguage: "Тіл курстары",
getCoursesSkills: "Жұмсақ дағдылар",
getCoursesAcademic: "Академиялық жазу",
essayWritingDesc: "Өтінім эссесін тартымды жазуды үйреніңіз",
essayWritingIntro: "Шаблондар, AI ұсыныстары және университетке арнайы нұсқаулармен эссе жазу өнерін меңгеріңіз. Тәжірибеңізді мықты оқиғаға айналдырыңыз.",
essayWritingTemplates: "Эссе шаблондары",
essayWritingTemplatesDesc: "Әртүрлі эссе түрлеріне дәлелденген құрылымдар",
essayWritingAi: "AI ұсыныстары",
essayWritingAiDesc: "Жазбаңызды жетілдіруге арналған ақылды кеңестер",
essayWritingPeer: "Өзара тексеру",
essayWritingPeerDesc: "Басқа абитуриенттерден пікір алыңыз",
essayWritingUniTips: "Университетке арнайы кеңестер",
essayWritingUniTipsDesc: "Әр университеттің сұрақтарына бейімделген нұсқаулар",
contactPremiumTitle: "Байланыс",
contactPremiumDesc: "Командамызбен хабарласыңыз",
contactPremiumKicker: "Premium қолдау",
contactPremiumLeftLabel: "Premium қолдау және кездесу жазылу",
contactPremiumIntro: "Сұрақтарыңыз бар ма немесе көмек керек пе? Командамыз өтінімдер, құжаттар және жоспарлау бойынша көмектеседі — маңызды кезде жауапты басымдықпен береді.",
contactBookMeeting: "Кездесу жазылу",
contactBookMeetingHint: "Тақырып алдын ала толтырылған электрондық пошта ашылады; уақытты растаймыз.",
contactBookMeetingEmailSubject: "Кездесу сұрауы — Ilmi",
contactAsideLabel: "Қоғамдастық және байланыс деректері",
contactTelegramTitle: "Telegram арнасы",
contactTelegramDesc: "Жаңартулар, еске салулар және басқа абитуриенттермен сөйлесулерге қосылыңыз.",
contactOpenTelegram: "Telegram-да ашу",
contactReachUsTitle: "Тікелей байланыс",
contactEmailLabel: "Электрондық пошта",
contactTelegramLabel: "Қоғамдастық",
contactTelegramChannelShort: "Ilmi ресми арнасы",
contactReachUsFootnote: "Ресми сұраулар мен құжаттар үшін электрондық пошта ыңғайлы. Telegram — жылдам сұрақтар мен жаңалықтарға ыңғайлы.",
contactPremiumPriority: "Басымдықты жауап",
contactPremiumPriorityDesc: "Командамыздан жылдам жауап алыңыз",
contactPremiumVideo: "Бейне кеңес",
contactPremiumVideoDesc: "Бетпе-бет бейне сөйлесуге жазылыңыз",
contactPremiumDoc: "Құжат көмегі",
contactPremiumDocDesc: "Құжаттар мен өтінімдерде көмек",
contactPremiumTeam: "Эксперт команда",
contactPremiumTeamDesc: "Тәжірибелі білім кеңесшілерінің қолдауы",
contactPremiumEmail: "Электрондық пошта қолдауы",
contactPremiumEmailDesc: "Хабарлама жіберіңіз — 24 сағат ішінде жауап беріледі",
contactPremiumChat: "Тікелей чат",
contactPremiumChatDesc: "Жұмыс уақытында командамызбен нақты уақытта сөйлесіңіз",
contactPremiumCall: "Қоңырауға жазылу",
contactPremiumCallDesc: "Білім кеңесшісімен жеке қоңырауға жазылыңыз",
contactPremiumContactUs: "Бізбен байланысу",
contactPremiumChannels: "Байланыс арналары",
dreamUniTitle: "Арман университеті",
dreamUniDesc: "Арман университетіне жолды жоспарлаңыз және бақылаңыз",
dreamUniIntro: "Мақсатты университеттерді белгілеңіз, өтінім мерзімдерін бақылаңыз және прогресіңізді қадағалаңыз. Ұйымшыл болып, мақсатыңызға жетіңіз.",
dreamUniGoals: "Мақсат бақылау",
dreamUniGoalsDesc: "Өтінім кезеңдерін белгілеп бақылаңыз",
dreamUniDeadlines: "Мерзім еске салулары",
dreamUniDeadlinesDesc: "Маңызды өтінім мерзімдерін жіберіп алмаңыз",
dreamUniTimeline: "Прогресс уақыт кестесі",
dreamUniTimelineDesc: "Бастаудан қабылдауға дейінгі жолыңызды бейнелеңіз",
dreamUniChecklist: "Өтінім тізімі",
dreamUniChecklistDesc: "Әр құжат пен талапты бақылаңыз",
searchScholarshipsTitle: "Стипендия іздеу",
searchScholarshipsDesc: "Бүкіл әлем бойынша стипендиялар мен қаржыландыру мүмкіндіктерін табыңыз",
searchScholarshipsIntro: "Орта Азия студенттеріне арналған мыңдаған стипендияны зерттеңіз. Ел, сала, сома және мерзім бойынша сүзіп, тиімді қаржыландыру мүмкіндігін табыңыз.",
searchScholarshipsType: "Түрі бойынша",
searchScholarshipsTypeDesc: "Үлгерімге, қажеттілікке, елге және басқа негіздерге сәйкес",
searchScholarshipsCountry: "Ел бойынша",
searchScholarshipsCountryDesc: "Стипендияларды мақсатты елі бойынша сүзіңіз",
searchScholarshipsDeadline: "Мерзімдер күнтізбесі",
searchScholarshipsDeadlineDesc: "Алдағы стипендия мерзімдерін бақылаңыз",
searchScholarshipsEligibility: "Сәйкестік тексеру",
searchScholarshipsEligibilityDesc: "Сізге сәйкес келетінін жылдам тексеру",
profileTitle: "Менің профилім",
profileDesc: "Аккаунт параметрлерін басқару",
profileChangePhoto: "Фотоны өзгерту",
profileFullName: "Толық аты-жөні",
profileFirstName: "Аты",
profileLastName: "Тегі",
profileEmail: "Электрондық пошта",
profilePhone: "Телефон",
profileLocation: "Орналасқан жері",
profileCertifications: "Сертификаттар мен біліктіліктер",
profileCertificationsHint: "Жолдан жол (мысалы, бағдарлама талаптарына қатысты дипломдар, тіл тесттері, емтихан балдары).",
profileShareTitle: "Профиль сілтемесі",
profileShareDesc: "Осы сілтемені бөлісіңіз немесе кодты сканерлеп профильді осы құрылғыда ашыңыз.",
profileCopyLink: "Сілтемені көшіру",
profileLinkCopied: "Сілтеме көшірілді",
profileLoadError: "Профильді жүктеу мүмкін болмады. Жүйеге кіргеніңізді және сервердің жұмыс істеп тұрғанын тексеріңіз.",
profileSaveError: "Өзгерістерді сақтау мүмкін болмады.",
profileSaveSuccess: "Профиль сақталды.",
profileGuestHint: "Профильді, сертификаттарды және бөлісу сілтемесін жүктеп сақтау үшін жүйеге кіріңіз.",
profileSaving: "Сақталуда…",
profileApplications: "Өтінімдер",
profileScholarships: "Стипендиялар",
profileViews: "Профиль қаралымдары",
profilePremium: "Premium мүше",
profilePremiumDesc: "Барлық Premium функцияларға қолжетімділігіңіз бар",
profilePremiumMatch: "Шексіз университет таңдау",
profilePremiumSupport: "Өтінімге басымдықты қолдау",
profilePremiumAlerts: "Эксклюзивті стипендия хабарламалары",
profilePremiumMentor: "Тікелей тәлімгерге қол жеткізу",
profileSave: "Өзгерістерді сақтау",
profileLogout: "Шығу",
dashMain: "НЕГІЗГІ",
dashDreamUniversity: "Арман университеті",
dashDreamPeakLabel: "UCA трегі",
dashDreamCardTagline: "Басты мақсат — құжаттар, балдар мен мерзімдерді осы университетпен үйлестіріңіз.",
dashDreamPillFit: "Профиліңізге 92% сәйкес",
dashDreamPillDeadline: "Келесі: UCA өтінімі · 6 қазан",
dashDreamPillDocs: "Тізім · 4 ашық",
dashDreamReadinessLabel: "Бұл мақсатқа дайындық",
dashSearchUniversities: "Университеттер",
dashFavoriteUniversities: "Сүйікті университеттер",
dashSearchFields: "Бағыттар",
dashSearchPrograms: "Бағдарламалар",
dashFavoritePrograms: "Сүйікті бағдарламалар",
dashSearchScholarships: "Стипендиялар",
dashAiMatching: "AI таңдау",
dashMatchUniversities: "Университет таңдау",
dashMatchScholarships: "Стипендия таңдау",
dashEssayReview: "Эссені тексеру",
dashSimilarStudents: "Ұқсас студенттер",
dashCommunity: "Қоғамдастық",
dashOthers: "Басқа",
dashConnections: "Байланыстар",
dashConnectFriends: "Достар",
dashAlumniMentors: "Түлек тәлімгерлер",
dashPremiumServices: "Premium қызметтер",
dashEssayReviews: "Эссені тексеру",
dashMockInterviews: "Жаттықтыру сұхбаттары",
dashConciergeSupport: "Консьерж қолдауы",
dashLearning: "Оқыту және курстар",
dashGetCourses: "Курстарды алу",
dashMath: "Математика",
dashEnglish: "Ағылшын тілі",
dashEssayWriting: "Эссе жазу",
dashAiLiteracy: "AI сауаттылығы",
dashDashboard: "Басты бет",
dashTagline: "Сіздің университеттік жолыңыз осы жерден басталады",
dashSendInfo: "Ақпарат жіберіп Premium алу",
dashJoinCommunity: "Қоғамдастыққа қосылу",
dashLogout: "Шығу",
dashNotifications: "Хабарламалар",
dashProfile: "Профиль",
dashWelcomeBackPrefix: "Қайта оралғаныңызбен,",
dashDefaultDisplayName: "Аты-жөні",
dashOpenPage: "Бетті ашу",
dashCardDashboardDesc: "Негізгі басқару тақтасына оралу.",
dashCardDreamDesc: "Арман университеті мақсаттары мен прогресіңізді қарау.",
dashCardUniversitiesDesc: "Университеттерді зерттеп, нұсқаларды салыстыру.",
dashCardFavoriteUniversitiesDesc: "Сақтаған университеттерді ашу.",
dashCardFieldsDesc: "Қызығушылықтарыңызға сәйкес бағыттарды шолу.",
dashCardProgramsDesc: "Үздік мектептердегі дипломдық бағдарламаларды ашу.",
dashCardFavoriteProgramsDesc: "Сақтаған бағдарламаларыңызды бір жерде қарау.",
dashCardScholarshipsDesc: "Өтінім бере алатын стипендияларды табу.",
dashCardMatchUniversitiesDesc: "AI-таңдаумен университеттер алу.",
dashCardMatchScholarshipsDesc: "AI-таңдаумен стипендиялар алу.",
dashCardSimilarStudentsDesc: "Ұқсас студент профильдерінен деректер қарау.",
dashCardFriendsDesc: "Бір жолдағы достармен байланысу.",
dashCardMentorsDesc: "Кеңес алу үшін түлек тәлімгерлерін табу.",
dashCardProfileDesc: "Профиль параметрлерін қарау және жаңарту.",
dashCardSendInfoDesc: "Деректер жіберіп, Premium қолдау сұрау.",
dashContactPremium: "Байланыс",
dashNavAiTools: "AI ҚҰРАЛДАРЫ",
dashNavApply: "ӨТІНІМДЕР",
dashMyAcademics: "Оқу үлгерімім",
dashMyApplications: "Менің өтінімдерім",
dashNavOpportunities: "МҮМКІНДІКТЕР",
dashJobs: "Жұмыс және тәжірибе",
dashCourses: "Курстар",
dashNavAdmin: "ӘКІМШІ",
dashAdminReview: "Мазмұнды тексеру",
dashNavFriendsAndMentors: "ДОСТАР",
dashNavSectionAiUniversities: "AI · Университеттер",
dashNavSectionAiScholarships: "AI · Стипендиялар",
dashNavSectionAiSimilarStudents: "AI · Ұқсас студенттер",
dashNavSectionConnectFriends: "Достар",
dashNavSectionAlumniMentors: "Түлек тәлімгерлер",
dashNavSectionContactPremium: "Байланыс",
dashCardContactPremiumDesc: "Командамен байланысу, кездесуге жазылу немесе Telegram-ға қосылу.",
dashAiDashboardUniTitle: "AI · Ең сәйкес университеттер",
dashAiShowcaseSeeWholeList: "Толық тізімді қарау",
dashCtaSeeAllUniversityMatches: "Барлық университет сәйкестіктерін қарау",
dashCtaSeeAllScholarshipMatches: "Барлық стипендия сәйкестіктерін қарау",
dashCtaSeeAllFriends: "Барлық достарды қарау",
dashCtaBrowseAllMentors: "Барлық тәлімгерлерді шолу",
dashConnAsideFriendsLabel: "Осы алдын ала қарауда достар",
dashFriendsCombinedSectionTitle: "Достар және танысатын адамдар",
dashFriendsSimilarColumnTitle: "Байланысуға болатын адамдар",
dashFriendsSimilarSeeMore: "Тағы қарау",
dashFriendsOnlineColumnTitle: "Достарыңыз",
dashFriendsOnlineNow: "Қазір желіде",
dashFriendsAllFriendsLabel: "Барлық достар",
dashFriendsSeeCountCta: "{{count}} досты қарау",
dashFriendsOnlineEmpty: "Қазір ешкім желіде жоқ",
dashConnAsideMentorsLabel: "Осы алдын ала қарауда тәлімгерлер",
dashSimilarStudentsAddFriend: "Дос қосу",
dashAiShowcaseUniCtaHint: "Сүзгілер мен барлық нұсқалары бар толық таңдау.",
dashAiShowcaseScholCtaHint: "Барлық стипендиялар мен сәйкестік шарттарын шолу.",
dashAiDashboardScholTitle: "AI · Ең сәйкес стипендиялар",
dashAiDashboardPeersTitle: "AI · Ұқсас студенттер",
dashAiUniMatchLead: "Профиліңіз, мақсаттарыңыз бен балдарыңызға сәйкестіктер бойынша сұрыпталған университеттер.",
dashAiScholMatchLead: "Келесі кезеңде жеңіп алу мүмкіндігіңіз жоғары стипендиялар.",
dashAiPeersMatchLead: "Мақсаттары ұқсас, тәжірибесінен үйрене алатын жолдастар.",
dashAiScholCardIntlTitle: "Global Merit Fund",
dashAiScholCardIntlMeta: "Халықаралық абитуриенттер · Мерзімі 15 сәуір",
dashSimilarStudent2Name: "Eldar M.",
dashSimilarStudent2Desc: "STEM бағыты, стипендияға негізделген өтінімдер.",
dashSimilarStudent3Name: "Timur B.",
dashSimilarStudent3Desc: "Европаға бағытталған тізім, жоғары ағылшын балдары.",
dashSimilarTagField: "Бір бағыт",
dashSimilarTagRegion: "Бір аймаққа бағытталған",
dashSimilarTagScores: "Ұқсас балдар",
dashSimilarOverlapGpa: "Ұқсас GPA аралығы",
dashSimilarOverlapShortlist: "Қысқа тізімдер қиылысады",
dashSimilarOverlapIntake: "Бір мақсатты қабылдау",
dashSimilarOverlapScholarFirst: "Стипендияны басым стратегия",
dashSimilarOverlapEuTargets: "ЕО мақсаттары қиылысады",
dashSimilarOverlapAidFocus: "Екеуі де қажеттілікке негізделген қолдауды қадағалайды",
dashSimilarOverlapEuropeList: "Европаға бағытталған тізімдер",
dashSimilarOverlapIelts: "Ағылшын балдары сопоставимый",
dashSimilarOverlapStemExtra: "Ұқсас STEM белсенділіктері",
dashSimilaritiesLabel: "Профиліңізбен ұқсастықтар",
dashFriend2SampleName: "Erkeaiym D.",
dashFriend2SampleDesc: "Сүйікті тізім қиылысады: Нидерланды және Германия.",
dashFriend3SampleName: "Sultan K.",
dashFriend3SampleDesc: "Эссе алмасу серіктесі · кеше белсенді болды.",
dashMentor2SampleName: "Laura N.",
dashMentor2SampleDesc: "MBA қабылдауы, сұхбатқа дайындық және CV тексеру.",
dashMentorBadgeStem: "Инженерия",
dashMentorBadgeMba: "Бизнес және MBA",
dashMentorVerified: "Расталған тәлімгер",
dashAway: "Желіде жоқ",
dashConnectionFriendsTitle: "Байланыстар · Достар",
dashConnectionFriendsLead: "Қабылдану жолында бірге немесе хабарласқыңыз келетін адамдар.",
dashConnectionMentorsTitle: "Байланыстар · Түлек тәлімгерлер",
dashConnectionMentorsLead: "Өтінімдер мен сұхбаттарда көмектесетін түлектер.",
dashConnectionActionChat: "Чатты ашу",
dashConnectionActionMentor: "Профильді қарау",
dashConnectionPremiumTitle: "Premium қолдау",
dashConnectionPremiumLead: "Мерзімдер, эссе және стратегия бойынша арнайы көмек.",
dashConnectionPremiumPoint1: "ilmi командасынан басымдықты жауаптар",
dashConnectionPremiumPoint2: "Нақты кері байланыспен эссе мен сұхбатты тексеру",
dashConnectionPremiumPoint3: "Қысқа тізімді консьерж форматында жоспарлау",
dashContactSubheading: "Байланыс",
dashContactDetailsTitle: "Бізге жету",
dashContactCompactHint: "Төменде жылдам сілтемелер. Толық хабарлама жіберу үшін Байланыс бетін пайдаланыңыз.",
dashContactFullPageCta: "Толық Байланыс бетін ашу",
dashContactUsTitle: "Бізбен байланысу",
dashContactPhoneLabel: "Телефон",
dashContactTelegramQrCaption: "Telegram арнамызды ашу үшін сканерлеңіз немесе басыңыз.",
dashContactSocialListLabel: "Әлеуметтік желілер мен қоғамдастық сілтемелері",
dashContactFormTitle: "Бізге хабарлама жіберіңіз",
dashContactFormName: "Толық аты-жөні",
dashContactFormNamePh: "Толық аты-жөніңізді енгізіңіз",
dashContactFormEmail: "Электрондық пошта",
dashContactFormEmailPh: "you@example.com",
dashContactFormTopic: "Тақырып",
dashContactFormTopicPh: "Қандай көмек керек?",
dashContactFormMessage: "Хабарлама",
dashContactFormMessagePh: "Хабарламаңызды осы жерге жазыңыз — дұрыс көмек ете алуымыз үшін жеткілікті мәлімет беріңіз.",
dashContactFormSubmit: "Хабарлама жіберу",
dashContactFormThanks: "Рахмет! Хабарламаңызды алдық, жақын арада жауап береміз.",
dashContactFormAgain: "Тағы хабарлама жіберу",
contactPlatformLinkedIn: "LinkedIn",
contactPlatformTelegram: "Telegram",
contactPlatformInstagram: "Instagram",
contactPlatformX: "X",
contactPlatformYouTube: "YouTube",
contactPlatformTikTok: "TikTok",
dashPerfectMatch: "Тамаша сәйкестік",
dashUcaName: "Орталық Азия университеті",
dashUcaLocation: "Нарын, Қырғызстан",
dashStartClimb: "Жолды бастау",
dashPackList: "Істер тізімі",
dashUpcomingDeadlines: "Жақындаған мерзімдер",
dashShowAll: "Барлығын көру",
dashUcaApplication: "UCA өтінімі",
dashAucaScholarship: "AUCA стипендиясы",
dashMitApplication: "MIT өтінімі",
dashOct6: "6 қаз 2025",
dashOct8: "8 қаз 2025",
dashDeadlineFarTitle: "Stanford SCEA · портфолио және транскриптер",
dashDeadlineFarDate: "15 қаң 2027",
dashTimeAbout9mo: "~9 ай",
dashTime45m: "45 мин қалды",
dashTime2h15m: "2 сағ 15 мин қалды",
dashTime2d3h: "2 күн 3 сағ қалды",
dashViewsTitle: "Университет және стипендия қараулары",
dashViewsTotal: "Үлгі деректер",
dashViewsDesc: "Қанша университет пен стипендияны қарағаныңызды бақылаңыз",
dashRecommendedUniversities: "Ұсынылған университеттер",
dashPreviewSearchPlaceholder: "Атауы немесе орны бойынша іздеу…",
dashFilters: "Сүзгілер",
dashFilterAll: "Барлығы",
dashFilterEurope: "Еуропа",
dashFilterEnglishTaught: "Ағылшын тілінде",
dashSearchPopularFilters: "Танымал сүзгілер",
dashSearchClearFilters: "Бәрін тазалау",
dashStartSearching: "Іздеуді бастау",
dashSearchUniPlaceholder: "Университет немесе колледж атауы бойынша іздеу…",
dashUniPopUnder10k: "€10 мыңға дейін / жыл",
dashUniPopUnder5k: "≤ €5 мың / жыл",
dashUniPopBusinessLaw: "Бизнес және құқық",
dashUniPopMedicine: "Медицина және ғылым",
dashUniPopArts: "Өнер және дизайн",
dashFieldTeaserCs: "Информатика және IT",
dashFieldTeaserBusiness: "Бизнес және менеджмент",
dashFieldTeaserMedicine: "Медицина және денсаулық",
dashFieldTeaserEngineering: "Инженерия",
dashFieldTeaserArts: "Өнер және дизайн",
dashScholarshipUrlHintMerit: "Сіз басқару тақтасынан үлгеріміне негізделген стипендияларды аштыңыз.",
dashScholarshipUrlHintNeed: "Сіз басқару тақтасынан қаржылық қажеттілікке негізделген стипендияларды аштыңыз.",
dashSearchTeaserSearchUniversities: "Университеттерді іздеу",
dashSearchTeaserSearchFields: "Бағыттарды іздеу",
dashSearchTeaserSearchScholarships: "Стипендияларды іздеу",
dashSearchFieldPlaceholder: "Бағыт атауы бойынша іздеу…",
dashSearchScholarshipPlaceholder: "Стипендияларды іздеу…",
dashPreviewMatches: "сәйкестік",
dashPreviewNoResults: "Бұл сүзгі бойынша нәтиже жоқ.",
dashPreviewUniversitiesLead: "Іздеу алдын ала қарауы: сол жақтағы сүзгілер оң жақтағы тізімді тарылтады.",
dashPreviewProgramsLead: "Жылдам сүзгілер мен қысқа тізімі бар бағдарлама іздеуінің алдын ала қарауы.",
dashPreviewScholarshipsLead: "Түр сүзгілері бар стипендия іздеуінің алдын ала қарауы.",
dashProgramFilterMaster: "Магистратура",
dashProgramFilterBachelor: "Бакалавриат",
dashScholarshipFilterMerit: "Үлгерімге негізделген",
dashScholarshipFilterNeed: "Қаражатқа негізделген",
dashProgramPreviewMsTitle: "M.Sc. Computer Science",
dashProgramPreviewMsMeta: "STEM · күзгі қабылдау",
dashProgramPreviewBsTitle: "B.A. Халықаралық қатынастар",
dashProgramPreviewBsMeta: "Әлеуметтік ғылымдар · үздіксіз",
dashProgramPreviewMbaTitle: "MBA",
dashProgramPreviewMbaMeta: "Бизнес · GMAT",
dashScholPreviewMeritTitle: "Үлгерім жетістік сыйлығы",
dashScholPreviewMeritMeta: "€5 000-ға дейін · мерзімі 1 наурыз",
dashScholPreviewNeedTitle: "Қаржылық қолдау гранты",
dashScholPreviewNeedMeta: "Табысқа негізделген · үздіксіз",
dashApplicationStatus: "Өтінім мәртебесі",
dashStatusCardLead: "ilmi-де бақылайтын барлық мәртебелер — санаттар мен воронкадағы үлес.",
dashStatusDonutLabel: "Өтінімдер",
dashStatusTotal: "Барлығы 15",
dashStatusPlan: "Беруді жоспарлаймын",
dashStatusApplied: "Берілді",
dashStatusAccepted: "Қабылданды",
dashStatusWaitlist: "Күту тізімі",
dashStatusRejected: "Қабылданбады",
dashRank: "Рейтинг",
dashMatch: "Сәйкестік",
dashUni1Name: "Massachusetts Institute of Technology",
dashUni1Loc: "Кембридж, MA, АҚШ",
dashUni1Rank: "#1",
dashUni1Match: "95%",
dashUni2Name: "Stanford University",
dashUni2Loc: "Стэнфорд, CA, АҚШ",
dashUni2Rank: "#2",
dashUni2Match: "92%",
dashAiSampleUniversities: "Профиль мен мақсаттарыңызға сай үздік таңдаулар.",
dashAiSampleScholarships: "Бюджет пен балдарыңызға сәйкес стипендиялар.",
dashAiSampleStudents: "Ұқсас жол мен нәтижелері бар студенттер.",
dashFriendSampleName: "Aizada K.",
dashFriendSampleDesc: "Data Science бағдарламаларына өтінім береді.",
dashMentorSampleName: "Murat R.",
dashMentorSampleDesc: "Инженерлік қабылдау бойынша түлек-тәлімгер.",
dashOnline: "Онлайн",
appTimelineTitle: "Өтінім хронологиясы",
appTimelineDesc: "Өтінім мерзімдері мен прогресін бақылаңыз",
appTimelineFeature1: "Мерзімдерді бақылау",
appTimelineFeature1Desc: "Ақылды еске салғыштармен өтінім мерзімін жіберіп алмаңыз",
appTimelineFeature2: "Прогресті бақылау",
appTimelineFeature2Desc: "Барлық университеттердегі өтінім мәртебесін бірден қараңыз",
appTimelineFeature3: "Кезеңдерді жоспарлау",
appTimelineFeature3Desc: "Тест дайындығынан виза өтінішіне дейін негізгі кезеңдерді жоспарлаңыз",
appTimelineFeature4: "Күнтізбемен синхрондау",
appTimelineFeature4Desc: "Мерзімдерді күнтізбеңізбен синхрондаңыз",
appTimelineCta: "Бақылауды бастау",
myDocsTitle: "Менің құжаттарым",
myDocsDesc: "Өтінім құжаттары мен транскриптеріңізді басқарыңыз",
myDocsFeature1: "Құжаттарды сақтау",
myDocsFeature1Desc: "Транскриптерді, эсселерді және ұсыным хаттарды қауіпсіз сақтаңыз",
myDocsFeature2: "Нұсқаларды басқару",
myDocsFeature2Desc: "Өзгерістерді бақылаңыз және эссе жобаларын басқарыңыз",
myDocsFeature3: "Жылдам бөлісу",
myDocsFeature3Desc: "Тексеру үшін кеңесшілер мен тәлімгерлерге құжаттар жіберіңіз",
myDocsFeature4: "Бақылау парағы",
myDocsFeature4Desc: "Әр университет үшін қажетті құжаттарды бақылаңыз",
myDocsCta: "Құжаттарды жүктеу",
careerAnalysisTitle: "Мансап жолын талдау",
careerAnalysisDesc: "Болашақ мансап жолдары мен мүмкіндіктерді талдаңыз",
careerAnalysisFeature1: "Сала шолуы",
careerAnalysisFeature1Desc: "Салалар бойынша мансап үрдістері мен жалақы деректерін зерттеңіз",
careerAnalysisFeature2: "Дағдылар картасы",
careerAnalysisFeature2Desc: "Дағдыларыңызды сұранысқа ие мансап мүмкіндіктерімен сәйкестендіріңіз",
careerAnalysisFeature3: "Жолдарды салыстыру",
careerAnalysisFeature3Desc: "Мансап жолдарын өсу болжамымен салыстырыңыз",
careerAnalysisFeature4: "Мақсат қою",
careerAnalysisFeature4Desc: "Мансаптық кезеңдерді белгілеп, мақсатқа жетудегі прогресті бақылаңыз",
careerAnalysisCta: "Мансапты талдау",
internshipsTitle: "Тағылымдама іздеу",
internshipsDesc: "Мақсаттарыңызға сәйкес тағылымдама мүмкіндіктерін табыңыз",
internshipsFeature1: "Ақылды таңдау",
internshipsFeature1Desc: "AI сізге тиісті тағылымдамаларды ұсынады",
internshipsFeature2: "Өтінім бақылаушысы",
internshipsFeature2Desc: "Тағылымдама өтінімдерін бір жерде бақылаңыз",
internshipsFeature3: "Компанияларды зерттеу",
internshipsFeature3Desc: "Тағылымдама ұсынатын компаниялардың толық профильдері",
internshipsFeature4: "Дағдыларды дамыту",
internshipsFeature4Desc: "Мақсатты тағылымдама үшін қажет дағдыларды анықтаңыз",
internshipsCta: "Тағылымдама табу",
mastersTitle: "Магистратура іздеу",
mastersDesc: "Дүниежүзіндегі магистрлік бағдарламаларды зерттеңіз",
mastersFeature1: "Бағдарламаларды іздеу",
mastersFeature1Desc: "Дүниежүзіндегі университеттердің магистрлік бағдарламаларын зерттеңіз",
mastersFeature2: "Қабылдау шарттары",
mastersFeature2Desc: "Қабылдау талаптары мен бәсекелестік деңгейін біліңіз",
mastersFeature3: "Қаржыландыру мүмкіндіктері",
mastersFeature3Desc: "Магистранттарға арналған стипендиялар мен ассистентуралар",
mastersFeature4: "Мансаптық нәтижелер",
mastersFeature4Desc: "Бағдарлама түлектерінің жұмысқа орналасу статистикасы",
mastersCta: "Бағдарламаларды зерттеу",
uniReelsTitle: "Университет бейнежазбалары",
uniReelsDesc: "Кампус туры мен студент өмірі туралы бейнелерді қараңыз",
uniReelsFeature1: "Кампус турлары",
uniReelsFeature1Desc: "Дүниежүзіндегі кампустардың виртуалды турлары",
uniReelsFeature2: "Студенттер әңгімелері",
uniReelsFeature2Desc: "Қазіргі студенттердің тәжірибесі туралы әңгімелері",
uniReelsFeature3: "Қала нұсқаулары",
uniReelsFeature3Desc: "Үздік университеттер орналасқан қалаларды зерттеңіз",
uniReelsFeature4: "Іс-шара шолулары",
uniReelsFeature4Desc: "Ашық есік күндері мен кампус іс-шараларының жазбалары",
uniReelsCta: "Қарау",
privacyTitle: "Менің құпиялылық тақтасы",
privacyDesc: "Құпиялылық параметрлері мен деректеріңізді басқарыңыз",
privacyFeature1: "Деректерді басқару",
privacyFeature1Desc: "Біз жинайтын барлық деректерді қараңыз және басқарыңыз",
privacyFeature2: "Көріну параметрлері",
privacyFeature2Desc: "Профиліңізді кім көретінін реттеңіз",
privacyFeature3: "Деректерді экспорттау",
privacyFeature3Desc: "Барлық жеке деректеріңіздің көшірмесін кез келген уақытта жүктеп алыңыз",
privacyFeature4: "Тіркелгіні жою",
privacyFeature4Desc: "Тіркелгіңізді және барлық байланысты деректерді толығымен жойыңыз",
privacyCta: "Параметрлерді тексеру",
studyTogetherTitle: "Бірге оқу",
studyTogetherDesc: "Құрдастармен және оқу топтарымен байланысыңыз",
studyTogetherFeature1: "Топ іздеу",
studyTogetherFeature1Desc: "Ұқсас мақсаттар мен кестесі бар оқу серіктесін табыңыз",
studyTogetherFeature2: "Тікелей сессиялар",
studyTogetherFeature2Desc: "Дүниежүзіндегі құрдастармен нақты уақытта оқу сессияларына қосылыңыз",
studyTogetherFeature3: "Материалдармен бөлісу",
studyTogetherFeature3Desc: "Конспектілер, материалдар және оқу стратегияларымен бөлісіңіз",
studyTogetherFeature4: "Бірге прогресс",
studyTogetherFeature4Desc: "Ортақ мақсаттарды бақылаңыз және бір-біріңізді ынталандырыңыз",
studyTogetherCta: "Оқу серіктесін табу",
sendInfoPageTitle: "Ақпарат жіберу — Premium алу",
sendInfoOfferHeadline: "7 күн Premium ТЕГІН!",
sendInfoOfferBody: "Университет немесе стипендия туралы сұраныс жіберіңіз — бірден 7 күн Premium алыңыз.",
sendInfoTabUniversity: "Университет туралы",
sendInfoTabScholarship: "Стипендия туралы",
sendInfoTabApplication: "Өтінімге көмек",
sendInfoTabMeeting: "Кездесу",
sendInfoTabOther: "Басқа сұраныс",
sendInfoFieldFullName: "Аты-жөні",
sendInfoFieldEmail: "Электрондық пошта",
sendInfoFieldPhone: "Телефон",
sendInfoFieldUniversity: "Университет",
sendInfoFieldUniversityInterest: "Қызықтыратын университет",
sendInfoFieldProgram: "Бағдарлама",
sendInfoFieldProgramMajor: "Бағдарлама / мамандық",
sendInfoFieldGpa: "Орташа балл (GPA)",
sendInfoFieldAdditional: "Қосымша ақпарат",
sendInfoFieldScholarshipName: "Стипендия атауы",
sendInfoFieldAchievements: "Академиялық жетістіктер",
sendInfoFieldDeadline: "Өтінім беру мерзімі",
sendInfoFieldHelp: "Қандай көмек керек?",
sendInfoFieldMeetingType: "Кездесу түрі",
sendInfoFieldPreferredDate: "Қалаулы күн",
sendInfoFieldPreferredTime: "Қалаулы уақыт",
sendInfoFieldNotes: "Қосымша ескертулер",
sendInfoFieldSubject: "Тақырып",
sendInfoFieldMessage: "Хабарлама",
sendInfoPhFullName: "Аты-жөніңізді жазыңыз",
sendInfoPhEmail: "Электрондық поштаңызды жазыңыз",
sendInfoPhPhone: "Телефон нөміріңізді жазыңыз",
sendInfoPhUniversityInterest: "Қандай университет қызықтырады?",
sendInfoPhProgramInterest: "Қандай бағдарлама қызықтырады?",
sendInfoPhGpa: "GPA жазыңыз",
sendInfoPhGoals: "Мақсаттарыңыз туралы айтып беріңіз...",
sendInfoPhScholarship: "Қандай стипендия қызықтырады?",
sendInfoPhUniversityOpt: "Қатысты университет (болса)",
sendInfoPhAchievements: "Жетістіктеріңізді жазыңыз...",
sendInfoPhUniversityRequired: "Қандай университет?",
sendInfoPhProgramRequired: "Қандай бағдарлама?",
sendInfoPhHelp: "Қандай көмек керек, жазыңыз...",
sendInfoPhSubject: "Сұранысыңыз не туралы?",
sendInfoPhContact: "Қалай көмектесе аламыз?",
sendInfoPhNotes: "Қосымша ақпарат...",
sendInfoMeetingSelect: "Кездесу түрін таңдаңыз",
sendInfoMeetingConsult: "Жалпы консультация",
sendInfoMeetingAppReview: "Өтінімді тексеру",
sendInfoMeetingScholarship: "Стипендия консультациясы",
sendInfoMeetingCareer: "Мансаптық кеңес",
sendInfoSubmit: "Жіберу — Premium алу",
sendInfoSubmitting: "Жіберілуде...",
sendInfoError: "Сұрауыңызды жіберу мүмкін болмады. Байланысты тексеріп, қайта көріңіз.",
sendInfoSuccessTitle: "Ақпарат сәтті жіберілді!",
sendInfoSuccessBody: "Хабарласқаныңыз үшін рахмет. Командамыз ақпаратты қарап шығып, сізбен жақын арада байланысады.",
sendInfoPremiumActivated: "Premium қолжетімділік белсенді!",
sendInfoPremiumActivatedBody: "Сізде 7 күн Premium функцияларға қолжетімділік бар.",
sendInfoBackToDashboard: "Басқару тақтасына оралу",
sendInfoTitleBack: "Басқару тақтасына оралу",
required: "міндетті",
smartMatch: "Ақылды таңдау",
aboutCoreAccess: "Негізгі қол жеткізу қамтылған",
aboutGlobal: "Жаhандық",
contactLabelEmail: "Электрондық пошта",
contactLabelTopic: "Тақырып",
loginSubtitle: "Қайта оралғаныңызбен! Тіркелгіңізге кіріңіз.",
loginEmailLabel: "Электрондық пошта",
loginEmailPlaceholder: "Электрондық поштаңызды жазыңыз",
loginPasswordLabel: "Құпиясөз",
loginPasswordPlaceholder: "Құпиясөзіңізді жазыңыз",
loginSubmit: "Кіру",
loginSubmitting: "Кіру...",
loginNoAccount: "Тіркелгіңіз жоқ па?",
loginSignUpHere: "Осы жерден тіркеліңіз",
loginContinueAsGuest: "Қонақ ретінде жалғастыру",
loginGuestSuffix: "— кірмей қолданбаны көру.",
loginForgotLink: "Құпиясөзді ұмыттыңыз ба?",
forgotSubtitle: "Электрондық поштаңызды жазыңыз — сілтеме жібереміз.",
forgotSubmit: "Қалпына келтіру сілтемесін жіберу",
forgotSent: "Бұл пошта тіркелген болса, сілтеме жолда. Кіріс қорапты тексеріңіз.",
forgotBackToLogin: "Кіруге оралу",
forgotError: "Қалпына келтіруді бастау мүмкін болмады. Қайта көріңіз.",
resetSubtitle: "Жаңа құпиясөз таңдаңыз.",
resetNoToken: "Сілтемеде токен жоқ. Жаңасын сұраңыз.",
resetDone: "Құпиясөз жаңартылды. Енді кіруге болады.",
resetGoToLogin: "Кіруге өту",
resetNewPasswordLabel: "Жаңа құпиясөз",
resetNewPasswordPlaceholder: "Кемінде 8 таңба",
resetSubmit: "Құпиясөзді жаңарту",
resetTooShort: "Құпиясөз кемінде 8 таңбадан тұруы керек.",
resetError: "Қалпына келтіру сілтемесі жарамсыз немесе мерзімі өткен.",
verifyVerifying: "Электрондық поштаңыз тексерілуде…",
verifyOk: "Электрондық поштаңыз расталды. Рахмет!",
verifyError: "Растау сілтемесі жарамсыз немесе мерзімі өткен.",
loginFailedMessage: "Кіру сәтсіз. Электрондық пошта мен құпиясөзіңізді тексеріңіз.",
registerSubtitle: "Тіркелгі жасаңыз — еліңізді таңдаңыз.",
registerFirstName: "Аты",
registerLastName: "Тегі",
registerEmail: "Электрондық пошта",
registerEmailPlaceholder: "you@example.com",
registerPassword: "Құпиясөз",
registerCountry: "Ел",
registerCountriesLoading: "Елдер жүктелуде...",
registerSelectCountry: "Еліңізді таңдаңыз",
registerCountryHint: "Тіркелгі жасау үшін қажет.",
registerNoCountriesHint: "Елдер жүктелмеді. Backend серверін іске қосып, дерекқорда елдер бар екенін тексеріңіз, немесе төменде «Қонақ ретінде жалғастыру» түймесін қолданыңыз.",
registerSubmit: "Тіркелгі жасау",
registerSubmitting: "Тіркелгі жасалуда...",
registerHaveAccount: "Тіркелгіңіз бар ма?",
registerLogIn: "Кіру",
registerGuestSuffix: "— тіркелмей қолданбаны көру.",
registerSelectCountryError: "Елді таңдаңыз.",
registerFillAllError: "Барлық өрістерді толтырыңыз.",
registerFailedError: "Тіркелу сәтсіз аяқталды.",
publicSeeHowItWorks: "YouTube-те қалай жұмыс істейтінін көру",
publicAboutUs: "Біз туралы",
publicSupportQr: "Қолдау QR",
publicFaq: "Жиі қойылатын сұрақтар",
publicContactUs: "Бізбен байланысу",
publicSendMessage: "Бізге хабарлама жіберіңіз",
publicMessageSent: "Рахмет! Хабарламаңыз жіберілді.",
publicFullName: "Аты-жөні",
publicFullNamePh: "Аты-жөніңізді жазыңыз",
publicTopicPh: "Қандай көмек керек?",
publicMessageLabel: "Хабарлама",
publicMessagePh: "Хабарламаңызды жазыңыз",
publicFooterPrivacy: "Құпиялылық",
publicFooterTerms: "Шарттар",
publicFooterContact: "Байланыс",
publicStudentSupport: "Студенттерге қолдау",
publicUnisWorldwide: "Әлем бойынша университеттер",
publicSupportNumber: "Қолдау нөмірі",
publicQrPlaceholder: "Осы жерге қолдау QR-суретін қосыңыз",
publicAboutLead: "ilmi әлем бойынша студенттерге AI-таңдау арқылы дұрыс университет пен стипендияларды табуға көмектеседі. Біздің миссиямыз — жоғары білімді әркімге қолжетімді ету.",
publicAboutCopy: "Университеттер мен стипендияларды іздеуге негізгі қол жеткізу қамтылған, студенттер бірден қолдана алатын құралдармен.",
publicMainServices: "Негізгі қызметтер",
searchUniNamePlaceholder: "Университет немесе колледж атауы бойынша іздеу…",
searchUniClearAll: "Бәрін тазалау",
searchUniTuitionRange: "Жылдық оқу ақысы (€)",
searchUniMatching: "Сәйкес келетін мекемелер",
searchUniLoadingList: "Университеттер жүктелуде...",
uniDetailLoadingTitle: "Жүктелуде...",
uniDetailLoadingBody: "Университет ақпараты жүктелуде...",
uniDetailNotFound: "Мекеме табылмады",
searchUniPopularUnder10k: "€10 мыңға дейін / жыл",
searchUniPopularUnder5k: "≤ €5 мың / жыл",
searchUniPopularEnglish: "Ағылшын тілінде",
searchUniPopularEurope: "Еуропа",
searchUniPopularBusiness: "Бизнес және құқық",
searchUniPopularMedicine: "Медицина және ғылым",
searchUniPopularArts: "Өнер және дизайн",
searchUniInstAll: "Барлығы",
searchUniInstUniversities: "Тек университеттер",
searchUniInstColleges: "Тек колледждер",
searchUniDegreeAll: "Барлық деңгейлер",
searchUniDegreeAssociate: "Ассоциат",
searchUniDegreeDiploma: "Диплом",
searchUniDegreeBachelor: "Бакалавр",
searchUniDegreeMaster: "Магистр",
searchUniDegreePhd: "PhD / Докторантура",
searchUniLangAny: "Кез келген тіл",
searchUniLangEnglish: "Ағылшын",
searchUniLangGerman: "Неміс",
searchUniLangFrench: "Француз",
searchUniLangSpanish: "Испан",
searchUniLangDutch: "Голланд",
searchUniLangCatalan: "Каталан",
searchUniAllCountries: "Барлық елдер",
searchUniAllFields: "Барлық бағыттар",
searchUniAllCities: "Осы елдегі барлық қалалар",
searchResultOne: "нәтиже",
searchResultMany: "нәтижелер",
searchUniNameLabel: "Мекеме атауы бойынша іздеу",
searchUniPopularHeading: "Танымал сүзгілер",
searchUniInstTypeLabel: "Мекеме түрі",
searchUniCountryLabel: "Ел",
searchUniCityLabel: "Қала / аймақ",
searchUniFieldLabel: "Бағыт",
searchUniDegreeLabel: "Дәреже деңгейі",
searchUniLanguageLabel: "Оқу тілі",
searchUniMin: "Мин",
searchUniMax: "Макс",
featureSmartMatchTitle: "Университеттерді ақылды таңдау",
featureSmartMatchDesc: "AI профиліңізді, мақсаттарыңыз бен қалауларыңызды талдап, лайықты университеттерді ұсынады.",
featureScholarshipTitle: "Стипендиялар мен қаржыландыру",
featureScholarshipDesc: "Білім беру бюджетіңізді жоспарлау үшін стипендиялар, гранттар мен қолдау бағдарламаларын табыңыз.",
featureInsightsTitle: "Қабылдау аналитикасы",
featureInsightsDesc: "Қабылдау трендтерін, бағдарлама бөлшектерін және нәтижелерді салыстырып, негізді шешім қабылдаңыз.",
featureGlobalTitle: "Әлемдегі университеттерге қол жеткізу",
featureGlobalDesc: "Әртүрлі елдердегі университеттерді нақты бағдарлама және қабылдау ақпаратымен зерттеңіз.",
featureAnyDeviceTitle: "Кез келген құрылғыдан ыңғайлы қол жеткізу",
featureAnyDeviceDesc: "ilmi-ні мобильдік немесе компьютерден қолданып, сәйкестіктер мен қадамдарыңызды бақылаңыз.",
featureAdvisorTitle: "Кеңесшілердің қолдауы",
featureAdvisorDesc: "Қабылдау, өтінім және жоспарлау бойынша кеңесшілерден практикалық көмек алыңыз.",
programsAllCategories: "Барлық санаттар",
programsAllCountries: "Барлық елдер",
programsTuitionFree: "Тегін / мемлекеттік",
searchUniLangItalian: "Итальян",
searchUniLangJapanese: "Жапон",
searchUniLangKorean: "Корей",
chartUnis: "Университеттер",
chartScholarshipsLabel: "Стипендиялар",
monthJan: "Қаң",
monthFeb: "Ақп",
monthMar: "Нау",
monthApr: "Сәу",
monthMay: "Мам",
monthJun: "Мау",
heroTitleLine2: "Оқу жолыңызға бағыт",
heroDescription2: "Бір қарапайым платформада университеттер, стипендиялар, қабылдау және магистратура бағдарламалары туралы нақты нұсқау.",
heroCtaPrimary: "Бастау",
heroCtaSecondary: "Қалай жұмыс істейді",
faqQ1: "ilmi ақылы ма?",
faqA1: "Негізгі функциялар — университеттерді таңдау, стипендияларды табу және негізгі ақпарат — тегін. Премиум қолдау тілек бойынша ақылы.",
faqQ2: "Таңдау процесі қалай жұмыс істейді?",
faqA2: "AI мақсаттарыңызды, профиліңіз бен қалауыңызды талдап, лайықты университеттер мен стипендиялар тізімін көрсетеді.",
faqQ3: "Қандай елдер мен университеттер қамтылған?",
faqA3: "Біз көптеген елдердегі университеттер мен стипендияларды қамтимыз. Ел, бағдарлама және қаржыландыру бойынша сүзіңіз.",
faqQ4: "ilmi-ді қалай қолдай аламын?",
faqA4: "«Біз туралы» бөліміндегі қайырмалдықтар арқылы қолдай аласыз. Сіздің қолдауыңыз барлық студенттер үшін негізгі қол жеткізуді сақтауға көмектеседі.",
searchFieldDefaultPlaceholder: "Мекемелерді іздеу",
selectFieldDefaultPlaceholder: "Таңдаңыз",
skyToggleToLight: "Ашық тақырыпқа ауысу",
skyToggleToDark: "Қара тақырыпқа ауысу",
errFailedLoadFavorites: "Сүйікті тізімін жүктеу сәтсіз.",
errFailedRemoveFavorite: "Сүйіктіден жою сәтсіз.",
interestsTitle: "Сіздің қызығушылықтарыңыз",
interestsIntro: "Қызығатын дәреже деңгейлері мен бағыттарды көрсетіңіз. Біз оларды сәйкестіктерді таңдауға қолданамыз.",
interestsDegreeLabel: "Қызығатын дәреже",
interestsFieldLabel: "Қызығатын бағыт",
interestsAdded: "Қосылды",
interestsAddDegree: "Дәреже қосу",
interestsAddField: "Бағыт қосу",
interestsNoDegrees: "Дәреже жоқ",
interestsNoFields: "Бағыт жоқ",
interestsRemoveAria: "жою",
fundingTitle: "Бюджет — қаржыландыру көздері",
fundingTotalLabel: "Барлығы",
fundingHint: "Оқуға бөле алатын сомаңызды қосыңыз (отбасы, жинақ, стипендия, несие). Жалпы сома қолжетімділік бойынша сәйкестік бюджетіңіз болады.",
fundingRemoveAria: "{label} жою",
fundingSourcePlaceholder: "Көзі (мыс. Отбасы)",
fundingAmountPlaceholder: "Сома/жыл (USD)",
fundingAdd: "Қосу",
profileMaxBudget: "Макс. бюджет / жыл (USD)",
profileMaxBudgetPlaceholder: "мыс. 15000",
dashNoDeadlines: "Мерзімдер жоқ. Мерзімді осы жерде көру үшін өтінімді бақылаңыз.",
dashNoTopMatches: "Нақты үздік университет сәйкестіктерін көру үшін сәйкестіктер бетіне өз бағаларыңызды қосыңыз.",
dashNoTopScholarships: "Профиліңізге стипендиялар қол жетімді болған кезде, үздік сәйкестіктер осы жерде шығады.",
dashEligible: "Сәйкес",
dashNotYet: "Әлі жоқ",
dashNotEligible: "Сәйкес емес",
matchTitle: "Университет сәйкестіктері",
matchDescriptionGuest: "Қандай бағдарламаларға сәйкес екеніңізді, сәйкестік дәрежесі бойынша көріңіз.",
matchDescription: "Қандай бағдарламаларға сәйкес екеніңізді көру үшін академиялық ақпаратыңызды енгізіңіз.",
matchGuestCtaTitle: "Сәйкестіктер алу үшін тегін тіркелгі жасаңыз",
matchGuestCtaDesc: "Таңдау бағалар мен емтихан нәтижелерін пайдаланады, сондықтан сақталған профиль қажет. Қонақтар шолуы мүмкін, бірақ сәйкестіктер үшін тіркелгі керек.",
matchGuestSignUp: "Тіркелу",
matchAcademicInfoTitle: "Академиялық ақпаратыңыз",
matchAcademicInfoIntro: "Пән бағалары мен емтихан нәтижесін қосыңыз. Біз оларды әр бағдарламаның жарияланған талаптарымен салыстырамыз — деректер профиліңізге сақталады.",
matchGradingSystem: "Бағалау жүйесі",
matchHighestDegree: "Жоғарғы дәреже",
matchSubjects: "Пәндер",
matchSubjectPlaceholder: "Пән",
matchGradePlaceholder: "Баға",
matchRemoveSubject: "Пәнді жою",
matchAddSubject: "+ Пән қосу",
matchExam: "Емтихан",
matchScore: "Балл",
matchScorePlaceholder: "мыс. 100",
matchMaxScore: "Макс. балл",
matchMaxScorePlaceholder: "мыс. 120",
matchSaving: "Сақталуда…",
matchSaveAndFind: "Сақтап, сәйкестіктерді табу",
matchFinding: "Сәйкестіктер іздеуде…",
matchPromptSave: "Жоғарыдан бағаларыңызды қосып, «Сақтап, сәйкестіктерді табу» түймесін басыңыз.",
matchNoPrograms: "Бағдарламалар әлі жоқ. Бағдарламалар қосылғаннан кейін қайта кіріңіз.",
matchEligibleOf: "{total} бағдарламадан {eligible} сәйкес",
matchTuitionFree: "Оқу ақысыз",
matchGradingGpa4: "GPA (4.0 шкаласы)",
matchGradingGpa5: "GPA (5.0 шкаласы)",
matchGradingFive: "5 балдық (ТМД)",
matchGradingTen: "10 балдық",
matchDegreeHighSchool: "Орта мектеп аттестаты",
matchDegreeAssociate: "Кіші маман",
matchDegreeBachelor: "Бакалавр",
matchDegreeMaster: "Магистр",
matchDegreeDoctorate: "Докторантура",
matchExamNone: "Емтихансыз",
matchTierSafety: "Сенімді",
matchTierTarget: "Мақсатты",
matchTierReach: "Қиындау",
matchTierFarReach: "Өте қиын",
matchTranscriptSelfReported: "Өзі көрсеткен",
matchTuitionPerYear: "{amount} {currency}/жыл",
matchPercentFit: "{fit}% сәйкестік",
matchPercentAcademic: "{score}% академиялық",
matchEligible: "Сәйкес",
matchNotYetEligible: "Әлі сәйкес емес",
matchAllMet: "✓ Барлық талаптарды орындадыңыз.",
matchWhatsMissing: "Нені жетіспейді",
matchNeedHave: "керек {required}, бар {actual}",
matchTracking: "✓ Бақыланып жатыр",
matchAdding: "Қосылуда…",
matchTrackApplication: "+ Өтінімді бақылау",
appsTitle: "Менің өтінімдерім",
appsDescription: "Өтінім беріп жатқан барлық бағдарламаны бақылаңыз — мәртебе, мерзімдер және жазбалар бір жерде.",
appsNoDeadlineSet: "Мерзім белгіленбеген",
appsPastDue: "Мерзімі өтіп кетті ({days} күн бұрын)",
appsDueToday: "Бүгін мерзімі аяқталады",
appsDaysLeft: "{days} күн қалды",
appsLoading: "Өтінімдер жүктелуде…",
appsEmptyTitle: "Өтінімдер жоқ",
appsEmptyHintBefore: "Сәйкес бағдарламаларды тауып,",
appsTrackApplicationQuoted: "«Өтінімді бақылау»",
appsEmptyHintAfter: "түймесін басып, мерзімдері бар тізім жасаңыз.",
appsFindMatches: "Сәйкестіктерді табу →",
appsCountOne: "{count} өтінім",
appsCountMany: "{count} өтінім",
appsStatus: "Мәртебе",
appsDeadline: "Мерзім",
appsRemove: "Жою",
appsSubmitted: "{date} жіберілді",
appsHideChecklist: "▾ Тізімді жасыру",
appsShowChecklist: "▸ Тізім",
checklistLoading: "Тізім жүктелуде…",
checklistDone: "{done}/{total} орындалды",
checklistRemoveTask: "Тапсырманы жою: {title}",
checklistAddPlaceholder: "Тапсырма қосу…",
checklistAdd: "Қосу",
uniDetailBackToSearch: "Іздеуге оралу",
uniDetailNoMatch: "«{slug}» сұранысы бойынша университет табылмады.",
uniDetailReturnToSearch: "Іздеуге оралу",
uniDetailUniversity: "Университет",
uniDetailCollege: "Колледж",
uniDetailLanguages: "Тілдер: {languages}",
uniDetailApply: "Өтінім беру",
uniDetailTuitionPublic: "Оқу ақысыз (мемлекеттік)",
uniDetailTuitionAnnual: "≈ {amount} / жыл",
uniDetailProgramFree: "Тегін / мемлекеттік",
onboardingRegionLabel: "Бастау",
onboardingTitle: "ilmi-ге қош келдіңіз 👋",
onboardingSub: "Университет сәйкестіктеріңізді, қабылдану мүмкіндіктеріңізді және стипендия сәйкестігіңізді ашу үшін бағаларыңызды және бір емтиханды қосыңыз — шамамен бір минут.",
onboardingCta: "Сәйкестікті табу →",
onboardingDismiss: "Жабу",
jobsTitle: "Жұмыс және тағылымдама",
jobsDesc: "Студенттерге арналған мүмкіндіктер — бағыт бойынша сүзіңіз.",
jobsFieldLabel: "Бағыт",
jobsAllFields: "Барлық бағыттар",
jobsLoading: "Жұмыс орындары жүктелуде…",
jobsEmpty: "Бұл сүзгі бойынша жұмыс орны жоқ.",
loadMore: "Көбірек жүктеу",
loadingMore: "Жүктелуде…",
jobsCount: "{count} мүмкіндік",
jobsApply: "Өтінім беру",
searchScholarshipsPageTitle: "Стипендиялар",
searchScholarshipsPageDesc: "Стипендияларды шолыңыз — бағыт және деңгей бойынша сүзіңіз.",
searchScholarshipsFieldLabel: "Бағыт",
searchScholarshipsAllFields: "Барлық бағыттар",
searchScholarshipsLevelLabel: "Деңгей",
searchScholarshipsAllLevels: "Барлық деңгейлер",
searchScholarshipsLevelBachelor: "Бакалавр",
searchScholarshipsLevelMaster: "Магистр",
searchScholarshipsLevelDoctorate: "Докторантура",
searchScholarshipsLoading: "Стипендиялар жүктелуде…",
searchScholarshipsEmpty: "Сүзгілеріңізге сәйкес стипендия жоқ — бағытты немесе деңгейді кеңейтіп көріңіз.",
searchScholarshipsCount: "{count} стипендия",
searchScholarshipsAwardFullTuition: "Толық оқу ақысы",
searchScholarshipsAwardPercentOff: "Оқу ақысынан {value}% жеңілдік",
searchScholarshipsAwardDefault: "Сыйақы",
matchScholTitle: "Стипендия сәйкестіктері",
matchScholDesc: "Профиліңіз бойынша — азаматтық, GPA және қызығушылықтар — ранжирленген белсенді стипендиялар.",
matchScholGuestDesc: "Қандай стипендияларға ықтимал сәйкес екеніңізді, сәйкестік дәрежесі бойынша көріңіз.",
matchScholGuestCtaTitle: "Сәйкестіктер алу үшін тегін тіркелгі жасаңыз",
matchScholGuestCtaDesc: "Таңдау еліңізді, бағаларыңызды және қызығушылықтарыңызды пайдаланады — қонақтар шолуы мүмкін, бірақ стипендия сәйкестіктері үшін сақталған профиль керек.",
matchScholGuestCtaBtn: "Тіркелу",
matchScholEligibleOnly: "Тек сәйкестер",
matchScholLoading: "Сіз үшін стипендиялар іздеуде…",
matchScholEmptyPrefix: "Стипендиялар әлі жоқ. Каталог толығуын күтіңіз немесе ",
matchScholEmptyLink: "қызығушылықтар мен бюджетті",
matchScholErrorDefault: "Стипендия сәйкестіктерін жүктеу мүмкін болмады",
matchScholCount: "{total} ішінен {eligible} сәйкес болуы мүмкін",
matchScholEligible: "Сәйкес",
matchScholNotEligible: "Сәйкес емес",
matchScholYourInterest: "★ Сіздің қызығушылығыңыз",
matchScholDue: "Мерзімі {date}",
matchScholAwardFullTuition: "Толық оқу ақысы",
matchScholAwardFullCost: "Оқуға кеткен барлық шығынды жабады",
matchScholAwardPercentOff: "Оқу ақысынан {value}% жеңілдік",
matchScholAwardTuitionDiscount: "Оқу ақысына жеңілдік",
matchScholAwardFixed: "Белгіленген сыйақы",
matchScholAwardVariable: "Өзгермелі сыйақы",
essayTitle: "Эссені тексеру",
essayDesc: "Өтінім эссеңізді қойып, Орталық Азиядан шыққан ағылшын тілін үйренушілерге арнап бапталған AI кері байланысын алыңыз.",
essayNotAvailableTitle: "Әлі қол жетімді емес",
essayNotAvailableText: "AI эссені тексеру бұл ортада әлі қосылмаған. Кейінірек қайта кіріңіз — қосылғанда эссеңізді осы жерге қойып, құрылымдық кері байланыс ала аласыз.",
essayTypeLabel: "Эссе түрі",
essayTypePersonalStatement: "Жеке мәлімдеме",
essayTypeMotivationLetter: "Стипендияға арналған мотивациялық хат",
essayTypeStatementOfPurpose: "Мақсат мәлімдемесі",
essayTypeCommonApp: "Common App эссесі",
essayTypeOther: "Басқа",
essayPlaceholder: "Эссеңізді осы жерге қойыңыз…",
essayReviewing: "Тексерілуде…",
essayGetFeedback: "Кері байланыс алу",
essayFeedbackTitle: "AI кері байланысы",
coursesDesc: "Серіктес дайындық курстары (ағылшын, математика және т.б.).",
coursesSubjectLabel: "Пән",
coursesAllSubjects: "Барлық пәндер",
coursesLoading: "Курстар жүктелуде…",
coursesEmpty: "Курстар әлі жоқ.",
coursesCount: "{count} курс",
coursesView: "Қарау",
dashToggleMenu: "Мәзірді ашу/жабу",
dashDeadlinesDueSoon: "{count} өтінім мерзімі жақындап қалды",
dashDeadlineToday: "Бүгін",
dashDaysAgo: "{n} күн бұрын",
dashDaysLeft: "{n} күн қалды",
publicFooterRights: "© {year} ilmi. Барлық құқықтар қорғалған",

  // My Academics page
  myAcademicsGuestDesc: "Таңдауға негіз болатын бағаларыңыз бен емтихан ұпайларыңыз.",
  myAcademicsDesc: "Таңдауларыңызға, мүмкіндіктеріңізге және стипендияларыңызға негіз болатын бағалар мен емтихандар.",
  myAcademicsGuestEmptyBefore: "Қонақтарда сақталған академиялық жазба жоқ. ",
  myAcademicsGuestEmptyAfter: " өзіңіздікін қосу үшін.",
  myAcademicsTranscripts: "Аттестаттар",
  myAcademicsAddViaMatching: "+ Таңдау арқылы қосу",
  myAcademicsLoading: "Жүктелуде…",
  myAcademicsNoTranscriptsBefore: "Әзірге аттестат жоқ. Бағаларыңызды ",
  myAcademicsMatchingPage: "таңдау бетіне",
  myAcademicsNoTranscriptsAfter: " қосып, таңдау алыңыз.",
  myAcademicsExams: "Емтихандар",
  myAcademicsNoExams: "Әзірге емтихан жоқ.",
};

export default kk;
