// Kazakh (Қазақша)
// Missing keys fall back to Russian (the audience's lingua franca), then English for
// any key Russian also lacks. Native Kazakh keys below override both.
import en from "./en";
import ru from "./ru";

const kk = {
  ...en,
  ...ru,

  // Navigation / common
  home: "Басты бет",
  search: "Іздеу",
  dashboard: "Басқару тақтасы",
  profile: "Профиль",
  settings: "Параметрлер",
  language: "Тіл",
  selectLanguage: "Тілді таңдаңыз",
  scholarships: "Стипендиялар",
  loading: "Жүктелуде...",
  required: "міндетті",

  // Dashboard nav
  dashMain: "НЕГІЗГІ",
  dashDashboard: "Басты бет",
  dashDreamUniversity: "Арман университеті",
  dashSearchUniversities: "Университеттер",
  dashFavoriteUniversities: "Сүйікті университеттер",
  dashSearchFields: "Бағыттар",
  dashSearchPrograms: "Бағдарламалар",
  dashFavoritePrograms: "Сүйікті бағдарламалар",
  dashSearchScholarships: "Стипендиялар",
  dashNavAiTools: "AI ҚҰРАЛДАРЫ",
  dashMatchUniversities: "Университет таңдау",
  dashMatchScholarships: "Стипендия таңдау",
  dashSimilarStudents: "Ұқсас студенттер",
  dashNavFriendsAndMentors: "ДОСТАР ЖӘНЕ ТӘЛІМГЕРЛЕР",
  dashConnectFriends: "Достар",
  dashNavSectionContactPremium: "БАЙЛАНЫС",
  dashContactPremium: "Байланыс",
  dashSendInfo: "Ақпарат жіберіп Premium алу",
  dashJoinCommunity: "Қоғамдастыққа қосылу",
  dashTagline: "Сіздің университеттік жолыңыз осы жерден басталады",
  dashWelcomeBackPrefix: "Қайта оралғаныңызбен,",
  dashNotifications: "Хабарламалар",
  dashProfile: "Профиль",
  dashDefaultDisplayName: "Аты-жөні",

  // Auth
  loginTitle: "Қолданбаға кіріңіз",
  registerTitle: "Тіркелгі жасау",

  // SendInfo
  sendInfoPageTitle: "Ақпарат жіберу — Premium алу",
  sendInfoOfferHeadline: "7 күн Premium ТЕГІН!",
  sendInfoOfferBody:
    "Университет немесе стипендия туралы сұраныс жіберіңіз — бірден 7 күн Premium алыңыз.",
  sendInfoTabUniversity: "Университет туралы",
  sendInfoTabScholarship: "Стипендия туралы",
  sendInfoTabApplication: "Өтінімге көмек",
  sendInfoTabMeeting: "Кездесу",
  sendInfoTabOther: "Басқа сұраныс",
  sendInfoFieldFullName: "Аты-жөні",
  sendInfoFieldEmail: "Электрондық пошта",
  sendInfoFieldPhone: "Телефон",
  sendInfoFieldUniversity: "Университет",
  sendInfoFieldUniversityInterest: "Қызықтыратын университет",
  sendInfoFieldProgram: "Бағдарлама",
  sendInfoFieldProgramMajor: "Бағдарлама / мамандық",
  sendInfoFieldGpa: "Орташа балл (GPA)",
  sendInfoFieldAdditional: "Қосымша ақпарат",
  sendInfoFieldScholarshipName: "Стипендия атауы",
  sendInfoFieldAchievements: "Академиялық жетістіктер",
  sendInfoFieldDeadline: "Өтінім беру мерзімі",
  sendInfoFieldHelp: "Қандай көмек керек?",
  sendInfoFieldMeetingType: "Кездесу түрі",
  sendInfoFieldPreferredDate: "Қалаулы күн",
  sendInfoFieldPreferredTime: "Қалаулы уақыт",
  sendInfoFieldNotes: "Қосымша ескертулер",
  sendInfoFieldSubject: "Тақырып",
  sendInfoFieldMessage: "Хабарлама",
  sendInfoPhFullName: "Аты-жөніңізді жазыңыз",
  sendInfoPhEmail: "Электрондық поштаңызды жазыңыз",
  sendInfoPhPhone: "Телефон нөміріңізді жазыңыз",
  sendInfoPhUniversityInterest: "Қандай университет қызықтырады?",
  sendInfoPhProgramInterest: "Қандай бағдарлама қызықтырады?",
  sendInfoPhGpa: "GPA жазыңыз",
  sendInfoPhGoals: "Мақсаттарыңыз туралы айтып беріңіз...",
  sendInfoPhScholarship: "Қандай стипендия қызықтырады?",
  sendInfoPhUniversityOpt: "Қатысты университет (болса)",
  sendInfoPhAchievements: "Жетістіктеріңізді жазыңыз...",
  sendInfoPhUniversityRequired: "Қандай университет?",
  sendInfoPhProgramRequired: "Қандай бағдарлама?",
  sendInfoPhHelp: "Қандай көмек керек, жазыңыз...",
  sendInfoPhSubject: "Сұранысыңыз не туралы?",
  sendInfoPhContact: "Қалай көмектесе аламыз?",
  sendInfoPhNotes: "Қосымша ақпарат...",
  sendInfoMeetingSelect: "Кездесу түрін таңдаңыз",
  sendInfoMeetingConsult: "Жалпы консультация",
  sendInfoMeetingAppReview: "Өтінімді тексеру",
  sendInfoMeetingScholarship: "Стипендия консультациясы",
  sendInfoMeetingCareer: "Мансаптық кеңес",
  sendInfoSubmit: "Жіберу — Premium алу",
  sendInfoSubmitting: "Жіберілуде...",
  sendInfoSuccessTitle: "Ақпарат сәтті жіберілді!",
  sendInfoSuccessBody:
    "Хабарласқаныңыз үшін рахмет. Командамыз ақпаратты қарап шығып, сізбен жақын арада байланысады.",
  sendInfoPremiumActivated: "Premium қолжетімділік белсенді!",
  sendInfoPremiumActivatedBody: "Сізде 7 күн Premium функцияларға қолжетімділік бар.",
  sendInfoBackToDashboard: "Басқару тақтасына оралу",
  sendInfoTitleBack: "Басқару тақтасына оралу",
  smartMatch: "Ақылды таңдау",
  aboutCoreAccess: "Негізгі қол жеткізу қамтылған",
  aboutGlobal: "Жаhандық",
  contactLabelEmail: "Электрондық пошта",
  contactLabelTopic: "Тақырып",

  // Login page
  loginSubtitle: "Қайта оралғаныңызбен! Тіркелгіңізге кіріңіз.",
  loginEmailLabel: "Электрондық пошта",
  loginEmailPlaceholder: "Электрондық поштаңызды жазыңыз",
  loginPasswordLabel: "Құпиясөз",
  loginPasswordPlaceholder: "Құпиясөзіңізді жазыңыз",
  loginSubmit: "Кіру",
  loginSubmitting: "Кіру...",
  loginNoAccount: "Тіркелгіңіз жоқ па?",
  loginSignUpHere: "Осы жерден тіркеліңіз",
  loginContinueAsGuest: "Қонақ ретінде жалғастыру",
  loginGuestSuffix: "— кірмей қолданбаны көру.",
  loginFailedMessage: "Кіру сәтсіз. Электрондық пошта мен құпиясөзіңізді тексеріңіз.",

  // Register page
  registerSubtitle: "Тіркелгі жасаңыз — еліңізді таңдаңыз.",
  registerFirstName: "Аты",
  registerLastName: "Тегі",
  registerEmail: "Электрондық пошта",
  registerEmailPlaceholder: "you@example.com",
  registerPassword: "Құпиясөз",
  registerCountry: "Ел",
  registerCountriesLoading: "Елдер жүктелуде...",
  registerSelectCountry: "Еліңізді таңдаңыз",
  registerCountryHint: "Тіркелгі жасау үшін қажет.",
  registerNoCountriesHint:
    "Елдер жүктелмеді. Backend серверін іске қосып, дерекқорда елдер бар екенін тексеріңіз, немесе төменде «Қонақ ретінде жалғастыру» түймесін қолданыңыз.",
  registerSubmit: "Тіркелгі жасау",
  registerSubmitting: "Тіркелгі жасалуда...",
  registerHaveAccount: "Тіркелгіңіз бар ма?",
  registerLogIn: "Кіру",
  registerGuestSuffix: "— тіркелмей қолданбаны көру.",
  registerSelectCountryError: "Елді таңдаңыз.",
  registerFillAllError: "Барлық өрістерді толтырыңыз.",
  registerFailedError: "Тіркелу сәтсіз аяқталды.",

  // PublicHome
  publicSeeHowItWorks: "YouTube-те қалай жұмыс істейтінін көру",
  publicAboutUs: "Біз туралы",
  publicSupportQr: "Қолдау QR",
  publicFaq: "Жиі қойылатын сұрақтар",
  publicContactUs: "Бізбен байланысу",
  publicSendMessage: "Бізге хабарлама жіберіңіз",
  publicMessageSent: "Рахмет! Хабарламаңыз жіберілді.",
  publicFullName: "Аты-жөні",
  publicFullNamePh: "Аты-жөніңізді жазыңыз",
  publicTopicPh: "Қандай көмек керек?",
  publicMessageLabel: "Хабарлама",
  publicMessagePh: "Хабарламаңызды жазыңыз",
  publicFooterPrivacy: "Құпиялылық",
  publicFooterTerms: "Шарттар",
  publicFooterContact: "Байланыс",
  publicStudentSupport: "Студенттерге қолдау",
  publicUnisWorldwide: "Әлем бойынша университеттер",
  publicSupportNumber: "Қолдау нөмірі",
  publicQrPlaceholder: "Осы жерге қолдау QR-суретін қосыңыз",
  publicAboutLead:
    "ilmi әлем бойынша студенттерге AI-таңдау арқылы дұрыс университет пен стипендияларды табуға көмектеседі. Біздің миссиямыз — жоғары білімді әркімге қолжетімді ету.",
  publicAboutCopy:
    "Университеттер мен стипендияларды іздеуге негізгі қол жеткізу қамтылған, студенттер бірден қолдана алатын құралдармен.",
  publicMainServices: "Негізгі қызметтер",

  searchUniNamePlaceholder: "Университет немесе колледж атауы бойынша іздеу…",
  searchUniClearAll: "Бәрін тазалау",
  searchUniTuitionRange: "Жылдық оқу ақысы (€)",
  searchUniMatching: "Сәйкес келетін мекемелер",
  searchUniLoadingList: "Университеттер жүктелуде...",

  uniDetailLoadingTitle: "Жүктелуде...",
  uniDetailLoadingBody: "Университет ақпараты жүктелуде...",
  uniDetailNotFound: "Мекеме табылмады",

  // Search Universities options
  searchUniPopularUnder10k: "€10 мыңға дейін / жыл",
  searchUniPopularUnder5k: "≤ €5 мың / жыл",
  searchUniPopularEnglish: "Ағылшын тілінде",
  searchUniPopularEurope: "Еуропа",
  searchUniPopularBusiness: "Бизнес және құқық",
  searchUniPopularMedicine: "Медицина және ғылым",
  searchUniPopularArts: "Өнер және дизайн",
  searchUniInstAll: "Барлығы",
  searchUniInstUniversities: "Тек университеттер",
  searchUniInstColleges: "Тек колледждер",
  searchUniDegreeAll: "Барлық деңгейлер",
  searchUniDegreeAssociate: "Ассоциат",
  searchUniDegreeDiploma: "Диплом",
  searchUniDegreeBachelor: "Бакалавр",
  searchUniDegreeMaster: "Магистр",
  searchUniDegreePhd: "PhD / Докторантура",
  searchUniLangAny: "Кез келген тіл",
  searchUniLangEnglish: "Ағылшын",
  searchUniLangGerman: "Неміс",
  searchUniLangFrench: "Француз",
  searchUniLangSpanish: "Испан",
  searchUniLangDutch: "Голланд",
  searchUniLangCatalan: "Каталан",
  searchUniAllCountries: "Барлық елдер",
  searchUniAllFields: "Барлық бағыттар",
  searchUniAllCities: "Осы елдегі барлық қалалар",

  searchResultOne: "нәтиже",
  searchResultMany: "нәтижелер",
  searchUniNameLabel: "Мекеме атауы бойынша іздеу",
  searchUniPopularHeading: "Танымал сүзгілер",
  searchUniInstTypeLabel: "Мекеме түрі",
  searchUniCountryLabel: "Ел",
  searchUniCityLabel: "Қала / аймақ",
  searchUniFieldLabel: "Бағыт",
  searchUniDegreeLabel: "Дәреже деңгейі",
  searchUniLanguageLabel: "Оқу тілі",
  searchUniMin: "Мин",
  searchUniMax: "Макс",

  featureSmartMatchTitle: "Университеттерді ақылды таңдау",
  featureSmartMatchDesc:
    "AI профиліңізді, мақсаттарыңыз бен қалауларыңызды талдап, лайықты университеттерді ұсынады.",
  featureScholarshipTitle: "Стипендиялар мен қаржыландыру",
  featureScholarshipDesc:
    "Білім беру бюджетіңізді жоспарлау үшін стипендиялар, гранттар мен қолдау бағдарламаларын табыңыз.",
  featureInsightsTitle: "Қабылдау аналитикасы",
  featureInsightsDesc:
    "Қабылдау трендтерін, бағдарлама бөлшектерін және нәтижелерді салыстырып, негізді шешім қабылдаңыз.",
  featureGlobalTitle: "Әлемдегі университеттерге қол жеткізу",
  featureGlobalDesc:
    "Әртүрлі елдердегі университеттерді нақты бағдарлама және қабылдау ақпаратымен зерттеңіз.",
  featureAnyDeviceTitle: "Кез келген құрылғыдан ыңғайлы қол жеткізу",
  featureAnyDeviceDesc:
    "ilmi-ні мобильдік немесе компьютерден қолданып, сәйкестіктер мен қадамдарыңызды бақылаңыз.",
  featureAdvisorTitle: "Кеңесшілердің қолдауы",
  featureAdvisorDesc:
    "Қабылдау, өтінім және жоспарлау бойынша кеңесшілерден практикалық көмек алыңыз.",

  programsAllCategories: "Барлық санаттар",
  programsAllCountries: "Барлық елдер",
  programsTuitionFree: "Тегін / мемлекеттік",
  searchUniLangItalian: "Итальян",
  searchUniLangJapanese: "Жапон",
  searchUniLangKorean: "Корей",

  chartUnis: "Университеттер",
  chartScholarshipsLabel: "Стипендиялар",
  monthJan: "Қаң",
  monthFeb: "Ақп",
  monthMar: "Нау",
  monthApr: "Сәу",
  monthMay: "Мам",
  monthJun: "Мау",

  heroTitleLine2: "Оқу жолыңызға бағыт",
  heroDescription2:
    "Бір қарапайым платформада университеттер, стипендиялар, қабылдау және магистратура бағдарламалары туралы нақты нұсқау.",
  heroCtaPrimary: "Бастау",
  heroCtaSecondary: "Қалай жұмыс істейді",

  faqQ1: "ilmi ақылы ма?",
  faqA1:
    "Негізгі функциялар — университеттерді таңдау, стипендияларды табу және негізгі ақпарат — тегін. Премиум қолдау тілек бойынша ақылы.",
  faqQ2: "Таңдау процесі қалай жұмыс істейді?",
  faqA2:
    "AI мақсаттарыңызды, профиліңіз бен қалауыңызды талдап, лайықты университеттер мен стипендиялар тізімін көрсетеді.",
  faqQ3: "Қандай елдер мен университеттер қамтылған?",
  faqA3:
    "Біз көптеген елдердегі университеттер мен стипендияларды қамтимыз. Ел, бағдарлама және қаржыландыру бойынша сүзіңіз.",
  faqQ4: "ilmi-ді қалай қолдай аламын?",
  faqA4:
    "«Біз туралы» бөліміндегі қайырмалдықтар арқылы қолдай аласыз. Сіздің қолдауыңыз барлық студенттер үшін негізгі қол жеткізуді сақтауға көмектеседі.",

  searchFieldDefaultPlaceholder: "Мекемелерді іздеу",
  selectFieldDefaultPlaceholder: "Таңдаңыз",
  skyToggleToLight: "Ашық тақырыпқа ауысу",
  skyToggleToDark: "Қара тақырыпқа ауысу",

  errFailedLoadFavorites: "Сүйікті тізімін жүктеу сәтсіз.",
  errFailedRemoveFavorite: "Сүйіктіден жою сәтсіз.",
};

export default kk;
