// Kyrgyz (Кыргызча)
// Missing keys fall back to Russian (the audience's lingua franca), then English for
// any key Russian also lacks. Native Kyrgyz keys below override both.
import en from "./en";
import ru from "./ru";

const ky = {
  ...en,
  ...ru,

  // Navigation / common
  home: "Башкы",
  search: "Издөө",
  dashboard: "Башкаруу панели",
  profile: "Профиль",
  settings: "Жөндөөлөр",
  language: "Тил",
  selectLanguage: "Тилди тандаңыз",
  scholarships: "Стипендиялар",
  loading: "Жүктөлүүдө...",
  required: "милдеттүү",

  // Dashboard nav
  dashMain: "НЕГИЗГИ",
  dashDashboard: "Башкы бет",
  dashDreamUniversity: "Кыял университети",
  dashSearchUniversities: "Университеттер",
  dashFavoriteUniversities: "Сүйүктүү университеттер",
  dashSearchFields: "Багыттар",
  dashSearchPrograms: "Программалар",
  dashFavoritePrograms: "Сүйүктүү программалар",
  dashSearchScholarships: "Стипендиялар",
  dashNavAiTools: "AI КУРАЛДАРЫ",
  dashMatchUniversities: "Университет тандоо",
  dashMatchScholarships: "Стипендия тандоо",
  dashSimilarStudents: "Окшош студенттер",
  dashNavFriendsAndMentors: "ДОСТОР ЖАНА МЕНТОРЛОР",
  dashConnectFriends: "Достор",
  dashNavSectionContactPremium: "КАРАЖАТ",
  dashContactPremium: "Байланыш",
  dashSendInfo: "Маалымат жөнөтүү жана Premium алуу",
  dashJoinCommunity: "Биздин коомдоштукка кошулуу",
  dashTagline: "Сиздин университеттик жолуңуз ушул жерден башталат",
  dashWelcomeBackPrefix: "Кош келиңиз,",
  dashNotifications: "Билдирүүлөр",
  dashProfile: "Профиль",
  dashDefaultDisplayName: "Аты-жөнү",

  // Auth
  loginTitle: "Тиркемеге кириңиз",
  registerTitle: "Аккаунт түзүү",

  // SendInfo
  sendInfoPageTitle: "Маалымат жөнөтүү — Premium алуу",
  sendInfoOfferHeadline: "7 күн Premium БЕКЕР!",
  sendInfoOfferBody:
    "Университет же стипендия боюнча суроо жөнөтүңүз — дароо 7 күн Premium алыңыз.",
  sendInfoTabUniversity: "Университет жөнүндө",
  sendInfoTabScholarship: "Стипендия жөнүндө",
  sendInfoTabApplication: "Арыз жардамы",
  sendInfoTabMeeting: "Жолугушуу",
  sendInfoTabOther: "Башка суроо",
  sendInfoFieldFullName: "Аты-жөнү",
  sendInfoFieldEmail: "Электрондук почта",
  sendInfoFieldPhone: "Телефон",
  sendInfoFieldUniversity: "Университет",
  sendInfoFieldUniversityInterest: "Кызыктырган университет",
  sendInfoFieldProgram: "Программа",
  sendInfoFieldProgramMajor: "Программа / адистик",
  sendInfoFieldGpa: "Орточо балл (GPA)",
  sendInfoFieldAdditional: "Кошумча маалымат",
  sendInfoFieldScholarshipName: "Стипендия аталышы",
  sendInfoFieldAchievements: "Академиялык жетишкендиктер",
  sendInfoFieldDeadline: "Арыз берүү мөөнөтү",
  sendInfoFieldHelp: "Кандай жардам керек?",
  sendInfoFieldMeetingType: "Жолугушуу түрү",
  sendInfoFieldPreferredDate: "Каалаган күн",
  sendInfoFieldPreferredTime: "Каалаган убакыт",
  sendInfoFieldNotes: "Кошумча эскертүүлөр",
  sendInfoFieldSubject: "Тема",
  sendInfoFieldMessage: "Билдирүү",
  sendInfoPhFullName: "Аты-жөнүңүздү жазыңыз",
  sendInfoPhEmail: "Электрондук почтаңызды жазыңыз",
  sendInfoPhPhone: "Телефон номериңизди жазыңыз",
  sendInfoPhUniversityInterest: "Кайсы университет кызыктырат?",
  sendInfoPhProgramInterest: "Кайсы программа кызыктырат?",
  sendInfoPhGpa: "GPA жазыңыз",
  sendInfoPhGoals: "Максаттарыңыз жөнүндө айтып бериңиз...",
  sendInfoPhScholarship: "Кайсы стипендия кызыктырат?",
  sendInfoPhUniversityOpt: "Тиешелүү университет (болсо)",
  sendInfoPhAchievements: "Жетишкендиктериңизди жазыңыз...",
  sendInfoPhUniversityRequired: "Кайсы университет?",
  sendInfoPhProgramRequired: "Кайсы программа?",
  sendInfoPhHelp: "Кандай жардам керек, жазыңыз...",
  sendInfoPhSubject: "Сурооңуз эмне жөнүндө?",
  sendInfoPhContact: "Кантип жардам бере алабыз?",
  sendInfoPhNotes: "Кошумча маалымат...",
  sendInfoMeetingSelect: "Жолугушуу түрүн тандаңыз",
  sendInfoMeetingConsult: "Жалпы консультация",
  sendInfoMeetingAppReview: "Арызды текшерүү",
  sendInfoMeetingScholarship: "Стипендия консультациясы",
  sendInfoMeetingCareer: "Карьералык кеңеш",
  sendInfoSubmit: "Жөнөтүү жана Premium алуу",
  sendInfoSubmitting: "Жөнөтүлүүдө...",
  sendInfoError: "Сурамыңызды жөнөтүү мүмкүн болбоду. Байланышты текшерип, кайра аракет кылыңыз.",
  sendInfoSuccessTitle: "Маалымат ийгиликтүү жөнөтүлдү!",
  sendInfoSuccessBody:
    "Кайрылууңуз үчүн рахмат. Командабыз маалыматты карап чыгат жана сиз менен жакын арада байланышат.",
  sendInfoPremiumActivated: "Premium-кирүү жигердүү!",
  sendInfoPremiumActivatedBody: "Сизде 7 күн Premium функцияларга кирүү бар.",
  sendInfoBackToDashboard: "Башкаруу панелине кайтуу",
  sendInfoTitleBack: "Башкаруу панелине кайтуу",
  smartMatch: "Акылдуу тандоо",
  aboutCoreAccess: "Негизги кирүү камтылган",
  aboutGlobal: "Глобалдуу",
  contactLabelEmail: "Электрондук почта",
  contactLabelTopic: "Тема",

  // Login page
  loginSubtitle: "Кош келиңиз! Аккаунтуңузга кириңиз.",
  loginEmailLabel: "Электрондук почта",
  loginEmailPlaceholder: "Электрондук почтаңызды жазыңыз",
  loginPasswordLabel: "Сырсөз",
  loginPasswordPlaceholder: "Сырсөзүңүздү жазыңыз",
  loginSubmit: "Кирүү",
  loginSubmitting: "Кирүүдө...",
  loginNoAccount: "Аккаунтуңуз жокпу?",
  loginSignUpHere: "Бул жерден катталыңыз",
  loginContinueAsGuest: "Конок катары улантуу",
  loginGuestSuffix: "— киризден, тиркемени көрүү.",
  loginFailedMessage: "Кирүү ийгиликсиз. Электрондук почта жана сырсөзүңүздү текшериңиз.",

  // Register page
  registerSubtitle: "Аккаунт түзүңүз — өлкөңүздү тандаңыз.",
  registerFirstName: "Атыңыз",
  registerLastName: "Фамилияңыз",
  registerEmail: "Электрондук почта",
  registerEmailPlaceholder: "you@example.com",
  registerPassword: "Сырсөз",
  registerCountry: "Өлкө",
  registerCountriesLoading: "Өлкөлөр жүктөлүүдө...",
  registerSelectCountry: "Өлкөңүздү тандаңыз",
  registerCountryHint: "Аккаунт түзүү үчүн милдеттүү.",
  registerNoCountriesHint:
    "Өлкөлөр жүктөлгөн жок. Backend серверди иштетип, базада өлкөлөр бар экенин текшериңиз, же ылдыйда «Конок катары улантуу» баскычын колдонуңуз.",
  registerSubmit: "Аккаунт түзүү",
  registerSubmitting: "Аккаунт түзүлүүдө...",
  registerHaveAccount: "Аккаунтуңуз барбы?",
  registerLogIn: "Кирүү",
  registerGuestSuffix: "— катталбай тиркемени көрүү.",
  registerSelectCountryError: "Өлкөнү тандаңыз.",
  registerFillAllError: "Бардык талааларды толтуруңуз.",
  registerFailedError: "Каттоо ийгиликсиз.",

  // PublicHome
  publicSeeHowItWorks: "YouTube'та кантип иштээрин көрүү",
  publicAboutUs: "Биз жөнүндө",
  publicSupportQr: "Колдоо QR",
  publicFaq: "Көп берилүүчү суроолор",
  publicContactUs: "Биз менен байланышуу",
  publicSendMessage: "Бизге билдирүү жөнөтүңүз",
  publicMessageSent: "Рахмат! Билдирүүңүз жөнөтүлдү.",
  publicFullName: "Аты-жөнү",
  publicFullNamePh: "Аты-жөнүңүздү жазыңыз",
  publicTopicPh: "Кандай жардам керек?",
  publicMessageLabel: "Билдирүү",
  publicMessagePh: "Билдирүүңүздү жазыңыз",
  publicFooterPrivacy: "Купуялык",
  publicFooterTerms: "Шарттар",
  publicFooterContact: "Байланыш",
  publicStudentSupport: "Студенттерге колдоо",
  publicUnisWorldwide: "Дүйнө жүзүндөгү университеттер",
  publicSupportNumber: "Колдоо номери",
  publicQrPlaceholder: "Бул жерге колдоо QR-сүрөтүн кошуңуз",
  publicAboutLead:
    "ilmi дүйнө жүзү боюнча студенттерге AI-тандоо аркылуу туура университетти жана стипендияларды табууга жардам берет. Биздин миссия — жогорку билимди ар бирине жеткиликтүү кылуу.",
  publicAboutCopy:
    "Университеттерди жана стипендияларды издөөгө негизги кирүү камтылган, студенттер дароо колдоно ала турган куралдар менен.",
  publicMainServices: "Негизги кызматтар",

  searchUniNamePlaceholder: "Университет же колледж атын издөө…",
  searchUniClearAll: "Баарын тазалоо",
  searchUniTuitionRange: "Жылдык окуу акысы (€)",
  searchUniMatching: "Дал келген окуу жайлары",
  searchUniLoadingList: "Университеттер жүктөлүүдө...",

  uniDetailLoadingTitle: "Жүктөлүүдө...",
  uniDetailLoadingBody: "Университеттин маалыматы жүктөлүүдө...",
  uniDetailNotFound: "Окуу жайы табылган жок",

  // Search Universities options
  searchUniPopularUnder10k: "€10 миңге чейин / жыл",
  searchUniPopularUnder5k: "≤ €5 миң / жыл",
  searchUniPopularEnglish: "Англис тилинде",
  searchUniPopularEurope: "Европа",
  searchUniPopularBusiness: "Бизнес жана укук",
  searchUniPopularMedicine: "Медицина жана илим",
  searchUniPopularArts: "Искусство жана дизайн",
  searchUniInstAll: "Баары",
  searchUniInstUniversities: "Университеттер гана",
  searchUniInstColleges: "Колледждер гана",
  searchUniDegreeAll: "Бардык деңгээлдер",
  searchUniDegreeAssociate: "Ассоциат",
  searchUniDegreeDiploma: "Диплом",
  searchUniDegreeBachelor: "Бакалавр",
  searchUniDegreeMaster: "Магистр",
  searchUniDegreePhd: "PhD / Докторантура",
  searchUniLangAny: "Каалаган тил",
  searchUniLangEnglish: "Англис",
  searchUniLangGerman: "Немис",
  searchUniLangFrench: "Француз",
  searchUniLangSpanish: "Испан",
  searchUniLangDutch: "Голланд",
  searchUniLangCatalan: "Каталан",
  searchUniAllCountries: "Бардык өлкөлөр",
  searchUniAllFields: "Бардык багыттар",
  searchUniAllCities: "Бул өлкөдөгү бардык шаарлар",

  searchResultOne: "натыйжа",
  searchResultMany: "натыйжалар",
  searchUniNameLabel: "Окуу жайдын аталышы боюнча издөө",
  searchUniPopularHeading: "Популярдуу чыпкалар",
  searchUniInstTypeLabel: "Окуу жайдын түрү",
  searchUniCountryLabel: "Өлкө",
  searchUniCityLabel: "Шаар / аймак",
  searchUniFieldLabel: "Багыт",
  searchUniDegreeLabel: "Даражанын деңгээли",
  searchUniLanguageLabel: "Окуу тили",
  searchUniMin: "Мин",
  searchUniMax: "Макс",

  featureSmartMatchTitle: "Университеттерди акылдуу тандоо",
  featureSmartMatchDesc:
    "AI сиздин профилиңизди, максаттарыңызды жана талаптарыңызды талдап, ылайыктуу университеттерди сунуштайт.",
  featureScholarshipTitle: "Стипендиялар жана каржылоо",
  featureScholarshipDesc:
    "Билим алуу бюджетин пландаштыруу үчүн стипендияларды, гранттарды жана жардам программаларын табыңыз.",
  featureInsightsTitle: "Тапшыруу боюнча аналитика",
  featureInsightsDesc:
    "Тапшыруу тренддерин, программа деталдарын жана натыйжаларды салыштырып, негиздүү тандоо жасаңыз.",
  featureGlobalTitle: "Дүйнө жүзүндөгү университеттерге кирүү",
  featureGlobalDesc:
    "Бир нече өлкөдөгү университеттерди ачык программа жана тапшыруу маалыматтары менен изилдеңиз.",
  featureAnyDeviceTitle: "Каалаган түзмөктөн ыңгайлуу кирүү",
  featureAnyDeviceDesc:
    "ilmi'ди мобилдүү же компьютерден колдонуп, дал келгендерди жана кадамдарыңызды көзөмөлдөңүз.",
  featureAdvisorTitle: "Кеңешчинин колдоосу",
  featureAdvisorDesc:
    "Тапшыруу, арыз жана пландоо боюнча кеңешчилерден практикалык жардам алыңыз.",

  programsAllCategories: "Бардык категориялар",
  programsAllCountries: "Бардык өлкөлөр",
  programsTuitionFree: "Акысыз / мамлекеттик",
  searchUniLangItalian: "Италиян",
  searchUniLangJapanese: "Жапон",
  searchUniLangKorean: "Корей",

  chartUnis: "Университеттер",
  chartScholarshipsLabel: "Стипендиялар",
  monthJan: "Янв",
  monthFeb: "Фев",
  monthMar: "Мар",
  monthApr: "Апр",
  monthMay: "Май",
  monthJun: "Июн",

  heroTitleLine2: "Окуу жолуңузга жетектөө",
  heroDescription2:
    "Бир жөнөкөй платформада университеттер, стипендиялар, тапшыруу жана магистр программалары боюнча так нускама.",
  heroCtaPrimary: "Баштоо",
  heroCtaSecondary: "Кантип иштейт",

  faqQ1: "ilmi колдонуу акылуубу?",
  faqA1:
    "Негизги мүмкүнчүлүктөр — университеттерди тандоо, стипендияларды табуу жана негизги маалымат — акысыз. Премиум колдоо каалоо боюнча төлөнөт.",
  faqQ2: "Тандоо процесси кантип иштейт?",
  faqA2:
    "AI сиздин максаттарыңызды, профилиңизди жана талаптарыңызды талдап, ылайыктуу университеттер менен стипендиялардын тизмесин көрсөтөт.",
  faqQ3: "Кайсы өлкөлөр жана университеттер камтылган?",
  faqA3:
    "Биз көптөгөн өлкөлөрдөгү университеттерди жана стипендияларды камтыйбыз. Өлкө, программа жана каржылоо боюнча чыпкалай аласыз.",
  faqQ4: "ilmi'ди кантип колдой алам?",
  faqA4:
    "«Биз жөнүндө» бөлүмүндөгү садакалар аркылуу колдой аласыз. Сиздин колдооңуз бардык студенттер үчүн негизги кирүүнү сактоого жардам берет.",

  searchFieldDefaultPlaceholder: "Окуу жайларын издөө",
  selectFieldDefaultPlaceholder: "Тандаңыз",
  skyToggleToLight: "Жарык темага которуу",
  skyToggleToDark: "Караңгы темага которуу",

  errFailedLoadFavorites: "Сүйүктүүлөрдү жүктөө ишке ашкан жок.",
  errFailedRemoveFavorite: "Сүйүктүүлөрдөн алып салуу ишке ашкан жок.",
};

export default ky;
