// Kyrgyz (Кыргызча)
// Fully translated — every key has a native value. Base spread of en provides an
// English (not Russian) safety net for any key that might be added later.
import en from "./en";

const ky = {
  ...en,

home: "Башкы",
search: "Издөө",
dashboard: "Башкаруу панели",
profile: "Профиль",
settings: "Жөндөөлөр",
language: "Тил",
selectLanguage: "Тилди тандаңыз",
languageNote: "Тил жөндөөлөрү кийинки кирүүдө сакталат",
scholarships: "Стипендиялар",
heroBadge: "AI-тандоо",
heroTitle: "Сизге ылайык университетти табыңыз",
heroSubtitle: "Дүйнө жүзүндөгү университеттерди ачыңыз",
heroDescription: "Академиялык максаттарыңызга, бюджетиңизге жана каалооларыңызга дал келген дүйнө жүзүндөгү университеттерди табыңыз",
heroStudents: "Жардам берилген студенттер",
heroUniversities: "Университеттер",
heroSuccessRate: "Ийгилик көрсөткүчү",
heroCta: "Жолуңузду баштаңыз",
heroDemo: "Демону көрүү",
searchPlaceholder: "Университеттерди, программаларды же жайгашкан жерлерди издөө...",
searchTitle: "Кыял университетиңизди табыңыз",
searchSubtitle: "Жайгашкан жер, программа, бюджет жана башкалар боюнча чыпкалаңыз",
searchFilters: "Чыпкалар",
searchResults: "Натыйжалар",
searchLocation: "Жайгашкан жер",
searchProgram: "Программа",
searchBudget: "Бюджет",
searchRanking: "Рейтинг",
dashboardTitle: "Сиздин панель",
dashboardWelcome: "Кош келиңиз!",
dashboardRecentSearches: "Акыркы издөөлөр",
dashboardSavedUniversities: "Сакталган университеттер",
dashboardApplications: "Арыздар",
dashboardScholarships: "Стипендиялар",
universityTuition: "Окуу акысы",
universityAcceptanceRate: "Кабыл алуу пайызы",
universityPrograms: "Программалар",
universityLearnMore: "Көбүрөөк билүү",
universityApplyNow: "Азыр тапшыруу",
scholarshipTitle: "Мыкты стипендиялар",
scholarshipSubtitle: "Билиминизди каржылоо мүмкүнчүлүктөрүн табыңыз",
scholarshipMerit: "Жетишкендик боюнча",
scholarshipNeed: "Муктаждык боюнча",
scholarshipAthletic: "Спорттук",
scholarshipAcademic: "Академиялык",
featuredTitle: "Сунушталган университеттер",
featuredSubtitle: "Дүйнө жүзүнөн жогору бааланган окуу жайлары",
save: "Сактоо",
cancel: "Жокко чыгаруу",
edit: "Өзгөртүү",
delete: "Жок кылуу",
apply: "Тапшыруу",
view: "Көрүү",
learnMore: "Көбүрөөк билүү",
uniTypeUniversity: "Университет",
uniTypeCollege: "Колледж",
notFoundTitle: "Барак табылган жок",
notFoundMessage: "Сиз издеген барак жок же жылдырылган.",
notFoundBackDashboard: "Панелге кайтуу",
notFoundBackHome: "Башкы бетке кайтуу",
errorBoundaryTitle: "Бир нерсе туура эмес болду",
errorBoundaryMessage: "Күтүлбөгөн ката баракты үзүп койду. Жаңылоо адатта жардам берет.",
errorBoundaryReload: "ilmi жаңылоо",
sessionExpiredMessage: "Сессияңыздын мөөнөтү бүттү. Кайра кириңиз.",
serverUnreachableMessage: "Серверге жетүү мүмкүн эмес. Байланышыңызды текшерип, кайра аракет кылыңыз.",
serverErrorMessage: "Биздин тарапта бир нерсе туура эмес болду. Кайра аракет кылыңыз.",
errorGeneric: "Бир нерсе туура эмес болду. Кайра аракет кылыңыз.",
viewAll: "Баарын көрүү",
success: "Ийгилик",
error: "Ката",
loading: "Жүктөлүүдө...",
noResults: "Эч натыйжа табылган жок",
deadline: "Мөөнөт",
type: "Түрү",
meritBased: "Жетишкендик боюнча",
needBased: "Муктаждык боюнча",
projectBased: "Долбоор боюнча",
notifications: "Билдирүүлөр",
close: "Жабуу",
open: "Ачуу",
light: "Жарык",
dark: "Күңүрт",
switchToLight: "Жарык режимге которуу",
switchToDark: "Күңүрт режимге которуу",
email: "Электрондук почта",
password: "Сырсөз",
firstName: "Аты",
lastName: "Фамилиясы",
phone: "Телефон",
address: "Дарек",
city: "Шаар",
country: "Өлкө",
zipCode: "Почта индекси",
today: "Бүгүн",
yesterday: "Кечээ",
tomorrow: "Эртең",
thisWeek: "Бул жуманы",
thisMonth: "Бул айда",
thisYear: "Бул жылы",
thousand: "К",
million: "М",
billion: "Б",
lightMode: "Жарык режим",
darkMode: "Күңүрт режим",
toggleTheme: "Темани алмаштыруу",
favoriteSave: "Сүйүктүүлөргө кошуу",
favoriteSaved: "Сакталды",
favoriteUniversitiesTitle: "Сүйүктүү университеттер",
favoriteUniversitiesDescription: "Сакталган университеттериңиздин тизмеси. Каалаган убакта алып салсаңыз болот.",
favoriteUniversitiesEmpty: "Сизде азырынча сүйүктүү университеттер жок.",
searchNoResults: "Дал келген окуу жайлар табылган жок.",
searchFieldsTitle: "Багыт боюнча издөө",
searchFieldsPickField: "Окуу багытын тандаңыз",
searchFieldsClearAll: "Баарын тазалоо",
searchFieldsSelectedOne: "багыт тандалды",
searchFieldsSelectedMany: "багыт тандалды",
searchFieldsSelectPrompt: "Дал келген университеттерди көрүү үчүн жогорудан бир же бир нече багыт тандаңыз.",
searchFieldsDegreeLevel: "Даража деңгээли",
searchFieldsLanguage: "Окуу тили",
searchFieldsTuition: "Окуу акысы (€)",
searchFieldsResults: "Дал келген университеттер",
searchFieldsLoading: "Жүктөлүүдө…",
searchFieldsViewDetails: "Деталдарды көрүү",
searchFieldsAdditionalFilters: "Кошумча чыпкалар",
searchFieldsFiltersActive: "жигердүү",
searchFieldsRemember: "Тандоолоримди сактоо",
searchFieldsCompact: "Кыскача көрүнүш",
searchFieldsFull: "Толук көрүнүш",
searchFieldsResultOne: "натыйжа",
searchFieldsResultMany: "натыйжалар",
filterAllLevels: "Бардык деңгээлдер",
filterBachelor: "Бакалавр",
filterMaster: "Магистр",
filterPhd: "PhD / Докторантура",
filterAnyLanguage: "Каалаган тил",
tuitionFree: "Акысыз / мамлекеттик",
tuitionPerYear: "/ жылына",
tuitionMin: "Мин",
tuitionMax: "Макс",
programResultOne: "программа",
programResultMany: "программалар",
favResultOne: "натыйжа",
favResultMany: "натыйжалар",
uniDetailCampusAlt: "кампус",
uniDetailLogoAlt: "логотип",
fundingPerYear: "/жыл",
dashLogoHome: "ilmi башкы бет",
fundingSourceAria: "Каржылоо булагынын аталышы",
fundingAmountAria: "Каржылоо суммасы",
fieldDetailBack: "Багыттарга кайтуу",
fieldDetailUniSingular: "университет бул багытты сунуштайт",
fieldDetailUniPlural: "университет бул багытты сунуштайт",
uniDetailPrograms: "Бул университеттеги программалар",
fieldUniNotFound: "Университет табылган жок",
fieldUniBackToFields: "Багыт издөөгө кайтуу",
fieldUniBackToResults: "Натыйжаларга кайтуу",
fieldUniSelectedFields: "Бул университеттеги тандалган багыттар",
fieldUniNoMatchingFields: "Бул университет үчүн дал келген багыттар табылган жок.",
fieldUniDegrees: "Даражалар",
fieldUniLanguages: "Тилдер",
fieldUniViewFull: "Университеттин толук профилин көрүү",
searchProgramsTitle: "Программаларды издөө",
searchProgramsPlaceholder: "Программаларды аты боюнча издөө…",
searchProgramsFilters: "Чыпкалар",
searchProgramsCategory: "Категория",
searchProgramsCountry: "Өлкө",
searchProgramsResults: "Программалар",
programDetailTitle: "Программа жөнүндө",
programDetailNotFound: "Программа табылган жок.",
programDetailBack: "Программаларга кайтуу",
programDetailUniversity: "Университет",
programDetailLocation: "Жайгашуу жери",
programDetailDegree: "Даража",
programDetailLanguage: "Тил",
programDetailDuration: "Узактыгы",
programDetailTuition: "Окуу акысы",
programDetailDescription: "Сүрөттөмө",
programDetailWebsite: "Сайтка өтүү",
favoriteProgramsTitle: "Сүйүктүү программалар",
favoriteProgramsEmpty: "Азырынча сүйүктүү программаларыңыз жок.",
favoriteProgramsRemove: "Алып салуу",
navFeatures: "Мүмкүнчүлүктөр",
navAbout: "Биз жөнүндө",
navFaq: "Суроолор",
navContact: "Байланыш",
navLogin: "Кирүү",
navGetStarted: "Баштоо",
comingSoon: "Жакында",
getStarted: "Баштоо",
startNow: "Азыр баштоо",
keyFeatures: "Негизги мүмкүнчүлүктөр",
howItWorks: "Кантип иштейт",
popularTopics: "Популярдуу темалар",
essayReviewsTitle: "Эссе текшерүү",
essayReviewsDesc: "Арыз эссеңизге профессионал пикир алыңыз",
essayReviewsIntro: "Эссеңизди экспертке текшертүүгө жөнөтүңүз. Командабыз структура, мазмун, грамматика жана ынандыруучулук боюнча кеңири пикир берет.",
essayReviewsAiFeedback: "AI-анализ",
essayReviewsAiFeedbackDesc: "Тон, ачыктык жана таасирин дароо талдоо",
essayReviewsStructure: "Структура анализи",
essayReviewsStructureDesc: "Абзацтардын агымы жана логикалык далилдөө",
essayReviewsGrammar: "Грамматика жана стиль",
essayReviewsGrammarDesc: "Грамматика, пунктуация жана стилди текшерүү",
essayReviewsTone: "Тон жана үн",
essayReviewsToneDesc: "Өзүңүздүн чыныгы үнүңүз угулсун",
essayReviewsPersonalStatement: "Жеке арыз",
essayReviewsSupplemental: "Кошумча эссе",
essayReviewsDiversity: "Ар түрдүүлүк жөнүндө",
essayReviewsResearchPurpose: "Максат билдирүүсү",
essayReviewsSubmitEssay: "Эссени жөнөтүү",
essayReviewsTurnaround: "24-48 саат ичинде",
matchUnisTitle: "Университет тандоо",
matchUnisDesc: "Профилиңизге негизделген AI-университет тандоо",
matchUnisIntro: "AI сиздин академиялык профилиңизди, каалоолоруңузду жана максаттарыңызды талдап, эң ылайыктуу университеттерди табат. Так дал келүүлөр үчүн профилиңизди толтуруңуз.",
matchUnisProfileAnalysis: "Профиль анализи",
matchUnisProfileAnalysisDesc: "Академиялык күчтөрүңүздү терең талдоо",
matchUnisCompatibility: "Шайкештик баллы",
matchUnisCompatibilityDesc: "Бир нече фактор боюнча дал келүү пайызы",
matchUnisSmartFilter: "Акылдуу чыпкалоо",
matchUnisSmartFilterDesc: "Чыпкалар каалоолоруңузга жараша ыңгайлашат",
matchUnisRealtime: "Нака убакыттагы жаңыртуулар",
matchUnisRealtimeDesc: "Жаңы маалымат келсе, дал келүүлөр жаңырат",
matchUnisProfileComplete: "Профилди толтуруу",
matchUnisCompleteProfile: "Жакшыраак натыйжа үчүн профилиңизди толтуруңуз",
matchScholarshipsTitle: "Стипендия тандоо",
matchScholarshipsDesc: "Профилиңизге ылайыктуу стипендияларды табыңыз",
matchScholarshipsIntro: "Академиялык жетишкендиктериңизге, жарандыгыңызга, окуу багытыңызга жана каржылык абалыңызга негизделген стипендияларды ачыңыз.",
matchScholarshipsEligibility: "Шарттарды текшерүү",
matchScholarshipsEligibilityDesc: "Стипендия критерийлерине автоматтык текшерүү",
matchScholarshipsDeadlines: "Мөөнөттөрдү көзөмөлдөө",
matchScholarshipsDeadlinesDesc: "Арыз берүү мөөнөттөрүн өткөрүп жибербеңиз",
matchScholarshipsGuidance: "Арыз берүүгө жардам",
matchScholarshipsGuidanceDesc: "Ар бир арыз үчүн кадам-кадам жардам",
matchScholarshipsCalculator: "Каржылык калькулятор",
matchScholarshipsCalculatorDesc: "Жалпы каржылоо потенциалыңызды баалаңыз",
matchScholarshipsMerit: "Жетишкендикке негизделген",
matchScholarshipsNeed: "Муктаждыкка негизделген",
matchScholarshipsCountry: "Өлкөгө жараша",
matchScholarshipsField: "Багытка жараша",
similarStudentsTitle: "Окшош студенттер",
similarStudentsDesc: "Окшош максаттары бар студенттер менен байланышыңыз",
similarStudentsIntro: "Окшош академиялык фон, максаттуу университеттер жана карьера максаттары бар студенттерди табыңыз. Тажрыйба бөлүшүп, бири-бириңизден үйрөнүңүз.",
similarStudentsMatching: "Профиль дал келтирүү",
similarStudentsMatchingDesc: "Окшош максаттары жана фону бар студенттерди табыңыз",
similarStudentsGroups: "Окуу топтору",
similarStudentsGroupsDesc: "Тема боюнча окуу топторуна кошулуңуз же түзүңүз",
similarStudentsExperience: "Тажрыйба бөлүшүү",
similarStudentsExperienceDesc: "Арыз тажрыйбаларын окуп, бөлүшүңүз",
similarStudentsNetwork: "Тармак куруу",
similarStudentsNetworkDesc: "Окшош университеттерге тапшырган курдаштар менен байланышыңыз",
alumniMentorsTitle: "Түлөк менторлор",
alumniMentorsDesc: "Ийгиликтүү түлөктөрдөн кеңеш алыңыз",
alumniMentorsIntro: "Чет өлкөдө окуган жана чыныгы тажрыйба, арыз кеңештери, маданий нускама жана карьера боюнча маалымат бере турган түлөктөр менен байланышыңыз.",
alumniMentorsCareer: "Карьера жетекчилиги",
alumniMentorsCareerDesc: "Бүтүрүүдөн кийинки карьера жолдору жөнүндө билиңиз",
alumniMentorsTips: "Арыз кеңештери",
alumniMentorsTipsDesc: "Ийгиликке жеткендерден кеңеш алыңыз",
alumniMentorsCulture: "Маданий түшүнүк",
alumniMentorsCultureDesc: "Жаңы өлкөдөгү жашоого даярдалыңыз",
alumniMentorsAccess: "Тармакка кирүү",
alumniMentorsAccessDesc: "Өсүп жаткан түлөктөр коомдоштугуна кошулуңуз",
connectFriendsTitle: "Достор табуу",
connectFriendsDesc: "Башка арыз берүүчүлөр менен тармак куруңуз",
connectFriendsIntro: "Чет өлкөдө окууга даярданган башка студенттер менен таанышыңыз. Кеңеш бөлүшүп, бөлмө жолдошторун табып, достук мамиле куруңуз.",
connectFriendsInterest: "Кызыгуу боюнча тандоо",
connectFriendsInterestDesc: "Жалпы хоббиси жана максаттары бар адамдар менен байланышыңыз",
connectFriendsStudy: "Окуу өнөктөштөрү",
connectFriendsStudyDesc: "Тест даярдыгы үчүн окуу өнөктөштөрүн табыңыз",
connectFriendsCampus: "Кампус байланыштары",
connectFriendsCampusDesc: "Бир эле университетке баратканdar менен таанышыңыз",
connectFriendsCultural: "Маданий алмашуу",
connectFriendsCulturalDesc: "Башка маданияттар жана фондор жөнүндө билиңиз",
mockInterviewsTitle: "Үйрөнчүк интервьюлар",
mockInterviewsDesc: "Университетке кабылуу интервьюсуна даярдыктар",
mockInterviewsIntro: "AI-даярдык сессиялары менен университет интервьюсуна даярдалыңыз. Жоопторуңузга нака убакыттагы пикир, дене тил кеңештери жана ишенимдүүлүк баллдарын алыңыз.",
mockInterviewsAi: "AI сурамжылоочу",
mockInterviewsAiDesc: "AI тарабынан түзүлгөн реалдуу суроолор менен машыгыңыз",
mockInterviewsFeedback: "Нака убакыттагы пикир",
mockInterviewsFeedbackDesc: "Жоопторуңузду дароо талдоо",
mockInterviewsBank: "Суроолор банки",
mockInterviewsBankDesc: "Университетке ылайыктуу суроолор жыйнагы",
mockInterviewsTrack: "Жетишкендикти көзөмөлдөө",
mockInterviewsTrackDesc: "Сессиялар арасындагы жакшырууну байкаңыз",
mockInterviewsGeneral: "Жалпы кабылуу",
mockInterviewsTechnical: "Техникалык интервью",
mockInterviewsScholarship: "Стипендия интервьюсу",
mockInterviewsPortfolio: "Портфолио карап чыгуу",
conciergeSupportTitle: "Жеке колдоо",
conciergeSupportDesc: "Жолуңуздагы Premium жеке жетекчилик",
conciergeSupportIntro: "Эксперт кеңешчилерибиздин атайын колдоосун алыңыз. Университет тандоодон визага чейин — чет өлкөдө окуунун ар бир кадамынан жетектейбиз.",
conciergeSupportPriority: "Артыкчылыктуу колдоо",
conciergeSupportPriorityDesc: "Кезекти өткөрүп, тезирээк жооп алыңыз",
conciergeSupportAdvisor: "Жеке кеңешчи",
conciergeSupportAdvisorDesc: "Сиздин ишиңизге дайындалган жеке кеңешчи",
conciergeSupportDocReview: "Документтерди текшерүү",
conciergeSupportDocReviewDesc: "Бардык арыз документтерин эксперт карап чыгат",
conciergeSupportTracking: "Арыздарды көзөмөлдөө",
conciergeSupportTrackingDesc: "Арыздардын абалы жөнүндө нака убакытта жаңыртуулар",
englishTitle: "Англис тилине даярдыктар",
englishDesc: "IELTS, TOEFL жана академиялык англис тилине даярдыктар",
englishIntro: "Университетке кабылуу үчүн англис тилиңизди жакшыртыңыз. IELTS, TOEFL жана академиялык контексттерде окуу, жазуу, угуу жана сүйлөшүү боюнча машыгыңыз.",
englishIelts: "IELTS Даярдыгы",
englishIeltsDesc: "Толук машыгуу тесттер жана стратегия жетекчилиги",
englishToefl: "TOEFL Даярдыгы",
englishToeflDesc: "Бөлүм боюнча машыгуу жана кеңештер",
englishAcademic: "Академиялык англис",
englishAcademicDesc: "Жазуу, окуу жана презентация жөндөмдөрү",
englishSpeaking: "Сүйлөшүү машыгуу",
englishSpeakingDesc: "AI-менен сүйлөшүү жаттыгуулары",
englishReading: "Окуу",
englishWriting: "Жазуу",
englishListening: "Угуу",
englishSpeakingSkill: "Сүйлөшүү",
mathTitle: "Математикага даярдыктар",
mathDesc: "SAT, GRE жана университет математикасына даярдыктар",
mathIntro: "Стандарттуу тесттер жана университет деңгээлиндеги курстар үчүн жетектелген машыгуу менен математикалык жөндөмдөрүңүздү чыңдаңыз. Алгебра, анализ, статистика жана маселе чечүү стратегиялары камтылган.",
mathSat: "SAT / ACT Математика",
mathSatDesc: "Машыгуу маселелери жана тест стратегиялары",
mathAdvanced: "Жогорку деңгээлдеги темалар",
mathAdvancedDesc: "Анализ, сызыктуу алгебра жана башка",
mathPractice: "Машыгуу маселелери",
mathPracticeDesc: "Кадам-кадам чечим менен миңдеген маселе",
mathProgress: "Жетишкендикти көзөмөлдөө",
mathProgressDesc: "Бардык темалар боюнча өздөштүрүүнү байкаңыз",
mathAlgebra: "Алгебра",
mathCalculus: "Математикалык анализ",
mathStatistics: "Статистика",
mathGeometry: "Геометрия",
aiLiteracyTitle: "AI Сабаттуулугу",
aiLiteracyDesc: "AI куралдарын академияда натыйжалуу колдонууну үйрөнүңүз",
aiLiteracyIntro: "AI негиздерин, промпт инженерияны жана академиялык жана кесиптик контексттерде этикалык AI колдонууну изилдеңиз. Заманбап студент үчүн зарыл жөндөмдөр.",
aiLiteracyFundamentals: "AI Негиздери",
aiLiteracyFundamentalsDesc: "Жасалма интеллекттин негизги түшүнүктөрү",
aiLiteracyPrompt: "Промпт Инженерия",
aiLiteracyPromptDesc: "AI куралдарына натыйжалуу суроо жазыңыз",
aiLiteracyData: "Маалымат Сабаттуулугу",
aiLiteracyDataDesc: "Маалыматты түшүнүп, натыйжалуу иштеңиз",
aiLiteracyEthics: "Этикалык AI",
aiLiteracyEthicsDesc: "Академияда AI-ны жооптуу колдонуу",
getCoursesTitle: "Курстарды карап чыгуу",
getCoursesDesc: "Тест даярдыгы жана жөндөмдөр үчүн курстар каталогу",
getCoursesIntro: "Университетке тапшырууда жана академияда ийгиликке жетишүүгө жардам берген өз темпте курстарды ачыңыз. Тест даярдыгынан жумшак жөндөмдөргө чейин — сизге ылайыктуу курсту табыңыз.",
getCoursesVideo: "Видео Лекциялар",
getCoursesVideoDesc: "Эксперт мугалимдерден өз темпиңизде үйрөнүңүз",
getCoursesInteractive: "Интерактивдүү Жаттыгуулар",
getCoursesInteractiveDesc: "Практикалык иш-аракеттер менен машыгыңыз",
getCoursesCertificate: "Сертификаттар",
getCoursesCertificateDesc: "Профилиңизди күчөтүүчү сертификаттарды алыңыз",
getCoursesSelfPaced: "Өз темпиңизде",
getCoursesSelfPacedDesc: "Өз графигиңизге ылайык окуңуз",
getCoursesTestPrep: "Тест Даярдыгы",
getCoursesLanguage: "Тил Курстары",
getCoursesSkills: "Жумшак Жөндөмдөр",
getCoursesAcademic: "Академиялык Жазуу",
essayWritingTitle: "Эссе Жазуу",
essayWritingDesc: "Чыкма арыздарды жазууну үйрөнүңүз",
essayWritingIntro: "Шаблондор, AI сунуштары жана университетке ылайыкталган нускамалар аркылуу эссе жазуу өнөрүн өздөштүрүңүз. Тажрыйбаңызды күчтүү окуяга айлантыңыз.",
essayWritingTemplates: "Эссе шаблондору",
essayWritingTemplatesDesc: "Ар түрдүү эссе үчүн далилденген структуралар",
essayWritingAi: "AI сунуштары",
essayWritingAiDesc: "Жазууңузду жакшыртуу үчүн акылдуу сунуштар",
essayWritingPeer: "Тең кесиптештердин текшерүүсү",
essayWritingPeerDesc: "Башка талапкерлерден пикир алыңыз",
essayWritingUniTips: "Университетке ылайыкталган кеңештер",
essayWritingUniTipsDesc: "Ар бир университеттин суроолоруна ылайыкталган кеңеш",
contactPremiumTitle: "Байланыш",
contactPremiumDesc: "Команда менен байланышуу",
contactPremiumKicker: "Premium жетекчилик",
contactPremiumLeftLabel: "Premium колдоо жана жолугушуу",
contactPremiumIntro: "Суроолоруңуз барбы же жардам керекпи? Командабыз арыздар, документтер жана жол картасы боюнча жардам берет — маанилүү учурда артыкчылыктуу жооп берип.",
contactBookMeeting: "Жолугушуу белгилөө",
contactBookMeetingHint: "Темасы толтурулган почта ачылат; убактыны биз ырастайбыз.",
contactBookMeetingEmailSubject: "Жолугушуу суранычы — Ilmi",
contactAsideLabel: "Коомдоштук жана байланыш маалыматтары",
contactTelegramTitle: "Telegram каналы",
contactTelegramDesc: "Жаңылыктарга, эстеткичтерге жана башка талапкерлер менен аңгемеге кошулуңуз.",
contactOpenTelegram: "Telegram'да ачуу",
contactReachUsTitle: "Түз байланыш",
contactEmailLabel: "Электрондук почта",
contactTelegramLabel: "Коомдоштук",
contactTelegramChannelShort: "Ilmi'нин расмий каналы",
contactReachUsFootnote: "Расмий суранычтар же документтер үчүн электрондук почта ыңгайлуу. Telegram тез суроолор жана жарыялар үчүн ылайыктуу.",
contactPremiumPriority: "Артыкчылыктуу жооп",
contactPremiumPriorityDesc: "Командабыздан тез жооп алыңыз",
contactPremiumVideo: "Видео консультациялар",
contactPremiumVideoDesc: "Жүздөн-жүз видео чалуу белгилеңиз",
contactPremiumDoc: "Документ жардамы",
contactPremiumDocDesc: "Документтер жана арыздар боюнча жардам",
contactPremiumTeam: "Эксперт команда",
contactPremiumTeamDesc: "Тажрыйбалуу билим кеңешчилеринин колдоосу",
contactPremiumEmail: "Почта колдоосу",
contactPremiumEmailDesc: "Бизге билдирүү жөнөтүңүз — 24 саат ичинде жооп алыңыз",
contactPremiumChat: "Түз чат",
contactPremiumChatDesc: "Жумуш убактысында командабыз менен нака убакытта сүйлөшүңүз",
contactPremiumCall: "Чалуу белгилөө",
contactPremiumCallDesc: "Билим кеңешчиси менен жеке чалуу белгилеңиз",
contactPremiumContactUs: "Биз менен байланышуу",
contactPremiumChannels: "Байланыш каналдары",
dreamUniTitle: "Кыял университети",
dreamUniDesc: "Кыял университетиңизге жетүү жолун пландаштырып, көзөмөлдөңүз",
dreamUniIntro: "Максаттуу университеттериңизди белгилеңиз, арыз мөөнөттөрүн байкаңыз жана ийгилигиңизди көзөмөлдөңүз. Максатыңызга жетүү үчүн иретке салынган жана диккатта болуңуз.",
dreamUniGoals: "Максат көзөмөлдөө",
dreamUniGoalsDesc: "Арыздын этаптарын белгилеп, аткарыңыз",
dreamUniDeadlines: "Мөөнөт эстеткичтери",
dreamUniDeadlinesDesc: "Маанилүү арыз мөөнөтүн эч качан өткөрүп жибербеңиз",
dreamUniTimeline: "Ийгилик хронологиясы",
dreamUniTimelineDesc: "Баштан кабылдоого чейинки жолду визуалдаштырыңыз",
dreamUniChecklist: "Арыз текшерме тизмеси",
dreamUniChecklistDesc: "Ар бир документти жана талапты көзөмөлдөңүз",
searchScholarshipsTitle: "Стипендиялар издөө",
searchScholarshipsDesc: "Дүйнө жүзүндөгү стипендиялар жана каржылоо мүмкүнчүлүктөрүн табыңыз",
searchScholarshipsIntro: "Борбордук Азия студенттери үчүн миңдеген стипендияларды изилдеңиз. Өлкө, тармак, сумма жана мөөнөт боюнча чыпкалап, эң ылайыктуу каржылоону табыңыз.",
searchScholarshipsType: "Түрү боюнча",
searchScholarshipsTypeDesc: "Жетишкендик, керектөө, өлкөгө байланыштуу жана башкалар",
searchScholarshipsCountry: "Өлкө боюнча",
searchScholarshipsCountryDesc: "Стипендияларды барган өлкө боюнча чыпкалаңыз",
searchScholarshipsDeadline: "Мөөнөт календары",
searchScholarshipsDeadlineDesc: "Стипендия мөөнөттөрүн көзөмөлдөңүз",
searchScholarshipsEligibility: "Шарттарга дал келүү",
searchScholarshipsEligibilityDesc: "Шарттарга дал келесизби — тез текшерүү",
profileTitle: "Менин профилим",
profileDesc: "Аккаунт жөндөөлөрүн башкаруу",
profileChangePhoto: "Сүрөттү өзгөртүү",
profileFullName: "Толук аты-жөнү",
profileFirstName: "Аты",
profileLastName: "Фамилиясы",
profileEmail: "Электрондук почта",
profilePhone: "Телефон",
profileLocation: "Жайгашкан жери",
profileCertifications: "Сертификаттар жана квалификациялар",
profileCertificationsHint: "Ар бири жаңы саптан (дипломдор, тил тесттери, программа талаптарына тиешелүү экзамен балдары).",
profileShareTitle: "Профиль шилтемеси",
profileShareDesc: "Профилиңизди ушул түзмөктө ачуу үчүн шилтемени бөлүшүңүз же кодду сканерлеңиз.",
profileCopyLink: "Шилтемени көчүрүү",
profileLinkCopied: "Шилтеме көчүрүлдү",
profileLoadError: "Профилди жүктөө мүмкүн болбоду. Кирип тургандыгыңызды жана сервердин иштеп жатканын текшериңиз.",
profileSaveError: "Өзгөртүүлөрдү сактоо мүмкүн болбоду.",
profileSaveSuccess: "Профиль сакталды.",
profileGuestHint: "Профилиңизди, сертификаттарыңызды жана бөлүшүү шилтемесин жүктөп жана сактоо үчүн кириңиз.",
profileSaving: "Сакталууда…",
profileApplications: "Арыздар",
profileScholarships: "Стипендиялар",
profileViews: "Профиль көрүүлөр",
profilePremium: "Premium мүчө",
profilePremiumDesc: "Бардык premium мүмкүнчүлүктөргө кирүүңүз бар",
profilePremiumMatch: "Чексиз университет тандоо",
profilePremiumSupport: "Арыз боюнча артыкчылыктуу колдоо",
profilePremiumAlerts: "Эксклюзивдүү стипендия эскертмелери",
profilePremiumMentor: "Ментор менен түз байланыш",
profileSave: "Өзгөртүүлөрдү сактоо",
profileLogout: "Чыгуу",
dashMain: "НЕГИЗГИ",
dashDreamUniversity: "Кыял университети",
dashDreamPeakLabel: "UCA трек",
dashDreamCardTagline: "Негизги максат — документтер, балдар жана мөөнөттөр ушул максатка дал келсин.",
dashDreamPillFit: "92% профилиңизге дал келет",
dashDreamPillDeadline: "Кийинки: UCA арызы · 6-окт",
dashDreamPillDocs: "Иш тизмеси · 4 ачык",
dashDreamReadinessLabel: "Бул максатка даярдык",
dashSearchUniversities: "Университеттер",
dashFavoriteUniversities: "Сүйүктүү университеттер",
dashSearchFields: "Багыттар",
dashSearchPrograms: "Программалар",
dashFavoritePrograms: "Сүйүктүү программалар",
dashSearchScholarships: "Стипендиялар",
dashAiMatching: "AI жана акылдуу тандоо",
dashMatchUniversities: "Университет тандоо",
dashMatchScholarships: "Стипендия тандоо",
dashEssayReview: "Эссе текшерүү",
dashSimilarStudents: "Окшош студенттер",
dashCommunity: "Коомдоштук",
dashOthers: "Башка",
dashConnections: "Байланыштар",
dashConnectFriends: "Достор",
dashAlumniMentors: "Бүтүрүүчү менторлор",
dashPremiumServices: "Premium кызматтар",
dashEssayReviews: "Эссе текшерүүлөр",
dashMockInterviews: "Машыктыруу интервьюлар",
dashConciergeSupport: "Консьерж колдоо",
dashLearning: "Окуу жана курстар",
dashGetCourses: "Курстарды алуу",
dashMath: "Математика",
dashEnglish: "Англис тили",
dashEssayWriting: "Эссе жазуу",
dashAiLiteracy: "AI сабаттуулугу",
dashDashboard: "Башкы бет",
dashTagline: "Сиздин университеттик жолуңуз ушул жерден башталат",
dashSendInfo: "Маалымат жөнөтүү жана Premium алуу",
dashJoinCommunity: "Биздин коомдоштукка кошулуу",
dashLogout: "Чыгуу",
dashNotifications: "Билдирүүлөр",
dashProfile: "Профиль",
dashWelcomeBackPrefix: "Кош келиңиз,",
dashDefaultDisplayName: "Аты-жөнү",
dashOpenPage: "Баракчаны ачуу",
dashCardDashboardDesc: "Башкы баракчаңызга кайтуу.",
dashCardDreamDesc: "Кыял университетиңиздин максаттарын жана ийгилигин кароо.",
dashCardUniversitiesDesc: "Университеттерди изилдеп, варианттарды салыштыруу.",
dashCardFavoriteUniversitiesDesc: "Сакталган университеттериңизди ачуу.",
dashCardFieldsDesc: "Кызыгууңузга дал келген окуу тармактарын карноо.",
dashCardProgramsDesc: "Мыкты университеттердин даражалык программаларын табуу.",
dashCardFavoriteProgramsDesc: "Сакталган программаларыңызды бир жерде көрүү.",
dashCardScholarshipsDesc: "Арыз бере турган стипендияларды табуу.",
dashCardMatchUniversitiesDesc: "AI аркылуу университет тандоону алуу.",
dashCardMatchScholarshipsDesc: "AI аркылуу стипендия тандоону алуу.",
dashCardSimilarStudentsDesc: "Окшош студент профилдеринен маалыматтарды көрүү.",
dashCardFriendsDesc: "Бир жолдо жүргөн достор менен байланышуу.",
dashCardMentorsDesc: "Жетекчилик үчүн бүтүрүүчү менторлорду табуу.",
dashCardProfileDesc: "Профиль жөндөөлөрүңүздү көрүп жаңыртуу.",
dashCardSendInfoDesc: "Маалыматтарыңызды жөнөтүп, premium колдоо суранычы.",
dashContactPremium: "Байланыш",
dashNavAiTools: "AI КУРАЛДАРЫ",
dashNavApply: "Арыздар",
dashMyAcademics: "Менин үлгөрүмүм",
dashMyApplications: "Менин арыздарым",
dashNavOpportunities: "Мүмкүнчүлүктөр",
dashJobs: "Жумуш жана стажировка",
dashCourses: "Курстар",
dashNavAdmin: "Администратор",
dashAdminReview: "Скрапинг текшерүүсү",
dashNavFriendsAndMentors: "ДОСТОР ЖАНА МЕНТОРЛОР",
dashNavSectionAiUniversities: "AI · Университеттер",
dashNavSectionAiScholarships: "AI · Стипендиялар",
dashNavSectionAiSimilarStudents: "AI · Окшош студенттер",
dashNavSectionConnectFriends: "Достор",
dashNavSectionAlumniMentors: "Бүтүрүүчү менторлор",
dashNavSectionContactPremium: "БАЙЛАНЫШ",
dashCardContactPremiumDesc: "Команда менен байланышуу, убакыт белгилөө же Telegram'га кошулуу.",
dashAiDashboardUniTitle: "AI · Эң ылайыктуу университеттер",
dashAiShowcaseSeeWholeList: "Толук тизмени көрүү",
dashCtaSeeAllUniversityMatches: "Бардык университет тандоолорун көрүү",
dashCtaSeeAllScholarshipMatches: "Бардык стипендия тандоолорун көрүү",
dashCtaSeeAllFriends: "Бардык достарды көрүү",
dashCtaBrowseAllMentors: "Бардык менторлорду карноо",
dashConnAsideFriendsLabel: "Алдын ала көрүнүштөгү достор",
dashFriendsCombinedSectionTitle: "Достор жана жаңы таанышуулар",
dashFriendsSimilarColumnTitle: "Байланыша турган адамдар",
dashFriendsSimilarSeeMore: "Дагы көрүү",
dashFriendsOnlineColumnTitle: "Досторуңуз",
dashFriendsOnlineNow: "Азыр желеде",
dashFriendsAllFriendsLabel: "Бардык достор",
dashFriendsSeeCountCta: "{{count}} дост көрүү",
dashFriendsOnlineEmpty: "Азыр желеде эч ким жок",
dashConnAsideMentorsLabel: "Алдын ала көрүнүштөгү менторлор",
dashSimilarStudentsAddFriend: "Дост катары кошуу",
dashAiShowcaseUniCtaHint: "Бардык тандоолор жана чыпкалар менен толук тандоо.",
dashAiShowcaseScholCtaHint: "Ар бир стипендияны жана шарттарды карноо.",
dashAiDashboardScholTitle: "AI · Эң ылайыктуу стипендиялар",
dashAiDashboardPeersTitle: "AI · Окшош студенттер",
dashAiUniMatchLead: "Профилиңизге, максаттарыңызга жана балдарыңызга жараша иреттелген университеттер.",
dashAiScholMatchLead: "Кийинки этапта алуу мүмкүнчүлүгүңүз жогору болгон стипендиялар.",
dashAiPeersMatchLead: "Максаттары окшош курдаштар — алардын тажрыйбасынан үйрөнүңүз.",
dashAiScholCardIntlTitle: "Global Merit Fund",
dashAiScholCardIntlMeta: "Эл аралык талапкерлер · Мөөнөт 15-апр",
dashSimilarStudent2Name: "Eldar M.",
dashSimilarStudent2Desc: "STEM трек, стипендия биринчи стратегия.",
dashSimilarStudent3Name: "Timur B.",
dashSimilarStudent3Desc: "Европага багытталган тизме, күчтүү англис тили балдары.",
dashSimilarTagField: "Бир тармак",
dashSimilarTagRegion: "Бир аймакка багыт",
dashSimilarTagScores: "Окшош балдар",
dashSimilarOverlapGpa: "Окшош GPA диапазону",
dashSimilarOverlapShortlist: "Шортлист тандоолору дал келет",
dashSimilarOverlapIntake: "Бир максаттуу кабыл алуу",
dashSimilarOverlapScholarFirst: "Стипендия биринчи стратегия",
dashSimilarOverlapEuTargets: "ЕС университеттери дал келет",
dashSimilarOverlapAidFocus: "Экөө тең керектөөгө негизделген жардамды карайт",
dashSimilarOverlapEuropeList: "Европага басым жасалган тизме",
dashSimilarOverlapIelts: "Окшош англис тили балдары",
dashSimilarOverlapStemExtra: "Окшош STEM активдүүлүктөр",
dashSimilaritiesLabel: "Профилиңиз менен окшоштуктар",
dashFriend2SampleName: "Erkeaiym D.",
dashFriend2SampleDesc: "Сүйүктүү тизме дал келет: Нидерланды жана Германия.",
dashFriend3SampleName: "Sultan K.",
dashFriend3SampleDesc: "Эссе алмашуу өнөктөшү · акыркы жолу кечээ жигердүү болгон.",
dashMentor2SampleName: "Laura N.",
dashMentor2SampleDesc: "MBA кабыл алуу, интервьюга даярдануу жана CV текшерүүлөр.",
dashMentorBadgeStem: "Инженерия",
dashMentorBadgeMba: "Бизнес жана MBA",
dashMentorVerified: "Текшерилген ментор",
dashAway: "Желеде жок",
dashConnectionFriendsTitle: "Байланыш · Достор",
dashConnectionFriendsLead: "Бир жолдо окуп жаткан же кабарлашкыңыз келген адамдар.",
dashConnectionMentorsTitle: "Байланыш · Бүтүрүүчү менторлор",
dashConnectionMentorsLead: "Арыздар жана интервью боюнча жардам берген бүтүрүүчүлөр.",
dashConnectionActionChat: "Чатты ачуу",
dashConnectionActionMentor: "Профилди көрүү",
dashConnectionPremiumTitle: "Premium колдоо",
dashConnectionPremiumLead: "Мөөнөттөр, эссе жана стратегия боюнча жеке жардам.",
dashConnectionPremiumPoint1: "ilmi командасынан артыкчылыктуу жооптор",
dashConnectionPremiumPoint2: "Так пикир менен эссе жана интервью текшерүүлөр",
dashConnectionPremiumPoint3: "Шортлист үчүн консьерж стилиндеги пландаштыруу",
dashContactSubheading: "Байланыш",
dashContactDetailsTitle: "Биз менен байланышуу",
dashContactCompactHint: "Төмөндө тез шилтемелер. Толук билдирүү жөнөткүңүз келсе, Байланыш баракчасын ачыңыз.",
dashContactFullPageCta: "Толук Байланыш баракчасын ачуу",
dashContactUsTitle: "Биз менен байланышуу",
dashContactPhoneLabel: "Телефон",
dashContactTelegramQrCaption: "Telegram каналыбызды ачуу үчүн сканерлеңиз же басыңыз.",
dashContactSocialListLabel: "Социалдык тармактар жана коомдоштук шилтемелери",
dashContactFormTitle: "Бизге билдирүү жөнөтүңүз",
dashContactFormName: "Толук аты-жөнү",
dashContactFormNamePh: "Толук аты-жөнүңүздү жазыңыз",
dashContactFormEmail: "Электрондук почта",
dashContactFormEmailPh: "you@example.com",
dashContactFormTopic: "Тема",
dashContactFormTopicPh: "Кандай жардам керек?",
dashContactFormMessage: "Билдирүү",
dashContactFormMessagePh: "Билдирүүңүздү ушул жерге жазыңыз — жардам бере алышыбыз үчүн жетиштүү маалымат кошуңуз.",
dashContactFormSubmit: "Билдирүү жөнөтүү",
dashContactFormThanks: "Рахмат! Билдирүүңүздү алдык, жакын арада жооп беребиз.",
dashContactFormAgain: "Дагы билдирүү жөнөтүү",
contactPlatformLinkedIn: "LinkedIn",
contactPlatformTelegram: "Telegram",
contactPlatformInstagram: "Instagram",
contactPlatformX: "X",
contactPlatformYouTube: "YouTube",
contactPlatformTikTok: "TikTok",
dashPerfectMatch: "Идеалдуу дал келүү",
dashUcaName: "Борбордук Азия Университети",
dashUcaLocation: "Нарын, Кыргызстан",
dashStartClimb: "Жолду баштоо",
dashPackList: "Иш тизмеси",
dashUpcomingDeadlines: "Жакындагы мөөнөттөр",
dashShowAll: "Баарын көрсөтүү",
dashUcaApplication: "UCA арызы",
dashAucaScholarship: "AUCA стипендиясы",
dashMitApplication: "MIT арызы",
dashOct6: "6 окт 2025",
dashOct8: "8 окт 2025",
dashDeadlineFarTitle: "Stanford SCEA · портфолио жана транскрипттер",
dashDeadlineFarDate: "15 янв 2027",
dashTimeAbout9mo: "~9 ай",
dashTime45m: "45 мүн калды",
dashTime2h15m: "2с 15м калды",
dashTime2d3h: "2к 3с калды",
dashViewsTitle: "Университет жана стипендия көрүүлөр",
dashViewsTotal: "Үлгү маалымат",
dashViewsDesc: "Канча университет жана стипендия карагандарыңызды көзөмөлдөңүз",
dashRecommendedUniversities: "Сунушталган университеттер",
dashPreviewSearchPlaceholder: "Аты же жери боюнча издөө…",
dashFilters: "Чыпкалар",
dashFilterAll: "Баары",
dashFilterEurope: "Европа",
dashFilterEnglishTaught: "Англис тилинде",
dashSearchPopularFilters: "Популярдуу чыпкалар",
dashSearchClearFilters: "Баарын тазалоо",
dashStartSearching: "Издөөнү баштоо",
dashSearchUniPlaceholder: "Университет же колледж аты боюнча издөө…",
dashUniPopUnder10k: "€10 миңге чейин / жыл",
dashUniPopUnder5k: "≤ €5 миң / жыл",
dashUniPopBusinessLaw: "Бизнес жана укук",
dashUniPopMedicine: "Медицина жана илимдер",
dashUniPopArts: "Искусство жана дизайн",
dashFieldTeaserCs: "Информатика жана IT",
dashFieldTeaserBusiness: "Бизнес жана менеджмент",
dashFieldTeaserMedicine: "Медицина жана саламаттык",
dashFieldTeaserEngineering: "Инженерия",
dashFieldTeaserArts: "Искусство жана дизайн",
dashScholarshipUrlHintMerit: "Башкаруу панелинен жетишкендик стипендияларын ачтыңыз.",
dashScholarshipUrlHintNeed: "Башкаруу панелинен муктаждыкка негизделген стипендияларды ачтыңыз.",
dashSearchTeaserSearchUniversities: "Университеттерди издөө",
dashSearchTeaserSearchFields: "Багыттарды издөө",
dashSearchTeaserSearchScholarships: "Стипендияларды издөө",
dashSearchFieldPlaceholder: "Багыт аты боюнча издөө…",
dashSearchScholarshipPlaceholder: "Стипендияларды издөө…",
dashPreviewMatches: "дал келүү",
dashPreviewNoResults: "Бул чыпка боюнча натыйжа жок.",
dashPreviewUniversitiesLead: "Издөө алдын ала көрүнүшү: солдогу чыпкалар оңдогу тизмени тарытат.",
dashPreviewProgramsLead: "Тез чыпкалар жана кыска тизме менен программа издөөнүн алдын ала көрүнүшү.",
dashPreviewScholarshipsLead: "Түр чыпкалары менен стипендия издөөнүн алдын ала көрүнүшү.",
dashProgramFilterMaster: "Магистратура",
dashProgramFilterBachelor: "Бакалавриат",
dashScholarshipFilterMerit: "Жетишкендик",
dashScholarshipFilterNeed: "Муктаждыкка негизделген",
dashProgramPreviewMsTitle: "M.Sc. Computer Science",
dashProgramPreviewMsMeta: "STEM · күзгү набор",
dashProgramPreviewBsTitle: "B.A. Эл аралык мамилелер",
dashProgramPreviewBsMeta: "Гуманитардык илимдер · Жыл бою",
dashProgramPreviewMbaTitle: "MBA",
dashProgramPreviewMbaMeta: "Бизнес · GMAT",
dashScholPreviewMeritTitle: "Жетишкендик сыйлыгы",
dashScholPreviewMeritMeta: "€5 000 чейин · Мөөнөт 1 март",
dashScholPreviewNeedTitle: "Каржылык муктаждык гранты",
dashScholPreviewNeedMeta: "Кирешеге жараша · Жыл бою",
dashApplicationStatus: "Арыз абалы",
dashStatusCardLead: "ilmi'де көзөмөлдөгөн бардык абалдар — сандар жана трубопроводдогу үлүшү.",
dashStatusDonutLabel: "Арыздар",
dashStatusTotal: "Жалпы 15",
dashStatusPlan: "Берүүнү пландоодо",
dashStatusApplied: "Берилди",
dashStatusAccepted: "Кабыл алынды",
dashStatusWaitlist: "Күтүү тизмеси",
dashStatusRejected: "Четке кагылды",
dashRank: "Рейтинг",
dashMatch: "Дал келүү",
dashUni1Name: "Массачусетс технологиялык институту",
dashUni1Loc: "Кембридж, МА, АКШ",
dashUni1Rank: "#1",
dashUni1Match: "95%",
dashUni2Name: "Stanford Университети",
dashUni2Loc: "Stanford, КА, АКШ",
dashUni2Rank: "#2",
dashUni2Match: "92%",
dashAiSampleUniversities: "Профиль жана максаттарга жараша эң ылайыктуулар.",
dashAiSampleScholarships: "Бюджет жана баллдарга ылайыктуу стипендиялар.",
dashAiSampleStudents: "Окшош жолдон өткөн жана натыйжаларга жеткен студенттер.",
dashFriendSampleName: "Aizada K.",
dashFriendSampleDesc: "Data Science программаларына арыз берүүдө.",
dashMentorSampleName: "Murat R.",
dashMentorSampleDesc: "Инженердик тапшыруу боюнча бүтүрүүчү ментор.",
dashOnline: "Онлайн",
appTimelineTitle: "Арыздар хронологиясы",
appTimelineDesc: "Арыз берүү мөөнөттөрүн жана прогрессти көзөмөлдөңүз",
appTimelineFeature1: "Мөөнөттөрдү көзөмөлдөө",
appTimelineFeature1Desc: "Акылдуу эскертүүлөр аркылуу арыз мөөнөттөрүн эч качан өткөрбөңүз",
appTimelineFeature2: "Прогрессти байкоо",
appTimelineFeature2Desc: "Бардык университеттердеги арыздардын абалын бир карашта көрүңүз",
appTimelineFeature3: "Этаптарды пландоо",
appTimelineFeature3Desc: "Тест даярдоодон визага чейин негизги этаптарды пландаңыз",
appTimelineFeature4: "Календарь синхрондоо",
appTimelineFeature4Desc: "Мөөнөттөрдү жылнаамаңызга синхрондоп, ыңгайлуу пландаңыз",
appTimelineCta: "Көзөмөлдөөнү баштоо",
myDocsTitle: "Менин документтерим",
myDocsDesc: "Арыз документтериңизди жана транскрипттериңизди башкарыңыз",
myDocsFeature1: "Документтерди сактоо",
myDocsFeature1Desc: "Транскрипттерди, эссени жана сунуштамаларды коопсуз сактаңыз",
myDocsFeature2: "Версия башкаруу",
myDocsFeature2Desc: "Өзгөрүүлөрдү көзөмөлдөп, бир нече эссе черновиктерин башкарыңыз",
myDocsFeature3: "Тез бөлүшүү",
myDocsFeature3Desc: "Документтерди кеңешчилер жана менторлор менен текшерүүгө бөлүшүңүз",
myDocsFeature4: "Чек-лист башкаруусу",
myDocsFeature4Desc: "Ар бир университет арызы үчүн талап кылынган документтерди көзөмөлдөңүз",
myDocsCta: "Документтерди жүктөө",
careerAnalysisTitle: "Карьералык жол анализи",
careerAnalysisDesc: "Потенциалдуу карьералык жолдорду жана мүмкүнчүлүктөрдү талдаңыз",
careerAnalysisFeature1: "Тармак боюнча маалымат",
careerAnalysisFeature1Desc: "Тармак боюнча карьера тенденцияларын жана маяна маалыматтарын изилдеңиз",
careerAnalysisFeature2: "Көндүм картасы",
careerAnalysisFeature2Desc: "Көндүмдөрүңүздү суроо-талапка ийгиликтүү карьера мүмкүнчүлүктөрүнө дал келтириңиз",
careerAnalysisFeature3: "Жол салыштыруу",
careerAnalysisFeature3Desc: "Карьералык жолдорду өсүү болжолдору менен салыштырыңыз",
careerAnalysisFeature4: "Максат коюу",
careerAnalysisFeature4Desc: "Карьералык этаптарды белгилеп, максаттарыңызга жетүүдөгү прогрессти көзөмөлдөңүз",
careerAnalysisCta: "Карьераны талдоо",
internshipsTitle: "Стажировка тандоо",
internshipsDesc: "Максаттарыңызга ылайыктуу стажировка мүмкүнчүлүктөрүн табыңыз",
internshipsFeature1: "Акылдуу тандоо",
internshipsFeature1Desc: "AI тиешелүү стажировкаларды табуу үчүн сизди туура байланыштырат",
internshipsFeature2: "Арыздар трекери",
internshipsFeature2Desc: "Стажировка арыздарыңызды бир жерде көзөмөлдөңүз",
internshipsFeature3: "Компанияларды изилдөө",
internshipsFeature3Desc: "Стажировка сунуштаган компаниялардын терең профилдери",
internshipsFeature4: "Көндүм өнүктүрүү",
internshipsFeature4Desc: "Максаттуу стажировкалар үчүн керектүү көндүмдөрдү аныктаңыз",
internshipsCta: "Стажировка табуу",
mastersTitle: "Магистратура тандоо",
mastersDesc: "Дүйнө жүзүндөгү аспирантура программаларын изилдеңиз",
mastersFeature1: "Программа издөө",
mastersFeature1Desc: "Дүйнө жүзүндөгү университеттердеги магистратура программаларын изилдеңиз",
mastersFeature2: "Кабыл алуу боюнча маалымат",
mastersFeature2Desc: "Кабыл алуу талаптарын жана конкурс деңгээлин билиңиз",
mastersFeature3: "Каржылоо мүмкүнчүлүктөрү",
mastersFeature3Desc: "Аспирантура үчүн стипендияларды жана ассистентураларды табыңыз",
mastersFeature4: "Карьералык натыйжалар",
mastersFeature4Desc: "Программа бүтүрүүчүлөрүнүн жумушка орношуу статистикасын көрүңүз",
mastersCta: "Программаларды изилдөө",
uniReelsTitle: "Университет видеолору",
uniReelsDesc: "Кампус турларын жана студент жашоосу боюнча видеолорду көрүңүз",
uniReelsFeature1: "Кампус турлары",
uniReelsFeature1Desc: "Дүйнөнүн ар кайсы жеринен кампустардын виртуалдык турлары",
uniReelsFeature2: "Студент окуялары",
uniReelsFeature2Desc: "Учурдагы студенттер өз тажрыйбалары жөнүндө айтат",
uniReelsFeature3: "Шаар гиддери",
uniReelsFeature3Desc: "Топ университеттер жайгашкан шаарларды изилдеңиз",
uniReelsFeature4: "Иш-чаралар жыйынтыктары",
uniReelsFeature4Desc: "Ачык эшиктер күнү жана кампус иш-чараларынын жыйынтыктарын көрүңүз",
uniReelsCta: "Азыр көрүү",
privacyTitle: "Купуялык башкаруу панели",
privacyDesc: "Купуялык жөндөөлөрүңүздү жана маалыматыңызды башкарыңыз",
privacyFeature1: "Маалыматты башкаруу",
privacyFeature1Desc: "Сиз жөнүндө чогулткан бардык маалыматты көрүп, башкарыңыз",
privacyFeature2: "Көрүнүштүк жөндөөлөрү",
privacyFeature2Desc: "Профилиңизди жана аракетиңизди ким көрөрүн башкарыңыз",
privacyFeature3: "Маалыматты экспорттоо",
privacyFeature3Desc: "Бардык жеке маалыматыңыздын көчүрмөсүн каалаган убакта жүктөп алыңыз",
privacyFeature4: "Аккаунтту жок кылуу",
privacyFeature4Desc: "Аккаунтуңузду жана байланышкан бардык маалыматты толугу менен өчүрүңүз",
privacyCta: "Жөндөөлөрдү карап чыгуу",
studyTogetherTitle: "Чогуу окуу",
studyTogetherDesc: "Курдаштар жана окуу топтору менен байланышыңыз",
studyTogetherFeature1: "Топ тандоо",
studyTogetherFeature1Desc: "Окшош максаттары жана жылнаамасы бар окуу өнөктөштөрүн табыңыз",
studyTogetherFeature2: "Жандуу сессиялар",
studyTogetherFeature2Desc: "Дүйнө жүзүндөгү курдаштар менен реалдуу убакытта окуу сессияларына кошулуңуз",
studyTogetherFeature3: "Ресурстарды бөлүшүү",
studyTogetherFeature3Desc: "Конспекттерди, материалдарды жана окуу стратегияларын бөлүшүңүз",
studyTogetherFeature4: "Чогуу прогресс",
studyTogetherFeature4Desc: "Жалпы максаттарды көзөмөлдөп, бири-бириңизди шыктандырыңыз",
studyTogetherCta: "Окуу өнөктөш табуу",
sendInfoPageTitle: "Маалымат жөнөтүү — Premium алуу",
sendInfoOfferHeadline: "7 күн Premium БЕКЕР!",
sendInfoOfferBody: "Университет же стипендия боюнча суроо жөнөтүңүз — дароо 7 күн Premium алыңыз.",
sendInfoTabUniversity: "Университет жөнүндө",
sendInfoTabScholarship: "Стипендия жөнүндө",
sendInfoTabApplication: "Арыз жардамы",
sendInfoTabMeeting: "Жолугушуу",
sendInfoTabOther: "Башка суроо",
sendInfoFieldFullName: "Аты-жөнү",
sendInfoFieldEmail: "Электрондук почта",
sendInfoFieldPhone: "Телефон",
sendInfoFieldUniversity: "Университет",
sendInfoFieldUniversityInterest: "Кызыктырган университет",
sendInfoFieldProgram: "Программа",
sendInfoFieldProgramMajor: "Программа / адистик",
sendInfoFieldGpa: "Орточо балл (GPA)",
sendInfoFieldAdditional: "Кошумча маалымат",
sendInfoFieldScholarshipName: "Стипендия аталышы",
sendInfoFieldAchievements: "Академиялык жетишкендиктер",
sendInfoFieldDeadline: "Арыз берүү мөөнөтү",
sendInfoFieldHelp: "Кандай жардам керек?",
sendInfoFieldMeetingType: "Жолугушуу түрү",
sendInfoFieldPreferredDate: "Каалаган күн",
sendInfoFieldPreferredTime: "Каалаган убакыт",
sendInfoFieldNotes: "Кошумча эскертүүлөр",
sendInfoFieldSubject: "Тема",
sendInfoFieldMessage: "Билдирүү",
sendInfoPhFullName: "Аты-жөнүңүздү жазыңыз",
sendInfoPhEmail: "Электрондук почтаңызды жазыңыз",
sendInfoPhPhone: "Телефон номериңизди жазыңыз",
sendInfoPhUniversityInterest: "Кайсы университет кызыктырат?",
sendInfoPhProgramInterest: "Кайсы программа кызыктырат?",
sendInfoPhGpa: "GPA жазыңыз",
sendInfoPhGoals: "Максаттарыңыз жөнүндө айтып бериңиз...",
sendInfoPhScholarship: "Кайсы стипендия кызыктырат?",
sendInfoPhUniversityOpt: "Тиешелүү университет (болсо)",
sendInfoPhAchievements: "Жетишкендиктериңизди жазыңыз...",
sendInfoPhUniversityRequired: "Кайсы университет?",
sendInfoPhProgramRequired: "Кайсы программа?",
sendInfoPhHelp: "Кандай жардам керек, жазыңыз...",
sendInfoPhSubject: "Сурооңуз эмне жөнүндө?",
sendInfoPhContact: "Кантип жардам бере алабыз?",
sendInfoPhNotes: "Кошумча маалымат...",
sendInfoMeetingSelect: "Жолугушуу түрүн тандаңыз",
sendInfoMeetingConsult: "Жалпы консультация",
sendInfoMeetingAppReview: "Арызды текшерүү",
sendInfoMeetingScholarship: "Стипендия консультациясы",
sendInfoMeetingCareer: "Карьералык кеңеш",
sendInfoSubmit: "Жөнөтүү жана Premium алуу",
sendInfoSubmitting: "Жөнөтүлүүдө...",
sendInfoError: "Сурамыңызды жөнөтүү мүмкүн болбоду. Байланышты текшерип, кайра аракет кылыңыз.",
sendInfoSuccessTitle: "Маалымат ийгиликтүү жөнөтүлдү!",
sendInfoSuccessBody: "Кайрылууңуз үчүн рахмат. Командабыз маалыматты карап чыгат жана сиз менен жакын арада байланышат.",
sendInfoPremiumActivated: "Premium-кирүү жигердүү!",
sendInfoPremiumActivatedBody: "Сизде 7 күн Premium функцияларга кирүү бар.",
sendInfoBackToDashboard: "Башкаруу панелине кайтуу",
sendInfoTitleBack: "Башкаруу панелине кайтуу",
required: "милдеттүү",
smartMatch: "Акылдуу тандоо",
aboutCoreAccess: "Негизги кирүү камтылган",
aboutGlobal: "Глобалдуу",
contactLabelEmail: "Электрондук почта",
contactLabelTopic: "Тема",
loginSubtitle: "Кош келиңиз! Аккаунтуңузга кириңиз.",
loginEmailLabel: "Электрондук почта",
loginEmailPlaceholder: "Электрондук почтаңызды жазыңыз",
loginPasswordLabel: "Сырсөз",
loginPasswordPlaceholder: "Сырсөзүңүздү жазыңыз",
loginSubmit: "Кирүү",
loginSubmitting: "Кирүүдө...",
loginNoAccount: "Аккаунтуңуз жокпу?",
loginSignUpHere: "Бул жерден катталыңыз",
loginContinueAsGuest: "Конок катары улантуу",
loginGuestSuffix: "— киризден, тиркемени көрүү.",
loginForgotLink: "Сырсөздү унуттуңузбу?",
forgotSubtitle: "Электрондук почтаңызды жазыңыз — баштапкы абалга келтирүү шилтемесин жөнөтөбүз.",
forgotSubmit: "Шилтеме жөнөтүү",
forgotSent: "Эгер бул почта катталган болсо, шилтеме жөнөтүлдү. Кутуңузду текшериңиз.",
forgotBackToLogin: "Кирүүгө кайтуу",
forgotError: "Баштапкы абалга келтирүү башталган жок. Кайра аракет кылыңыз.",
resetSubtitle: "Жаңы сырсөз тандаңыз.",
resetNoToken: "Шилтемеде токен жок. Жаңы шилтеме сураңыз.",
resetDone: "Сырсөз жаңыланды. Эми кире аласыз.",
resetGoToLogin: "Кирүүгө өтүү",
resetNewPasswordLabel: "Жаңы сырсөз",
resetNewPasswordPlaceholder: "Кеминде 8 символ",
resetSubmit: "Сырсөздү жаңылоо",
resetTooShort: "Сырсөз кеминде 8 символдон турушу керек.",
resetError: "Баштапкы абалга келтирүү шилтемеси жараксыз же мөөнөтү өтүп кеткен.",
verifyVerifying: "Электрондук почтаңыз текшерилүүдө…",
verifyOk: "Электрондук почтаңыз тастыкталды. Рахмат!",
verifyError: "Тастыктоо шилтемеси жараксыз же мөөнөтү өтүп кеткен.",
loginFailedMessage: "Кирүү ийгиликсиз. Электрондук почта жана сырсөзүңүздү текшериңиз.",
registerSubtitle: "Аккаунт түзүңүз — өлкөңүздү тандаңыз.",
registerFirstName: "Атыңыз",
registerLastName: "Фамилияңыз",
registerEmail: "Электрондук почта",
registerEmailPlaceholder: "you@example.com",
registerPassword: "Сырсөз",
registerCountry: "Өлкө",
registerCountriesLoading: "Өлкөлөр жүктөлүүдө...",
registerSelectCountry: "Өлкөңүздү тандаңыз",
registerCountryHint: "Аккаунт түзүү үчүн милдеттүү.",
registerNoCountriesHint: "Өлкөлөр жүктөлгөн жок. Backend серверди иштетип, базада өлкөлөр бар экенин текшериңиз, же ылдыйда «Конок катары улантуу» баскычын колдонуңуз.",
registerSubmit: "Аккаунт түзүү",
registerSubmitting: "Аккаунт түзүлүүдө...",
registerHaveAccount: "Аккаунтуңуз барбы?",
registerLogIn: "Кирүү",
registerGuestSuffix: "— катталбай тиркемени көрүү.",
registerSelectCountryError: "Өлкөнү тандаңыз.",
registerFillAllError: "Бардык талааларды толтуруңуз.",
registerFailedError: "Каттоо ийгиликсиз.",
publicSeeHowItWorks: "YouTube'та кантип иштээрин көрүү",
publicAboutUs: "Биз жөнүндө",
publicSupportQr: "Колдоо QR",
publicFaq: "Көп берилүүчү суроолор",
publicContactUs: "Биз менен байланышуу",
publicSendMessage: "Бизге билдирүү жөнөтүңүз",
publicMessageSent: "Рахмат! Билдирүүңүз жөнөтүлдү.",
publicFullName: "Аты-жөнү",
publicFullNamePh: "Аты-жөнүңүздү жазыңыз",
publicTopicPh: "Кандай жардам керек?",
publicMessageLabel: "Билдирүү",
publicMessagePh: "Билдирүүңүздү жазыңыз",
publicFooterPrivacy: "Купуялык",
publicFooterTerms: "Шарттар",
publicFooterContact: "Байланыш",
publicStudentSupport: "Студенттерге колдоо",
publicUnisWorldwide: "Дүйнө жүзүндөгү университеттер",
publicSupportNumber: "Колдоо номери",
publicQrPlaceholder: "Бул жерге колдоо QR-сүрөтүн кошуңуз",
publicAboutLead: "ilmi дүйнө жүзү боюнча студенттерге AI-тандоо аркылуу туура университетти жана стипендияларды табууга жардам берет. Биздин миссия — жогорку билимди ар бирине жеткиликтүү кылуу.",
publicAboutCopy: "Университеттерди жана стипендияларды издөөгө негизги кирүү камтылган, студенттер дароо колдоно ала турган куралдар менен.",
publicMainServices: "Негизги кызматтар",
searchUniNamePlaceholder: "Университет же колледж атын издөө…",
searchUniClearAll: "Баарын тазалоо",
searchUniTuitionRange: "Жылдык окуу акысы (€)",
searchUniMatching: "Дал келген окуу жайлары",
searchUniLoadingList: "Университеттер жүктөлүүдө...",
uniDetailLoadingTitle: "Жүктөлүүдө...",
uniDetailLoadingBody: "Университеттин маалыматы жүктөлүүдө...",
uniDetailNotFound: "Окуу жайы табылган жок",
searchUniPopularUnder10k: "€10 миңге чейин / жыл",
searchUniPopularUnder5k: "≤ €5 миң / жыл",
searchUniPopularEnglish: "Англис тилинде",
searchUniPopularEurope: "Европа",
searchUniPopularBusiness: "Бизнес жана укук",
searchUniPopularMedicine: "Медицина жана илим",
searchUniPopularArts: "Искусство жана дизайн",
searchUniInstAll: "Баары",
searchUniInstUniversities: "Университеттер гана",
searchUniInstColleges: "Колледждер гана",
searchUniDegreeAll: "Бардык деңгээлдер",
searchUniDegreeAssociate: "Ассоциат",
searchUniDegreeDiploma: "Диплом",
searchUniDegreeBachelor: "Бакалавр",
searchUniDegreeMaster: "Магистр",
searchUniDegreePhd: "PhD / Докторантура",
searchUniLangAny: "Каалаган тил",
searchUniLangEnglish: "Англис",
searchUniLangGerman: "Немис",
searchUniLangFrench: "Француз",
searchUniLangSpanish: "Испан",
searchUniLangDutch: "Голланд",
searchUniLangCatalan: "Каталан",
searchUniAllCountries: "Бардык өлкөлөр",
searchUniAllFields: "Бардык багыттар",
searchUniAllCities: "Бул өлкөдөгү бардык шаарлар",
searchResultOne: "натыйжа",
searchResultMany: "натыйжалар",
searchUniNameLabel: "Окуу жайдын аталышы боюнча издөө",
searchUniPopularHeading: "Популярдуу чыпкалар",
searchUniInstTypeLabel: "Окуу жайдын түрү",
searchUniCountryLabel: "Өлкө",
searchUniCityLabel: "Шаар / аймак",
searchUniFieldLabel: "Багыт",
searchUniDegreeLabel: "Даражанын деңгээли",
searchUniLanguageLabel: "Окуу тили",
searchUniMin: "Мин",
searchUniMax: "Макс",
featureSmartMatchTitle: "Университеттерди акылдуу тандоо",
featureSmartMatchDesc: "AI сиздин профилиңизди, максаттарыңызды жана талаптарыңызды талдап, ылайыктуу университеттерди сунуштайт.",
featureScholarshipTitle: "Стипендиялар жана каржылоо",
featureScholarshipDesc: "Билим алуу бюджетин пландаштыруу үчүн стипендияларды, гранттарды жана жардам программаларын табыңыз.",
featureInsightsTitle: "Тапшыруу боюнча аналитика",
featureInsightsDesc: "Тапшыруу тренддерин, программа деталдарын жана натыйжаларды салыштырып, негиздүү тандоо жасаңыз.",
featureGlobalTitle: "Дүйнө жүзүндөгү университеттерге кирүү",
featureGlobalDesc: "Бир нече өлкөдөгү университеттерди ачык программа жана тапшыруу маалыматтары менен изилдеңиз.",
featureAnyDeviceTitle: "Каалаган түзмөктөн ыңгайлуу кирүү",
featureAnyDeviceDesc: "ilmi'ди мобилдүү же компьютерден колдонуп, дал келгендерди жана кадамдарыңызды көзөмөлдөңүз.",
featureAdvisorTitle: "Кеңешчинин колдоосу",
featureAdvisorDesc: "Тапшыруу, арыз жана пландоо боюнча кеңешчилерден практикалык жардам алыңыз.",
programsAllCategories: "Бардык категориялар",
programsAllCountries: "Бардык өлкөлөр",
programsTuitionFree: "Акысыз / мамлекеттик",
searchUniLangItalian: "Италиян",
searchUniLangJapanese: "Жапон",
searchUniLangKorean: "Корей",
chartUnis: "Университеттер",
chartScholarshipsLabel: "Стипендиялар",
monthJan: "Янв",
monthFeb: "Фев",
monthMar: "Мар",
monthApr: "Апр",
monthMay: "Май",
monthJun: "Июн",
heroTitleLine2: "Окуу жолуңузга жетектөө",
heroDescription2: "Бир жөнөкөй платформада университеттер, стипендиялар, тапшыруу жана магистр программалары боюнча так нускама.",
heroCtaPrimary: "Баштоо",
heroCtaSecondary: "Кантип иштейт",
faqQ1: "ilmi колдонуу акылуубу?",
faqA1: "Негизги мүмкүнчүлүктөр — университеттерди тандоо, стипендияларды табуу жана негизги маалымат — акысыз. Премиум колдоо каалоо боюнча төлөнөт.",
faqQ2: "Тандоо процесси кантип иштейт?",
faqA2: "AI сиздин максаттарыңызды, профилиңизди жана талаптарыңызды талдап, ылайыктуу университеттер менен стипендиялардын тизмесин көрсөтөт.",
faqQ3: "Кайсы өлкөлөр жана университеттер камтылган?",
faqA3: "Биз көптөгөн өлкөлөрдөгү университеттерди жана стипендияларды камтыйбыз. Өлкө, программа жана каржылоо боюнча чыпкалай аласыз.",
faqQ4: "ilmi'ди кантип колдой алам?",
faqA4: "«Биз жөнүндө» бөлүмүндөгү садакалар аркылуу колдой аласыз. Сиздин колдооңуз бардык студенттер үчүн негизги кирүүнү сактоого жардам берет.",
searchFieldDefaultPlaceholder: "Окуу жайларын издөө",
selectFieldDefaultPlaceholder: "Тандаңыз",
skyToggleToLight: "Жарык темага которуу",
skyToggleToDark: "Караңгы темага которуу",
errFailedLoadFavorites: "Сүйүктүүлөрдү жүктөө ишке ашкан жок.",
errFailedRemoveFavorite: "Сүйүктүүлөрдөн алып салуу ишке ашкан жок.",
interestsTitle: "Кызыгуулар",
interestsIntro: "Кызыккан билим деңгээлдериңизди жана тармактарыңызды белгилеңиз. Биз аларды тандоолорду ылайыкташтырууга колдонобуз.",
interestsDegreeLabel: "Кызыккан деңгээл",
interestsFieldLabel: "Кызыккан тармак",
interestsAdded: "Кошулду",
interestsAddDegree: "Деңгээл кошуу",
interestsAddField: "Тармак кошуу",
interestsNoDegrees: "Деңгээл жок",
interestsNoFields: "Тармак жок",
interestsRemoveAria: "алып салуу",
fundingTitle: "Бюджет — каржылоо булактары",
fundingTotalLabel: "Жалпы",
fundingHint: "Окуу акысына чыгара ала тургануңузду кошуңуз (үй-бүлө, топтолгон, стипендия, насыя). Жалпы сумма жеткиликтүүлүк боюнча тандоо үчүн бюджетиңиз болот.",
fundingRemoveAria: "{label} алып салуу",
fundingSourcePlaceholder: "Булак (мис. Үй-бүлө)",
fundingAmountPlaceholder: "Сумма/жыл (USD)",
fundingAdd: "Кошуу",
profileMaxBudget: "Макс. бюджет / жыл (USD)",
profileMaxBudgetPlaceholder: "мис. 15000",
dashNoDeadlines: "Дедлайн жок. Арыздарды көзөмөлдөп, мөөнөттөрдү ушул жерден көрүңүз.",
dashNoTopMatches: "Тандоо барагына баалоолоруңузду кошуп, эң жакшы университет тандооңузду ушул жерден көрүңүз.",
dashNoTopScholarships: "Профилиңизге ылайыктуу стипендиялар пайда болгондо, эң жакшылары ушул жерде көрсөтүлөт.",
dashEligible: "Ылайыктуу",
dashNotYet: "Азырынча жок",
dashNotEligible: "Ылайыксыз",
matchTitle: "Университет тандоо",
matchDescriptionGuest: "Кайсы программаларга ылайыктуу экениңизди, дал келүү деңгээли боюнча рейтинг менен көрүңүз.",
matchDescription: "Кайсы программаларга ылайыктуу экениңизди билүү үчүн академиялык маалыматыңызды жазыңыз.",
matchGuestCtaTitle: "Тандоо алуу үчүн акысыз аккаунт түзүңүз",
matchGuestCtaDesc: "Тандоо баалоолоруңузду жана экзамен баллдарыңызды колдонот, ошондуктан сакталган профиль керек. Конокторло'уч карап чыгуу мүмкүн, бирок тандоо аккаунтту талап кылат.",
matchGuestSignUp: "Катталуу",
matchAcademicInfoTitle: "Академиялык маалыматыңыз",
matchAcademicInfoIntro: "Предмет баалоолоруңузду жана экзамен баллыңызды кошуңуз. Биз аларды ар бир программанын жарыяланган талаптары менен салыштырабыз — маалыматтар профилиңизге сакталат.",
matchGradingSystem: "Баалоо системасы",
matchHighestDegree: "Эң жогорку деңгээл",
matchSubjects: "Предметтер",
matchSubjectPlaceholder: "Предмет",
matchGradePlaceholder: "Баа",
matchRemoveSubject: "Предметти алып салуу",
matchAddSubject: "+ Предмет кошуу",
matchExam: "Экзамен",
matchScore: "Балл",
matchScorePlaceholder: "мис. 100",
matchMaxScore: "Макс. балл",
matchMaxScorePlaceholder: "мис. 120",
matchSaving: "Сакталууда…",
matchSaveAndFind: "Сактап, Тандоолорду Издөө",
matchFinding: "Тандоолор изделүүдө…",
matchPromptSave: "Жогоруга баалоолорду кошуп, «Сактап, Тандоолорду Издөө» баскычын басыңыз.",
matchNoPrograms: "Азырынча программалар жок. Программалар кошулгандан кийин кайра келиңиз.",
matchEligibleOf: "{total} программанын {eligible}и ылайыктуу",
matchTuitionFree: "Акысыз окуу",
matchGradingGpa4: "GPA (4.0 шкаласы)",
matchGradingGpa5: "GPA (5.0 шкаласы)",
matchGradingFive: "5 баллдык (МДА)",
matchGradingTen: "10 баллдык",
matchDegreeHighSchool: "Орто билим аттестаты",
matchDegreeAssociate: "Ассоциат",
matchDegreeBachelor: "Бакалавр",
matchDegreeMaster: "Магистр",
matchDegreeDoctorate: "Докторантура",
matchExamNone: "Экзаменсиз",
matchTierSafety: "Коопсуз",
matchTierTarget: "Максаттуу",
matchTierReach: "Амбициялуу",
matchTierFarReach: "Өтө амбициялуу",
matchTranscriptSelfReported: "Өзү көрсөткөн",
matchTuitionPerYear: "{amount} {currency}/жыл",
matchPercentFit: "{fit}% дал келүү",
matchPercentAcademic: "{score}% академиялык",
matchEligible: "Ылайыктуу",
matchNotYetEligible: "Азырынча ылайыксыз",
matchAllMet: "✓ Бардык талаптарды аткарасыз.",
matchWhatsMissing: "Эмне жетишпей жатат",
matchNeedHave: "{required} керек, {actual} бар",
matchTracking: "✓ Көзөмөлдөнүүдө",
matchAdding: "Кошулууда…",
matchTrackApplication: "+ Арызды көзөмөлдөө",
appsTitle: "Менин арыздарым",
appsDescription: "Арыз берүүдөгү ар бир программаны көзөмөлдөңүз — статус, мөөнөттөр жана эскертүүлөр бир жерде.",
appsNoDeadlineSet: "Мөөнөт белгиленген жок",
appsPastDue: "Мөөнөтү өткөн ({days}к. мурун)",
appsDueToday: "Бүгүн мөөнөтү",
appsDaysLeft: "{days}к. калды",
appsLoading: "Арыздар жүктөлүүдө…",
appsEmptyTitle: "Арыздар жок",
appsEmptyHintBefore: "Ылайыктуу программаларды таап,",
appsTrackApplicationQuoted: "«Арызды көзөмөлдөө»",
appsEmptyHintAfter: "баскычын басыңыз — мөөнөттүү тизме башталат.",
appsFindMatches: "Тандоолорду табуу →",
appsCountOne: "{count} арыз",
appsCountMany: "{count} арыз",
appsStatus: "Статус",
appsDeadline: "Мөөнөт",
appsRemove: "Алып салуу",
appsSubmitted: "{date} жөнөтүлдү",
appsHideChecklist: "▾ Тизмени жашыруу",
appsShowChecklist: "▸ Тизме",
checklistLoading: "Тизме жүктөлүүдө…",
checklistDone: "{done}/{total} аткарылды",
checklistRemoveTask: "Тапшырманы алып салуу: {title}",
checklistAddPlaceholder: "Тапшырма кошуу…",
checklistAdd: "Кошуу",
uniDetailBackToSearch: "Издөөгө кайтуу",
uniDetailNoMatch: "«{slug}» боюнча университет табылган жок.",
uniDetailReturnToSearch: "Издөөгө кайтуу",
uniDetailUniversity: "Университет",
uniDetailCollege: "Колледж",
uniDetailLanguages: "Тилдер: {languages}",
uniDetailApply: "Арыз берүү",
uniDetailTuitionPublic: "Акысыз (мамлекеттик)",
uniDetailTuitionAnnual: "≈ {amount} / жыл",
uniDetailProgramFree: "Акысыз / мамлекеттик",
onboardingRegionLabel: "Баштоо",
onboardingTitle: "ilmi'ге кош келиңиз 👋",
onboardingSub: "Университет тандоолоруңузду, кабыл алынуу мүмкүнчүлүктөрүңүздү жана стипендия дал келүүсүн ачуу үчүн баалоолоруңузду жана бир экзаменди кошуңуз — болжол менен бир мүнөт.",
onboardingCta: "Тандоо алуу →",
onboardingDismiss: "Жабуу",
jobsTitle: "Жумуш жана стажировкалар",
jobsDesc: "Студенттер үчүн мүмкүнчүлүктөр — тармак боюнча чыпкалаңыз.",
jobsFieldLabel: "Тармак",
jobsAllFields: "Бардык тармактар",
jobsLoading: "Жумуш орундары жүктөлүүдө…",
jobsEmpty: "Бул чыпка боюнча жумуш орундары жок.",
loadMore: "Дагы жүктөө",
loadingMore: "Жүктөлүүдө…",
jobsCount: "{count} мүмкүнчүлүк",
jobsApply: "Арыз берүү",
searchScholarshipsPageTitle: "Стипендиялар",
searchScholarshipsPageDesc: "Стипендияларды карап чыгыңыз — тармак жана деңгээл боюнча чыпкалаңыз.",
searchScholarshipsFieldLabel: "Тармак",
searchScholarshipsAllFields: "Бардык тармактар",
searchScholarshipsLevelLabel: "Деңгээл",
searchScholarshipsAllLevels: "Бардык деңгээлдер",
searchScholarshipsLevelBachelor: "Бакалавр",
searchScholarshipsLevelMaster: "Магистр",
searchScholarshipsLevelDoctorate: "Докторантура",
searchScholarshipsLoading: "Стипендиялар жүктөлүүдө…",
searchScholarshipsEmpty: "Чыпкаларыңызга дал келген стипендиялар жок — тармакты же деңгээлди кеңейтип көрүңүз.",
searchScholarshipsCount: "{count} стипендия",
searchScholarshipsAwardFullTuition: "Толук окуу акысы",
searchScholarshipsAwardPercentOff: "Окуу акысынан {value}% арзандатуу",
searchScholarshipsAwardDefault: "Сыйлык",
matchScholTitle: "Стипендия тандоо",
matchScholDesc: "Профилиңизге карата рейтинг берилген активдүү стипендиялар — жарандык, GPA жана кызыгуулар.",
matchScholGuestDesc: "Кайсы стипендияларга ылайыктуу болушуңуз мүмкүн экенин, дал келүү боюнча рейтинг менен көрүңүз.",
matchScholGuestCtaTitle: "Тандоо алуу үчүн акысыз аккаунт түзүңүз",
matchScholGuestCtaDesc: "Тандоо өлкөңүздү, баалоолоруңузду жана кызыгуулоруңузду колдонот — конокторго карап чыгуу мүмкүн, бирок стипендия тандоо сакталган профилди талап кылат.",
matchScholGuestCtaBtn: "Катталуу",
matchScholEligibleOnly: "Ылайыктуулар гана",
matchScholLoading: "Стипендиялар изделүүдө…",
matchScholEmptyPrefix: "Азырынча стипендия жок. Каталог толукталгандан кийин кайра келиңиз, же ",
matchScholEmptyLink: "кызыгуулар жана бюджет",
matchScholErrorDefault: "Стипендия тандоолорун жүктөө мүмкүн болбоду",
matchScholCount: "{total} стипендиянын {eligible}ине ылайыктуу болосуз",
matchScholEligible: "Ылайыктуу",
matchScholNotEligible: "Ылайыксыз",
matchScholYourInterest: "★ Сиздин кызыгууңуз",
matchScholDue: "Мөөнөт {date}",
matchScholAwardFullTuition: "Толук окуу акысы",
matchScholAwardFullCost: "Окуунун толук чыгымы",
matchScholAwardPercentOff: "Окуу акысынан {value}% арзандатуу",
matchScholAwardTuitionDiscount: "Окуу акысынан арзандатуу",
matchScholAwardFixed: "Туруктуу сыйлык",
matchScholAwardVariable: "Өзгөрмөлүү сыйлык",
essayTitle: "Эссени текшерүү",
essayDesc: "Кабыл алуу эссеңизди чаптап, Борбордук Азиядан чет тилинде окуган абитуриенттерге ылайыкташтырылган AI пикирин алыңыз.",
essayNotAvailableTitle: "Азырынча жеткиликтүү эмес",
essayNotAvailableText: "AI менен эссе текшерүү бул чөйрөдө азырынча иштетилген жок. Кийинчерээк кайра текшериңиз — иштей баштаганда эссеңизди ушул жерге чаптап, структураланган пикир ала аласыз.",
essayTypeLabel: "Эссе түрү",
essayTypePersonalStatement: "Жеке билдирүү",
essayTypeMotivationLetter: "Стипендия үчүн мотивациялык кат",
essayTypeStatementOfPurpose: "Максаттар билдирүүсү",
essayTypeCommonApp: "Common App эссеси",
essayTypeOther: "Башка",
essayPlaceholder: "Эссеңизди ушул жерге чаптаңыз…",
essayReviewing: "Текшерилүүдө…",
essayGetFeedback: "Пикир алуу",
essayFeedbackTitle: "AI пикири",
coursesDesc: "Өнөктөш даярдык курстары (англис, математика жана башка).",
coursesSubjectLabel: "Предмет",
coursesAllSubjects: "Бардык предметтер",
coursesLoading: "Курстар жүктөлүүдө…",
coursesEmpty: "Азырынча курс жок.",
coursesCount: "{count} курс",
coursesView: "Ачуу",
dashToggleMenu: "Менюну которуу",
dashDeadlinesDueSoon: "{count} арыздын мөөнөтү жакынлады",
dashDeadlineToday: "Бүгүн",
dashDaysAgo: "{n}к. мурун",
dashDaysLeft: "{n}к. калды",
publicFooterRights: "© {year} ilmi. Бардык укуктар корголгон",

  // My Academics page
  myAcademicsGuestDesc: "Тандоого негиз болгон бааларыңыз жана сынак упайларыңыз.",
  myAcademicsDesc: "Тандооңузга, мүмкүнчүлүктөрүңүзгө жана стипендияларыңызга негиз болгон баалар жана сынактар.",
  myAcademicsGuestEmptyBefore: "Коноктордо сакталган академиялык жазуу жок. ",
  myAcademicsGuestEmptyAfter: " өзүңүздүкүн кошуу үчүн.",
  myAcademicsTranscripts: "Аттестаттар",
  myAcademicsAddViaMatching: "+ Тандоо аркылуу кошуу",
  myAcademicsLoading: "Жүктөлүүдө…",
  myAcademicsNoTranscriptsBefore: "Азырынча аттестат жок. Бааларыңызды ",
  myAcademicsMatchingPage: "тандоо бетине",
  myAcademicsNoTranscriptsAfter: " кошуп, тандоо алыңыз.",
  myAcademicsExams: "Сынактар",
  myAcademicsNoExams: "Азырынча сынак жок.",
};

export default ky;
