const ru = {
  // Navigation
  home: "Главная",
  search: "Поиск",
  dashboard: "Панель",
  profile: "Профиль",
  settings: "Настройки",
  language: "Язык",
  selectLanguage: "Выберите язык",
  languageNote: "Настройки языка будут сохранены для следующего посещения",
  scholarships: "Стипендии",

  // Hero Section
  heroBadge: "ИИ-подбор",
  heroTitle: "Найдите идеальный университет",
  heroSubtitle: "Откройте университеты по всему миру",
  heroDescription:
    "Откройте для себя университеты по всему миру, которые соответствуют вашим академическим целям, бюджету и предпочтениям",
  heroStudents: "Студентов помогли",
  heroUniversities: "Университеты",
  heroSuccessRate: "Успешность",
  heroCta: "Начните путь",
  heroDemo: "Смотреть демо",

  // Search
  searchPlaceholder: "Поиск университетов, программ или местоположений...",
  searchTitle: "Найдите университет мечты",
  searchSubtitle:
    "Фильтр по местоположению, программе, бюджету и многому другому",
  searchFilters: "Фильтры",
  searchResults: "Результаты",
  searchLocation: "Местоположение",
  searchProgram: "Программа",
  searchBudget: "Бюджет",
  searchRanking: "Рейтинг",

  // Dashboard
  dashboardTitle: "Ваша панель",
  dashboardWelcome: "Добро пожаловать!",
  dashboardRecentSearches: "Недавние поиски",
  dashboardSavedUniversities: "Сохраненные университеты",
  dashboardApplications: "Заявки",
  dashboardScholarships: "Стипендии",

  // University Cards
  universityTuition: "Обучение",
  universityAcceptanceRate: "Процент приема",
  universityPrograms: "Программы",
  universityLearnMore: "Узнать больше",
  universityApplyNow: "Подать заявку",

  // Scholarships
  scholarshipTitle: "Топ стипендии",
  scholarshipSubtitle:
    "Откройте возможности финансирования для вашего образования",
  scholarshipMerit: "По заслугам",
  scholarshipNeed: "По потребности",
  scholarshipAthletic: "Спортивные",
  scholarshipAcademic: "Академические",

  // Featured Universities
  featuredTitle: "Рекомендуемые университеты",
  featuredSubtitle: "Высоко оцененные учреждения со всего мира",

  // Actions
  save: "Сохранить",
  cancel: "Отмена",
  edit: "Редактировать",
  delete: "Удалить",
  apply: "Подать заявку",
  view: "Просмотр",
  learnMore: "Узнать больше",
  viewAll: "Посмотреть все",

  // Status
  success: "Успех",
  error: "Ошибка",
  loading: "Загрузка...",
  noResults: "Результаты не найдены",

  // Additional
  deadline: "Срок подачи",
  type: "Тип",
  meritBased: "По заслугам",
  needBased: "По потребности",
  projectBased: "Проектная",
  notifications: "Уведомления",
  close: "Закрыть",
  open: "Открыть",
  light: "Светлая",
  dark: "Темная",
  switchToLight: "Переключить на светлую тему",
  switchToDark: "Переключить на темную тему",

  // Forms
  email: "Электронная почта",
  password: "Пароль",
  firstName: "Имя",
  lastName: "Фамилия",
  phone: "Телефон",
  address: "Адрес",
  city: "Город",
  country: "Страна",
  zipCode: "Почтовый индекс",

  // Time
  today: "Сегодня",
  yesterday: "Вчера",
  tomorrow: "Завтра",
  thisWeek: "На этой неделе",
  thisMonth: "В этом месяце",
  thisYear: "В этом году",

  // Numbers
  thousand: "К",
  million: "М",
  billion: "Б",

  // Theme
  lightMode: "Светлая тема",
  darkMode: "Темная тема",
  toggleTheme: "Переключить тему",

  // Favorites
  favoriteSave: "Добавить в избранное",
  favoriteSaved: "Сохранено",
  favoriteUniversitiesTitle: "Избранные университеты",
  favoriteUniversitiesDescription:
    "Ваш список сохраненных университетов. Вы можете убрать любой в любой момент.",
  favoriteUniversitiesEmpty: "У вас пока нет избранных университетов.",

  // Search page
  searchNoResults: "Нет совпадающих учебных заведений.",

  // Search Fields page
  searchFieldsTitle: "Поиск по направлению",
  searchFieldsPickField: "Выберите направление обучения",
  searchFieldsClearAll: "Очистить все",
  searchFieldsSelectedOne: "направление выбрано",
  searchFieldsSelectedMany: "направлений выбрано",
  searchFieldsSelectPrompt: "Выберите одно или несколько направлений выше, чтобы увидеть подходящие университеты.",
  searchFieldsDegreeLevel: "Степень",
  searchFieldsLanguage: "Язык обучения",
  searchFieldsTuition: "Стоимость обучения (€)",
  searchFieldsResults: "Подходящие университеты",
  searchFieldsLoading: "Загрузка…",
  searchFieldsViewDetails: "Подробнее",
  searchFieldsAdditionalFilters: "Дополнительные фильтры",
  searchFieldsFiltersActive: "активно",
  searchFieldsRemember: "Запомнить мой выбор",
  searchFieldsCompact: "Компактный вид",
  searchFieldsFull: "Полный вид",
  searchFieldsResultOne: "результат",
  searchFieldsResultMany: "результатов",
  filterAllLevels: "Все уровни",
  filterBachelor: "Бакалавриат",
  filterMaster: "Магистратура",
  filterPhd: "PhD / Докторантура",
  filterAnyLanguage: "Любой язык",
  tuitionFree: "Бесплатно",
  tuitionPerYear: "/ год",

  // Field Detail page
  fieldDetailBack: "Назад к направлениям",
  fieldDetailUniSingular: "университет предлагает это направление",
  fieldDetailUniPlural: "университетов предлагают это направление",

  // University Detail page
  uniDetailPrograms: "Программы в этом университете",

  // Field + University Detail page
  fieldUniNotFound: "Университет не найден",
  fieldUniBackToFields: "Назад к направлениям",
  fieldUniBackToResults: "Назад к результатам",
  fieldUniSelectedFields: "Выбранные направления в этом университете",
  fieldUniNoMatchingFields: "Подходящих направлений не найдено.",
  fieldUniDegrees: "Степени",
  fieldUniLanguages: "Языки",
  fieldUniViewFull: "Полный профиль университета",

  // Search Programs page
  searchProgramsTitle: "Поиск программ",
  searchProgramsPlaceholder: "Искать программы по названию…",
  searchProgramsFilters: "Фильтры",
  searchProgramsCategory: "Категория",
  searchProgramsCountry: "Страна",
  searchProgramsResults: "Программы",

  // Program Detail page
  programDetailTitle: "О программе",
  programDetailNotFound: "Программа не найдена.",
  programDetailBack: "Назад к программам",
  programDetailUniversity: "Университет",
  programDetailLocation: "Расположение",
  programDetailDegree: "Степень",
  programDetailLanguage: "Язык",
  programDetailDuration: "Длительность",
  programDetailTuition: "Стоимость",
  programDetailDescription: "Описание",
  programDetailWebsite: "Перейти на сайт",

  // Favorite Programs page
  favoriteProgramsTitle: "Избранные программы",
  favoriteProgramsEmpty: "У вас пока нет избранных программ.",
  favoriteProgramsRemove: "Удалить",

  // Public landing nav
  navFeatures: "Возможности",
  navAbout: "О нас",
  navFaq: "Вопросы",
  navContact: "Контакты",
  navLogin: "Войти",
  navGetStarted: "Начать",
  // Shared page labels
  comingSoon: "Скоро",
  getStarted: "Начать",
  startNow: "Начать сейчас",
  keyFeatures: "Ключевые возможности",
  howItWorks: "Как это работает",
  popularTopics: "Популярные темы",

  // Essay Reviews page
  essayReviewsTitle: "Проверка эссе",
  essayReviewsDesc: "Получите профессиональный отзыв на ваши эссе",
  essayReviewsIntro: "Отправьте эссе на экспертную проверку. Наша команда предоставит подробный отзыв по структуре, содержанию, грамматике и убедительности.",
  essayReviewsAiFeedback: "ИИ-анализ",
  essayReviewsAiFeedbackDesc: "Мгновенный анализ тона, ясности и воздействия",
  essayReviewsStructure: "Анализ структуры",
  essayReviewsStructureDesc: "Логика абзацев и аргументации",
  essayReviewsGrammar: "Грамматика и стиль",
  essayReviewsGrammarDesc: "Проверка грамматики, пунктуации и стиля",
  essayReviewsTone: "Тон и голос",
  essayReviewsToneDesc: "Убедитесь, что ваш голос звучит искренне",
  essayReviewsPersonalStatement: "Личное заявление",
  essayReviewsSupplemental: "Дополнительные эссе",
  essayReviewsDiversity: "О разнообразии",
  essayReviewsResearchPurpose: "Заявление о цели",
  essayReviewsSubmitEssay: "Отправить эссе",
  essayReviewsTurnaround: "Срок: 24-48 часов",

  // Match Universities page
  matchUnisTitle: "Подбор университетов",
  matchUnisDesc: "ИИ-подбор университетов на основе вашего профиля",
  matchUnisIntro: "Наш ИИ анализирует ваш профиль, предпочтения и цели, чтобы найти лучшие университеты для вас.",
  matchUnisProfileAnalysis: "Анализ профиля",
  matchUnisProfileAnalysisDesc: "Глубокий анализ ваших академических сильных сторон",
  matchUnisCompatibility: "Оценка совместимости",
  matchUnisCompatibilityDesc: "Процент совпадения по множеству факторов",
  matchUnisSmartFilter: "Умная фильтрация",
  matchUnisSmartFilterDesc: "Фильтры адаптируются к вашим предпочтениям",
  matchUnisRealtime: "Обновления в реальном времени",
  matchUnisRealtimeDesc: "Результаты обновляются при появлении новых данных",
  matchUnisProfileComplete: "Заполнение профиля",
  matchUnisCompleteProfile: "Заполните профиль для лучших результатов",

  // Match Scholarships page
  matchScholarshipsTitle: "Подбор стипендий",
  matchScholarshipsDesc: "Найдите стипендии, соответствующие вашему профилю",
  matchScholarshipsIntro: "Откройте стипендии, на которые вы можете претендовать, на основе вашей академической записи, гражданства, специальности и финансового положения.",
  matchScholarshipsEligibility: "Проверка соответствия",
  matchScholarshipsEligibilityDesc: "Автоматическая проверка критериев стипендии",
  matchScholarshipsDeadlines: "Отслеживание сроков",
  matchScholarshipsDeadlinesDesc: "Не пропустите дедлайны подачи",
  matchScholarshipsGuidance: "Помощь с заявкой",
  matchScholarshipsGuidanceDesc: "Пошаговая помощь для каждой заявки",
  matchScholarshipsCalculator: "Финансовый калькулятор",
  matchScholarshipsCalculatorDesc: "Оцените общий потенциал финансирования",
  matchScholarshipsMerit: "По заслугам",
  matchScholarshipsNeed: "По потребности",
  matchScholarshipsCountry: "По странам",
  matchScholarshipsField: "По специальности",

  // Similar Students page
  similarStudentsTitle: "Похожие студенты",
  similarStudentsDesc: "Находите студентов с похожими целями",
  similarStudentsIntro: "Найдите студентов с похожим академическим опытом, целевыми университетами и карьерными целями.",
  similarStudentsMatching: "Подбор профилей",
  similarStudentsMatchingDesc: "Найдите студентов с похожими целями",
  similarStudentsGroups: "Учебные группы",
  similarStudentsGroupsDesc: "Присоединяйтесь или создавайте группы",
  similarStudentsExperience: "Обмен опытом",
  similarStudentsExperienceDesc: "Читайте и делитесь опытом поступления",
  similarStudentsNetwork: "Нетворкинг",
  similarStudentsNetworkDesc: "Связывайтесь с теми, кто поступает в те же вузы",

  // Alumni Mentors page
  alumniMentorsTitle: "Менторы-выпускники",
  alumniMentorsDesc: "Получите советы от успешных выпускников",
  alumniMentorsIntro: "Свяжитесь с выпускниками, которые учились за рубежом и могут поделиться реальным опытом, советами и рекомендациями.",
  alumniMentorsCareer: "Карьерное руководство",
  alumniMentorsCareerDesc: "Узнайте о карьере после выпуска",
  alumniMentorsTips: "Советы по поступлению",
  alumniMentorsTipsDesc: "Получите советы от тех, кто прошёл этот путь",
  alumniMentorsCulture: "Культурные особенности",
  alumniMentorsCultureDesc: "Подготовьтесь к жизни в новой стране",
  alumniMentorsAccess: "Доступ к сети",
  alumniMentorsAccessDesc: "Присоединяйтесь к растущему сообществу выпускников",

  // Connect Friends page
  connectFriendsTitle: "Найти друзей",
  connectFriendsDesc: "Стройте связи с другими абитуриентами",
  connectFriendsIntro: "Познакомьтесь с другими студентами, которые готовятся к учёбе за рубежом. Делитесь советами и заводите друзей.",
  connectFriendsInterest: "По интересам",
  connectFriendsInterestDesc: "Находите людей с общими хобби и целями",
  connectFriendsStudy: "Партнёры для учёбы",
  connectFriendsStudyDesc: "Найдите партнёров для подготовки к тестам",
  connectFriendsCampus: "Однокурсники",
  connectFriendsCampusDesc: "Знакомьтесь со студентами того же вуза",
  connectFriendsCultural: "Культурный обмен",
  connectFriendsCulturalDesc: "Узнайте о разных культурах",

  // Mock Interviews page
  mockInterviewsTitle: "Тренировочные интервью",
  mockInterviewsDesc: "Подготовка к собеседованиям при поступлении",
  mockInterviewsIntro: "Готовьтесь к интервью с ИИ-тренером. Получайте обратную связь в реальном времени и отслеживайте свой прогресс.",
  mockInterviewsAi: "ИИ-интервьюер",
  mockInterviewsAiDesc: "Тренировка с реалистичными вопросами",
  mockInterviewsFeedback: "Обратная связь",
  mockInterviewsFeedbackDesc: "Мгновенный анализ ваших ответов",
  mockInterviewsBank: "Банк вопросов",
  mockInterviewsBankDesc: "Коллекции вопросов для разных университетов",
  mockInterviewsTrack: "Отслеживание прогресса",
  mockInterviewsTrackDesc: "Отслеживайте улучшения между сессиями",
  mockInterviewsGeneral: "Общее собеседование",
  mockInterviewsTechnical: "Техническое интервью",
  mockInterviewsScholarship: "Стипендиальное интервью",
  mockInterviewsPortfolio: "Обзор портфолио",

  // Concierge Support page
  conciergeSupportTitle: "Персональная поддержка",
  conciergeSupportDesc: "Премиум-сопровождение на каждом этапе",
  conciergeSupportIntro: "Получите персонального консультанта. От выбора университета до визы — мы направляем вас на каждом шагу.",
  conciergeSupportPriority: "Приоритетная поддержка",
  conciergeSupportPriorityDesc: "Быстрые ответы без ожидания",
  conciergeSupportAdvisor: "Личный консультант",
  conciergeSupportAdvisorDesc: "Персональный эксперт для вашего случая",
  conciergeSupportDocReview: "Проверка документов",
  conciergeSupportDocReviewDesc: "Экспертная проверка всех документов",
  conciergeSupportTracking: "Отслеживание заявок",
  conciergeSupportTrackingDesc: "Статус ваших заявок в реальном времени",

  // English page
  englishTitle: "Подготовка по английскому",
  englishDesc: "Подготовка к IELTS, TOEFL и академическому английскому",
  englishIntro: "Улучшите навыки английского для поступления. Практикуйте чтение, письмо, аудирование и говорение.",
  englishIelts: "Подготовка к IELTS",
  englishIeltsDesc: "Полные тесты и стратегии",
  englishToefl: "Подготовка к TOEFL",
  englishToeflDesc: "Практика по секциям и советы",
  englishAcademic: "Академический английский",
  englishAcademicDesc: "Навыки письма, чтения и презентаций",
  englishSpeaking: "Практика речи",
  englishSpeakingDesc: "Разговорные упражнения с ИИ",
  englishReading: "Чтение",
  englishWriting: "Письмо",
  englishListening: "Аудирование",
  englishSpeakingSkill: "Говорение",

  // Math page
  mathTitle: "Подготовка по математике",
  mathDesc: "Подготовка к SAT, GRE и университетской математике",
  mathIntro: "Укрепите навыки математики с управляемой практикой. Алгебра, анализ, статистика и стратегии решения задач.",
  mathSat: "SAT / ACT математика",
  mathSatDesc: "Задачи и стратегии подготовки к тесту",
  mathAdvanced: "Продвинутые темы",
  mathAdvancedDesc: "Математический анализ, линейная алгебра и другое",
  mathPractice: "Практические задачи",
  mathPracticeDesc: "Тысячи задач с пошаговыми решениями",
  mathProgress: "Отслеживание прогресса",
  mathProgressDesc: "Отслеживайте успехи по всем темам",
  mathAlgebra: "Алгебра",
  mathCalculus: "Матанализ",
  mathStatistics: "Статистика",
  mathGeometry: "Геометрия",

  // AI Literacy page
  aiLiteracyTitle: "ИИ-грамотность",
  aiLiteracyDesc: "Научитесь эффективно использовать ИИ-инструменты",
  aiLiteracyIntro: "Изучите основы ИИ, промпт-инженерию и этичное использование ИИ в учёбе и профессии.",
  aiLiteracyFundamentals: "Основы ИИ",
  aiLiteracyFundamentalsDesc: "Ключевые концепции искусственного интеллекта",
  aiLiteracyPrompt: "Промпт-инженерия",
  aiLiteracyPromptDesc: "Создавайте эффективные запросы к ИИ",
  aiLiteracyData: "Работа с данными",
  aiLiteracyDataDesc: "Понимание и работа с данными",
  aiLiteracyEthics: "Этика ИИ",
  aiLiteracyEthicsDesc: "Ответственное использование ИИ в учёбе",

  // Get Courses page
  getCoursesTitle: "Каталог курсов",
  getCoursesDesc: "Курсы для подготовки к тестам и развития навыков",
  getCoursesIntro: "Откройте для себя курсы для подготовки к поступлению. От тестов до разговорных навыков.",
  getCoursesVideo: "Видеолекции",
  getCoursesVideoDesc: "Учитесь у экспертов в своём темпе",
  getCoursesInteractive: "Интерактивные упражнения",
  getCoursesInteractiveDesc: "Практика с практическими заданиями",
  getCoursesCertificate: "Сертификаты",
  getCoursesCertificateDesc: "Получайте сертификаты для портфолио",
  getCoursesSelfPaced: "Свой темп",
  getCoursesSelfPacedDesc: "Учитесь по своему расписанию",
  getCoursesTestPrep: "Подготовка к тестам",
  getCoursesLanguage: "Языковые курсы",
  getCoursesSkills: "Мягкие навыки",
  getCoursesAcademic: "Академическое письмо",

  // Essay Writing page
  essayWritingTitle: "Написание эссе",
  essayWritingDesc: "Научитесь писать убедительные эссе",
  essayWritingIntro: "Освойте искусство написания эссе с шаблонами, ИИ-рекомендациями и советами для конкретных университетов.",
  essayWritingTemplates: "Шаблоны эссе",
  essayWritingTemplatesDesc: "Проверенные структуры для разных типов эссе",
  essayWritingAi: "ИИ-рекомендации",
  essayWritingAiDesc: "Умные предложения для улучшения текста",
  essayWritingPeer: "Взаимная проверка",
  essayWritingPeerDesc: "Получайте отзывы от других абитуриентов",
  essayWritingUniTips: "Советы по университетам",
  essayWritingUniTipsDesc: "Рекомендации для конкретных университетов",

  // Contact page (premium support + community)
  contactPremiumTitle: "Контакт",
  contactPremiumDesc: "Связь с командой",
  contactPremiumKicker: "Премиум-сопровождение",
  contactPremiumLeftLabel: "Премиум-поддержка и запись",
  contactPremiumIntro:
    "Есть вопросы или нужна помощь? Мы помогаем с заявками, документами и планированием поступления — с приоритетными ответами, когда это важно.",
  contactBookMeeting: "Записаться на встречу",
  contactBookMeetingHint: "Откроется почта с темой письма — мы подтвердим время.",
  contactBookMeetingEmailSubject: "Запрос на встречу — Ilmi",
  contactAsideLabel: "Сообщество и контакты",
  contactTelegramTitle: "Канал в Telegram",
  contactTelegramDesc: "Новости, напоминания и общение с другими абитуриентами.",
  contactOpenTelegram: "Открыть в Telegram",
  contactReachUsTitle: "Прямые контакты",
  contactEmailLabel: "Email",
  contactTelegramLabel: "Сообщество",
  contactTelegramChannelShort: "Официальный канал Ilmi",
  contactReachUsFootnote:
    "Для официальных запросов и документов удобнее email. Telegram — для быстрых вопросов и объявлений сообщества.",
  contactPremiumPriority: "Приоритетный ответ",
  contactPremiumPriorityDesc: "Быстрые ответы от нашей команды",
  contactPremiumVideo: "Видеоконсультации",
  contactPremiumVideoDesc: "Запишитесь на видеозвонок",
  contactPremiumDoc: "Помощь с документами",
  contactPremiumDocDesc: "Помощь с документами и заявками",
  contactPremiumTeam: "Экспертная команда",
  contactPremiumTeamDesc: "Поддержка от опытных консультантов",
  contactPremiumEmail: "Поддержка по email",
  contactPremiumEmailDesc: "Отправьте сообщение и получите ответ в течение 24 часов",
  contactPremiumChat: "Онлайн-чат",
  contactPremiumChatDesc: "Общайтесь с нашей командой в реальном времени",
  contactPremiumCall: "Запланировать звонок",
  contactPremiumCallDesc: "Запишитесь на индивидуальный звонок с консультантом",
  contactPremiumContactUs: "Связаться с нами",
  contactPremiumChannels: "Каналы связи",

  // Dream University page
  dreamUniTitle: "Университет мечты",
  dreamUniDesc: "Планируйте путь к университету мечты",
  dreamUniIntro: "Установите целевые университеты, отслеживайте дедлайны и контролируйте прогресс на пути к поступлению.",
  dreamUniGoals: "Отслеживание целей",
  dreamUniGoalsDesc: "Ставьте и отслеживайте вехи поступления",
  dreamUniDeadlines: "Напоминания о сроках",
  dreamUniDeadlinesDesc: "Не пропустите ни одного дедлайна",
  dreamUniTimeline: "Хроника прогресса",
  dreamUniTimelineDesc: "Визуализируйте путь от начала до зачисления",
  dreamUniChecklist: "Чек-лист заявки",
  dreamUniChecklistDesc: "Отслеживайте каждый документ и требование",

  // Search Scholarships page
  searchScholarshipsTitle: "Поиск стипендий",
  searchScholarshipsDesc: "Найдите стипендии и возможности финансирования",
  searchScholarshipsIntro: "Изучите тысячи стипендий для студентов из Центральной Азии. Фильтруйте по стране, специальности, сумме и дедлайну.",
  searchScholarshipsType: "По типу",
  searchScholarshipsTypeDesc: "По заслугам, потребности, стране и другим критериям",
  searchScholarshipsCountry: "По стране",
  searchScholarshipsCountryDesc: "Фильтр стипендий по стране назначения",
  searchScholarshipsDeadline: "Календарь дедлайнов",
  searchScholarshipsDeadlineDesc: "Отслеживайте сроки подачи на стипендии",
  searchScholarshipsEligibility: "Проверка соответствия",
  searchScholarshipsEligibilityDesc: "Быстрая проверка вашей пригодности",

  // Profile page
  profileTitle: "Мой профиль",
  profileDesc: "Управление настройками аккаунта",
  profileChangePhoto: "Изменить фото",
  profileFullName: "Полное имя",
  profileFirstName: "Имя",
  profileLastName: "Фамилия",
  profileEmail: "Электронная почта",
  profilePhone: "Телефон",
  profileLocation: "Местоположение",
  profileCertifications: "Сертификаты и квалификация",
  profileCertificationsHint:
    "По одному на строку (дипломы, языковые тесты, баллы экзаменов для требований программ).",
  profileShareTitle: "Ссылка на профиль",
  profileShareDesc: "Поделитесь ссылкой или отсканируйте код, чтобы открыть профиль на этом устройстве.",
  profileCopyLink: "Копировать ссылку",
  profileLinkCopied: "Ссылка скопирована",
  profileLoadError: "Не удалось загрузить профиль. Войдите в аккаунт и проверьте, что сервер запущен.",
  profileSaveError: "Не удалось сохранить изменения.",
  profileSaveSuccess: "Профиль сохранён.",
  profileGuestHint:
    "Войдите, чтобы загружать и сохранять профиль, сертификаты и ссылку для sharing.",
  profileSaving: "Сохранение…",
  profileApplications: "Заявки",
  profileScholarships: "Стипендии",
  profileViews: "Просмотры профиля",
  profilePremium: "Премиум участник",
  profilePremiumDesc: "У вас есть доступ ко всем премиум функциям",
  profilePremiumMatch: "Безлимитный подбор университетов",
  profilePremiumSupport: "Приоритетная поддержка заявок",
  profilePremiumAlerts: "Эксклюзивные уведомления о стипендиях",
  profilePremiumMentor: "Прямой доступ к менторам",
  profileSave: "Сохранить изменения",
  profileLogout: "Выйти",

  // Dashboard
  dashMain: "Главная",
  dashDreamUniversity: "Университет мечты",
  dashDreamPeakLabel: "Трек UCA",
  dashDreamCardTagline: "Главная цель — держите документы, баллы и дедлайны в одной линии с этим вузом.",
  dashDreamPillFit: "92% совпадение с профилем",
  dashDreamPillDeadline: "Дальше: заявка UCA · 6 окт",
  dashDreamPillDocs: "Список дел · 4 открыто",
  dashDreamReadinessLabel: "Готовность к этой цели",
  dashSearchUniversities: "Поиск университетов",
  dashFavoriteUniversities: "Избранные университеты",
  dashSearchFields: "Поиск направлений",
  dashSearchPrograms: "Поиск программ",
  dashFavoritePrograms: "Избранные программы",
  dashSearchScholarships: "Поиск стипендий",
  dashAiMatching: "AI подбор",
  dashMatchUniversities: "Подбор университетов",
  dashMatchScholarships: "Подбор стипендий",
  dashEssayReview: "Проверка эссе",
  dashSimilarStudents: "Похожие студенты",
  dashCommunity: "Сообщество",
  dashOthers: "Другое",
  dashConnections: "Связи",
  dashConnectFriends: "Найти друзей",
  dashAlumniMentors: "Менторы-выпускники",
  dashPremiumServices: "Премиум сервисы",
  dashEssayReviews: "Проверка эссе",
  dashMockInterviews: "Пробные интервью",
  dashConciergeSupport: "Консьерж поддержка",
  dashLearning: "Обучение и курсы",
  dashGetCourses: "Получить курсы",
  dashMath: "Математика",
  dashEnglish: "Английский",
  dashEssayWriting: "Написание эссе",
  dashAiLiteracy: "AI грамотность",
  dashDashboard: "Панель",
  dashTagline: "Ваш путь в университет начинается здесь",
  dashSendInfo: "Отправить данные и получить Премиум",
  dashJoinCommunity: "Присоединиться к сообществу",
  dashLogout: "Выйти",
  dashNotifications: "Уведомления",
  dashProfile: "Профиль",
  dashWelcomeBackPrefix: "С возвращением,",
  dashDefaultDisplayName: "Имя Фамилия",
  dashOpenPage: "Открыть страницу",
  dashCardDashboardDesc: "Вернуться к основной панели.",
  dashCardDreamDesc: "Посмотреть цели и прогресс университета мечты.",
  dashCardUniversitiesDesc: "Искать университеты и сравнивать варианты.",
  dashCardFavoriteUniversitiesDesc: "Открыть сохраненные университеты.",
  dashCardFieldsDesc: "Изучить направления по вашим интересам.",
  dashCardProgramsDesc: "Найти программы обучения в лучших вузах.",
  dashCardFavoriteProgramsDesc: "Посмотреть сохраненные программы.",
  dashCardScholarshipsDesc: "Найти подходящие стипендии.",
  dashCardMatchUniversitiesDesc: "Получить AI-подбор университетов.",
  dashCardMatchScholarshipsDesc: "Получить AI-подбор стипендий.",
  dashCardSimilarStudentsDesc: "Смотреть данные похожих студентов.",
  dashCardFriendsDesc: "Найти друзей с похожими целями.",
  dashCardMentorsDesc: "Найти наставников-выпускников.",
  dashCardProfileDesc: "Открыть и обновить профиль.",
  dashCardSendInfoDesc: "Отправить данные и запросить премиум-поддержку.",
  dashContactPremium: "Контакт",
  dashNavAiTools: "AI-инструменты",
  dashNavApply: "Заявки",
  dashMyAcademics: "Моя успеваемость",
  dashMyApplications: "Мои заявки",
  dashNavFriendsAndMentors: "Друзья",
  dashNavSectionAiUniversities: "AI · Университеты",
  dashNavSectionAiScholarships: "AI · Стипендии",
  dashNavSectionAiSimilarStudents: "AI · Похожие студенты",
  dashNavSectionConnectFriends: "Друзья",
  dashNavSectionAlumniMentors: "Менторы-выпускники",
  dashNavSectionContactPremium: "Контакт",
  dashCardContactPremiumDesc: "Связь с командой, запись на встречу или Telegram.",
  dashAiDashboardUniTitle: "AI · Лучшие совпадения по вузам",
  dashAiShowcaseSeeWholeList: "Смотреть весь список",
  dashCtaSeeAllUniversityMatches: "Все совпадения по вузам",
  dashCtaSeeAllScholarshipMatches: "Все совпадения по стипендиям",
  dashCtaSeeAllFriends: "Все друзья",
  dashCtaBrowseAllMentors: "Все менторы",
  dashConnAsideFriendsLabel: "Друзья в этом превью",
  dashFriendsCombinedSectionTitle: "Друзья и знакомства",
  dashFriendsSimilarColumnTitle: "С кем можно познакомиться",
  dashFriendsSimilarSeeMore: "Ещё",
  dashFriendsOnlineColumnTitle: "Ваши друзья",
  dashFriendsOnlineNow: "Сейчас в сети",
  dashFriendsAllFriendsLabel: "Все друзья",
  dashFriendsSeeCountCta: "Посмотреть {{count}} друзей",
  dashFriendsOnlineEmpty: "Сейчас никого в сети",
  dashConnAsideMentorsLabel: "Менторы в этом превью",
  dashSimilarStudentsAddFriend: "В друзья",
  dashAiShowcaseUniCtaHint: "Полный подбор с фильтрами и всеми вариантами.",
  dashAiShowcaseScholCtaHint: "Все стипендии и условия участия на одной странице.",
  dashAiDashboardScholTitle: "AI · Лучшие совпадения по стипендиям",
  dashAiDashboardPeersTitle: "AI · Похожие студенты",
  dashAiUniMatchLead: "Вузы отсортированы по соответствию вашему профилю, целям и баллам.",
  dashAiScholMatchLead: "Стипендии, на которые вы с наибольшей вероятностью претендуете дальше.",
  dashAiPeersMatchLead: "Сверстники со схожими целями — можно учиться на их опыте.",
  dashAiScholCardIntlTitle: "Global Merit Fund",
  dashAiScholCardIntlMeta: "Для международных абитуриентов · дедлайн 15 апр",
  dashSimilarStudent2Name: "Эльдар М.",
  dashSimilarStudent2Desc: "STEM, приоритет стипендий.",
  dashSimilarStudent3Name: "Тимур Б.",
  dashSimilarStudent3Desc: "Фокус на Европу, сильный английский.",
  dashSimilarTagField: "То же направление",
  dashSimilarTagRegion: "Похожий регион",
  dashSimilarTagScores: "Похожие баллы",
  dashSimilarOverlapGpa: "Похожий диапазон GPA",
  dashSimilarOverlapShortlist: "Пересечение шортлиста вузов",
  dashSimilarOverlapIntake: "Тот же целевой набор",
  dashSimilarOverlapScholarFirst: "Фокус на стипендиях",
  dashSimilarOverlapEuTargets: "Пересечение по вузам ЕС",
  dashSimilarOverlapAidFocus: "Оба смотрят need-based помощь",
  dashSimilarOverlapEuropeList: "Упор на Европу в списке",
  dashSimilarOverlapIelts: "Сопоставимый уровень английского",
  dashSimilarOverlapStemExtra: "Похожий STEM-профиль активностей",
  dashSimilaritiesLabel: "Совпадения с вашим профилем",
  dashFriend2SampleName: "Эркежан Д.",
  dashFriend2SampleDesc: "Пересечение избранного: Нидерланды и Германия.",
  dashFriend3SampleName: "Султан К.",
  dashFriend3SampleDesc: "Партнёр по эссе · был вчера.",
  dashMentor2SampleName: "Лаура Н.",
  dashMentor2SampleDesc: "MBA, собеседования и резюме.",
  dashMentorBadgeStem: "Инженерия",
  dashMentorBadgeMba: "Бизнес и MBA",
  dashMentorVerified: "Проверенный ментор",
  dashAway: "Не в сети",
  dashConnectionFriendsTitle: "Связи · Друзья",
  dashConnectionFriendsLead: "Люди рядом по пути поступления — можно написать.",
  dashConnectionMentorsTitle: "Связи · Менторы-выпускники",
  dashConnectionMentorsLead: "Выпускники помогают с заявками и интервью.",
  dashConnectionActionChat: "Открыть чат",
  dashConnectionActionMentor: "Профиль",
  dashConnectionPremiumTitle: "Премиум-поддержка",
  dashConnectionPremiumLead: "Персональная помощь по дедлайнам, эссе и стратегии.",
  dashConnectionPremiumPoint1: "Приоритетные ответы команды ilmi",
  dashConnectionPremiumPoint2: "Разбор эссе и пробных интервью с обратной связью",
  dashConnectionPremiumPoint3: "Планирование шортлиста в формате консьержа",
  dashContactSubheading: "Контакт",
  dashContactDetailsTitle: "Как связаться",
  dashContactCompactHint:
    "Быстрые ссылки ниже. Для развёрнутого сообщения откройте страницу «Контакт».",
  dashContactFullPageCta: "Полная страница «Контакт»",
  dashContactUsTitle: "Связаться с нами",
  dashContactPhoneLabel: "Телефон",
  dashContactTelegramQrCaption:
    "Сканируйте или нажмите, чтобы открыть наш канал в Telegram.",
  dashContactSocialListLabel: "Соцсети и сообщество",
  dashContactFormTitle: "Отправить сообщение",
  dashContactFormName: "Полное имя",
  dashContactFormNamePh: "Введите имя и фамилию",
  dashContactFormEmail: "Email",
  dashContactFormEmailPh: "you@example.com",
  dashContactFormTopic: "Тема",
  dashContactFormTopicPh: "С чем нужна помощь?",
  dashContactFormMessage: "Сообщение",
  dashContactFormMessagePh:
    "Напишите сообщение здесь — добавьте детали, чтобы мы могли помочь.",
  dashContactFormSubmit: "Отправить",
  dashContactFormThanks: "Спасибо! Мы получили сообщение и скоро ответим.",
  dashContactFormAgain: "Отправить ещё одно",
  contactPlatformLinkedIn: "LinkedIn",
  contactPlatformTelegram: "Telegram",
  contactPlatformInstagram: "Instagram",
  contactPlatformX: "X",
  contactPlatformYouTube: "YouTube",
  contactPlatformTikTok: "TikTok",
  dashPerfectMatch: "Идеальное совпадение",
  dashUcaName: "Университет Центральной Азии",
  dashUcaLocation: "Нарын, Кыргызстан",
  dashStartClimb: "Начать путь",
  dashPackList: "Список дел",
  dashUpcomingDeadlines: "Ближайшие дедлайны",
  dashShowAll: "Показать все",
  dashUcaApplication: "Заявка в UCA",
  dashAucaScholarship: "Стипендия AUCA",
  dashMitApplication: "Заявка в MIT",
  dashOct6: "6 окт 2025",
  dashOct8: "8 окт 2025",
  dashDeadlineFarTitle: "Stanford SCEA · портфолио и транскрипты",
  dashDeadlineFarDate: "15 янв 2027",
  dashTimeAbout9mo: "~9 мес.",
  dashTime45m: "45 мин осталось",
  dashTime2h15m: "2ч 15м осталось",
  dashTime2d3h: "2д 3ч осталось",
  dashViewsTitle: "Просмотры вузов и стипендий",
  dashViewsTotal: "Демо-данные",
  dashViewsDesc: "Отслеживайте, сколько вузов и стипендий вы просмотрели",
  dashRecommendedUniversities: "Рекомендуемые университеты",
  dashPreviewSearchPlaceholder: "Поиск по названию или месту…",
  dashFilters: "Фильтры",
  dashFilterAll: "Все",
  dashFilterEurope: "Европа",
  dashFilterEnglishTaught: "На английском",
  dashSearchPopularFilters: "Популярные фильтры",
  dashSearchClearFilters: "Сбросить",
  dashStartSearching: "Начать поиск",
  dashSearchUniPlaceholder: "Поиск по названию вуза или колледжа…",
  dashUniPopUnder10k: "До €10 тыс. / год",
  dashUniPopUnder5k: "≤ €5 тыс. / год",
  dashUniPopBusinessLaw: "Бизнес и право",
  dashUniPopMedicine: "Медицина и науки",
  dashUniPopArts: "Искусство и дизайн",
  dashFieldTeaserCs: "Информатика и IT",
  dashFieldTeaserBusiness: "Бизнес и менеджмент",
  dashFieldTeaserMedicine: "Медицина и здоровье",
  dashFieldTeaserEngineering: "Инженерия",
  dashFieldTeaserArts: "Искусство и дизайн",
  dashScholarshipUrlHintMerit: "Вы перешли к стипендиям за заслуги с панели.",
  dashScholarshipUrlHintNeed: "Вы перешли к стипендиям по нужде с панели.",
  dashSearchTeaserSearchUniversities: "Искать вузы",
  dashSearchTeaserSearchFields: "Искать направления",
  dashSearchTeaserSearchScholarships: "Искать стипендии",
  dashSearchFieldPlaceholder: "Поиск по названию направления…",
  dashSearchScholarshipPlaceholder: "Поиск стипендий…",
  dashPreviewMatches: "совпадений",
  dashPreviewNoResults: "Нет совпадений для этого фильтра.",
  dashPreviewUniversitiesLead: "Предпросмотр поиска: фильтры слева сужают список справа.",
  dashPreviewProgramsLead: "Предпросмотр поиска программ с быстрыми фильтрами.",
  dashPreviewScholarshipsLead: "Предпросмотр поиска стипендий с типом фильтра.",
  dashProgramFilterMaster: "Магистратура",
  dashProgramFilterBachelor: "Бакалавриат",
  dashScholarshipFilterMerit: "За заслуги",
  dashScholarshipFilterNeed: "По нужде",
  dashProgramPreviewMsTitle: "M.Sc. Computer Science",
  dashProgramPreviewMsMeta: "STEM · осенний набор",
  dashProgramPreviewBsTitle: "B.A. Международные отношения",
  dashProgramPreviewBsMeta: "Гуманитарные науки · круглый год",
  dashProgramPreviewMbaTitle: "MBA",
  dashProgramPreviewMbaMeta: "Бизнес · GMAT",
  dashScholPreviewMeritTitle: "Стипендия за заслуги",
  dashScholPreviewMeritMeta: "До €5 000 · дедлайн 1 марта",
  dashScholPreviewNeedTitle: "Грант по финансовой нужде",
  dashScholPreviewNeedMeta: "По доходу · круглый год",
  dashApplicationStatus: "Статус заявок",
  dashStatusCardLead: "Все статусы, которые вы ведёте в ilmi — числа и доля в воронке.",
  dashStatusDonutLabel: "Заявок",
  dashStatusTotal: "Всего 15",
  dashStatusPlan: "Планирую подать",
  dashStatusApplied: "Подано",
  dashStatusAccepted: "Принято",
  dashStatusWaitlist: "Лист ожидания",
  dashStatusRejected: "Отклонено",
  dashRank: "Рейтинг",
  dashMatch: "Совпадение",
  dashUni1Name: "Массачусетский технологический институт",
  dashUni1Loc: "Кембридж, Массачусетс, США",
  dashUni1Rank: "#1",
  dashUni1Match: "95%",
  dashUni2Name: "Стэнфордский университет",
  dashUni2Loc: "Стэнфорд, Калифорния, США",
  dashUni2Rank: "#2",
  dashUni2Match: "92%",
  dashAiSampleUniversities: "Топ-подбор по профилю и вашим целям.",
  dashAiSampleScholarships: "Стипендии по бюджету и вашим баллам.",
  dashAiSampleStudents: "Студенты с похожими траекториями и результатами.",
  dashFriendSampleName: "Айзада К.",
  dashFriendSampleDesc: "Подает на программы Data Science.",
  dashMentorSampleName: "Мурат Р.",
  dashMentorSampleDesc: "Ментор-выпускник по инженерным заявкам.",
  dashOnline: "Онлайн",

  appTimelineTitle: "Таймлайн заявок",
  appTimelineDesc: "Отслеживайте дедлайны и прогресс заявок",
  appTimelineFeature1: "Отслеживание дедлайнов",
  appTimelineFeature1Desc: "Умные напоминания о дедлайнах подачи заявок",
  appTimelineFeature2: "Мониторинг прогресса",
  appTimelineFeature2Desc: "Статус заявок во все университеты на одном экране",
  appTimelineFeature3: "Планирование этапов",
  appTimelineFeature3Desc: "Планируйте от подготовки к тестам до подачи на визу",
  appTimelineFeature4: "Синхронизация календаря",
  appTimelineFeature4Desc: "Синхронизируйте дедлайны с вашим календарём",
  appTimelineCta: "Начать отслеживание",

  myDocsTitle: "Мои документы",
  myDocsDesc: "Управляйте документами и транскриптами",
  myDocsFeature1: "Хранение документов",
  myDocsFeature1Desc: "Безопасное хранение транскриптов, эссе и рекомендаций",
  myDocsFeature2: "Контроль версий",
  myDocsFeature2Desc: "Управление изменениями и черновиками эссе",
  myDocsFeature3: "Быстрая отправка",
  myDocsFeature3Desc: "Делитесь документами с наставниками для проверки",
  myDocsFeature4: "Чеклист документов",
  myDocsFeature4Desc: "Отслеживайте необходимые документы для каждого вуза",
  myDocsCta: "Загрузить документы",

  careerAnalysisTitle: "Анализ карьерного пути",
  careerAnalysisDesc: "Анализируйте карьерные возможности",
  careerAnalysisFeature1: "Обзор отраслей",
  careerAnalysisFeature1Desc: "Тренды рынка и данные о зарплатах по отраслям",
  careerAnalysisFeature2: "Карта навыков",
  careerAnalysisFeature2Desc: "Соотнесите навыки с востребованными вакансиями",
  careerAnalysisFeature3: "Сравнение путей",
  careerAnalysisFeature3Desc: "Сравнивайте карьерные пути с прогнозами роста",
  careerAnalysisFeature4: "Постановка целей",
  careerAnalysisFeature4Desc: "Ставьте карьерные цели и отслеживайте прогресс",
  careerAnalysisCta: "Анализировать карьеру",

  internshipsTitle: "Подбор стажировок",
  internshipsDesc: "Найдите стажировки, соответствующие вашим целям",
  internshipsFeature1: "Умный подбор",
  internshipsFeature1Desc: "ИИ подберёт релевантные стажировки для вас",
  internshipsFeature2: "Трекер заявок",
  internshipsFeature2Desc: "Отслеживайте заявки на стажировки в одном месте",
  internshipsFeature3: "Исследование компаний",
  internshipsFeature3Desc: "Подробные профили компаний, предлагающих стажировки",
  internshipsFeature4: "Развитие навыков",
  internshipsFeature4Desc: "Определите навыки для целевых стажировок",
  internshipsCta: "Найти стажировки",

  mastersTitle: "Подбор магистратуры",
  mastersDesc: "Изучайте магистерские программы по всему миру",
  mastersFeature1: "Поиск программ",
  mastersFeature1Desc: "Магистерские программы в разных университетах мира",
  mastersFeature2: "Условия приёма",
  mastersFeature2Desc: "Требования к поступлению и уровень конкурса",
  mastersFeature3: "Варианты финансирования",
  mastersFeature3Desc: "Стипендии и ассистентуры для магистрантов",
  mastersFeature4: "Карьерные результаты",
  mastersFeature4Desc: "Статистика трудоустройства выпускников программ",
  mastersCta: "Изучить программы",

  uniReelsTitle: "Видео университетов",
  uniReelsDesc: "Смотрите туры по кампусам и видео студенческой жизни",
  uniReelsFeature1: "Туры по кампусам",
  uniReelsFeature1Desc: "Виртуальные туры по кампусам со всего мира",
  uniReelsFeature2: "Истории студентов",
  uniReelsFeature2Desc: "Рассказы студентов о своём опыте обучения",
  uniReelsFeature3: "Гиды по городам",
  uniReelsFeature3Desc: "Познакомьтесь с городами, где находятся топ-вузы",
  uniReelsFeature4: "Обзоры мероприятий",
  uniReelsFeature4Desc: "Видео дней открытых дверей и кампусных событий",
  uniReelsCta: "Смотреть",

  privacyTitle: "Панель конфиденциальности",
  privacyDesc: "Управляйте настройками приватности и данными",
  privacyFeature1: "Контроль данных",
  privacyFeature1Desc: "Просматривайте и управляйте собранными данными",
  privacyFeature2: "Настройки видимости",
  privacyFeature2Desc: "Контролируйте, кто видит ваш профиль",
  privacyFeature3: "Экспорт данных",
  privacyFeature3Desc: "Скачайте копию всех ваших личных данных",
  privacyFeature4: "Удаление аккаунта",
  privacyFeature4Desc: "Полное удаление аккаунта и всех связанных данных",
  privacyCta: "Проверить настройки",

  studyTogetherTitle: "Учимся вместе",
  studyTogetherDesc: "Находите единомышленников и учебные группы",
  studyTogetherFeature1: "Подбор групп",
  studyTogetherFeature1Desc: "Найдите партнёров с похожими целями и расписанием",
  studyTogetherFeature2: "Живые сессии",
  studyTogetherFeature2Desc: "Учебные сессии в реальном времени с учениками по всему миру",
  studyTogetherFeature3: "Обмен материалами",
  studyTogetherFeature3Desc: "Делитесь заметками, материалами и стратегиями подготовки",
  studyTogetherFeature4: "Прогресс вместе",
  studyTogetherFeature4Desc: "Отслеживайте общие цели и мотивируйте друг друга",
  studyTogetherCta: "Найти партнёров",

  // SendInfo page
  sendInfoPageTitle: "Отправьте заявку — получите Premium",
  sendInfoOfferHeadline: "Получите 7 дней Premium БЕСПЛАТНО!",
  sendInfoOfferBody:
    "Отправьте запрос по университету или стипендии — и получите 7 дней premium-доступа мгновенно.",
  sendInfoTabUniversity: "Об университете",
  sendInfoTabScholarship: "О стипендии",
  sendInfoTabApplication: "Помощь с заявкой",
  sendInfoTabMeeting: "Записаться на встречу",
  sendInfoTabOther: "Другой запрос",
  sendInfoFieldFullName: "Полное имя",
  sendInfoFieldEmail: "Электронная почта",
  sendInfoFieldPhone: "Телефон",
  sendInfoFieldUniversity: "Университет",
  sendInfoFieldUniversityInterest: "Интересующий университет",
  sendInfoFieldProgram: "Программа",
  sendInfoFieldProgramMajor: "Программа / специальность",
  sendInfoFieldGpa: "Ваш средний балл (GPA)",
  sendInfoFieldAdditional: "Дополнительная информация",
  sendInfoFieldScholarshipName: "Название стипендии",
  sendInfoFieldAchievements: "Ваши академические достижения",
  sendInfoFieldDeadline: "Дедлайн подачи",
  sendInfoFieldHelp: "Какая помощь нужна?",
  sendInfoFieldMeetingType: "Тип встречи",
  sendInfoFieldPreferredDate: "Желаемая дата",
  sendInfoFieldPreferredTime: "Желаемое время",
  sendInfoFieldNotes: "Дополнительные заметки",
  sendInfoFieldSubject: "Тема",
  sendInfoFieldMessage: "Сообщение",
  sendInfoPhFullName: "Введите ваше полное имя",
  sendInfoPhEmail: "Введите электронную почту",
  sendInfoPhPhone: "Введите номер телефона",
  sendInfoPhUniversityInterest: "Какой университет вас интересует?",
  sendInfoPhProgramInterest: "Какая программа интересует?",
  sendInfoPhGpa: "Введите GPA",
  sendInfoPhGoals: "Расскажите о своих целях...",
  sendInfoPhScholarship: "Какая стипендия интересует?",
  sendInfoPhUniversityOpt: "Связанный университет (если есть)",
  sendInfoPhAchievements: "Опишите свои достижения...",
  sendInfoPhUniversityRequired: "Какой университет?",
  sendInfoPhProgramRequired: "Какая программа?",
  sendInfoPhHelp: "Опишите, какая помощь нужна...",
  sendInfoPhSubject: "О чём ваш запрос?",
  sendInfoPhContact: "Расскажите, чем можем помочь...",
  sendInfoPhNotes: "Любая дополнительная информация...",
  sendInfoMeetingSelect: "Выберите тип встречи",
  sendInfoMeetingConsult: "Общая консультация",
  sendInfoMeetingAppReview: "Проверка заявки",
  sendInfoMeetingScholarship: "Консультация по стипендиям",
  sendInfoMeetingCareer: "Карьерное наставничество",
  sendInfoSubmit: "Отправить и получить Premium",
  sendInfoSubmitting: "Отправляется...",
  sendInfoError: "Не удалось отправить запрос. Проверьте соединение и попробуйте снова.",
  sendInfoSuccessTitle: "Заявка успешно отправлена!",
  sendInfoSuccessBody:
    "Спасибо за обращение. Наша команда рассмотрит вашу информацию и свяжется с вами в ближайшее время.",
  sendInfoPremiumActivated: "Premium-доступ активирован!",
  sendInfoPremiumActivatedBody: "У вас есть доступ к premium-функциям на 7 дней.",
  sendInfoBackToDashboard: "Назад в панель",
  sendInfoTitleBack: "Назад в панель",
  required: "обязательно",

  // Search shared
  smartMatch: "Умный подбор",

  // PublicHomePage extras
  aboutCoreAccess: "Базовый доступ включён",
  aboutGlobal: "Глобально",
  contactLabelEmail: "Электронная почта",
  contactLabelTopic: "Тема",

  // Login page
  loginSubtitle: "С возвращением! Войдите в свой аккаунт.",
  loginEmailLabel: "Электронная почта",
  loginEmailPlaceholder: "Введите электронную почту",
  loginPasswordLabel: "Пароль",
  loginPasswordPlaceholder: "Введите пароль",
  loginSubmit: "Войти",
  loginSubmitting: "Вход...",
  loginNoAccount: "Нет аккаунта?",
  loginSignUpHere: "Зарегистрируйтесь здесь",
  loginContinueAsGuest: "Продолжить как гость",
  loginGuestSuffix: "— без входа, попробовать приложение.",
  loginForgotLink: "Забыли пароль?",
  forgotSubtitle: "Введите email — мы отправим ссылку для сброса.",
  forgotSubmit: "Отправить ссылку",
  forgotSent: "Если этот email зарегистрирован, ссылка для сброса уже в пути. Проверьте почту.",
  forgotBackToLogin: "Назад ко входу",
  forgotError: "Не удалось начать сброс. Попробуйте снова.",
  resetSubtitle: "Выберите новый пароль.",
  resetNoToken: "В ссылке нет токена. Запросите новую.",
  resetDone: "Пароль обновлён. Теперь можно войти.",
  resetGoToLogin: "Перейти ко входу",
  resetNewPasswordLabel: "Новый пароль",
  resetNewPasswordPlaceholder: "Минимум 8 символов",
  resetSubmit: "Обновить пароль",
  resetTooShort: "Пароль должен содержать минимум 8 символов.",
  resetError: "Ссылка для сброса недействительна или истекла.",
  verifyVerifying: "Проверяем ваш email…",
  verifyOk: "Ваш email подтверждён. Спасибо!",
  verifyError: "Ссылка подтверждения недействительна или истекла.",
  loginFailedMessage: "Ошибка входа. Проверьте email и пароль.",

  // Register page
  registerSubtitle: "Создайте аккаунт — выберите страну для регистрации.",
  registerFirstName: "Имя",
  registerLastName: "Фамилия",
  registerEmail: "Электронная почта",
  registerEmailPlaceholder: "you@example.com",
  registerPassword: "Пароль",
  registerCountry: "Страна",
  registerCountriesLoading: "Загрузка стран...",
  registerSelectCountry: "Выберите страну",
  registerCountryHint: "Необходимо для создания аккаунта.",
  registerNoCountriesHint:
    "Список стран не загружен. Запустите backend и убедитесь, что в базе данных есть страны, или используйте «Продолжить как гость» ниже.",
  registerSubmit: "Создать аккаунт",
  registerSubmitting: "Создание аккаунта...",
  registerHaveAccount: "Уже есть аккаунт?",
  registerLogIn: "Войти",
  registerGuestSuffix: "— попробовать без регистрации.",
  registerSelectCountryError: "Пожалуйста, выберите страну.",
  registerFillAllError: "Пожалуйста, заполните все поля.",
  registerFailedError: "Регистрация не удалась.",

  // PublicHome
  publicSeeHowItWorks: "Посмотреть, как это работает, на YouTube",
  publicAboutUs: "О нас",
  publicSupportQr: "QR поддержки",
  publicFaq: "Часто задаваемые вопросы",
  publicContactUs: "Связаться с нами",
  publicSendMessage: "Отправьте нам сообщение",
  publicMessageSent: "Спасибо! Ваше сообщение отправлено.",
  publicFullName: "Полное имя",
  publicFullNamePh: "Введите ваше полное имя",
  publicTopicPh: "С чем нужна помощь?",
  publicMessageLabel: "Сообщение",
  publicMessagePh: "Напишите ваше сообщение",
  publicFooterPrivacy: "Конфиденциальность",
  publicFooterTerms: "Условия",
  publicFooterContact: "Контакты",
  publicStudentSupport: "Поддержка студентов",
  publicUnisWorldwide: "Университетов по всему миру",
  publicSupportNumber: "Телефон поддержки",
  publicQrPlaceholder: "Добавьте сюда QR-код поддержки",
  publicAboutLead:
    "ilmi помогает студентам со всего мира найти подходящий университет и стипендии с помощью AI-подбора. Наша миссия — сделать высшее образование доступным для каждого.",
  publicAboutCopy:
    "Базовый доступ к поиску университетов и стипендий включён, с практичными инструментами для немедленного использования.",
  publicMainServices: "Основные услуги",

  searchUniNamePlaceholder: "Поиск по названию университета или колледжа…",
  searchUniClearAll: "Очистить всё",
  searchUniTuitionRange: "Стоимость обучения в год (€)",
  searchUniMatching: "Подходящие учреждения",
  searchUniLoadingList: "Загрузка университетов...",

  uniDetailLoadingTitle: "Загрузка...",
  uniDetailLoadingBody: "Загрузка информации об университете...",
  uniDetailNotFound: "Учреждение не найдено",

  // Search Universities options
  searchUniPopularUnder10k: "До €10 тыс / год",
  searchUniPopularUnder5k: "≤ €5 тыс / год",
  searchUniPopularEnglish: "На английском",
  searchUniPopularEurope: "Европа",
  searchUniPopularBusiness: "Бизнес и право",
  searchUniPopularMedicine: "Медицина и науки",
  searchUniPopularArts: "Искусство и дизайн",
  searchUniInstAll: "Все",
  searchUniInstUniversities: "Только университеты",
  searchUniInstColleges: "Только колледжи",
  searchUniDegreeAll: "Все уровни",
  searchUniDegreeAssociate: "Ассоциированная степень",
  searchUniDegreeDiploma: "Диплом",
  searchUniDegreeBachelor: "Бакалавриат",
  searchUniDegreeMaster: "Магистратура",
  searchUniDegreePhd: "PhD / Докторантура",
  searchUniLangAny: "Любой язык",
  searchUniLangEnglish: "Английский",
  searchUniLangGerman: "Немецкий",
  searchUniLangFrench: "Французский",
  searchUniLangSpanish: "Испанский",
  searchUniLangDutch: "Голландский",
  searchUniLangCatalan: "Каталанский",
  searchUniAllCountries: "Все страны",
  searchUniAllFields: "Все направления",
  searchUniAllCities: "Все города в этой стране",

  searchResultOne: "результат",
  searchResultMany: "результатов",
  searchUniNameLabel: "Поиск по названию учреждения",
  searchUniPopularHeading: "Популярные фильтры",
  searchUniInstTypeLabel: "Тип учреждения",
  searchUniCountryLabel: "Страна",
  searchUniCityLabel: "Город / регион",
  searchUniFieldLabel: "Направление",
  searchUniDegreeLabel: "Уровень степени",
  searchUniLanguageLabel: "Язык обучения",
  searchUniMin: "Мин",
  searchUniMax: "Макс",

  featureSmartMatchTitle: "Умный подбор университетов",
  featureSmartMatchDesc:
    "ИИ анализирует ваш профиль, цели и предпочтения, чтобы рекомендовать подходящие университеты.",
  featureScholarshipTitle: "Стипендии и финансирование",
  featureScholarshipDesc:
    "Найдите стипендии, гранты и финансовые программы для планирования бюджета на образование.",
  featureInsightsTitle: "Аналитика поступлений",
  featureInsightsDesc:
    "Сравнивайте тренды поступлений, детали программ и результаты, чтобы принимать обоснованные решения.",
  featureGlobalTitle: "Доступ к университетам по всему миру",
  featureGlobalDesc:
    "Исследуйте университеты в разных странах с понятной информацией о программах и поступлении.",
  featureAnyDeviceTitle: "Удобный доступ с любого устройства",
  featureAnyDeviceDesc:
    "Используйте ilmi на мобильном или ПК — следите за подборками и шагами поступления.",
  featureAdvisorTitle: "Поддержка консультантов",
  featureAdvisorDesc:
    "Получите практическую помощь от консультантов по поступлению и планированию.",

  programsAllCategories: "Все категории",
  programsAllCountries: "Все страны",
  programsTuitionFree: "Бесплатно / государственное",
  searchUniLangItalian: "Итальянский",
  searchUniLangJapanese: "Японский",
  searchUniLangKorean: "Корейский",

  chartUnis: "Университеты",
  chartScholarshipsLabel: "Стипендии",
  monthJan: "Янв",
  monthFeb: "Фев",
  monthMar: "Мар",
  monthApr: "Апр",
  monthMay: "Май",
  monthJun: "Июн",

  heroTitleLine2: "Поддержка на пути к учёбе",
  heroDescription2:
    "Чёткие рекомендации по университетам, стипендиям, поступлению и магистерским программам на одной платформе.",
  heroCtaPrimary: "Начать",
  heroCtaSecondary: "Как это работает",

  faqQ1: "ilmi платный?",
  faqA1:
    "Основные функции — подбор университетов, поиск стипендий и ключевые инсайты — бесплатны. Премиум-поддержка по желанию.",
  faqQ2: "Как работает подбор?",
  faqA2:
    "ИИ анализирует ваши цели, профиль и предпочтения, затем показывает ранжированный список университетов и стипендий, подходящих вам.",
  faqQ3: "Какие страны и университеты включены?",
  faqA3:
    "Мы охватываем университеты и стипендии во многих странах. Фильтруйте по стране, программе и финансированию.",
  faqQ4: "Как поддержать ilmi?",
  faqA4:
    "Поддержать нас можно через пожертвования, указанные в разделе «О нас». Ваша поддержка помогает сохранить доступ к основным функциям для всех студентов.",

  searchFieldDefaultPlaceholder: "Поиск учреждений",
  selectFieldDefaultPlaceholder: "Выберите вариант",
  skyToggleToLight: "Переключить на светлую тему",
  skyToggleToDark: "Переключить на тёмную тему",

  errFailedLoadFavorites: "Не удалось загрузить избранное.",
  errFailedRemoveFavorite: "Не удалось удалить из избранного.",

  // Profile — interests section
  interestsTitle: "Ваши интересы",
  interestsIntro:
    "Укажите интересующие вас уровни образования и направления. Мы используем это для подбора вариантов.",
  interestsDegreeLabel: "Интересующая степень",
  interestsFieldLabel: "Интересующее направление",
  interestsAdded: "Добавлено",
  interestsAddDegree: "Добавить степень",
  interestsAddField: "Добавить направление",
  interestsNoDegrees: "Пока нет степеней",
  interestsNoFields: "Пока нет направлений",
  interestsRemoveAria: "удалить",

  // Profile — funding section
  fundingTitle: "Бюджет — источники финансирования",
  fundingTotalLabel: "Итого",
  fundingHint:
    "Добавьте, что можете направить на обучение (семья, накопления, стипендия, кредит). Сумма станет вашим бюджетом для подбора по доступности.",
  fundingRemoveAria: "Удалить {label}",
  fundingSourcePlaceholder: "Источник (напр. Семья)",
  fundingAmountPlaceholder: "Сумма/год (USD)",
  fundingAdd: "Добавить",

  // Profile — max budget field
  profileMaxBudget: "Макс. бюджет / год (USD)",
  profileMaxBudgetPlaceholder: "напр. 15000",

  // Dashboard — empty states & match badges
  dashNoDeadlines: "Пока нет дедлайнов. Отслеживайте заявку, чтобы её дедлайн появился здесь.",
  dashNoTopMatches:
    "Добавьте свои оценки на странице подбора, чтобы увидеть здесь ваши лучшие совпадения по университетам.",
  dashNoTopScholarships:
    "Как только появятся стипендии для вашего профиля, здесь отобразятся лучшие совпадения.",
  dashEligible: "Подходит",
  dashNotYet: "Пока нет",
  dashNotEligible: "Не подходит",

  // University matches page
  matchTitle: "Совпадения университетов",
  matchDescriptionGuest: "Узнайте, на какие программы вы проходите, с ранжированием по соответствию.",
  matchDescription: "Введите свои академические данные, чтобы увидеть, на какие программы вы проходите.",
  matchGuestCtaTitle: "Создайте бесплатный аккаунт, чтобы получить совпадения",
  matchGuestCtaDesc:
    "Подбор использует ваши оценки и баллы экзаменов, поэтому нужен сохранённый профиль. Гости могут просматривать, но для совпадений нужен аккаунт.",
  matchGuestSignUp: "Зарегистрироваться",
  matchAcademicInfoTitle: "Ваши академические данные",
  matchAcademicInfoIntro:
    "Добавьте оценки по предметам и балл за экзамен. Мы сравним их с опубликованными требованиями каждой программы — ваши данные сохраняются в профиле.",
  matchGradingSystem: "Система оценивания",
  matchHighestDegree: "Высшая степень",
  matchSubjects: "Предметы",
  matchSubjectPlaceholder: "Предмет",
  matchGradePlaceholder: "Оценка",
  matchRemoveSubject: "Удалить предмет",
  matchAddSubject: "+ Добавить предмет",
  matchExam: "Экзамен",
  matchScore: "Балл",
  matchScorePlaceholder: "напр. 100",
  matchMaxScore: "Макс. балл",
  matchMaxScorePlaceholder: "напр. 120",
  matchSaving: "Сохранение…",
  matchSaveAndFind: "Сохранить и найти совпадения",
  matchFinding: "Поиск совпадений…",
  matchPromptSave: "Добавьте оценки выше и нажмите «Сохранить и найти совпадения».",
  matchNoPrograms: "Пока нет доступных программ. Зайдите позже, когда программы будут добавлены.",
  matchEligibleOf: "{eligible} подходящих из {total} программ",
  matchTuitionFree: "Без оплаты обучения",
  matchTuitionPerYear: "{amount} {currency}/год",
  matchPercentFit: "{fit}% соответствие",
  matchPercentAcademic: "{score}% академически",
  matchEligible: "Подходит",
  matchNotYetEligible: "Пока не подходит",
  matchAllMet: "✓ Вы соответствуете всем требованиям.",
  matchWhatsMissing: "Чего не хватает",
  matchNeedHave: "нужно {required}, есть {actual}",
  matchTracking: "✓ Отслеживается",
  matchAdding: "Добавление…",
  matchTrackApplication: "+ Отслеживать заявку",

  // My applications page
  appsTitle: "Мои заявки",
  appsDescription:
    "Отслеживайте каждую программу, на которую подаёте: статус, дедлайны и заметки в одном месте.",
  appsNoDeadlineSet: "Дедлайн не задан",
  appsPastDue: "Просрочено ({days} дн. назад)",
  appsDueToday: "Срок сегодня",
  appsDaysLeft: "осталось {days} дн.",
  appsLoading: "Загрузка ваших заявок…",
  appsEmptyTitle: "Пока нет заявок",
  appsEmptyHintBefore: "Найдите подходящие программы и нажмите",
  appsTrackApplicationQuoted: "«Отслеживать заявку»",
  appsEmptyHintAfter: "чтобы начать чек-лист с дедлайнами.",
  appsFindMatches: "Найти совпадения →",
  appsCountOne: "{count} заявка",
  appsCountMany: "{count} заявок",
  appsStatus: "Статус",
  appsDeadline: "Дедлайн",
  appsRemove: "Удалить",
  appsSubmitted: "Отправлено {date}",
  appsHideChecklist: "▾ Скрыть чек-лист",
  appsShowChecklist: "▸ Чек-лист",

  // Application checklist
  checklistLoading: "Загрузка чек-листа…",
  checklistDone: "{done}/{total} выполнено",
  checklistRemoveTask: "Удалить задачу: {title}",
  checklistAddPlaceholder: "Добавить задачу…",
  checklistAdd: "Добавить",

  // University detail page
  uniDetailBackToSearch: "Назад к поиску",
  uniDetailNoMatch: "Нет университетов по запросу «{slug}».",
  uniDetailReturnToSearch: "Вернуться к поиску",
  uniDetailUniversity: "Университет",
  uniDetailCollege: "Колледж",
  uniDetailLanguages: "Языки: {languages}",
  uniDetailApply: "Подать заявку",
  uniDetailTuitionPublic: "Без оплаты (государственный)",
  uniDetailTuitionAnnual: "≈ {amount} / год",
  uniDetailProgramFree: "Бесплатно / государственный",

  // Onboarding banner
  onboardingRegionLabel: "Начать",
  onboardingTitle: "Добро пожаловать в ilmi 👋",
  onboardingSub:
    "Добавьте оценки и один экзамен, чтобы открыть совпадения университетов, шансы на поступление и подбор стипендий — около минуты.",
  onboardingCta: "Подобрать →",
  onboardingDismiss: "Закрыть",

  // Reused page titles (missing in ru before)
  dashJobs: "Работа и стажировки",
  dashCourses: "Курсы",

  // Jobs page
  jobsTitle: "Работа и стажировки",
  jobsDesc: "Возможности для студентов — фильтруйте по направлению.",
  jobsFieldLabel: "Направление",
  jobsAllFields: "Все направления",
  jobsLoading: "Загрузка вакансий…",
  jobsEmpty: "Пока нет вакансий по этому фильтру.",
  loadMore: "Показать ещё",
  loadingMore: "Загрузка…",
  jobsCount: "{count} возможностей",
  jobsApply: "Откликнуться",

  // Search scholarships page
  searchScholarshipsPageTitle: "Стипендии",
  searchScholarshipsPageDesc: "Просматривайте стипендии — фильтруйте по направлению и уровню.",
  searchScholarshipsFieldLabel: "Направление",
  searchScholarshipsAllFields: "Все направления",
  searchScholarshipsLevelLabel: "Уровень",
  searchScholarshipsAllLevels: "Все уровни",
  searchScholarshipsLevelBachelor: "Бакалавриат",
  searchScholarshipsLevelMaster: "Магистратура",
  searchScholarshipsLevelDoctorate: "Докторантура",
  searchScholarshipsLoading: "Загрузка стипендий…",
  searchScholarshipsEmpty: "Пока нет стипендий по вашим фильтрам — попробуйте расширить направление или уровень.",
  searchScholarshipsCount: "{count} стипендий",
  searchScholarshipsAwardFullTuition: "Полное покрытие обучения",
  searchScholarshipsAwardPercentOff: "Скидка {value}% на обучение",
  searchScholarshipsAwardDefault: "Награда",

  // Match scholarships page
  matchScholTitle: "Подбор стипендий",
  matchScholDesc: "Активные стипендии, ранжированные по вашему профилю — гражданство, средний балл и интересы.",
  matchScholGuestDesc: "Узнайте, на какие стипендии вы вероятно подходите, в порядке соответствия.",
  matchScholGuestCtaTitle: "Создайте бесплатный аккаунт, чтобы получить подбор",
  matchScholGuestCtaDesc: "Подбор использует вашу страну, оценки и интересы — гости могут просматривать, но для подбора стипендий нужен сохранённый профиль.",
  matchScholGuestCtaBtn: "Зарегистрироваться",
  matchScholEligibleOnly: "Только подходящие",
  matchScholLoading: "Подбираем стипендии для вас…",
  matchScholEmptyPrefix: "Пока нет доступных стипендий. Загляните позже, когда каталог пополнится, или укажите ваши ",
  matchScholEmptyLink: "интересы и бюджет",
  matchScholErrorDefault: "Не удалось загрузить подбор стипендий",
  matchScholCount: "{eligible} подходящих из {total}",
  matchScholEligible: "Подходит",
  matchScholNotEligible: "Не подходит",
  matchScholYourInterest: "★ Ваш интерес",
  matchScholDue: "Срок {date}",
  matchScholAwardFullTuition: "Полное покрытие обучения",
  matchScholAwardFullCost: "Полное покрытие расходов на обучение",
  matchScholAwardPercentOff: "Скидка {value}% на обучение",
  matchScholAwardTuitionDiscount: "Скидка на обучение",
  matchScholAwardFixed: "Фиксированная награда",
  matchScholAwardVariable: "Переменная награда",

  // Essay review page
  essayTitle: "Проверка эссе",
  essayDesc: "Вставьте ваше вступительное эссе и получите отзыв ИИ, настроенный для абитуриентов из Центральной Азии, изучающих английский как иностранный.",
  essayNotAvailableTitle: "Пока недоступно",
  essayNotAvailableText: "Проверка эссе с помощью ИИ пока не включена в этой среде. Загляните позже — когда функция заработает, вы сможете вставить эссе здесь и получить структурированный отзыв.",
  essayTypeLabel: "Тип эссе",
  essayTypePersonalStatement: "Личное заявление",
  essayTypeMotivationLetter: "Мотивационное письмо для стипендии",
  essayTypeStatementOfPurpose: "Заявление о целях",
  essayTypeCommonApp: "Эссе Common App",
  essayTypeOther: "Другое",
  essayPlaceholder: "Вставьте ваше эссе здесь…",
  essayReviewing: "Проверяем…",
  essayGetFeedback: "Получить отзыв",
  essayFeedbackTitle: "Отзыв ИИ",

  // Courses page
  coursesDesc: "Партнёрские подготовительные курсы (английский, математика и другое).",
  coursesSubjectLabel: "Предмет",
  coursesAllSubjects: "Все предметы",
  coursesLoading: "Загрузка курсов…",
  coursesEmpty: "Пока нет курсов.",
  coursesCount: "{count} курсов",
  coursesView: "Открыть",

  // Dashboard layout
  dashToggleMenu: "Переключить меню",
  dashDeadlinesDueSoon: "Скоро истекают сроки подачи заявок: {count}",

  // Public footer
  publicFooterRights: "© {year} ilmi. Все права защищены",
};

export default ru;
