const ru = {
  // Navigation
  home: "Главная",
  search: "Поиск",
  dashboard: "Панель",
  profile: "Профиль",
  settings: "Настройки",
  language: "Язык",
  selectLanguage: "Выберите язык",
  languageNote: "Настройки языка будут сохранены для следующего посещения",
  scholarships: "Стипендии",

  // Hero Section
  heroBadge: "ИИ-подбор",
  heroTitle: "Найдите идеальный университет",
  heroSubtitle: "Откройте университеты по всему миру",
  heroDescription:
    "Откройте для себя университеты по всему миру, которые соответствуют вашим академическим целям, бюджету и предпочтениям",
  heroStudents: "Студентов помогли",
  heroUniversities: "Университеты",
  heroSuccessRate: "Успешность",
  heroCta: "Начните путь",
  heroDemo: "Смотреть демо",

  // Search
  searchPlaceholder: "Поиск университетов, программ или местоположений...",
  searchTitle: "Найдите университет мечты",
  searchSubtitle:
    "Фильтр по местоположению, программе, бюджету и многому другому",
  searchFilters: "Фильтры",
  searchResults: "Результаты",
  searchLocation: "Местоположение",
  searchProgram: "Программа",
  searchBudget: "Бюджет",
  searchRanking: "Рейтинг",

  // Dashboard
  dashboardTitle: "Ваша панель",
  dashboardWelcome: "Добро пожаловать!",
  dashboardRecentSearches: "Недавние поиски",
  dashboardSavedUniversities: "Сохраненные университеты",
  dashboardApplications: "Заявки",
  dashboardScholarships: "Стипендии",

  // University Cards
  universityTuition: "Обучение",
  universityAcceptanceRate: "Процент приема",
  universityPrograms: "Программы",
  universityLearnMore: "Узнать больше",
  universityApplyNow: "Подать заявку",

  // Scholarships
  scholarshipTitle: "Топ стипендии",
  scholarshipSubtitle:
    "Откройте возможности финансирования для вашего образования",
  scholarshipMerit: "По заслугам",
  scholarshipNeed: "По потребности",
  scholarshipAthletic: "Спортивные",
  scholarshipAcademic: "Академические",

  // Featured Universities
  featuredTitle: "Рекомендуемые университеты",
  featuredSubtitle: "Высоко оцененные учреждения со всего мира",

  // Actions
  save: "Сохранить",
  cancel: "Отмена",
  edit: "Редактировать",
  delete: "Удалить",
  apply: "Подать заявку",
  view: "Просмотр",
  learnMore: "Узнать больше",
  viewAll: "Посмотреть все",

  // Status
  success: "Успех",
  error: "Ошибка",
  loading: "Загрузка...",
  noResults: "Результаты не найдены",

  // Additional
  deadline: "Срок подачи",
  type: "Тип",
  meritBased: "По заслугам",
  needBased: "По потребности",
  projectBased: "Проектная",
  notifications: "Уведомления",
  close: "Закрыть",
  open: "Открыть",
  light: "Светлая",
  dark: "Темная",
  switchToLight: "Переключить на светлую тему",
  switchToDark: "Переключить на темную тему",

  // Forms
  email: "Электронная почта",
  password: "Пароль",
  firstName: "Имя",
  lastName: "Фамилия",
  phone: "Телефон",
  address: "Адрес",
  city: "Город",
  country: "Страна",
  zipCode: "Почтовый индекс",

  // Time
  today: "Сегодня",
  yesterday: "Вчера",
  tomorrow: "Завтра",
  thisWeek: "На этой неделе",
  thisMonth: "В этом месяце",
  thisYear: "В этом году",

  // Numbers
  thousand: "К",
  million: "М",
  billion: "Б",

  // Theme
  lightMode: "Светлая тема",
  darkMode: "Темная тема",
  toggleTheme: "Переключить тему",

  // Favorites
  favoriteSave: "Добавить в избранное",
  favoriteSaved: "Сохранено",
  favoriteUniversitiesTitle: "Избранные университеты",
  favoriteUniversitiesDescription:
    "Ваш список сохраненных университетов. Вы можете убрать любой в любой момент.",
  favoriteUniversitiesEmpty: "У вас пока нет избранных университетов.",

  // Search page
  searchNoResults: "Нет совпадающих учебных заведений.",

  // Search Fields page
  searchFieldsTitle: "Поиск по направлению",
  searchFieldsPickField: "Выберите направление обучения",
  searchFieldsClearAll: "Очистить все",
  searchFieldsSelectedOne: "направление выбрано",
  searchFieldsSelectedMany: "направлений выбрано",
  searchFieldsSelectPrompt: "Выберите одно или несколько направлений выше, чтобы увидеть подходящие университеты.",
  searchFieldsDegreeLevel: "Степень",
  searchFieldsLanguage: "Язык обучения",
  searchFieldsTuition: "Стоимость обучения (€)",
  searchFieldsResults: "Подходящие университеты",
  searchFieldsLoading: "Загрузка…",
  searchFieldsViewDetails: "Подробнее",
  searchFieldsAdditionalFilters: "Дополнительные фильтры",
  searchFieldsFiltersActive: "активно",
  searchFieldsRemember: "Запомнить мой выбор",
  searchFieldsCompact: "Компактный вид",
  searchFieldsFull: "Полный вид",
  searchFieldsResultOne: "результат",
  searchFieldsResultMany: "результатов",
  filterAllLevels: "Все уровни",
  filterBachelor: "Бакалавриат",
  filterMaster: "Магистратура",
  filterPhd: "PhD / Докторантура",
  filterAnyLanguage: "Любой язык",
  tuitionFree: "Бесплатно",
  tuitionPerYear: "/ год",

  // Field Detail page
  fieldDetailBack: "Назад к направлениям",
  fieldDetailUniSingular: "университет предлагает это направление",
  fieldDetailUniPlural: "университетов предлагают это направление",

  // University Detail page
  uniDetailPrograms: "Программы в этом университете",

  // Field + University Detail page
  fieldUniNotFound: "Университет не найден",
  fieldUniBackToFields: "Назад к направлениям",
  fieldUniBackToResults: "Назад к результатам",
  fieldUniSelectedFields: "Выбранные направления в этом университете",
  fieldUniNoMatchingFields: "Подходящих направлений не найдено.",
  fieldUniDegrees: "Степени",
  fieldUniLanguages: "Языки",
  fieldUniViewFull: "Полный профиль университета",

  // Search Programs page
  searchProgramsTitle: "Поиск программ",
  searchProgramsPlaceholder: "Искать программы по названию…",
  searchProgramsFilters: "Фильтры",
  searchProgramsCategory: "Категория",
  searchProgramsCountry: "Страна",
  searchProgramsResults: "Программы",

  // Program Detail page
  programDetailTitle: "О программе",
  programDetailNotFound: "Программа не найдена.",
  programDetailBack: "Назад к программам",
  programDetailUniversity: "Университет",
  programDetailLocation: "Расположение",
  programDetailDegree: "Степень",
  programDetailLanguage: "Язык",
  programDetailDuration: "Длительность",
  programDetailTuition: "Стоимость",
  programDetailDescription: "Описание",
  programDetailWebsite: "Перейти на сайт",

  // Favorite Programs page
  favoriteProgramsTitle: "Избранные программы",
  favoriteProgramsEmpty: "У вас пока нет избранных программ.",
  favoriteProgramsRemove: "Удалить",

  // Shared page labels
  comingSoon: "Скоро",
  getStarted: "Начать",
  startNow: "Начать сейчас",
  keyFeatures: "Ключевые возможности",
  howItWorks: "Как это работает",
  popularTopics: "Популярные темы",

  // Essay Reviews page
  essayReviewsTitle: "Проверка эссе",
  essayReviewsDesc: "Получите профессиональный отзыв на ваши эссе",
  essayReviewsIntro: "Отправьте эссе на экспертную проверку. Наша команда предоставит подробный отзыв по структуре, содержанию, грамматике и убедительности.",
  essayReviewsAiFeedback: "ИИ-анализ",
  essayReviewsAiFeedbackDesc: "Мгновенный анализ тона, ясности и воздействия",
  essayReviewsStructure: "Анализ структуры",
  essayReviewsStructureDesc: "Логика абзацев и аргументации",
  essayReviewsGrammar: "Грамматика и стиль",
  essayReviewsGrammarDesc: "Проверка грамматики, пунктуации и стиля",
  essayReviewsTone: "Тон и голос",
  essayReviewsToneDesc: "Убедитесь, что ваш голос звучит искренне",
  essayReviewsPersonalStatement: "Личное заявление",
  essayReviewsSupplemental: "Дополнительные эссе",
  essayReviewsDiversity: "О разнообразии",
  essayReviewsResearchPurpose: "Заявление о цели",
  essayReviewsSubmitEssay: "Отправить эссе",
  essayReviewsTurnaround: "Срок: 24-48 часов",

  // Match Universities page
  matchUnisTitle: "Подбор университетов",
  matchUnisDesc: "ИИ-подбор университетов на основе вашего профиля",
  matchUnisIntro: "Наш ИИ анализирует ваш профиль, предпочтения и цели, чтобы найти лучшие университеты для вас.",
  matchUnisProfileAnalysis: "Анализ профиля",
  matchUnisProfileAnalysisDesc: "Глубокий анализ ваших академических сильных сторон",
  matchUnisCompatibility: "Оценка совместимости",
  matchUnisCompatibilityDesc: "Процент совпадения по множеству факторов",
  matchUnisSmartFilter: "Умная фильтрация",
  matchUnisSmartFilterDesc: "Фильтры адаптируются к вашим предпочтениям",
  matchUnisRealtime: "Обновления в реальном времени",
  matchUnisRealtimeDesc: "Результаты обновляются при появлении новых данных",
  matchUnisProfileComplete: "Заполнение профиля",
  matchUnisCompleteProfile: "Заполните профиль для лучших результатов",

  // Match Scholarships page
  matchScholarshipsTitle: "Подбор стипендий",
  matchScholarshipsDesc: "Найдите стипендии, соответствующие вашему профилю",
  matchScholarshipsIntro: "Откройте стипендии, на которые вы можете претендовать, на основе вашей академической записи, гражданства, специальности и финансового положения.",
  matchScholarshipsEligibility: "Проверка соответствия",
  matchScholarshipsEligibilityDesc: "Автоматическая проверка критериев стипендии",
  matchScholarshipsDeadlines: "Отслеживание сроков",
  matchScholarshipsDeadlinesDesc: "Не пропустите дедлайны подачи",
  matchScholarshipsGuidance: "Помощь с заявкой",
  matchScholarshipsGuidanceDesc: "Пошаговая помощь для каждой заявки",
  matchScholarshipsCalculator: "Финансовый калькулятор",
  matchScholarshipsCalculatorDesc: "Оцените общий потенциал финансирования",
  matchScholarshipsMerit: "По заслугам",
  matchScholarshipsNeed: "По потребности",
  matchScholarshipsCountry: "По странам",
  matchScholarshipsField: "По специальности",

  // Similar Students page
  similarStudentsTitle: "Похожие студенты",
  similarStudentsDesc: "Находите студентов с похожими целями",
  similarStudentsIntro: "Найдите студентов с похожим академическим опытом, целевыми университетами и карьерными целями.",
  similarStudentsMatching: "Подбор профилей",
  similarStudentsMatchingDesc: "Найдите студентов с похожими целями",
  similarStudentsGroups: "Учебные группы",
  similarStudentsGroupsDesc: "Присоединяйтесь или создавайте группы",
  similarStudentsExperience: "Обмен опытом",
  similarStudentsExperienceDesc: "Читайте и делитесь опытом поступления",
  similarStudentsNetwork: "Нетворкинг",
  similarStudentsNetworkDesc: "Связывайтесь с теми, кто поступает в те же вузы",

  // Alumni Mentors page
  alumniMentorsTitle: "Менторы-выпускники",
  alumniMentorsDesc: "Получите советы от успешных выпускников",
  alumniMentorsIntro: "Свяжитесь с выпускниками, которые учились за рубежом и могут поделиться реальным опытом, советами и рекомендациями.",
  alumniMentorsCareer: "Карьерное руководство",
  alumniMentorsCareerDesc: "Узнайте о карьере после выпуска",
  alumniMentorsTips: "Советы по поступлению",
  alumniMentorsTipsDesc: "Получите советы от тех, кто прошёл этот путь",
  alumniMentorsCulture: "Культурные особенности",
  alumniMentorsCultureDesc: "Подготовьтесь к жизни в новой стране",
  alumniMentorsAccess: "Доступ к сети",
  alumniMentorsAccessDesc: "Присоединяйтесь к растущему сообществу выпускников",

  // Connect Friends page
  connectFriendsTitle: "Найти друзей",
  connectFriendsDesc: "Стройте связи с другими абитуриентами",
  connectFriendsIntro: "Познакомьтесь с другими студентами, которые готовятся к учёбе за рубежом. Делитесь советами и заводите друзей.",
  connectFriendsInterest: "По интересам",
  connectFriendsInterestDesc: "Находите людей с общими хобби и целями",
  connectFriendsStudy: "Партнёры для учёбы",
  connectFriendsStudyDesc: "Найдите партнёров для подготовки к тестам",
  connectFriendsCampus: "Однокурсники",
  connectFriendsCampusDesc: "Знакомьтесь со студентами того же вуза",
  connectFriendsCultural: "Культурный обмен",
  connectFriendsCulturalDesc: "Узнайте о разных культурах",

  // Mock Interviews page
  mockInterviewsTitle: "Тренировочные интервью",
  mockInterviewsDesc: "Подготовка к собеседованиям при поступлении",
  mockInterviewsIntro: "Готовьтесь к интервью с ИИ-тренером. Получайте обратную связь в реальном времени и отслеживайте свой прогресс.",
  mockInterviewsAi: "ИИ-интервьюер",
  mockInterviewsAiDesc: "Тренировка с реалистичными вопросами",
  mockInterviewsFeedback: "Обратная связь",
  mockInterviewsFeedbackDesc: "Мгновенный анализ ваших ответов",
  mockInterviewsBank: "Банк вопросов",
  mockInterviewsBankDesc: "Коллекции вопросов для разных университетов",
  mockInterviewsTrack: "Отслеживание прогресса",
  mockInterviewsTrackDesc: "Отслеживайте улучшения между сессиями",
  mockInterviewsGeneral: "Общее собеседование",
  mockInterviewsTechnical: "Техническое интервью",
  mockInterviewsScholarship: "Стипендиальное интервью",
  mockInterviewsPortfolio: "Обзор портфолио",

  // Concierge Support page
  conciergeSupportTitle: "Персональная поддержка",
  conciergeSupportDesc: "Премиум-сопровождение на каждом этапе",
  conciergeSupportIntro: "Получите персонального консультанта. От выбора университета до визы — мы направляем вас на каждом шагу.",
  conciergeSupportPriority: "Приоритетная поддержка",
  conciergeSupportPriorityDesc: "Быстрые ответы без ожидания",
  conciergeSupportAdvisor: "Личный консультант",
  conciergeSupportAdvisorDesc: "Персональный эксперт для вашего случая",
  conciergeSupportDocReview: "Проверка документов",
  conciergeSupportDocReviewDesc: "Экспертная проверка всех документов",
  conciergeSupportTracking: "Отслеживание заявок",
  conciergeSupportTrackingDesc: "Статус ваших заявок в реальном времени",

  // English page
  englishTitle: "Подготовка по английскому",
  englishDesc: "Подготовка к IELTS, TOEFL и академическому английскому",
  englishIntro: "Улучшите навыки английского для поступления. Практикуйте чтение, письмо, аудирование и говорение.",
  englishIelts: "Подготовка к IELTS",
  englishIeltsDesc: "Полные тесты и стратегии",
  englishToefl: "Подготовка к TOEFL",
  englishToeflDesc: "Практика по секциям и советы",
  englishAcademic: "Академический английский",
  englishAcademicDesc: "Навыки письма, чтения и презентаций",
  englishSpeaking: "Практика речи",
  englishSpeakingDesc: "Разговорные упражнения с ИИ",
  englishReading: "Чтение",
  englishWriting: "Письмо",
  englishListening: "Аудирование",
  englishSpeakingSkill: "Говорение",

  // Math page
  mathTitle: "Подготовка по математике",
  mathDesc: "Подготовка к SAT, GRE и университетской математике",
  mathIntro: "Укрепите навыки математики с управляемой практикой. Алгебра, анализ, статистика и стратегии решения задач.",
  mathSat: "SAT / ACT математика",
  mathSatDesc: "Задачи и стратегии подготовки к тесту",
  mathAdvanced: "Продвинутые темы",
  mathAdvancedDesc: "Математический анализ, линейная алгебра и другое",
  mathPractice: "Практические задачи",
  mathPracticeDesc: "Тысячи задач с пошаговыми решениями",
  mathProgress: "Отслеживание прогресса",
  mathProgressDesc: "Отслеживайте успехи по всем темам",
  mathAlgebra: "Алгебра",
  mathCalculus: "Матанализ",
  mathStatistics: "Статистика",
  mathGeometry: "Геометрия",

  // AI Literacy page
  aiLiteracyTitle: "ИИ-грамотность",
  aiLiteracyDesc: "Научитесь эффективно использовать ИИ-инструменты",
  aiLiteracyIntro: "Изучите основы ИИ, промпт-инженерию и этичное использование ИИ в учёбе и профессии.",
  aiLiteracyFundamentals: "Основы ИИ",
  aiLiteracyFundamentalsDesc: "Ключевые концепции искусственного интеллекта",
  aiLiteracyPrompt: "Промпт-инженерия",
  aiLiteracyPromptDesc: "Создавайте эффективные запросы к ИИ",
  aiLiteracyData: "Работа с данными",
  aiLiteracyDataDesc: "Понимание и работа с данными",
  aiLiteracyEthics: "Этика ИИ",
  aiLiteracyEthicsDesc: "Ответственное использование ИИ в учёбе",

  // Get Courses page
  getCoursesTitle: "Каталог курсов",
  getCoursesDesc: "Курсы для подготовки к тестам и развития навыков",
  getCoursesIntro: "Откройте для себя курсы для подготовки к поступлению. От тестов до разговорных навыков.",
  getCoursesVideo: "Видеолекции",
  getCoursesVideoDesc: "Учитесь у экспертов в своём темпе",
  getCoursesInteractive: "Интерактивные упражнения",
  getCoursesInteractiveDesc: "Практика с практическими заданиями",
  getCoursesCertificate: "Сертификаты",
  getCoursesCertificateDesc: "Получайте сертификаты для портфолио",
  getCoursesSelfPaced: "Свой темп",
  getCoursesSelfPacedDesc: "Учитесь по своему расписанию",
  getCoursesTestPrep: "Подготовка к тестам",
  getCoursesLanguage: "Языковые курсы",
  getCoursesSkills: "Мягкие навыки",
  getCoursesAcademic: "Академическое письмо",

  // Essay Writing page
  essayWritingTitle: "Написание эссе",
  essayWritingDesc: "Научитесь писать убедительные эссе",
  essayWritingIntro: "Освойте искусство написания эссе с шаблонами, ИИ-рекомендациями и советами для конкретных университетов.",
  essayWritingTemplates: "Шаблоны эссе",
  essayWritingTemplatesDesc: "Проверенные структуры для разных типов эссе",
  essayWritingAi: "ИИ-рекомендации",
  essayWritingAiDesc: "Умные предложения для улучшения текста",
  essayWritingPeer: "Взаимная проверка",
  essayWritingPeerDesc: "Получайте отзывы от других абитуриентов",
  essayWritingUniTips: "Советы по университетам",
  essayWritingUniTipsDesc: "Рекомендации для конкретных университетов",

  // Contact Premium page
  contactPremiumTitle: "Связаться с поддержкой",
  contactPremiumDesc: "Обратитесь в нашу команду поддержки",
  contactPremiumIntro: "Есть вопросы? Наша команда поддержки готова помочь вам с поступлением, аккаунтом и вопросами платформы.",
  contactPremiumPriority: "Приоритетный ответ",
  contactPremiumPriorityDesc: "Быстрые ответы от нашей команды",
  contactPremiumVideo: "Видеоконсультации",
  contactPremiumVideoDesc: "Запишитесь на видеозвонок",
  contactPremiumDoc: "Помощь с документами",
  contactPremiumDocDesc: "Помощь с документами и заявками",
  contactPremiumTeam: "Экспертная команда",
  contactPremiumTeamDesc: "Поддержка от опытных консультантов",
  contactPremiumEmail: "Поддержка по email",
  contactPremiumEmailDesc: "Отправьте сообщение и получите ответ в течение 24 часов",
  contactPremiumChat: "Онлайн-чат",
  contactPremiumChatDesc: "Общайтесь с нашей командой в реальном времени",
  contactPremiumCall: "Запланировать звонок",
  contactPremiumCallDesc: "Запишитесь на индивидуальный звонок с консультантом",
  contactPremiumContactUs: "Связаться с нами",
  contactPremiumChannels: "Каналы связи",

  // Dream University page
  dreamUniTitle: "Университет мечты",
  dreamUniDesc: "Планируйте путь к университету мечты",
  dreamUniIntro: "Установите целевые университеты, отслеживайте дедлайны и контролируйте прогресс на пути к поступлению.",
  dreamUniGoals: "Отслеживание целей",
  dreamUniGoalsDesc: "Ставьте и отслеживайте вехи поступления",
  dreamUniDeadlines: "Напоминания о сроках",
  dreamUniDeadlinesDesc: "Не пропустите ни одного дедлайна",
  dreamUniTimeline: "Хроника прогресса",
  dreamUniTimelineDesc: "Визуализируйте путь от начала до зачисления",
  dreamUniChecklist: "Чек-лист заявки",
  dreamUniChecklistDesc: "Отслеживайте каждый документ и требование",

  // Search Scholarships page
  searchScholarshipsTitle: "Поиск стипендий",
  searchScholarshipsDesc: "Найдите стипендии и возможности финансирования",
  searchScholarshipsIntro: "Изучите тысячи стипендий для студентов из Центральной Азии. Фильтруйте по стране, специальности, сумме и дедлайну.",
  searchScholarshipsType: "По типу",
  searchScholarshipsTypeDesc: "По заслугам, потребности, стране и другим критериям",
  searchScholarshipsCountry: "По стране",
  searchScholarshipsCountryDesc: "Фильтр стипендий по стране назначения",
  searchScholarshipsDeadline: "Календарь дедлайнов",
  searchScholarshipsDeadlineDesc: "Отслеживайте сроки подачи на стипендии",
  searchScholarshipsEligibility: "Проверка соответствия",
  searchScholarshipsEligibilityDesc: "Быстрая проверка вашей пригодности",

  // Profile page
  profileTitle: "Мой профиль",
  profileDesc: "Управление настройками аккаунта",
  profileChangePhoto: "Изменить фото",
  profileFullName: "Полное имя",
  profileEmail: "Электронная почта",
  profilePhone: "Телефон",
  profileLocation: "Местоположение",
  profileApplications: "Заявки",
  profileScholarships: "Стипендии",
  profileViews: "Просмотры профиля",
  profilePremium: "Премиум участник",
  profilePremiumDesc: "У вас есть доступ ко всем премиум функциям",
  profilePremiumMatch: "Безлимитный подбор университетов",
  profilePremiumSupport: "Приоритетная поддержка заявок",
  profilePremiumAlerts: "Эксклюзивные уведомления о стипендиях",
  profilePremiumMentor: "Прямой доступ к менторам",
  profileSave: "Сохранить изменения",
  profileLogout: "Выйти",

  // Dashboard
  dashMain: "Главная",
  dashDreamUniversity: "Университет мечты",
  dashSearchUniversities: "Поиск университетов",
  dashFavoriteUniversities: "Избранные университеты",
  dashSearchFields: "Поиск направлений",
  dashSearchPrograms: "Поиск программ",
  dashFavoritePrograms: "Избранные программы",
  dashSearchScholarships: "Поиск стипендий",
  dashAiMatching: "AI подбор",
  dashMatchUniversities: "Подбор университетов",
  dashMatchScholarships: "Подбор стипендий",
  dashSimilarStudents: "Похожие студенты",
  dashCommunity: "Сообщество",
  dashConnectFriends: "Найти друзей",
  dashAlumniMentors: "Менторы-выпускники",
  dashPremiumServices: "Премиум сервисы",
  dashEssayReviews: "Проверка эссе",
  dashMockInterviews: "Пробные интервью",
  dashConciergeSupport: "Консьерж поддержка",
  dashLearning: "Обучение и курсы",
  dashGetCourses: "Получить курсы",
  dashMath: "Математика",
  dashEnglish: "Английский",
  dashEssayWriting: "Написание эссе",
  dashAiLiteracy: "AI грамотность",
  dashDashboard: "Панель",
  dashTagline: "Ваш путь в университет начинается здесь",
  dashSendInfo: "Отправить данные и получить Премиум",
  dashJoinCommunity: "Присоединиться к сообществу",
  dashLogout: "Выйти",
  dashNotifications: "Уведомления",
  dashProfile: "Профиль",

  appTimelineTitle: "Таймлайн заявок",
  appTimelineDesc: "Отслеживайте дедлайны и прогресс заявок",
  appTimelineFeature1: "Отслеживание дедлайнов",
  appTimelineFeature1Desc: "Умные напоминания о дедлайнах подачи заявок",
  appTimelineFeature2: "Мониторинг прогресса",
  appTimelineFeature2Desc: "Статус заявок во все университеты на одном экране",
  appTimelineFeature3: "Планирование этапов",
  appTimelineFeature3Desc: "Планируйте от подготовки к тестам до подачи на визу",
  appTimelineFeature4: "Синхронизация календаря",
  appTimelineFeature4Desc: "Синхронизируйте дедлайны с вашим календарём",
  appTimelineCta: "Начать отслеживание",

  myDocsTitle: "Мои документы",
  myDocsDesc: "Управляйте документами и транскриптами",
  myDocsFeature1: "Хранение документов",
  myDocsFeature1Desc: "Безопасное хранение транскриптов, эссе и рекомендаций",
  myDocsFeature2: "Контроль версий",
  myDocsFeature2Desc: "Управление изменениями и черновиками эссе",
  myDocsFeature3: "Быстрая отправка",
  myDocsFeature3Desc: "Делитесь документами с наставниками для проверки",
  myDocsFeature4: "Чеклист документов",
  myDocsFeature4Desc: "Отслеживайте необходимые документы для каждого вуза",
  myDocsCta: "Загрузить документы",

  careerAnalysisTitle: "Анализ карьерного пути",
  careerAnalysisDesc: "Анализируйте карьерные возможности",
  careerAnalysisFeature1: "Обзор отраслей",
  careerAnalysisFeature1Desc: "Тренды рынка и данные о зарплатах по отраслям",
  careerAnalysisFeature2: "Карта навыков",
  careerAnalysisFeature2Desc: "Соотнесите навыки с востребованными вакансиями",
  careerAnalysisFeature3: "Сравнение путей",
  careerAnalysisFeature3Desc: "Сравнивайте карьерные пути с прогнозами роста",
  careerAnalysisFeature4: "Постановка целей",
  careerAnalysisFeature4Desc: "Ставьте карьерные цели и отслеживайте прогресс",
  careerAnalysisCta: "Анализировать карьеру",

  internshipsTitle: "Подбор стажировок",
  internshipsDesc: "Найдите стажировки, соответствующие вашим целям",
  internshipsFeature1: "Умный подбор",
  internshipsFeature1Desc: "ИИ подберёт релевантные стажировки для вас",
  internshipsFeature2: "Трекер заявок",
  internshipsFeature2Desc: "Отслеживайте заявки на стажировки в одном месте",
  internshipsFeature3: "Исследование компаний",
  internshipsFeature3Desc: "Подробные профили компаний, предлагающих стажировки",
  internshipsFeature4: "Развитие навыков",
  internshipsFeature4Desc: "Определите навыки для целевых стажировок",
  internshipsCta: "Найти стажировки",

  mastersTitle: "Подбор магистратуры",
  mastersDesc: "Изучайте магистерские программы по всему миру",
  mastersFeature1: "Поиск программ",
  mastersFeature1Desc: "Магистерские программы в разных университетах мира",
  mastersFeature2: "Условия приёма",
  mastersFeature2Desc: "Требования к поступлению и уровень конкурса",
  mastersFeature3: "Варианты финансирования",
  mastersFeature3Desc: "Стипендии и ассистентуры для магистрантов",
  mastersFeature4: "Карьерные результаты",
  mastersFeature4Desc: "Статистика трудоустройства выпускников программ",
  mastersCta: "Изучить программы",

  uniReelsTitle: "Видео университетов",
  uniReelsDesc: "Смотрите туры по кампусам и видео студенческой жизни",
  uniReelsFeature1: "Туры по кампусам",
  uniReelsFeature1Desc: "Виртуальные туры по кампусам со всего мира",
  uniReelsFeature2: "Истории студентов",
  uniReelsFeature2Desc: "Рассказы студентов о своём опыте обучения",
  uniReelsFeature3: "Гиды по городам",
  uniReelsFeature3Desc: "Познакомьтесь с городами, где находятся топ-вузы",
  uniReelsFeature4: "Обзоры мероприятий",
  uniReelsFeature4Desc: "Видео дней открытых дверей и кампусных событий",
  uniReelsCta: "Смотреть",

  privacyTitle: "Панель конфиденциальности",
  privacyDesc: "Управляйте настройками приватности и данными",
  privacyFeature1: "Контроль данных",
  privacyFeature1Desc: "Просматривайте и управляйте собранными данными",
  privacyFeature2: "Настройки видимости",
  privacyFeature2Desc: "Контролируйте, кто видит ваш профиль",
  privacyFeature3: "Экспорт данных",
  privacyFeature3Desc: "Скачайте копию всех ваших личных данных",
  privacyFeature4: "Удаление аккаунта",
  privacyFeature4Desc: "Полное удаление аккаунта и всех связанных данных",
  privacyCta: "Проверить настройки",

  studyTogetherTitle: "Учимся вместе",
  studyTogetherDesc: "Находите единомышленников и учебные группы",
  studyTogetherFeature1: "Подбор групп",
  studyTogetherFeature1Desc: "Найдите партнёров с похожими целями и расписанием",
  studyTogetherFeature2: "Живые сессии",
  studyTogetherFeature2Desc: "Учебные сессии в реальном времени с учениками по всему миру",
  studyTogetherFeature3: "Обмен материалами",
  studyTogetherFeature3Desc: "Делитесь заметками, материалами и стратегиями подготовки",
  studyTogetherFeature4: "Прогресс вместе",
  studyTogetherFeature4Desc: "Отслеживайте общие цели и мотивируйте друг друга",
  studyTogetherCta: "Найти партнёров",
};

export default ru;
