// Tajik (Тоҷикӣ)
// Missing keys fall back to Russian (the audience's lingua franca), then English for
// any key Russian also lacks. Native Tajik keys below override both.
import en from "./en";
import ru from "./ru";

const tg = {
  ...en,
  ...ru,

  // Navigation / common
  home: "Саҳифаи асосӣ",
  search: "Ҷустуҷӯ",
  dashboard: "Лавҳаи идоракунӣ",
  profile: "Профил",
  settings: "Танзимот",
  language: "Забон",
  selectLanguage: "Забонро интихоб кунед",
  scholarships: "Стипендияҳо",
  loading: "Боргузорӣ...",
  required: "ҳатмист",

  // Dashboard nav
  dashMain: "АСОСӢ",
  dashDashboard: "Лавҳаи асосӣ",
  dashDreamUniversity: "Донишгоҳи орзу",
  dashSearchUniversities: "Донишгоҳҳо",
  dashFavoriteUniversities: "Дилхоҳҳо: донишгоҳҳо",
  dashSearchFields: "Соҳаҳо",
  dashSearchPrograms: "Барномаҳо",
  dashFavoritePrograms: "Дилхоҳҳо: барномаҳо",
  dashSearchScholarships: "Стипендияҳо",
  dashNavAiTools: "АБЗОРҲОИ AI",
  dashMatchUniversities: "Интихоби донишгоҳ",
  dashMatchScholarships: "Интихоби стипендия",
  dashSimilarStudents: "Донишҷӯёни монанд",
  dashNavFriendsAndMentors: "ДӮСТОН ВА МУРАББИЁН",
  dashConnectFriends: "Дӯстон",
  dashNavSectionContactPremium: "ТАМОС",
  dashContactPremium: "Тамос",
  dashSendInfo: "Маълумот фиристед — Premium гиред",
  dashJoinCommunity: "Ба ҷамоаи мо ҳамроҳ шавед",
  dashTagline: "Сафари донишгоҳии шумо аз ин ҷо оғоз меёбад",
  dashWelcomeBackPrefix: "Хуш омадед,",
  dashNotifications: "Огоҳиномаҳо",
  dashProfile: "Профил",
  dashDefaultDisplayName: "Ном Насаб",

  // Auth
  loginTitle: "Ба барнома ворид шавед",
  registerTitle: "Сабт ном кардан",

  // SendInfo
  sendInfoPageTitle: "Маълумот фиристед — Premium гиред",
  sendInfoOfferHeadline: "7 рӯз Premium РОЙГОН!",
  sendInfoOfferBody:
    "Дархост дар бораи донишгоҳ ё стипендия фиристед — фавран 7 рӯз Premium гиред.",
  sendInfoTabUniversity: "Дар бораи донишгоҳ",
  sendInfoTabScholarship: "Дар бораи стипендия",
  sendInfoTabApplication: "Кӯмак барои ариза",
  sendInfoTabMeeting: "Вохӯрӣ таъин кардан",
  sendInfoTabOther: "Дархости дигар",
  sendInfoFieldFullName: "Ном ва насаб",
  sendInfoFieldEmail: "Почтаи электронӣ",
  sendInfoFieldPhone: "Телефон",
  sendInfoFieldUniversity: "Донишгоҳ",
  sendInfoFieldUniversityInterest: "Донишгоҳи мавриди таваҷҷӯҳ",
  sendInfoFieldProgram: "Барнома",
  sendInfoFieldProgramMajor: "Барнома / ихтисос",
  sendInfoFieldGpa: "Бали миёна (GPA)",
  sendInfoFieldAdditional: "Маълумоти иловагӣ",
  sendInfoFieldScholarshipName: "Номи стипендия",
  sendInfoFieldAchievements: "Дастовардҳои таҳсилӣ",
  sendInfoFieldDeadline: "Муҳлати ариза",
  sendInfoFieldHelp: "Чӣ гуна кӯмак лозим аст?",
  sendInfoFieldMeetingType: "Намуди вохӯрӣ",
  sendInfoFieldPreferredDate: "Санаи дилхоҳ",
  sendInfoFieldPreferredTime: "Вақти дилхоҳ",
  sendInfoFieldNotes: "Эзоҳҳои иловагӣ",
  sendInfoFieldSubject: "Мавзӯъ",
  sendInfoFieldMessage: "Паём",
  sendInfoPhFullName: "Ном ва насабатонро ворид кунед",
  sendInfoPhEmail: "Почтаи электрониатонро ворид кунед",
  sendInfoPhPhone: "Рақами телефонатонро ворид кунед",
  sendInfoPhUniversityInterest: "Кадом донишгоҳ ҷолиб аст?",
  sendInfoPhProgramInterest: "Кадом барнома ҷолиб аст?",
  sendInfoPhGpa: "GPA-ро ворид кунед",
  sendInfoPhGoals: "Дар бораи ҳадафҳоятон бигӯед...",
  sendInfoPhScholarship: "Кадом стипендия ҷолиб аст?",
  sendInfoPhUniversityOpt: "Донишгоҳи марбут (агар бошад)",
  sendInfoPhAchievements: "Дастовардҳоятонро навишта диҳед...",
  sendInfoPhUniversityRequired: "Кадом донишгоҳ?",
  sendInfoPhProgramRequired: "Кадом барнома?",
  sendInfoPhHelp: "Кадом кӯмак лозим — нависед...",
  sendInfoPhSubject: "Дархостатон дар бораи чист?",
  sendInfoPhContact: "Чӣ гуна мо кӯмак расонда метавонем?",
  sendInfoPhNotes: "Ҳар маълумоти иловагӣ...",
  sendInfoMeetingSelect: "Намуди вохӯриро интихоб кунед",
  sendInfoMeetingConsult: "Машварати умумӣ",
  sendInfoMeetingAppReview: "Аризаро санҷидан",
  sendInfoMeetingScholarship: "Машварат оид ба стипендия",
  sendInfoMeetingCareer: "Машварати касбӣ",
  sendInfoSubmit: "Фиристодан — Premium гирифтан",
  sendInfoSubmitting: "Фиристода мешавад...",
  sendInfoError: "Дархости шумо фиристода нашуд. Пайвастро санҷед ва дубора кӯшиш кунед.",
  sendInfoSuccessTitle: "Маълумот бомуваффақият фиристода шуд!",
  sendInfoSuccessBody:
    "Барои дархости шумо ташаккур. Дастаи мо маълумотро дида мебарояд ва ба зудӣ бо шумо тамос мегирад.",
  sendInfoPremiumActivated: "Дастрасии Premium фаъол шуд!",
  sendInfoPremiumActivatedBody: "Шумо ба функсияҳои Premium 7 рӯз дастрасӣ доред.",
  sendInfoBackToDashboard: "Бозгашт ба лавҳаи идоракунӣ",
  sendInfoTitleBack: "Бозгашт ба лавҳаи идоракунӣ",
  smartMatch: "Интихоби ҳушёр",
  aboutCoreAccess: "Дастрасии асосӣ дохилкарда шудааст",
  aboutGlobal: "Ҷаҳонӣ",
  contactLabelEmail: "Почтаи электронӣ",
  contactLabelTopic: "Мавзӯъ",

  // Login page
  loginSubtitle: "Хуш омадед! Ба ҳисоби худ ворид шавед.",
  loginEmailLabel: "Почтаи электронӣ",
  loginEmailPlaceholder: "Почтаи электрониатонро ворид кунед",
  loginPasswordLabel: "Рамз",
  loginPasswordPlaceholder: "Рамзи худро ворид кунед",
  loginSubmit: "Ворид шудан",
  loginSubmitting: "Воридшавӣ...",
  loginNoAccount: "Ҳисоб надоред?",
  loginSignUpHere: "Дар ин ҷо сабт шавед",
  loginContinueAsGuest: "Чун меҳмон давом додан",
  loginGuestSuffix: "— бе воридшавӣ, барномаро санҷидан.",
  loginFailedMessage: "Воридшавӣ ноком шуд. Почта ва рамзи худро санҷед.",

  // Register page
  registerSubtitle: "Ҳисоб созед — кишвари худро интихоб кунед.",
  registerFirstName: "Ном",
  registerLastName: "Насаб",
  registerEmail: "Почтаи электронӣ",
  registerEmailPlaceholder: "you@example.com",
  registerPassword: "Рамз",
  registerCountry: "Кишвар",
  registerCountriesLoading: "Кишварҳо бор мешаванд...",
  registerSelectCountry: "Кишвари худро интихоб кунед",
  registerCountryHint: "Барои сохтани ҳисоб ҳатмист.",
  registerNoCountriesHint:
    "Кишварҳо бор нашуданд. Backend-ро шурӯъ кунед ва тасдиқ кунед, ки дар базаи маълумот кишварҳо ҳастанд, ё дар поён «Чун меҳмон давом додан»-ро истифода кунед.",
  registerSubmit: "Ҳисоб сохтан",
  registerSubmitting: "Ҳисоб сохта мешавад...",
  registerHaveAccount: "Аллакай ҳисоб доред?",
  registerLogIn: "Ворид шудан",
  registerGuestSuffix: "— бе сабтиномӣ, барномаро санҷидан.",
  registerSelectCountryError: "Лутфан кишварро интихоб кунед.",
  registerFillAllError: "Лутфан ҳамаи майдонҳоро пур кунед.",
  registerFailedError: "Сабт ноком шуд.",

  // PublicHome
  publicSeeHowItWorks: "Дар YouTube бубинед, ки чӣ гуна кор мекунад",
  publicAboutUs: "Дар бораи мо",
  publicSupportQr: "QR-и дастгирӣ",
  publicFaq: "Саволҳои зуд-зуд додашаванда",
  publicContactUs: "Бо мо тамос гиред",
  publicSendMessage: "Ба мо паём фиристед",
  publicMessageSent: "Ташаккур! Паёми шумо фиристода шуд.",
  publicFullName: "Ном ва насаб",
  publicFullNamePh: "Ном ва насабатонро ворид кунед",
  publicTopicPh: "Чӣ гуна кӯмак лозим аст?",
  publicMessageLabel: "Паём",
  publicMessagePh: "Паёматонро нависед",
  publicFooterPrivacy: "Махфият",
  publicFooterTerms: "Шартҳо",
  publicFooterContact: "Тамос",
  publicStudentSupport: "Дастгирии донишҷӯён",
  publicUnisWorldwide: "Донишгоҳҳои ҷаҳон",
  publicSupportNumber: "Рақами дастгирӣ",
  publicQrPlaceholder: "QR-и дастгириро ин ҷо илова кунед",
  publicAboutLead:
    "ilmi ба донишҷӯёни ҷаҳон ёрӣ медиҳад, ки тавассути AI-интихоб донишгоҳ ва стипендияҳои дуруст ёбанд. Маъмурияти мо — таҳсилоти олиро ба ҳама дастрас сохтан.",
  publicAboutCopy:
    "Дастрасии асосӣ ба ҷустуҷӯи донишгоҳҳо ва стипендияҳо дохилкарда шудааст, бо абзорҳои амалӣ барои истифодаи фаврӣ.",
  publicMainServices: "Хадамоти асосӣ",

  searchUniNamePlaceholder: "Ҷустуҷӯ бо номи донишгоҳ ё коллеҷ…",
  searchUniClearAll: "Ҳамаро тоза кардан",
  searchUniTuitionRange: "Маблағи таҳсил дар як сол (€)",
  searchUniMatching: "Муассисаҳои мувофиқ",
  searchUniLoadingList: "Донишгоҳҳо бор мешаванд...",

  uniDetailLoadingTitle: "Боргузорӣ...",
  uniDetailLoadingBody: "Маълумоти донишгоҳ бор мешавад...",
  uniDetailNotFound: "Муассиса ёфт нашуд",

  // Search Universities options
  searchUniPopularUnder10k: "То €10 ҳазор / сол",
  searchUniPopularUnder5k: "≤ €5 ҳазор / сол",
  searchUniPopularEnglish: "Бо забони англисӣ",
  searchUniPopularEurope: "Аврупо",
  searchUniPopularBusiness: "Тиҷорат ва ҳуқуқ",
  searchUniPopularMedicine: "Тиб ва илм",
  searchUniPopularArts: "Санъат ва дизайн",
  searchUniInstAll: "Ҳамаро",
  searchUniInstUniversities: "Танҳо донишгоҳҳо",
  searchUniInstColleges: "Танҳо коллеҷҳо",
  searchUniDegreeAll: "Ҳамаи сатҳҳо",
  searchUniDegreeAssociate: "Ассотсиат",
  searchUniDegreeDiploma: "Диплом",
  searchUniDegreeBachelor: "Бакалавр",
  searchUniDegreeMaster: "Магистр",
  searchUniDegreePhd: "PhD / Докторантура",
  searchUniLangAny: "Ҳар забон",
  searchUniLangEnglish: "Англисӣ",
  searchUniLangGerman: "Олмонӣ",
  searchUniLangFrench: "Фаронсавӣ",
  searchUniLangSpanish: "Испанӣ",
  searchUniLangDutch: "Ҳолландӣ",
  searchUniLangCatalan: "Каталанӣ",
  searchUniAllCountries: "Ҳамаи кишварҳо",
  searchUniAllFields: "Ҳамаи соҳаҳо",
  searchUniAllCities: "Ҳамаи шаҳрҳо дар ин кишвар",

  searchResultOne: "натиҷа",
  searchResultMany: "натиҷаҳо",
  searchUniNameLabel: "Ҷустуҷӯ бо номи муассиса",
  searchUniPopularHeading: "Филтрҳои маъмул",
  searchUniInstTypeLabel: "Намуди муассиса",
  searchUniCountryLabel: "Кишвар",
  searchUniCityLabel: "Шаҳр / минтақа",
  searchUniFieldLabel: "Соҳа",
  searchUniDegreeLabel: "Сатҳи дараҷа",
  searchUniLanguageLabel: "Забони таҳсил",
  searchUniMin: "Мин",
  searchUniMax: "Макс",

  featureSmartMatchTitle: "Интихоби ҳушёри донишгоҳҳо",
  featureSmartMatchDesc:
    "AI профил, ҳадафҳо ва афзалиятҳои шуморо таҳлил карда, донишгоҳҳои мувофиқро тавсия медиҳад.",
  featureScholarshipTitle: "Стипендияҳо ва дастгирии молиявӣ",
  featureScholarshipDesc:
    "Барои банақшагирии буҷети таҳсилот стипендияҳо, грантҳо ва кӯмакҳоро ёбед.",
  featureInsightsTitle: "Таҳлили қабул",
  featureInsightsDesc:
    "Тамоюлҳои қабул, тафсилоти барномаҳо ва натиҷаҳоро муқоиса карда, қарорҳои асоснок қабул кунед.",
  featureGlobalTitle: "Дастрасӣ ба донишгоҳҳои ҷаҳон",
  featureGlobalDesc:
    "Донишгоҳҳоро дар якчанд кишвар бо маълумоти равшани барномаҳо ва қабул тадқиқ кунед.",
  featureAnyDeviceTitle: "Дастрасии осон аз ҳар дастгоҳ",
  featureAnyDeviceDesc:
    "ilmi-ро дар мобайл ё компютер истифода кунед — мувофиқатҳо ва қадамҳои худро пайгирӣ кунед.",
  featureAdvisorTitle: "Дастгирии маслиҳатчиён",
  featureAdvisorDesc:
    "Аз маслиҳатчиёни таҷрибадор оид ба қабул, ариза ва банақшагирӣ кӯмаки амалӣ гиред.",

  programsAllCategories: "Ҳамаи категорияҳо",
  programsAllCountries: "Ҳамаи кишварҳо",
  programsTuitionFree: "Ройгон / давлатӣ",
  searchUniLangItalian: "Италянӣ",
  searchUniLangJapanese: "Японӣ",
  searchUniLangKorean: "Кореягӣ",

  chartUnis: "Донишгоҳҳо",
  chartScholarshipsLabel: "Стипендияҳо",
  monthJan: "Янв",
  monthFeb: "Фев",
  monthMar: "Мар",
  monthApr: "Апр",
  monthMay: "Май",
  monthJun: "Июн",

  heroTitleLine2: "Роҳнамо барои сафари таҳсилии шумо",
  heroDescription2:
    "Дар як платформаи оддӣ нишондодҳои равшан оид ба донишгоҳҳо, стипендияҳо, қабул ва барномаҳои магистр.",
  heroCtaPrimary: "Шурӯъ кардан",
  heroCtaSecondary: "Чӣ гуна кор мекунад",

  faqQ1: "Истифодаи ilmi пулакӣ аст?",
  faqA1:
    "Хусусиятҳои асосӣ — интихоби донишгоҳ, ҷустуҷӯи стипендия ва нишондодҳои калидӣ — ройгон. Дастгирии Premium ихтиёрӣ ва пулакӣ.",
  faqQ2: "Раванди интихоб чӣ гуна кор мекунад?",
  faqA2:
    "AI ҳадафҳо, профил ва афзалиятҳои шуморо таҳлил карда, рӯйхати дараҷабандишудаи донишгоҳҳо ва стипендияҳои мувофиқро нишон медиҳад.",
  faqQ3: "Кадом кишварҳо ва донишгоҳҳо дохил карда шудаанд?",
  faqA3:
    "Мо донишгоҳҳо ва имкониятҳои стипендиявиро дар бисёр кишварҳо дохил мекунем. Шумо метавонед бо кишвар, барнома ва имкониятҳои маблағгузорӣ филтр кунед.",
  faqQ4: "Чӣ гуна ман метавонам ilmi-ро дастгирӣ кунам?",
  faqA4:
    "Шумо метавонед моро тавассути садақаҳои дар бахши «Дар бораи мо» нишондодашуда дастгирӣ кунед. Дастгирии шумо ба мо имкон медиҳад дастрасии асосиро барои ҳамаи донишҷӯён нигоҳ дорем.",

  searchFieldDefaultPlaceholder: "Ҷустуҷӯи муассисаҳо",
  selectFieldDefaultPlaceholder: "Интихоб кунед",
  skyToggleToLight: "Ба темаи равшан гузаштан",
  skyToggleToDark: "Ба темаи торик гузаштан",

  errFailedLoadFavorites: "Боргузории дилхоҳҳо ноком шуд.",
  errFailedRemoveFavorite: "Аз дилхоҳҳо ҷудо кардан ноком шуд.",
};

export default tg;
