// Tajik (Тоҷикӣ)
// Fully translated — every key has a native value. Base spread of en provides an
// English (not Russian) safety net for any key that might be added later.
import en from "./en";

const tg = {
  ...en,
essayWritingTitle: "Навиштани иншо",

home: "Саҳифаи асосӣ",
search: "Ҷустуҷӯ",
dashboard: "Лавҳаи идоракунӣ",
profile: "Профил",
settings: "Танзимот",
language: "Забон",
selectLanguage: "Забонро интихоб кунед",
languageNote: "Танзимоти забон барои ташрифи оянда нигоҳ дошта мешавад",
scholarships: "Стипендияҳо",
heroBadge: "Интихоби AI",
heroTitle: "Донишгоҳи мукаммали худро ёбед",
heroSubtitle: "Донишгоҳҳои ҷаҳонро кашф кунед",
heroDescription: "Донишгоҳҳои ҷаҳонро кашф кунед, ки ба ҳадафҳои таҳсилӣ, буҷет ва афзалиятҳои шумо мувофиқанд",
heroStudents: "Донишҷӯёни ёридидашуда",
heroUniversities: "Донишгоҳҳо",
heroSuccessRate: "Муваффақият",
heroCta: "Сафарро оғоз кунед",
heroDemo: "Намоишро бубинед",
searchPlaceholder: "Ҷустуҷӯи донишгоҳҳо, барномаҳо ё ҷойҳо...",
searchTitle: "Донишгоҳи орзуи худро ёбед",
searchSubtitle: "Аз рӯи ҷой, барнома, буҷет ва дигар меъёрҳо филтр кунед",
searchFilters: "Филтрҳо",
searchResults: "Натиҷаҳо",
searchLocation: "Ҷойгоҳ",
searchProgram: "Барнома",
searchBudget: "Буҷет",
searchRanking: "Рейтинг",
dashboardTitle: "Лавҳаи шумо",
dashboardWelcome: "Хуш омадед!",
dashboardRecentSearches: "Ҷустуҷӯҳои охирин",
dashboardSavedUniversities: "Донишгоҳҳои нигоҳдошташуда",
dashboardApplications: "Аризаҳо",
dashboardScholarships: "Стипендияҳо",
universityTuition: "Маблағи таҳсил",
universityAcceptanceRate: "Фоизи қабул",
universityPrograms: "Барномаҳо",
universityLearnMore: "Бештар донед",
universityApplyNow: "Ариза диҳед",
scholarshipTitle: "Стипендияҳои беҳтарин",
scholarshipSubtitle: "Имкониятҳои маблағгузорӣ барои таҳсилоти шуморо кашф кунед",
scholarshipMerit: "Аз рӯи дастовард",
scholarshipNeed: "Аз рӯи ниёз",
scholarshipAthletic: "Варзишӣ",
scholarshipAcademic: "Академӣ",
featuredTitle: "Донишгоҳҳои тавсияшуда",
featuredSubtitle: "Муассисаҳои баландрейтинг аз саросари ҷаҳон",
save: "Нигоҳ доштан",
cancel: "Бекор кардан",
edit: "Таҳрир кардан",
delete: "Нест кардан",
apply: "Ариза додан",
view: "Дидан",
learnMore: "Бештар донед",
uniTypeUniversity: "Донишгоҳ",
uniTypeCollege: "Коллеҷ",
notFoundTitle: "Саҳифа ёфт нашуд",
notFoundMessage: "Саҳифаи дархостшуда вуҷуд надорад ё ҷойи он иваз шудааст.",
notFoundBackDashboard: "Бозгашт ба лавҳа",
notFoundBackHome: "Бозгашт ба саҳифаи асосӣ",
errorBoundaryTitle: "Чизе нодуруст рафт",
errorBoundaryMessage: "Хатои ногаҳонӣ саҳифаро қатъ кард. Аз нав боркунӣ одатан ёрӣ мерасонад.",
errorBoundaryReload: "ilmi-ро аз нав боркунӣ кунед",
sessionExpiredMessage: "Сессияи шумо тамом шуд. Лутфан дубора ворид шавед.",
serverUnreachableMessage: "Ба сервер пайваст шуда намешавад. Пайвастро санҷед ва дубора кӯшиш кунед.",
serverErrorMessage: "Дар тарафи мо хато рух дод. Лутфан дубора кӯшиш кунед.",
errorGeneric: "Чизе нодуруст рафт. Лутфан дубора кӯшиш кунед.",
viewAll: "Ҳамаро бубинед",
success: "Муваффақият",
error: "Хато",
loading: "Боргузорӣ...",
noResults: "Натиҷа ёфт нашуд",
deadline: "Муҳлати ариза",
type: "Намуд",
meritBased: "Аз рӯи дастовард",
needBased: "Аз рӯи ниёз",
projectBased: "Лоиҳавӣ",
notifications: "Огоҳиномаҳо",
close: "Пӯшидан",
open: "Кушодан",
light: "Равшан",
dark: "Торик",
switchToLight: "Ба темаи равшан гузаштан",
switchToDark: "Ба темаи торик гузаштан",
email: "Почтаи электронӣ",
password: "Рамз",
firstName: "Ном",
lastName: "Насаб",
phone: "Телефон",
address: "Суроға",
city: "Шаҳр",
country: "Кишвар",
zipCode: "Индекси почтавӣ",
today: "Имрӯз",
yesterday: "Дирӯз",
tomorrow: "Фардо",
thisWeek: "Ин ҳафта",
thisMonth: "Ин моҳ",
thisYear: "Ин сол",
thousand: "ҳз",
million: "млн",
billion: "млрд",
lightMode: "Темаи равшан",
darkMode: "Темаи торик",
toggleTheme: "Тема иваз кардан",
favoriteSave: "Ба дилхоҳҳо илова кунед",
favoriteSaved: "Нигоҳ дошта шуд",
favoriteUniversitiesTitle: "Донишгоҳҳои дилхоҳ",
favoriteUniversitiesDescription: "Рӯйхати донишгоҳҳои нигоҳдошташудаи шумо. Ҳар вақт хостед ҳар яке را хорӣ кунед.",
favoriteUniversitiesEmpty: "Шумо ҳанӯз ягон донишгоҳи дилхоҳ надоред.",
searchNoResults: "Ягон муассиса мувофиқат намекунад.",
searchFieldsTitle: "Ҷустуҷӯ аз рӯи соҳа",
searchFieldsPickField: "Соҳаи таҳсилро интихоб кунед",
searchFieldsClearAll: "Ҳамаро тоза кунед",
searchFieldsSelectedOne: "соҳа интихоб шуд",
searchFieldsSelectedMany: "соҳа интихоб шуд",
searchFieldsSelectPrompt: "Барои дидани донишгоҳҳои мувофиқ як ё якчанд соҳаи боло интихоб кунед.",
searchFieldsDegreeLevel: "Сатҳи дараҷа",
searchFieldsLanguage: "Забони таҳсил",
searchFieldsTuition: "Маблағи таҳсил (€)",
searchFieldsResults: "Донишгоҳҳои мувофиқ",
searchFieldsLoading: "Боргузорӣ...",
searchFieldsViewDetails: "Тафсилот",
searchFieldsAdditionalFilters: "Филтрҳои иловагӣ",
searchFieldsFiltersActive: "фаъол",
searchFieldsRemember: "Интихоби маро дар хотир нигоҳ дор",
searchFieldsCompact: "Намои фишурда",
searchFieldsFull: "Намои пурра",
searchFieldsResultOne: "натиҷа",
searchFieldsResultMany: "натиҷаҳо",
filterAllLevels: "Ҳамаи сатҳҳо",
filterBachelor: "Бакалавр",
filterMaster: "Магистр",
filterPhd: "PhD / Докторантура",
filterAnyLanguage: "Ҳар забон",
tuitionFree: "Ройгон / давлатӣ",
tuitionPerYear: "/ сол",
tuitionMin: "Мин",
tuitionMax: "Макс",
programResultOne: "барнома",
programResultMany: "барнома",
favResultOne: "натиҷа",
favResultMany: "натиҷаҳо",
uniDetailCampusAlt: "кампус",
uniDetailLogoAlt: "логотип",
fundingPerYear: "/сол",
dashLogoHome: "ilmi саҳифаи асосӣ",
fundingSourceAria: "Номи манбаи маблағгузорӣ",
fundingAmountAria: "Маблағи маблағгузорӣ",
fieldDetailBack: "Бозгашт ба соҳаҳо",
fieldDetailUniSingular: "донишгоҳ ин соҳаро пешниҳод мекунад",
fieldDetailUniPlural: "донишгоҳ ин соҳаро пешниҳод мекунанд",
uniDetailPrograms: "Барномаҳои ин донишгоҳ",
fieldUniNotFound: "Донишгоҳ ёфт нашуд",
fieldUniBackToFields: "Бозгашт ба соҳаҳо",
fieldUniBackToResults: "Бозгашт ба натиҷаҳо",
fieldUniSelectedFields: "Соҳаҳои интихобшуда дар ин донишгоҳ",
fieldUniNoMatchingFields: "Дар ин донишгоҳ соҳаи мувофиқ ёфт нашуд.",
fieldUniDegrees: "Дараҷаҳо",
fieldUniLanguages: "Забонҳо",
fieldUniViewFull: "Профили пурраи донишгоҳ",
searchProgramsTitle: "Ҷустуҷӯи барномаҳо",
searchProgramsPlaceholder: "Барномаҳоро бо ном ҷустуҷӯ кунед…",
searchProgramsFilters: "Филтрҳо",
searchProgramsCategory: "Категория",
searchProgramsCountry: "Кишвар",
searchProgramsResults: "Барномаҳо",
programDetailTitle: "Тафсилоти барнома",
programDetailNotFound: "Барнома ёфт нашуд.",
programDetailBack: "Бозгашт ба барномаҳо",
programDetailUniversity: "Донишгоҳ",
programDetailLocation: "Ҷойгиршавӣ",
programDetailDegree: "Дараҷа",
programDetailLanguage: "Забон",
programDetailDuration: "Давомнокӣ",
programDetailTuition: "Маблағи таҳсил",
programDetailDescription: "Тавсиф",
programDetailWebsite: "Ба сайт гузаштан",
favoriteProgramsTitle: "Барномаҳои дилхоҳ",
favoriteProgramsEmpty: "Шумо ҳоло барномаҳои дилхоҳ надоред.",
favoriteProgramsRemove: "Ҳазф кардан",
navFeatures: "Имкониятҳо",
navAbout: "Дар бораи мо",
navFaq: "Саволҳо",
navContact: "Тамос",
navLogin: "Ворид шудан",
navGetStarted: "Шурӯъ кардан",
comingSoon: "Ба зудӣ",
getStarted: "Шурӯъ кардан",
startNow: "Ҳозир шурӯъ кунед",
keyFeatures: "Имкониятҳои асосӣ",
howItWorks: "Чӣ гуна кор мекунад",
popularTopics: "Мавзӯъҳои маъмул",
essayReviewsTitle: "Баррасии иншоҳо",
essayReviewsDesc: "Бозхӯрди касбӣ ба иншоҳои аризаатон гиред",
essayReviewsIntro: "Иншоҳоятонро барои баррасии коршиносон фиристед. Дастаи мо тавзеҳоти муфассал оид ба сохтор, мӯҳтаво, грамматика ва таъсирнокӣ медиҳад.",
essayReviewsAiFeedback: "Таҳлили AI",
essayReviewsAiFeedbackDesc: "Таҳлили фаврии оҳанг, равшанӣ ва таъсир",
essayReviewsStructure: "Таҳлили сохтор",
essayReviewsStructureDesc: "Ҷараёни банд ва нақшаи мантиқии далелҳо",
essayReviewsGrammar: "Грамматика ва услуб",
essayReviewsGrammarDesc: "Санҷиши грамматика, нуқтагузорӣ ва услуб",
essayReviewsTone: "Оҳанг ва овоз",
essayReviewsToneDesc: "Боварӣ ҳосил кунед, ки овози воқеии шумо мешунавад",
essayReviewsPersonalStatement: "Баёноти шахсӣ",
essayReviewsSupplemental: "Иншоҳои иловагӣ",
essayReviewsDiversity: "Баёноти гуногунӣ",
essayReviewsResearchPurpose: "Баёноти мақсад",
essayReviewsSubmitEssay: "Иншо фиристодан",
essayReviewsTurnaround: "Муддат: 24-48 соат",
matchUnisTitle: "Интихоби донишгоҳ",
matchUnisDesc: "Интихоби донишгоҳ бо AI дар асоси профили шумо",
matchUnisIntro: "AI-и мо профил, афзалиятҳо ва ҳадафҳои шуморо таҳлил карда, донишгоҳҳои мувофиқтаринро меёбад. Профили худро пур кунед то натиҷаҳо дақиқтар шаванд.",
matchUnisProfileAnalysis: "Таҳлили профил",
matchUnisProfileAnalysisDesc: "Таҳлили амиқи қувватҳои таҳсилии шумо",
matchUnisCompatibility: "Бали мувофиқат",
matchUnisCompatibilityDesc: "Фоизи мувофиқат аз рӯи омилҳои гуногун",
matchUnisSmartFilter: "Филтрации ҳушёр",
matchUnisSmartFilterDesc: "Филтрҳо мутобиқи афзалиятҳои шумо тағйир меёбанд",
matchUnisRealtime: "Навсозии фаврӣ",
matchUnisRealtimeDesc: "Мувофиқатҳо бо пайдоишии маълумоти нав навсозӣ мешаванд",
matchUnisProfileComplete: "Пурсозии профил",
matchUnisCompleteProfile: "Барои натиҷаҳои беҳтар профили худро пур кунед",
matchScholarshipsTitle: "Интихоби стипендия",
matchScholarshipsDesc: "Стипендияҳои мувофиқи профили шуморо ёбед",
matchScholarshipsIntro: "Стипендияҳоеро кашф кунед, ки шумо барои онҳо ҳуқуқ доред — дар асоси сабти таҳсилӣ, миллият, соҳа ва вазъияти молиявӣ.",
matchScholarshipsEligibility: "Санҷиши ҳуқуқ",
matchScholarshipsEligibilityDesc: "Санҷиши автоматӣ бар асоси меъёрҳои стипендия",
matchScholarshipsDeadlines: "Пайгирии мӯҳлатҳо",
matchScholarshipsDeadlinesDesc: "Мӯҳлати аризаро аз даст надиҳед",
matchScholarshipsGuidance: "Роҳнамоии ариза",
matchScholarshipsGuidanceDesc: "Кӯмаки қадам ба қадам барои ҳар ариза",
matchScholarshipsCalculator: "Калкулятори молиявӣ",
matchScholarshipsCalculatorDesc: "Имкониятҳои умумии маблағгузориро баҳо диҳед",
matchScholarshipsMerit: "Дар асоси хидматҳо",
matchScholarshipsNeed: "Дар асоси ниёз",
matchScholarshipsCountry: "Аз рӯи кишвар",
matchScholarshipsField: "Аз рӯи соҳа",
similarStudentsTitle: "Донишҷӯёни монанд",
similarStudentsDesc: "Бо донишҷӯёни дорои ҳадафҳои якхела пайваст шавед",
similarStudentsIntro: "Донишҷӯёни дорои заминаи таҳсилӣ, донишгоҳҳои мақсаднок ва ҳадафҳои касбии монанд ёбед. Таҷрибаро мубодила кунед.",
similarStudentsMatching: "Мувофиқати профил",
similarStudentsMatchingDesc: "Донишҷӯёни дорои ҳадафҳо ва заминаи монанд ёбед",
similarStudentsGroups: "Гурӯҳҳои таҳсилӣ",
similarStudentsGroupsDesc: "Ба гурӯҳҳо аз рӯи мавзӯъ ҳамроҳ шавед ё созед",
similarStudentsExperience: "Мубодилаи таҷриба",
similarStudentsExperienceDesc: "Таҷрибаи аризаро хонед ва мубодила кунед",
similarStudentsNetwork: "Шабака созед",
similarStudentsNetworkDesc: "Бо дӯстоне пайваст шавед, ки ба донишгоҳҳои монанд мераванд",
alumniMentorsTitle: "Мураббиёни хатмкардагон",
alumniMentorsDesc: "Аз хатмкардагони муваффақ роҳнамоӣ гиред",
alumniMentorsIntro: "Бо хатмкардагоне пайваст шавед, ки хориҷ таҳсил кардаанд ва метавонанд таҷриба, маслиҳат ва роҳнамоии фарҳангӣ диҳанд.",
alumniMentorsCareer: "Роҳнамоии касбӣ",
alumniMentorsCareerDesc: "Дар бораи масирҳои касбӣ пас аз хатм маълумот гиред",
alumniMentorsTips: "Маслиҳатҳои аризадиҳӣ",
alumniMentorsTipsDesc: "Аз онҳое маслиҳат гиред, ки муваффақ шуданд",
alumniMentorsCulture: "Нуктаҳои фарҳангӣ",
alumniMentorsCultureDesc: "Барои зиндагӣ дар кишвари нав омода шавед",
alumniMentorsAccess: "Дастрасӣ ба шабака",
alumniMentorsAccessDesc: "Ба ҷамоаи рӯ ба афзоиши хатмкардагон ҳамроҳ шавед",
connectFriendsTitle: "Дӯстон ёфтан",
connectFriendsDesc: "Шабакаи худро бо аризадиҳандагони дигар созед",
connectFriendsIntro: "Бо дигар донишҷӯёне, ки барои таҳсил дар хориҷ омода мешаванд, шинос шавед. Маслиҳат мубодила кунед ва дӯстии мустаҳкам бандед.",
connectFriendsInterest: "Мувофиқати манфиатҳо",
connectFriendsInterestDesc: "Дар асоси хобиҳо ва ҳадафҳои умумӣ пайваст шавед",
connectFriendsStudy: "Шарикони таҳсил",
connectFriendsStudyDesc: "Барои омодагӣ ба имтиҳонҳо шарик ёбед",
connectFriendsCampus: "Пайвандҳои донишгоҳ",
connectFriendsCampusDesc: "Бо донишҷӯёни ҳамон донишгоҳ шинос шавед",
connectFriendsCultural: "Мубодилаи фарҳангӣ",
connectFriendsCulturalDesc: "Дар бораи фарҳанг ва заминаҳои гуногун маълумот гиред",
mockInterviewsTitle: "Мусоҳибаҳои машқӣ",
mockInterviewsDesc: "Барои мусоҳибаи қабул ба донишгоҳ омодагӣ бинед",
mockInterviewsIntro: "Барои мусоҳибаи донишгоҳ бо дарсҳои машқии AI омода шавед. Бозхӯрди фаврӣ ба посухҳо, маслиҳат оид ба забони бадан ва бали итминон гиред.",
mockInterviewsAi: "Мусоҳибгари AI",
mockInterviewsAiDesc: "Машқ бо саволҳои воқеъии AI",
mockInterviewsFeedback: "Бозхӯрди фаврӣ",
mockInterviewsFeedbackDesc: "Таҳлили фаврии посухҳои шумо",
mockInterviewsBank: "Бонки саволҳо",
mockInterviewsBankDesc: "Маҷмӯаи саволҳо барои донишгоҳҳои мушаххас",
mockInterviewsTrack: "Пайгирии пешрафт",
mockInterviewsTrackDesc: "Беҳшавиро дар миёни дарсҳо пайгирӣ кунед",
mockInterviewsGeneral: "Мусоҳибаи умумӣ",
mockInterviewsTechnical: "Мусоҳибаи техникӣ",
mockInterviewsScholarship: "Мусоҳибаи стипендиявӣ",
mockInterviewsPortfolio: "Баррасии портфолио",
conciergeSupportTitle: "Дастгирии шахсӣ",
conciergeSupportDesc: "Роҳнамоии Premium барои сафари шумо",
conciergeSupportIntro: "Аз маслиҳатчиёни мутахассиси мо дастгирии вижа гиред. Аз интихоби донишгоҳ то ариза барои виза — мо шуморо дар ҳар қадам роҳнамоӣ мекунем.",
conciergeSupportPriority: "Дастгирии авлавиятнок",
conciergeSupportPriorityDesc: "Бе навбат бо посухи афзалиятнок",
conciergeSupportAdvisor: "Маслиҳатчии шахсӣ",
conciergeSupportAdvisorDesc: "Маслиҳатчии алоҳида барои парвандаи шумо",
conciergeSupportDocReview: "Баррасии ҳуҷҷатҳо",
conciergeSupportDocReviewDesc: "Баррасии коршиносонаи ҳамаи ҳуҷҷатҳо",
conciergeSupportTracking: "Пайгирии ариза",
conciergeSupportTrackingDesc: "Навсозии фаврии вазъи аризаҳо",
englishTitle: "Омодагӣ ба забони англисӣ",
englishDesc: "Омодагӣ ба IELTS, TOEFL ва забони академии англисӣ",
englishIntro: "Малакаҳои забони англисиро барои қабул ба донишгоҳ бело кунед. Хондан, навиштан, гӯш кардан ва гуфтанро бо машқҳои ҳадафнок тамрин кунед.",
englishIelts: "Омодагӣ ба IELTS",
englishIeltsDesc: "Тестҳои пурра ва роҳнамоҳои стратегӣ",
englishToefl: "Омодагӣ ба TOEFL",
englishToeflDesc: "Машқ аз рӯи бахшҳо ва маслиҳатҳо",
englishAcademic: "Забони академии англисӣ",
englishAcademicDesc: "Малакаҳои навиштан, хондан ва пешниҳод кардан",
englishSpeaking: "Машқи гуфтугӯ",
englishSpeakingDesc: "Машқҳои суҳбат бо AI",
englishReading: "Хондан",
englishWriting: "Навиштан",
englishListening: "Гӯш кардан",
englishSpeakingSkill: "Гуфтан",
mathTitle: "Омодагӣ ба математика",
mathDesc: "Омодагӣ ба SAT, GRE ва талаботи математикии донишгоҳ",
mathIntro: "Малакаҳои математикиро бо машқҳои роҳнамоишуда мустаҳкам кунед. Алгебра, ҳисоб, омор ва стратегияҳои ҳалли масъалаҳоро фаро мегирад.",
mathSat: "SAT / ACT математика",
mathSatDesc: "Масъалаҳои машқӣ ва стратегияҳои имтиҳон",
mathAdvanced: "Мавзӯъҳои пешрафта",
mathAdvancedDesc: "Ҳисоб, алгебраи хатӣ ва бештар аз ин",
mathPractice: "Масъалаҳои машқӣ",
mathPracticeDesc: "Ҳазорҳо масъала бо ҳалли қадам ба қадам",
mathProgress: "Пайгирии пешрафт",
mathProgressDesc: "Дар ҳамаи мавзӯъҳо пешрафтро пайгирӣ кунед",
mathAlgebra: "Алгебра",
mathCalculus: "Ҳисоб",
mathStatistics: "Омор",
mathGeometry: "Ҳандаса",
aiLiteracyTitle: "Саводнокии AI",
aiLiteracyDesc: "Истифодаи самараноки абзорҳои AI барои таҳсил",
aiLiteracyIntro: "Асосҳои AI, муҳандисии промпт ва истифодаи ахлоқии AI дар муҳити таҳсилӣ ва касбиро омӯзед. Малакаҳои зарурӣ барои донишҷӯи муосир.",
aiLiteracyFundamentals: "Асосҳои AI",
aiLiteracyFundamentalsDesc: "Мафҳумҳои асосии зеҳни сунъӣ",
aiLiteracyPrompt: "Муҳандисии промпт",
aiLiteracyPromptDesc: "Дархостҳои самаранок барои абзорҳои AI нависед",
aiLiteracyData: "Саводнокии маълумот",
aiLiteracyDataDesc: "Маълумотро дарк кунед ва бо он кор кунед",
aiLiteracyEthics: "AI-и ахлоқӣ",
aiLiteracyEthicsDesc: "Истифодаи масъулонаи AI дар таҳсил",
getCoursesTitle: "Каталоги курсҳо",
getCoursesDesc: "Курсҳоро барои омодагӣ ба имтиҳонҳо ва рушди малакаҳо кашф кунед",
getCoursesIntro: "Курсҳои худомӯзиро кашф кунед, ки барои муваффақияти шумо дар аризаи донишгоҳ тарҳрезӣ шудаанд. Аз омодагӣ ба тест то малакаҳои нарм.",
getCoursesVideo: "Лексияҳои видеоӣ",
getCoursesVideoDesc: "Аз устодони мутахассис бо суръати худ омӯзед",
getCoursesInteractive: "Машқҳои интерактивӣ",
getCoursesInteractiveDesc: "Бо фаъолиятҳои амалӣ машқ кунед",
getCoursesCertificate: "Сертификатҳо",
getCoursesCertificateDesc: "Барои бело кардани профил сертификат гиред",
getCoursesSelfPaced: "Суръати худ",
getCoursesSelfPacedDesc: "Бо ҷадвали худ таҳсил кунед",
getCoursesTestPrep: "Омодагӣ ба имтиҳон",
getCoursesLanguage: "Курсҳои забон",
getCoursesSkills: "Малакаҳои нарм",
getCoursesAcademic: "Навиштани академӣ",
essayWritingDesc: "Навиштани иншоҳои таъсирбахшро биомӯзед",
essayWritingIntro: "Санъати иншонависиро бо шаблонҳо, пешниҳодҳои AI ва роҳнамои хосса барои ҳар донишгоҳ азхуд кунед. Таҷрибаҳоятонро ба ҳикояҳои қавӣ табдил диҳед.",
essayWritingTemplates: "Шаблонҳои иншо",
essayWritingTemplatesDesc: "Сохторҳои санҷидашуда барои намудҳои гуногуни иншо",
essayWritingAi: "Пешниҳодҳои AI",
essayWritingAiDesc: "Тавсияҳои ҳушёр барои беҳтар кардани навиштатон",
essayWritingPeer: "Санҷиши ҳамсолон",
essayWritingPeerDesc: "Фикру мулоҳизаи дигар довталабонро гиред",
essayWritingUniTips: "Маслиҳатҳои хосса барои донишгоҳ",
essayWritingUniTipsDesc: "Роҳнамои мувофиқ барои саволоти ҳар донишгоҳ",
contactPremiumTitle: "Тамос",
contactPremiumDesc: "Бо дастаи мо тамос гиред",
contactPremiumKicker: "Роҳнамоии Premium",
contactPremiumLeftLabel: "Дастгирии Premium ва сабти вохӯрӣ",
contactPremiumIntro: "Савол доред ё кӯмак лозим аст? Дастаи мо дар аризаҳо, ҳуҷҷатҳо ва банақшагирии роҳатон ёрӣ мерасонад — бо ҷавобҳои афзалиятӣ вақте ки муҳим аст.",
contactBookMeeting: "Вохӯрӣ таъин кардан",
contactBookMeetingHint: "Барномаи почтаатонро бо мавзӯи аз пеш пуршуда мекушояд; мо вақтро тасдиқ мекунем.",
contactBookMeetingEmailSubject: "Дархости вохӯрӣ — Ilmi",
contactAsideLabel: "Ҷамоа ва маълумоти тамос",
contactTelegramTitle: "Канали Telegram",
contactTelegramDesc: "Ба навсозиҳо, ёдоварӣ ва гуфтугӯ бо дигар довталабон ҳамроҳ шавед.",
contactOpenTelegram: "Дар Telegram кушодан",
contactReachUsTitle: "Тамоси мустақим",
contactEmailLabel: "Почтаи электронӣ",
contactTelegramLabel: "Ҷамоа",
contactTelegramChannelShort: "Канали расмии Ilmi",
contactReachUsFootnote: "Барои дархостҳои расмӣ ё ҳуҷҷатҳо почтаи электронӣ беҳтар аст. Telegram барои саволҳои зуд ва эълонҳои ҷамоа мувофиқтар.",
contactPremiumPriority: "Ҷавоби афзалиятӣ",
contactPremiumPriorityDesc: "Ҷавобҳои зуд аз дастаи мо гиред",
contactPremiumVideo: "Машваратҳои видеоӣ",
contactPremiumVideoDesc: "Вохӯриҳои видеоӣ рӯ ба рӯ таъин кунед",
contactPremiumDoc: "Кӯмак бо ҳуҷҷатҳо",
contactPremiumDocDesc: "Ёрӣ дар ҳуҷҷатҳо ва аризаҳо",
contactPremiumTeam: "Дастаи мутахассисон",
contactPremiumTeamDesc: "Дастгирӣ аз маслиҳатчиёни таҷрибадори таҳсил",
contactPremiumEmail: "Дастгирӣ тавассути почта",
contactPremiumEmailDesc: "Паём фиристед ва дар муддати 24 соат ҷавоб гиред",
contactPremiumChat: "Чати зинда",
contactPremiumChatDesc: "Дар вақти корӣ бо дастаи мо дар вақти воқеӣ гуфтугӯ кунед",
contactPremiumCall: "Занги таъиншуда",
contactPremiumCallDesc: "Занги инфиродӣ бо маслиҳатчии таҳсил таъин кунед",
contactPremiumContactUs: "Бо мо тамос гиред",
contactPremiumChannels: "Каналҳои тамос",
dreamUniTitle: "Донишгоҳи орзу",
dreamUniDesc: "Роҳатонро ба донишгоҳи орзу банақша гиред ва пайгирӣ кунед",
dreamUniIntro: "Донишгоҳҳои мақсадӣ муайян кунед, муҳлатҳои ариза пайгирӣ кунед ва пешрафтатонро назорат кунед. Ташкилёфта ва бармақсад бошед.",
dreamUniGoals: "Пайгирии ҳадафҳо",
dreamUniGoalsDesc: "Нишонаҳои аризаатонро муқаррар карда пайгирӣ кунед",
dreamUniDeadlines: "Ёдоварии муҳлатҳо",
dreamUniDeadlinesDesc: "Ягон муҳлати муҳими ариза аз даст надиҳед",
dreamUniTimeline: "Хронологияи пешрафт",
dreamUniTimelineDesc: "Сафари худро аз оғоз то қабулшавӣ тасвир кунед",
dreamUniChecklist: "Рӯйхати санҷишии ариза",
dreamUniChecklistDesc: "Ҳар ҳуҷҷат ва талаботро пайгирӣ кунед",
searchScholarshipsTitle: "Ҷустуҷӯи стипендияҳо",
searchScholarshipsDesc: "Стипендияҳо ва имкониятҳои маблағгузорӣ дар саросари ҷаҳон ёбед",
searchScholarshipsIntro: "Ҳазорҳо стипендияро барои донишҷӯёни Осиёи Марказӣ кофтед. Бо кишвар, соҳа, маблағ ва муҳлат филтр кунед то имкониятҳои мувофиқ ёбед.",
searchScholarshipsType: "Аз рӯи намуд",
searchScholarshipsTypeDesc: "Лаёқатӣ, ниёзмандӣ, миллӣ ва ғайра",
searchScholarshipsCountry: "Аз рӯи кишвар",
searchScholarshipsCountryDesc: "Стипендияҳоро аз рӯи кишвари мақсадӣ филтр кунед",
searchScholarshipsDeadline: "Тақвими муҳлатҳо",
searchScholarshipsDeadlineDesc: "Муҳлатҳои наздики стипендияҳоро пайгирӣ кунед",
searchScholarshipsEligibility: "Санҷиши мутобиқат",
searchScholarshipsEligibilityDesc: "Зуд санҷед, ки оё шумо мутобиқ ҳастед",
profileTitle: "Профили ман",
profileDesc: "Танзимоти ҳисобатонро идора кунед",
profileChangePhoto: "Акс иваз кардан",
profileFullName: "Ному насаб",
profileFirstName: "Ном",
profileLastName: "Насаб",
profileEmail: "Почтаи электронӣ",
profilePhone: "Телефон",
profileLocation: "Ҷойгиршавӣ",
profileCertifications: "Сертификатҳо ва тахассус",
profileCertificationsHint: "Ҳар яке дар як хат (масалан дипломҳо, санҷишҳои забонӣ, натиҷаҳои имтиҳон барои талаботи барнома).",
profileShareTitle: "Истинод ба профил",
profileShareDesc: "Ин истинодро мубодила кунед ё рамзро скан кунед то профилатонро дар ин дастгоҳ кушоед.",
profileCopyLink: "Истинодро нусхабардорӣ кунед",
profileLinkCopied: "Истинод нусхабардорӣ шуд",
profileLoadError: "Профилро бор кардан мумкин набуд. Тасдиқ кунед, ки ворид шудаед ва сервер кор мекунад.",
profileSaveError: "Тағйиротро сохтан мумкин набуд.",
profileSaveSuccess: "Профил захира шуд.",
profileGuestHint: "Ворид шавед то профил, сертификатҳо ва истинод барои мубодиларо бор ва захира кунед.",
profileSaving: "Захира мешавад…",
profileApplications: "Аризаҳо",
profileScholarships: "Стипендияҳо",
profileViews: "Дидани профил",
profilePremium: "Узви Premium",
profilePremiumDesc: "Шумо ба ҳамаи хусусиятҳои Premium дастрасӣ доред",
profilePremiumMatch: "Интихоби номаҳдуди донишгоҳ",
profilePremiumSupport: "Дастгирии афзалиятии ариза",
profilePremiumAlerts: "Огоҳиномаҳои хоссаи стипендия",
profilePremiumMentor: "Дастрасии мустақим ба мураббиён",
profileSave: "Тағйиротро захира кунед",
profileLogout: "Баромадан",
dashMain: "АСОСӢ",
dashDreamUniversity: "Донишгоҳи орзу",
dashDreamPeakLabel: "Трек UCA",
dashDreamCardTagline: "Ҳадафи аслии шумо — ҳуҷҷатҳо, баллҳо ва муҳлатҳоро бо ин донишгоҳ ҳамоҳанг нигоҳ доред.",
dashDreamPillFit: "92% мутобиқат бо профилатон",
dashDreamPillDeadline: "Навбатӣ: аризаи UCA · 6 окт",
dashDreamPillDocs: "Рӯйхати ҳуҷҷатҳо · 4 кушода",
dashDreamReadinessLabel: "Омодагӣ барои ин ҳадаф",
dashSearchUniversities: "Донишгоҳҳо",
dashFavoriteUniversities: "Дилхоҳҳо: донишгоҳҳо",
dashSearchFields: "Соҳаҳо",
dashSearchPrograms: "Барномаҳо",
dashFavoritePrograms: "Дилхоҳҳо: барномаҳо",
dashSearchScholarships: "Стипендияҳо",
dashAiMatching: "Интихоби AI",
dashMatchUniversities: "Интихоби донишгоҳ",
dashMatchScholarships: "Интихоби стипендия",
dashEssayReview: "Санҷиши иншо",
dashSimilarStudents: "Донишҷӯёни монанд",
dashCommunity: "Ҷамоа",
dashOthers: "Дигар",
dashConnections: "Алоқаҳо",
dashConnectFriends: "Дӯстон",
dashAlumniMentors: "Мураббиёни хатмкардагон",
dashPremiumServices: "Хадамоти Premium",
dashEssayReviews: "Санҷиши иншо",
dashMockInterviews: "Мусоҳибаҳои машқӣ",
dashConciergeSupport: "Дастгирии консерж",
dashLearning: "Омӯзиш ва курсҳо",
dashGetCourses: "Курсҳо гирифтан",
dashMath: "Математика",
dashEnglish: "Англисӣ",
dashEssayWriting: "Навиштани иншо",
dashAiLiteracy: "Саводнокии AI",
dashDashboard: "Лавҳаи асосӣ",
dashTagline: "Сафари донишгоҳии шумо аз ин ҷо оғоз меёбад",
dashSendInfo: "Маълумот фиристед — Premium гиред",
dashJoinCommunity: "Ба ҷамоаи мо ҳамроҳ шавед",
dashLogout: "Баромадан",
dashNotifications: "Огоҳиномаҳо",
dashProfile: "Профил",
dashWelcomeBackPrefix: "Хуш омадед,",
dashDefaultDisplayName: "Ном Насаб",
dashOpenPage: "Саҳифаро кушодан",
dashCardDashboardDesc: "Ба лавҳаи асосӣ бозгаштан.",
dashCardDreamDesc: "Ҳадафҳо ва пешрафти донишгоҳи орзуро дидан.",
dashCardUniversitiesDesc: "Донишгоҳҳоро ҷустуҷӯ ва муқоиса кунед.",
dashCardFavoriteUniversitiesDesc: "Донишгоҳҳои захирашударо кушодан.",
dashCardFieldsDesc: "Соҳаҳоро мувофиқи таваҷҷӯҳатон кофтан.",
dashCardProgramsDesc: "Барномаҳои таҳсилӣ дар донишгоҳҳои беҳтаринро ёбед.",
dashCardFavoriteProgramsDesc: "Барномаҳои захирашударо дар як ҷо бубинед.",
dashCardScholarshipsDesc: "Стипендияҳои мувофиқро ёбед.",
dashCardMatchUniversitiesDesc: "Интихоби донишгоҳ тавассути AI гиред.",
dashCardMatchScholarshipsDesc: "Интихоби стипендия тавассути AI гиред.",
dashCardSimilarStudentsDesc: "Маълумоти донишҷӯёни монандро бубинед.",
dashCardFriendsDesc: "Бо дӯстоне, ки ҳамин роҳро мераванд, алоқа гиред.",
dashCardMentorsDesc: "Мураббиёни хатмкардагонро барои роҳнамоӣ ёбед.",
dashCardProfileDesc: "Профилатонро бубинед ва навсозӣ кунед.",
dashCardSendInfoDesc: "Маълумот фиристед ва дастгирии Premium дархост кунед.",
dashContactPremium: "Тамос",
dashNavAiTools: "АБЗОРҲОИ AI",
dashNavApply: "Аризаҳо",
dashMyAcademics: "Таҳсили ман",
dashMyApplications: "Аризаҳои ман",
dashNavOpportunities: "Имкониятҳо",
dashJobs: "Кор ва стажировка",
dashCourses: "Курсҳо",
dashNavAdmin: "Маъмурият",
dashAdminReview: "Санҷиши ҷамъоварӣ",
dashNavFriendsAndMentors: "ДӮСТОН ВА МУРАББИЁН",
dashNavSectionAiUniversities: "AI · Донишгоҳҳо",
dashNavSectionAiScholarships: "AI · Стипендияҳо",
dashNavSectionAiSimilarStudents: "AI · Донишҷӯёни монанд",
dashNavSectionConnectFriends: "Дӯстон",
dashNavSectionAlumniMentors: "Мураббиёни хатмкардагон",
dashNavSectionContactPremium: "ТАМОС",
dashCardContactPremiumDesc: "Бо даста тамос гиред, вохӯрӣ таъин кунед ё ба Telegram ҳамроҳ шавед.",
dashAiDashboardUniTitle: "AI · Беҳтарин мутобиқатҳо оид ба донишгоҳ",
dashAiShowcaseSeeWholeList: "Рӯйхати пурраро бинед",
dashCtaSeeAllUniversityMatches: "Ҳамаи мутобиқатҳои донишгоҳро бинед",
dashCtaSeeAllScholarshipMatches: "Ҳамаи мутобиқатҳои стипендияро бинед",
dashCtaSeeAllFriends: "Ҳамаи дӯстонро бинед",
dashCtaBrowseAllMentors: "Ҳамаи мураббиёнро кофтед",
dashConnAsideFriendsLabel: "Дӯстон дар ин пешнамоиш",
dashFriendsCombinedSectionTitle: "Дӯстон ва шиносоиҳо",
dashFriendsSimilarColumnTitle: "Касоне, ки метавонед бо онҳо шинос шавед",
dashFriendsSimilarSeeMore: "Бештар",
dashFriendsOnlineColumnTitle: "Дӯстони шумо",
dashFriendsOnlineNow: "Ҳоло дар тор",
dashFriendsAllFriendsLabel: "Ҳамаи дӯстон",
dashFriendsSeeCountCta: "{{count}} дӯстро бинед",
dashFriendsOnlineEmpty: "Ҳоло ҳеҷ кас дар тор нест",
dashConnAsideMentorsLabel: "Мураббиён дар ин пешнамоиш",
dashSimilarStudentsAddFriend: "Ба дӯстон илова кунед",
dashAiShowcaseUniCtaHint: "Интихобгари пурра бо филтрҳо ва ҳамаи вариантҳо.",
dashAiShowcaseScholCtaHint: "Ҳамаи стипендияҳо ва шартҳои иштирокро кофтед.",
dashAiDashboardScholTitle: "AI · Беҳтарин мутобиқатҳо оид ба стипендия",
dashAiDashboardPeersTitle: "AI · Донишҷӯёни монанд",
dashAiUniMatchLead: "Донишгоҳҳо аз рӯи мутобиқат бо профил, ҳадафҳо ва баллҳои шумо дараҷабандӣ шудаанд.",
dashAiScholMatchLead: "Стипендияҳое, ки шумо бештар эҳтимол дошта шароити онҳоро баробар мекунед.",
dashAiPeersMatchLead: "Ҳамсолоне, ки ҳадафҳои умумӣ доранд — аз таҷрибаи онҳо биомӯзед.",
dashAiScholCardIntlTitle: "Global Merit Fund",
dashAiScholCardIntlMeta: "Довталабони байналмилалӣ · Муҳлат 15 апр",
dashSimilarStudent2Name: "Eldar M.",
dashSimilarStudent2Desc: "Трек STEM, аввал стипендияҳо.",
dashSimilarStudent3Name: "Timur B.",
dashSimilarStudent3Desc: "Рӯйхат бо тамаркуз ба Аврупо, баллҳои қавии англисӣ.",
dashSimilarTagField: "Ҳамон соҳа",
dashSimilarTagRegion: "Ҳамон минтақаи мақсадӣ",
dashSimilarTagScores: "Баллҳои монанд",
dashSimilarOverlapGpa: "Диапазони монанди GPA",
dashSimilarOverlapShortlist: "Интихоби шортлист мувофиқ меояд",
dashSimilarOverlapIntake: "Ҳамон набори мақсадӣ",
dashSimilarOverlapScholarFirst: "Стратегияи аввал — стипендия",
dashSimilarOverlapEuTargets: "Ҳадафҳои ЕИ мувофиқ меояд",
dashSimilarOverlapAidFocus: "Ҳар дуяшон кӯмаки ниёзӣ пайгирӣ мекунанд",
dashSimilarOverlapEuropeList: "Рӯйхатҳои бо тамаркуз ба Аврупо",
dashSimilarOverlapIelts: "Сатҳи монанди англисӣ",
dashSimilarOverlapStemExtra: "Фаъолиятҳои монанди STEM",
dashSimilaritiesLabel: "Мувофиқатҳо бо профили шумо",
dashFriend2SampleName: "Erkeaiym D.",
dashFriend2SampleDesc: "Рӯйхатҳои дилхоҳ мувофиқ меояд: Нидерланд ва Олмон.",
dashFriend3SampleName: "Sultan K.",
dashFriend3SampleDesc: "Шарики мубодилаи иншо · дирӯз фаъол буд.",
dashMentor2SampleName: "Laura N.",
dashMentor2SampleDesc: "Қабул ба MBA, омодагӣ ба мусоҳиба ва санҷиши CV.",
dashMentorBadgeStem: "Муҳандисӣ",
dashMentorBadgeMba: "Тиҷорат ва MBA",
dashMentorVerified: "Мураббии тасдиқшуда",
dashAway: "Дур аст",
dashConnectionFriendsTitle: "Алоқаҳо · Дӯстон",
dashConnectionFriendsLead: "Касоне, ки дар ҳамин роҳ мехонанд ё метавонед ба онҳо паём фиристед.",
dashConnectionMentorsTitle: "Алоқаҳо · Мураббиёни хатмкардагон",
dashConnectionMentorsLead: "Хатмкардагоне, ки дар аризаҳо ва мусоҳибаҳо кӯмак мерасонанд.",
dashConnectionActionChat: "Чатро кушодан",
dashConnectionActionMentor: "Профилро дидан",
dashConnectionPremiumTitle: "Дастгирии Premium",
dashConnectionPremiumLead: "Кӯмаки хоссаи муҳлатҳо, иншоҳо ва стратегия.",
dashConnectionPremiumPoint1: "Ҷавобҳои афзалиятӣ аз дастаи ilmi",
dashConnectionPremiumPoint2: "Санҷиши иншо ва мусоҳибаи машқӣ бо фикру мулоҳизаи равшан",
dashConnectionPremiumPoint3: "Банақшагирии шортлист бо услуби консерж",
dashContactSubheading: "Тамос",
dashContactDetailsTitle: "Бо мо тамос гиред",
dashContactCompactHint: "Истинодҳои зуд дар зер. Барои фиристодани паёми пурра саҳифаи «Тамос»-ро кушоед.",
dashContactFullPageCta: "Саҳифаи пурраи «Тамос»-ро кушодан",
dashContactUsTitle: "Бо мо тамос гиред",
dashContactPhoneLabel: "Телефон",
dashContactTelegramQrCaption: "Рамзро скан кунед ё клик кунед то канали Telegram-и моро кушоед.",
dashContactSocialListLabel: "Шабакаҳои иҷтимоӣ ва истинодҳои ҷамоа",
dashContactFormTitle: "Ба мо паём фиристед",
dashContactFormName: "Ному насаб",
dashContactFormNamePh: "Ному насабатонро ворид кунед",
dashContactFormEmail: "Почтаи электронӣ",
dashContactFormEmailPh: "you@example.com",
dashContactFormTopic: "Мавзӯъ",
dashContactFormTopicPh: "Кӣ гуна кӯмак лозим аст?",
dashContactFormMessage: "Паём",
dashContactFormMessagePh: "Паёматонро ин ҷо нависед — кофӣ тафсилот илова кунед то мо дуруст кӯмак расонем.",
dashContactFormSubmit: "Паём фиристодан",
dashContactFormThanks: "Ташаккур! Мо паёми шуморо гирифтем ва ба зудӣ ҷавоб медиҳем.",
dashContactFormAgain: "Паёми дигар фиристодан",
contactPlatformLinkedIn: "LinkedIn",
contactPlatformTelegram: "Telegram",
contactPlatformInstagram: "Instagram",
contactPlatformX: "X",
contactPlatformYouTube: "YouTube",
contactPlatformTikTok: "TikTok",
dashPerfectMatch: "Мувофиқати комил",
dashUcaName: "University of Central Asia",
dashUcaLocation: "Нарын, Қирғизистон",
dashStartClimb: "Оғоз кардан",
dashPackList: "Рӯйхати корҳо",
dashUpcomingDeadlines: "Мӯҳлатҳои наздик",
dashShowAll: "Ҳамаро нишон додан",
dashUcaApplication: "Ариза ба UCA",
dashAucaScholarship: "Стипендияи AUCA",
dashMitApplication: "Ариза ба MIT",
dashOct6: "6 окт 2025",
dashOct8: "8 окт 2025",
dashDeadlineFarTitle: "Stanford SCEA · портфолио ва транскриптҳо",
dashDeadlineFarDate: "15 янв 2027",
dashTimeAbout9mo: "~9 моҳ",
dashTime45m: "45 дақ монд",
dashTime2h15m: "2с 15д монд",
dashTime2d3h: "2р 3с монд",
dashViewsTitle: "Дидани донишгоҳҳо ва стипендияҳо",
dashViewsTotal: "Маълумоти намунавӣ",
dashViewsDesc: "Шумораи донишгоҳҳо ва стипендияҳои дидашударо пайгирӣ кунед",
dashRecommendedUniversities: "Донишгоҳҳои тавсияшуда",
dashPreviewSearchPlaceholder: "Ҷустуҷӯ бо ном ё ҷой…",
dashFilters: "Филтрҳо",
dashFilterAll: "Ҳама",
dashFilterEurope: "Аврупо",
dashFilterEnglishTaught: "Бо забони англисӣ",
dashSearchPopularFilters: "Филтрҳои маъмул",
dashSearchClearFilters: "Ҳамаро тоза кардан",
dashStartSearching: "Ҷустуҷӯ оғоз кардан",
dashSearchUniPlaceholder: "Ҷустуҷӯ бо номи донишгоҳ ё коллеҷ…",
dashUniPopUnder10k: "То €10 ҳазор / сол",
dashUniPopUnder5k: "≤ €5 ҳазор / сол",
dashUniPopBusinessLaw: "Тиҷорат ва ҳуқуқ",
dashUniPopMedicine: "Тиб ва илм",
dashUniPopArts: "Санъат ва дизайн",
dashFieldTeaserCs: "Информатика ва IT",
dashFieldTeaserBusiness: "Тиҷорат ва менеҷмент",
dashFieldTeaserMedicine: "Тиб ва саломатӣ",
dashFieldTeaserEngineering: "Муҳандисӣ",
dashFieldTeaserArts: "Санъат ва дизайн",
dashScholarshipUrlHintMerit: "Шумо аз лавҳа стипендияҳои шоистагӣ кушодед.",
dashScholarshipUrlHintNeed: "Шумо аз лавҳа стипендияҳои ниёзмандӣ кушодед.",
dashSearchTeaserSearchUniversities: "Ҷустуҷӯи донишгоҳҳо",
dashSearchTeaserSearchFields: "Ҷустуҷӯи соҳаҳо",
dashSearchTeaserSearchScholarships: "Ҷустуҷӯи стипендияҳо",
dashSearchFieldPlaceholder: "Ҷустуҷӯ бо номи соҳа…",
dashSearchScholarshipPlaceholder: "Ҷустуҷӯи стипендияҳо…",
dashPreviewMatches: "мувофиқат",
dashPreviewNoResults: "Натиҷае барои ин филтр ёфт нашуд.",
dashPreviewUniversitiesLead: "Пешнамоиши ҷустуҷӯ: филтрҳои чап рӯйхати ростро маҳдуд мекунанд.",
dashPreviewProgramsLead: "Пешнамоиши ҷустуҷӯи барномаҳо бо филтрҳои зуд ва рӯйхати кӯтоҳ.",
dashPreviewScholarshipsLead: "Пешнамоиши ҷустуҷӯи стипендияҳо бо филтрҳои намуд.",
dashProgramFilterMaster: "Магистратура",
dashProgramFilterBachelor: "Бакалавриат",
dashScholarshipFilterMerit: "Шоистагӣ",
dashScholarshipFilterNeed: "Ниёзмандӣ",
dashProgramPreviewMsTitle: "M.Sc. Computer Science",
dashProgramPreviewMsMeta: "STEM · қабули тирамоҳӣ",
dashProgramPreviewBsTitle: "B.A. International Relations",
dashProgramPreviewBsMeta: "Илмҳои иҷтимоӣ · доимӣ",
dashProgramPreviewMbaTitle: "MBA",
dashProgramPreviewMbaMeta: "Тиҷорат · GMAT",
dashScholPreviewMeritTitle: "Ҷоизаи шоистагӣ",
dashScholPreviewMeritMeta: "То €5,000 · мӯҳлат 1 март",
dashScholPreviewNeedTitle: "Гранти дастгирии молиявӣ",
dashScholPreviewNeedMeta: "Аз рӯи даромад · доимӣ",
dashApplicationStatus: "Вазъи аризаҳо",
dashStatusCardLead: "Ҳамаи вазъҳое, ки дар ilmi пайгирӣ мекунед — шумора ва саҳми қаналатон.",
dashStatusDonutLabel: "Аризаҳо",
dashStatusTotal: "Ҳамаги 15",
dashStatusPlan: "Нақша дорам",
dashStatusApplied: "Фиристода шуд",
dashStatusAccepted: "Қабул шуд",
dashStatusWaitlist: "Рӯйхати интизорӣ",
dashStatusRejected: "Рад шуд",
dashRank: "Рейтинг",
dashMatch: "Мувофиқат",
dashUni1Name: "Massachusetts Institute of Technology",
dashUni1Loc: "Cambridge, MA, USA",
dashUni1Rank: "#1",
dashUni1Match: "95%",
dashUni2Name: "Stanford University",
dashUni2Loc: "Stanford, CA, USA",
dashUni2Rank: "#2",
dashUni2Match: "92%",
dashAiSampleUniversities: "Беҳтарин мувофиқатҳо аз рӯи профил ва ҳадафҳо.",
dashAiSampleScholarships: "Стипендияҳо мувофиқи буҷет ва балҳо.",
dashAiSampleStudents: "Донишҷӯён бо масирҳо ва натиҷаҳои монанд.",
dashFriendSampleName: "Aizada K.",
dashFriendSampleDesc: "Барои барномаҳои Data Science ариза медиҳад.",
dashMentorSampleName: "Murat R.",
dashMentorSampleDesc: "Мураббии хатмкарда барои қабул ба муҳандисӣ.",
dashOnline: "Онлайн",
appTimelineTitle: "Ҷадвали аризаҳо",
appTimelineDesc: "Мӯҳлатҳо ва пешрафти аризаҳоятонро пайгирӣ кунед",
appTimelineFeature1: "Пайгирии мӯҳлатҳо",
appTimelineFeature1Desc: "Мӯҳлатҳои аризаро бо ёдоварии ҳушёр аз даст надиҳед",
appTimelineFeature2: "Назорати пешрафт",
appTimelineFeature2Desc: "Вазъи аризаҳоро дар ҳамаи донишгоҳҳо дар як назар бубинед",
appTimelineFeature3: "Банақшагирии марҳилаҳо",
appTimelineFeature3Desc: "Аз омодагӣ ба имтиҳон то ариза барои виза марҳилаҳоро банақша гиред",
appTimelineFeature4: "Ҳамоҳангсозии тақвим",
appTimelineFeature4Desc: "Мӯҳлатҳоро ба тақвими худ илова кунед",
appTimelineCta: "Пайгирӣ оғоз кардан",
myDocsTitle: "Ҳуҷҷатҳои ман",
myDocsDesc: "Ҳуҷҷатҳо ва транскриптҳои аризаатонро идора кунед",
myDocsFeature1: "Нигоҳдории ҳуҷҷатҳо",
myDocsFeature1Desc: "Транскриптҳо, эссеҳо ва тавсиянномаҳоро бехатар нигоҳ доред",
myDocsFeature2: "Назорати нусхаҳо",
myDocsFeature2Desc: "Тағйиротро пайгирӣ кунед ва якчанд черновики эссе идора кунед",
myDocsFeature3: "Мубодилаи зуд",
myDocsFeature3Desc: "Ҳуҷҷатҳоро барои баррасӣ бо маслиҳатчиён мубодила кунед",
myDocsFeature4: "Менеҷери рӯйхати санҷишӣ",
myDocsFeature4Desc: "Ҳуҷҷатҳои лозимиро барои ҳар ариза пайгирӣ кунед",
myDocsCta: "Боргузории ҳуҷҷатҳо",
careerAnalysisTitle: "Таҳлили масири касбӣ",
careerAnalysisDesc: "Масирҳо ва имкониятҳои касбии эҳтимолиро таҳлил кунед",
careerAnalysisFeature1: "Маълумоти соҳавӣ",
careerAnalysisFeature1Desc: "Тамоюлҳои касбӣ ва маълумоти музди кор аз рӯи соҳаро омӯзед",
careerAnalysisFeature2: "Харитаи малакаҳо",
careerAnalysisFeature2Desc: "Малакаҳоятонро бо имкониятҳои касбии пурталаб мувофиқ кунед",
careerAnalysisFeature3: "Муқоисаи масирҳо",
careerAnalysisFeature3Desc: "Масирҳои касбиро бо пешгӯии рушд паҳлӯба паҳлӯ муқоиса кунед",
careerAnalysisFeature4: "Гузоштани ҳадаф",
careerAnalysisFeature4Desc: "Ҳадафҳои касбӣ гузоред ва пешрафти онҳоро пайгирӣ кунед",
careerAnalysisCta: "Таҳлили касбӣ",
internshipsTitle: "Интихоби стажировка",
internshipsDesc: "Стажировкаҳоеро ёбед, ки бо ҳадафҳоятон мувофиқанд",
internshipsFeature1: "Интихоби ҳушёр",
internshipsFeature1Desc: "Интихоби AI-асос шуморо бо стажировкаҳои мувофиқ мепайвандад",
internshipsFeature2: "Трекери аризаҳо",
internshipsFeature2Desc: "Аризаҳои стажировкаро дар як ҷой пайгирӣ кунед",
internshipsFeature3: "Тадқиқи ширкатҳо",
internshipsFeature3Desc: "Профилҳои муфассали ширкатҳои пешниҳодкунандаи стажировка",
internshipsFeature4: "Рушди малакаҳо",
internshipsFeature4Desc: "Малакаҳои лозимиро барои стажировкаҳои ҳадафӣ муайян кунед",
internshipsCta: "Ёфтани стажировка",
mastersTitle: "Интихоби магистратура",
mastersDesc: "Барномаҳои аспирантураро дар саросари ҷаҳон омӯзед",
mastersFeature1: "Ҷустуҷӯи барномаҳо",
mastersFeature1Desc: "Барномаҳои магистрро дар донишгоҳҳои ҷаҳон омӯзед",
mastersFeature2: "Маълумоти қабул",
mastersFeature2Desc: "Талаботи қабул ва сатҳи рақобатро дарк кунед",
mastersFeature3: "Имкониятҳои маблағгузорӣ",
mastersFeature3Desc: "Стипендияҳо ва ассистентураро барои таҳсили аспирантура ёбед",
mastersFeature4: "Натиҷаҳои касбӣ",
mastersFeature4Desc: "Омори шуғли хатмкардагони барномаҳоро бубинед",
mastersCta: "Омӯзиши барномаҳо",
uniReelsTitle: "Видеоҳои донишгоҳ",
uniReelsDesc: "Тури кампусҳо ва видеоҳои зиндагии донишҷӯиро тамошо кунед",
uniReelsFeature1: "Тури кампусҳо",
uniReelsFeature1Desc: "Туризми виртуалии кампусҳо аз саросари ҷаҳон",
uniReelsFeature2: "Ҳикояҳои донишҷӯён",
uniReelsFeature2Desc: "Аз донишҷӯёни феълӣ дар бораи таҷрибаашон бишнавед",
uniReelsFeature3: "Роҳнамоҳои шаҳрӣ",
uniReelsFeature3Desc: "Шаҳрҳоеро, ки донишгоҳҳои барҷаста дар онҳо ҷойгиранд, омӯзед",
uniReelsFeature4: "Тасвирҳои рӯйдодҳо",
uniReelsFeature4Desc: "Тасвирҳои рӯзҳои кушод ва рӯйдодҳои кампусро тамошо кунед",
uniReelsCta: "Тамошо кардан",
privacyTitle: "Лавҳаи махфияти ман",
privacyDesc: "Танзимоти махфият ва маълумотатонро идора кунед",
privacyFeature1: "Назорати маълумот",
privacyFeature1Desc: "Ҳамаи маълумоте, ки мо ҷамъ мекунем, бубинед ва идора кунед",
privacyFeature2: "Танзимоти намоиш",
privacyFeature2Desc: "Назорат кунед, ки кӣ профил ва фаъолияти шуморо мебинад",
privacyFeature3: "Содироти маълумот",
privacyFeature3Desc: "Нусхаи ҳамаи маълумоти шахсиатонро ҳар вақт боргирӣ кунед",
privacyFeature4: "Нест кардани ҳисоб",
privacyFeature4Desc: "Ҳисоб ва ҳамаи маълумоти алоқамандро доимӣ нест кунед",
privacyCta: "Санҷиши танзимот",
studyTogetherTitle: "Якҷоя мехонем",
studyTogetherDesc: "Бо ҳамсолон ва гурӯҳҳои таҳсилӣ иртибот гиред",
studyTogetherFeature1: "Интихоби гурӯҳ",
studyTogetherFeature1Desc: "Ҳамроҳони таҳсилиро бо ҳадафҳо ва ҷадвали монанд ёбед",
studyTogetherFeature2: "Сессияҳои зинда",
studyTogetherFeature2Desc: "Ба сессияҳои таҳсилии онлайн бо ҳамсолони ҷаҳон ҳамроҳ шавед",
studyTogetherFeature3: "Мубодилаи маводҳо",
studyTogetherFeature3Desc: "Ёддоштҳо, маводҳо ва усулҳои омодагиро мубодила кунед",
studyTogetherFeature4: "Пешрафти муштарак",
studyTogetherFeature4Desc: "Ҳадафҳои умумиро пайгирӣ кунед ва якдигарро рӯҳбаланд кунед",
studyTogetherCta: "Ёфтани ҳамроҳи таҳсил",
sendInfoPageTitle: "Маълумот фиристед — Premium гиред",
sendInfoOfferHeadline: "7 рӯз Premium РОЙГОН!",
sendInfoOfferBody: "Дархост дар бораи донишгоҳ ё стипендия фиристед — фавран 7 рӯз Premium гиред.",
sendInfoTabUniversity: "Дар бораи донишгоҳ",
sendInfoTabScholarship: "Дар бораи стипендия",
sendInfoTabApplication: "Кӯмак барои ариза",
sendInfoTabMeeting: "Вохӯрӣ таъин кардан",
sendInfoTabOther: "Дархости дигар",
sendInfoFieldFullName: "Ном ва насаб",
sendInfoFieldEmail: "Почтаи электронӣ",
sendInfoFieldPhone: "Телефон",
sendInfoFieldUniversity: "Донишгоҳ",
sendInfoFieldUniversityInterest: "Донишгоҳи мавриди таваҷҷӯҳ",
sendInfoFieldProgram: "Барнома",
sendInfoFieldProgramMajor: "Барнома / ихтисос",
sendInfoFieldGpa: "Бали миёна (GPA)",
sendInfoFieldAdditional: "Маълумоти иловагӣ",
sendInfoFieldScholarshipName: "Номи стипендия",
sendInfoFieldAchievements: "Дастовардҳои таҳсилӣ",
sendInfoFieldDeadline: "Муҳлати ариза",
sendInfoFieldHelp: "Чӣ гуна кӯмак лозим аст?",
sendInfoFieldMeetingType: "Намуди вохӯрӣ",
sendInfoFieldPreferredDate: "Санаи дилхоҳ",
sendInfoFieldPreferredTime: "Вақти дилхоҳ",
sendInfoFieldNotes: "Эзоҳҳои иловагӣ",
sendInfoFieldSubject: "Мавзӯъ",
sendInfoFieldMessage: "Паём",
sendInfoPhFullName: "Ном ва насабатонро ворид кунед",
sendInfoPhEmail: "Почтаи электрониатонро ворид кунед",
sendInfoPhPhone: "Рақами телефонатонро ворид кунед",
sendInfoPhUniversityInterest: "Кадом донишгоҳ ҷолиб аст?",
sendInfoPhProgramInterest: "Кадом барнома ҷолиб аст?",
sendInfoPhGpa: "GPA-ро ворид кунед",
sendInfoPhGoals: "Дар бораи ҳадафҳоятон бигӯед...",
sendInfoPhScholarship: "Кадом стипендия ҷолиб аст?",
sendInfoPhUniversityOpt: "Донишгоҳи марбут (агар бошад)",
sendInfoPhAchievements: "Дастовардҳоятонро навишта диҳед...",
sendInfoPhUniversityRequired: "Кадом донишгоҳ?",
sendInfoPhProgramRequired: "Кадом барнома?",
sendInfoPhHelp: "Кадом кӯмак лозим — нависед...",
sendInfoPhSubject: "Дархостатон дар бораи чист?",
sendInfoPhContact: "Чӣ гуна мо кӯмак расонда метавонем?",
sendInfoPhNotes: "Ҳар маълумоти иловагӣ...",
sendInfoMeetingSelect: "Намуди вохӯриро интихоб кунед",
sendInfoMeetingConsult: "Машварати умумӣ",
sendInfoMeetingAppReview: "Аризаро санҷидан",
sendInfoMeetingScholarship: "Машварат оид ба стипендия",
sendInfoMeetingCareer: "Машварати касбӣ",
sendInfoSubmit: "Фиристодан — Premium гирифтан",
sendInfoSubmitting: "Фиристода мешавад...",
sendInfoError: "Дархости шумо фиристода нашуд. Пайвастро санҷед ва дубора кӯшиш кунед.",
sendInfoSuccessTitle: "Маълумот бомуваффақият фиристода шуд!",
sendInfoSuccessBody: "Барои дархости шумо ташаккур. Дастаи мо маълумотро дида мебарояд ва ба зудӣ бо шумо тамос мегирад.",
sendInfoPremiumActivated: "Дастрасии Premium фаъол шуд!",
sendInfoPremiumActivatedBody: "Шумо ба функсияҳои Premium 7 рӯз дастрасӣ доред.",
sendInfoBackToDashboard: "Бозгашт ба лавҳаи идоракунӣ",
sendInfoTitleBack: "Бозгашт ба лавҳаи идоракунӣ",
required: "ҳатмист",
smartMatch: "Интихоби ҳушёр",
aboutCoreAccess: "Дастрасии асосӣ дохилкарда шудааст",
aboutGlobal: "Ҷаҳонӣ",
contactLabelEmail: "Почтаи электронӣ",
contactLabelTopic: "Мавзӯъ",
loginSubtitle: "Хуш омадед! Ба ҳисоби худ ворид шавед.",
loginEmailLabel: "Почтаи электронӣ",
loginEmailPlaceholder: "Почтаи электрониатонро ворид кунед",
loginPasswordLabel: "Рамз",
loginPasswordPlaceholder: "Рамзи худро ворид кунед",
loginSubmit: "Ворид шудан",
loginSubmitting: "Воридшавӣ...",
loginNoAccount: "Ҳисоб надоред?",
loginSignUpHere: "Дар ин ҷо сабт шавед",
loginContinueAsGuest: "Чун меҳмон давом додан",
loginGuestSuffix: "— бе воридшавӣ, барномаро санҷидан.",
loginForgotLink: "Рамзро фаромӯш кардед?",
forgotSubtitle: "Почтаатонро ворид кунед — пайванди барқарорсозӣ мефиристем.",
forgotSubmit: "Пайванди барқарорсозиро фиристодан",
forgotSent: "Агар ин почта сабт шуда бошад, пайванди барқарорсозӣ фиристода мешавад. Паёмдонатонро санҷед.",
forgotBackToLogin: "Бозгашт ба воридшавӣ",
forgotError: "Барқарорсозӣ оғоз нашуд. Дубора кӯшиш кунед.",
resetSubtitle: "Рамзи навро интихоб кунед.",
resetNoToken: "Ин пайванд токен надорад. Пайванди навро дархост кунед.",
resetDone: "Рамз навшуд. Ҳоло метавонед ворид шавед.",
resetGoToLogin: "Ба воридшавӣ гузаштан",
resetNewPasswordLabel: "Рамзи нав",
resetNewPasswordPlaceholder: "Ҳадди ақал 8 аломат",
resetSubmit: "Рамзро навкардан",
resetTooShort: "Рамз бояд ҳадди ақал 8 аломат дошта бошад.",
resetError: "Ин пайванди барқарорсозӣ беэътибор аст ё мӯҳлаташ гузаштааст.",
verifyVerifying: "Почтаи шумо тасдиқ карда мешавад…",
verifyOk: "Почтаи шумо тасдиқ шуд. Ташаккур!",
verifyError: "Ин пайванди тасдиқ беэътибор аст ё мӯҳлаташ гузаштааст.",
loginFailedMessage: "Воридшавӣ ноком шуд. Почта ва рамзи худро санҷед.",
registerSubtitle: "Ҳисоб созед — кишвари худро интихоб кунед.",
registerFirstName: "Ном",
registerLastName: "Насаб",
registerEmail: "Почтаи электронӣ",
registerEmailPlaceholder: "you@example.com",
registerPassword: "Рамз",
registerCountry: "Кишвар",
registerCountriesLoading: "Кишварҳо бор мешаванд...",
registerSelectCountry: "Кишвари худро интихоб кунед",
registerCountryHint: "Барои сохтани ҳисоб ҳатмист.",
registerNoCountriesHint: "Кишварҳо бор нашуданд. Backend-ро шурӯъ кунед ва тасдиқ кунед, ки дар базаи маълумот кишварҳо ҳастанд, ё дар поён «Чун меҳмон давом додан»-ро истифода кунед.",
registerSubmit: "Ҳисоб сохтан",
registerSubmitting: "Ҳисоб сохта мешавад...",
registerHaveAccount: "Аллакай ҳисоб доред?",
registerLogIn: "Ворид шудан",
registerGuestSuffix: "— бе сабтиномӣ, барномаро санҷидан.",
registerSelectCountryError: "Лутфан кишварро интихоб кунед.",
registerFillAllError: "Лутфан ҳамаи майдонҳоро пур кунед.",
registerFailedError: "Сабт ноком шуд.",
publicSeeHowItWorks: "Дар YouTube бубинед, ки чӣ гуна кор мекунад",
publicAboutUs: "Дар бораи мо",
publicSupportQr: "QR-и дастгирӣ",
publicFaq: "Саволҳои зуд-зуд додашаванда",
publicContactUs: "Бо мо тамос гиред",
publicSendMessage: "Ба мо паём фиристед",
publicMessageSent: "Ташаккур! Паёми шумо фиристода шуд.",
publicFullName: "Ном ва насаб",
publicFullNamePh: "Ном ва насабатонро ворид кунед",
publicTopicPh: "Чӣ гуна кӯмак лозим аст?",
publicMessageLabel: "Паём",
publicMessagePh: "Паёматонро нависед",
publicFooterPrivacy: "Махфият",
publicFooterTerms: "Шартҳо",
publicFooterContact: "Тамос",
publicStudentSupport: "Дастгирии донишҷӯён",
publicUnisWorldwide: "Донишгоҳҳои ҷаҳон",
publicSupportNumber: "Рақами дастгирӣ",
publicQrPlaceholder: "QR-и дастгириро ин ҷо илова кунед",
publicAboutLead: "ilmi ба донишҷӯёни ҷаҳон ёрӣ медиҳад, ки тавассути AI-интихоб донишгоҳ ва стипендияҳои дуруст ёбанд. Маъмурияти мо — таҳсилоти олиро ба ҳама дастрас сохтан.",
publicAboutCopy: "Дастрасии асосӣ ба ҷустуҷӯи донишгоҳҳо ва стипендияҳо дохилкарда шудааст, бо абзорҳои амалӣ барои истифодаи фаврӣ.",
publicMainServices: "Хадамоти асосӣ",
searchUniNamePlaceholder: "Ҷустуҷӯ бо номи донишгоҳ ё коллеҷ…",
searchUniClearAll: "Ҳамаро тоза кардан",
searchUniTuitionRange: "Маблағи таҳсил дар як сол (€)",
searchUniMatching: "Муассисаҳои мувофиқ",
searchUniLoadingList: "Донишгоҳҳо бор мешаванд...",
uniDetailLoadingTitle: "Боргузорӣ...",
uniDetailLoadingBody: "Маълумоти донишгоҳ бор мешавад...",
uniDetailNotFound: "Муассиса ёфт нашуд",
searchUniPopularUnder10k: "То €10 ҳазор / сол",
searchUniPopularUnder5k: "≤ €5 ҳазор / сол",
searchUniPopularEnglish: "Бо забони англисӣ",
searchUniPopularEurope: "Аврупо",
searchUniPopularBusiness: "Тиҷорат ва ҳуқуқ",
searchUniPopularMedicine: "Тиб ва илм",
searchUniPopularArts: "Санъат ва дизайн",
searchUniInstAll: "Ҳамаро",
searchUniInstUniversities: "Танҳо донишгоҳҳо",
searchUniInstColleges: "Танҳо коллеҷҳо",
searchUniDegreeAll: "Ҳамаи сатҳҳо",
searchUniDegreeAssociate: "Ассотсиат",
searchUniDegreeDiploma: "Диплом",
searchUniDegreeBachelor: "Бакалавр",
searchUniDegreeMaster: "Магистр",
searchUniDegreePhd: "PhD / Докторантура",
searchUniLangAny: "Ҳар забон",
searchUniLangEnglish: "Англисӣ",
searchUniLangGerman: "Олмонӣ",
searchUniLangFrench: "Фаронсавӣ",
searchUniLangSpanish: "Испанӣ",
searchUniLangDutch: "Ҳолландӣ",
searchUniLangCatalan: "Каталанӣ",
searchUniAllCountries: "Ҳамаи кишварҳо",
searchUniAllFields: "Ҳамаи соҳаҳо",
searchUniAllCities: "Ҳамаи шаҳрҳо дар ин кишвар",
searchResultOne: "натиҷа",
searchResultMany: "натиҷаҳо",
searchUniNameLabel: "Ҷустуҷӯ бо номи муассиса",
searchUniPopularHeading: "Филтрҳои маъмул",
searchUniInstTypeLabel: "Намуди муассиса",
searchUniCountryLabel: "Кишвар",
searchUniCityLabel: "Шаҳр / минтақа",
searchUniFieldLabel: "Соҳа",
searchUniDegreeLabel: "Сатҳи дараҷа",
searchUniLanguageLabel: "Забони таҳсил",
searchUniMin: "Мин",
searchUniMax: "Макс",
featureSmartMatchTitle: "Интихоби ҳушёри донишгоҳҳо",
featureSmartMatchDesc: "AI профил, ҳадафҳо ва афзалиятҳои шуморо таҳлил карда, донишгоҳҳои мувофиқро тавсия медиҳад.",
featureScholarshipTitle: "Стипендияҳо ва дастгирии молиявӣ",
featureScholarshipDesc: "Барои банақшагирии буҷети таҳсилот стипендияҳо, грантҳо ва кӯмакҳоро ёбед.",
featureInsightsTitle: "Таҳлили қабул",
featureInsightsDesc: "Тамоюлҳои қабул, тафсилоти барномаҳо ва натиҷаҳоро муқоиса карда, қарорҳои асоснок қабул кунед.",
featureGlobalTitle: "Дастрасӣ ба донишгоҳҳои ҷаҳон",
featureGlobalDesc: "Донишгоҳҳоро дар якчанд кишвар бо маълумоти равшани барномаҳо ва қабул тадқиқ кунед.",
featureAnyDeviceTitle: "Дастрасии осон аз ҳар дастгоҳ",
featureAnyDeviceDesc: "ilmi-ро дар мобайл ё компютер истифода кунед — мувофиқатҳо ва қадамҳои худро пайгирӣ кунед.",
featureAdvisorTitle: "Дастгирии маслиҳатчиён",
featureAdvisorDesc: "Аз маслиҳатчиёни таҷрибадор оид ба қабул, ариза ва банақшагирӣ кӯмаки амалӣ гиред.",
programsAllCategories: "Ҳамаи категорияҳо",
programsAllCountries: "Ҳамаи кишварҳо",
programsTuitionFree: "Ройгон / давлатӣ",
searchUniLangItalian: "Италянӣ",
searchUniLangJapanese: "Японӣ",
searchUniLangKorean: "Кореягӣ",
chartUnis: "Донишгоҳҳо",
chartScholarshipsLabel: "Стипендияҳо",
monthJan: "Янв",
monthFeb: "Фев",
monthMar: "Мар",
monthApr: "Апр",
monthMay: "Май",
monthJun: "Июн",
heroTitleLine2: "Роҳнамо барои сафари таҳсилии шумо",
heroDescription2: "Дар як платформаи оддӣ нишондодҳои равшан оид ба донишгоҳҳо, стипендияҳо, қабул ва барномаҳои магистр.",
heroCtaPrimary: "Шурӯъ кардан",
heroCtaSecondary: "Чӣ гуна кор мекунад",
faqQ1: "Истифодаи ilmi пулакӣ аст?",
faqA1: "Хусусиятҳои асосӣ — интихоби донишгоҳ, ҷустуҷӯи стипендия ва нишондодҳои калидӣ — ройгон. Дастгирии Premium ихтиёрӣ ва пулакӣ.",
faqQ2: "Раванди интихоб чӣ гуна кор мекунад?",
faqA2: "AI ҳадафҳо, профил ва афзалиятҳои шуморо таҳлил карда, рӯйхати дараҷабандишудаи донишгоҳҳо ва стипендияҳои мувофиқро нишон медиҳад.",
faqQ3: "Кадом кишварҳо ва донишгоҳҳо дохил карда шудаанд?",
faqA3: "Мо донишгоҳҳо ва имкониятҳои стипендиявиро дар бисёр кишварҳо дохил мекунем. Шумо метавонед бо кишвар, барнома ва имкониятҳои маблағгузорӣ филтр кунед.",
faqQ4: "Чӣ гуна ман метавонам ilmi-ро дастгирӣ кунам?",
faqA4: "Шумо метавонед моро тавассути садақаҳои дар бахши «Дар бораи мо» нишондодашуда дастгирӣ кунед. Дастгирии шумо ба мо имкон медиҳад дастрасии асосиро барои ҳамаи донишҷӯён нигоҳ дорем.",
searchFieldDefaultPlaceholder: "Ҷустуҷӯи муассисаҳо",
selectFieldDefaultPlaceholder: "Интихоб кунед",
skyToggleToLight: "Ба темаи равшан гузаштан",
skyToggleToDark: "Ба темаи торик гузаштан",
errFailedLoadFavorites: "Боргузории дилхоҳҳо ноком шуд.",
errFailedRemoveFavorite: "Аз дилхоҳҳо ҷудо кардан ноком шуд.",
interestsTitle: "Манфиатҳои шумо",
interestsIntro: "Дараҷаҳо ва соҳаҳои таҳсилии мавриди таваҷҷӯҳатонро нишон диҳед. Мо инро барои танзими интихобҳо истифода мекунем.",
interestsDegreeLabel: "Дараҷаи мавриди таваҷҷӯҳ",
interestsFieldLabel: "Соҳаи мавриди таваҷҷӯҳ",
interestsAdded: "Илова шуд",
interestsAddDegree: "Дараҷа илова кунед",
interestsAddField: "Соҳа илова кунед",
interestsNoDegrees: "Ҳанӯз дараҷае нест",
interestsNoFields: "Ҳанӯз соҳае нест",
interestsRemoveAria: "ҳазф кардан",
fundingTitle: "Буҷет — манбаҳои маблағгузорӣ",
fundingTotalLabel: "Ҷамъ",
fundingHint: "Он чиро, ки метавонед барои таҳсил ҷудо кунед, илова кунед (оила, пасандоз, стипендия, қарз). Ҷамъ буҷети шумо барои муқоисаи дастрасӣ мешавад.",
fundingRemoveAria: "Ҳазф кардани {label}",
fundingSourcePlaceholder: "Манбаъ (мас. Оила)",
fundingAmountPlaceholder: "Маблағ/сол (USD)",
fundingAdd: "Илова кунед",
profileMaxBudget: "Буҷети максималӣ / сол (USD)",
profileMaxBudgetPlaceholder: "мас. 15000",
dashNoDeadlines: "Ҳанӯз муҳлате нест. Аризаеро пайгирӣ кунед, то муҳлати он ин ҷо намоён шавад.",
dashNoTopMatches: "Баҳоҳои худро дар саҳифаи интихоб илова кунед, то беҳтарин донишгоҳҳои мувофиқро ин ҷо бубинед.",
dashNoTopScholarships: "Вақте ки стипендияҳо барои профили шумо пайдо шаванд, беҳтарин мувофиқатҳо ин ҷо намоён мешаванд.",
dashEligible: "Мувофиқ",
dashNotYet: "Ҳанӯз не",
dashNotEligible: "Мувофиқ нест",
matchTitle: "Донишгоҳҳои мувофиқ",
matchDescriptionGuest: "Бубинед, ки ба кадом барномаҳо мувофиқед, бо дараҷабандӣ аз рӯи мувофиқат.",
matchDescription: "Маълумоти таҳсилии худро ворид кунед, то бубинед ба кадом барномаҳо мувофиқед.",
matchGuestCtaTitle: "Барои дарёфти мувофиқатҳо ҳисоби ройгон созед",
matchGuestCtaDesc: "Интихоб баҳоҳо ва натиҷаҳои имтиҳони шуморо истифода мекунад, аз ин рӯ профили сабтшуда лозим аст. Меҳмонон метавонанд корошноӣ кунанд, аммо мувофиқатҳо ҳисоб талаб мекунанд.",
matchGuestSignUp: "Сабт шудан",
matchAcademicInfoTitle: "Маълумоти таҳсилии шумо",
matchAcademicInfoIntro: "Баҳоҳои фанҳо ва натиҷаи имтиҳонро илова кунед. Мо онҳоро бо талаботи нашршудаи ҳар барнома муқоиса мекунем — маълумоти шумо дар профил нигоҳ дошта мешавад.",
matchGradingSystem: "Системаи баҳогузорӣ",
matchHighestDegree: "Олитарин дараҷа",
matchSubjects: "Фанҳо",
matchSubjectPlaceholder: "Фан",
matchGradePlaceholder: "Баҳо",
matchRemoveSubject: "Фанро ҳазф кунед",
matchAddSubject: "+ Фан илова кунед",
matchExam: "Имтиҳон",
matchScore: "Бал",
matchScorePlaceholder: "мас. 100",
matchMaxScore: "Бали максималӣ",
matchMaxScorePlaceholder: "мас. 120",
matchSaving: "Нигоҳ дошта мешавад…",
matchSaveAndFind: "Нигоҳ доштан ва ёфтан",
matchFinding: "Мувофиқатҳо ёфта мешаванд…",
matchPromptSave: "Баҳоҳоро дар боло илова кунед ва «Нигоҳ доштан ва ёфтан»-ро интихоб кунед.",
matchNoPrograms: "Ҳанӯз барнома нест. Баъдтар дубора санҷед.",
matchEligibleOf: "{eligible} мувофиқ аз {total} барнома",
matchTuitionFree: "Бе маблағи таҳсил",
matchGradingGpa4: "GPA (шкалаи 4.0)",
matchGradingGpa5: "GPA (шкалаи 5.0)",
matchGradingFive: "5-балла (КМА)",
matchGradingTen: "10-балла",
matchDegreeHighSchool: "Аттестати мактаби миёна",
matchDegreeAssociate: "Ассотсиат",
matchDegreeBachelor: "Бакалавр",
matchDegreeMaster: "Магистр",
matchDegreeDoctorate: "Докторантура",
matchExamNone: "Имтиҳон нест",
matchTierSafety: "Боэтимод",
matchTierTarget: "Ҳадаф",
matchTierReach: "Баланд",
matchTierFarReach: "Хеле баланд",
matchTranscriptSelfReported: "Худ нишондода",
matchTuitionPerYear: "{amount} {currency}/сол",
matchPercentFit: "{fit}% мувофиқат",
matchPercentAcademic: "{score}% таҳсилӣ",
matchEligible: "Мувофиқ",
matchNotYetEligible: "Ҳанӯз мувофиқ нест",
matchAllMet: "✓ Шумо ба ҳамаи талаботҳо ҷавобгӯед.",
matchWhatsMissing: "Чӣ камбуд дорад",
matchNeedHave: "лозим {required}, дорад {actual}",
matchTracking: "✓ Пайгирӣ мешавад",
matchAdding: "Илова мешавад…",
matchTrackApplication: "+ Аризаро пайгирӣ кунед",
appsTitle: "Аризаҳои ман",
appsDescription: "Ҳар барномаеро, ки барои он ариза медиҳед, пайгирӣ кунед — вазъ, муҳлатҳо ва эзоҳҳо дар як ҷой.",
appsNoDeadlineSet: "Муҳлат таъин нашудааст",
appsPastDue: "Муҳлат гузаштааст ({days} рӯз пеш)",
appsDueToday: "Муҳлат имрӯз",
appsDaysLeft: "{days} рӯз монд",
appsLoading: "Аризаҳои шумо бор мешаванд…",
appsEmptyTitle: "Ҳанӯз ариза нест",
appsEmptyHintBefore: "Барномаҳои мувофиқ ёбед ва",
appsTrackApplicationQuoted: "«Аризаро пайгирӣ кунед»",
appsEmptyHintAfter: "барои оғози рӯйхати вазифаҳо бо муҳлатҳо зер кунед.",
appsFindMatches: "Мувофиқатҳоро ёбед →",
appsCountOne: "{count} ариза",
appsCountMany: "{count} ариза",
appsStatus: "Вазъ",
appsDeadline: "Муҳлат",
appsRemove: "Ҳазф кардан",
appsSubmitted: "Фиристода шуд {date}",
appsHideChecklist: "▾ Рӯйхатро пинҳон кунед",
appsShowChecklist: "▸ Рӯйхати вазифаҳо",
checklistLoading: "Рӯйхат бор мешавад…",
checklistDone: "{done}/{total} иҷро шуд",
checklistRemoveTask: "Вазифаро ҳазф кунед: {title}",
checklistAddPlaceholder: "Вазифа илова кунед…",
checklistAdd: "Илова кунед",
uniDetailBackToSearch: "Бозгашт ба ҷустуҷӯ",
uniDetailNoMatch: "Ягон донишгоҳ бо «{slug}» ёфт нашуд.",
uniDetailReturnToSearch: "Бозгашт ба ҷустуҷӯ",
uniDetailUniversity: "Донишгоҳ",
uniDetailCollege: "Коллеҷ",
uniDetailLanguages: "Забонҳо: {languages}",
uniDetailApply: "Ариза диҳед",
uniDetailTuitionPublic: "Маблаги таҳсил нест (давлатӣ)",
uniDetailTuitionAnnual: "≈ {amount} / сол",
uniDetailProgramFree: "Ройгон / давлатӣ",
onboardingRegionLabel: "Шурӯъ кунед",
onboardingTitle: "Хуш омадед ба ilmi 👋",
onboardingSub: "Баҳоҳо ва як имтиҳонро илова кунед, то мувофиқатҳои донишгоҳ, шансҳои қабул ва стипендияҳои мувофиқро бикушоед — тақрибан як дақиқа.",
onboardingCta: "Интихоб кунед →",
onboardingDismiss: "Пӯшидан",
jobsTitle: "Кор ва стажировка",
jobsDesc: "Имкониятҳо барои донишҷӯён — бо соҳа филтр кунед.",
jobsFieldLabel: "Соҳа",
jobsAllFields: "Ҳамаи соҳаҳо",
jobsLoading: "Ҷойҳои кор бор мешаванд…",
jobsEmpty: "Барои ин филтр ҳанӯз ҷойи кор нест.",
loadMore: "Бештар нишон диҳед",
loadingMore: "Боргузорӣ…",
jobsCount: "{count} имконият",
jobsApply: "Ариза диҳед",
searchScholarshipsPageTitle: "Стипендияҳо",
searchScholarshipsPageDesc: "Стипендияҳоро дидан — бо соҳа ва сатҳ филтр кунед.",
searchScholarshipsFieldLabel: "Соҳа",
searchScholarshipsAllFields: "Ҳамаи соҳаҳо",
searchScholarshipsLevelLabel: "Сатҳ",
searchScholarshipsAllLevels: "Ҳамаи сатҳҳо",
searchScholarshipsLevelBachelor: "Бакалавр",
searchScholarshipsLevelMaster: "Магистр",
searchScholarshipsLevelDoctorate: "Докторантура",
searchScholarshipsLoading: "Стипендияҳо бор мешаванд…",
searchScholarshipsEmpty: "Барои филтрҳои шумо ҳанӯз стипендия нест — соҳа ё сатҳро васеъ кунед.",
searchScholarshipsCount: "{count} стипендия",
searchScholarshipsAwardFullTuition: "Пӯшиши пурраи таҳсил",
searchScholarshipsAwardPercentOff: "{value}% тахфифи таҳсил",
searchScholarshipsAwardDefault: "Мукофот",
matchScholTitle: "Стипендияҳои мувофиқ",
matchScholDesc: "Стипендияҳои фаъол бо дараҷабандӣ аз рӯи профили шумо — шаҳрвандӣ, GPA ва манфиатҳо.",
matchScholGuestDesc: "Бубинед, ба кадом стипендияҳо эҳтимолан мувофиқед, бо дараҷабандӣ аз рӯи мувофиқат.",
matchScholGuestCtaTitle: "Барои дарёфти мувофиқатҳо ҳисоби ройгон созед",
matchScholGuestCtaDesc: "Интихоб кишвар, баҳоҳо ва манфиатҳои шуморо истифода мекунад — меҳмонон метавонанд корошноӣ кунанд, аммо мувофиқатҳои стипендия профили сабтшуда талаб мекунанд.",
matchScholGuestCtaBtn: "Сабт шудан",
matchScholEligibleOnly: "Танҳо мувофиқ",
matchScholLoading: "Стипендияҳои мувофиқ ёфта мешаванд…",
matchScholEmptyPrefix: "Ҳанӯз стипендия нест. Баъдтар дубора санҷед, ё ",
matchScholEmptyLink: "манфиатҳо ва буҷет",
matchScholErrorDefault: "Стипендияҳои мувофиқ бор нашуданд",
matchScholCount: "{eligible} мувофиқ аз {total}",
matchScholEligible: "Мувофиқ",
matchScholNotEligible: "Мувофиқ нест",
matchScholYourInterest: "★ Манфиати шумо",
matchScholDue: "Муҳлат {date}",
matchScholAwardFullTuition: "Пӯшиши пурраи таҳсил",
matchScholAwardFullCost: "Пӯшиши пурраи хароҷоти таҳсил",
matchScholAwardPercentOff: "{value}% тахфифи таҳсил",
matchScholAwardTuitionDiscount: "Тахфифи таҳсил",
matchScholAwardFixed: "Мукофоти собит",
matchScholAwardVariable: "Мукофоти тағйирёбанда",
essayTitle: "Санҷиши иншо",
essayDesc: "Иншои аризатонро часпонед ва бозхӯрди AI барои аризадиҳандагони Осиёи Марказӣ, ки забони англисӣ омӯзанд, гиред.",
essayNotAvailableTitle: "Ҳанӯз дастрас нест",
essayNotAvailableText: "Санҷиши иншо бо AI дар ин муҳит ҳанӯз фаъол нашудааст. Баъдтар санҷед — вақте ки фаъол шавад, метавонед иншоро ин ҷо часпонед ва бозхӯрди сохторбандишуда гиред.",
essayTypeLabel: "Навъи иншо",
essayTypePersonalStatement: "Баёноти шахсӣ",
essayTypeMotivationLetter: "Мактуби мотивасионии стипендия",
essayTypeStatementOfPurpose: "Баёноти ҳадаф",
essayTypeCommonApp: "Иншои Common App",
essayTypeOther: "Дигар",
essayPlaceholder: "Иншоатонро ин ҷо часпонед…",
essayReviewing: "Тафтиш мешавад…",
essayGetFeedback: "Бозхӯрд гирифтан",
essayFeedbackTitle: "Бозхӯрди AI",
coursesDesc: "Курсҳои омодагии шарикӣ (забони англисӣ, математика ва ғайра).",
coursesSubjectLabel: "Фан",
coursesAllSubjects: "Ҳамаи фанҳо",
coursesLoading: "Курсҳо бор мешаванд…",
coursesEmpty: "Ҳанӯз курс нест.",
coursesCount: "{count} курс",
coursesView: "Дидан",
dashToggleMenu: "Менюро кушоед/бандед",
dashDeadlinesDueSoon: "{count} муҳлати ариза наздик аст",
dashDeadlineToday: "Имрӯз",
dashDaysAgo: "{n} рӯз пеш",
dashDaysLeft: "{n} рӯз монд",
publicFooterRights: "© {year} ilmi. Ҳамаи ҳуқуқҳо ҳифз шудаанд",

  // My Academics page
  myAcademicsGuestDesc: "Баҳоҳо ва натиҷаҳои имтиҳони шумо, ки интихобро таъмин мекунанд.",
  myAcademicsDesc: "Баҳоҳо ва имтиҳонҳое, ки интихоб, имконият ва стипендияҳои шуморо таъмин мекунанд.",
  myAcademicsGuestEmptyBefore: "Меҳмонон сабти академии нигоҳдошташуда надоранд. ",
  myAcademicsGuestEmptyAfter: " то аз они худро илова кунед.",
  myAcademicsTranscripts: "Шаҳодатномаҳо",
  myAcademicsAddViaMatching: "+ Тавассути интихоб илова кунед",
  myAcademicsLoading: "Боргузорӣ…",
  myAcademicsNoTranscriptsBefore: "Ҳоло шаҳодатнома нест. Баҳоҳои худро дар ",
  myAcademicsMatchingPage: "саҳифаи интихоб",
  myAcademicsNoTranscriptsAfter: " илова кунед, то интихоб гиред.",
  myAcademicsExams: "Имтиҳонҳо",
  myAcademicsNoExams: "Ҳоло имтиҳон нест.",
};

export default tg;
